### ISSUE TITLE
How to plan and analyse large and segmented expense.

### ISSUE THREAD

**Issue by Aquariu** [firefly-iii/firefly-iii#1034]
Dear all,

I'll be buying an apartment next month an it needs a lot of work. I'll probably end up spending more than 30k€ on it during a 6-9 months timeframe. How do I manage that in Firefly ?
I already have a Category for that and I can just check regularly the total spent on  that category. 

But is there a way to have a multi-month Budget (or something like it) and slowly see my repair bills add up to a pre-set maximum ?

Kind regards,
Olivier

**Comment by JC5** [comment]
You can also use tags, but a multi-month budget is possible. Go to `/budgets` first. Then, change the data range using the top right date-indicator. In this example, I've changed it to 2-dec/1-mar:

![screen shot 2017-12-03 at 09 04 19](https://user-images.githubusercontent.com/5889984/33523490-0925b510-d809-11e7-8898-db12e6bd0014.png)

Any budget you will set the amount for will have that amount applied to the given period (in this example, the "Car" budget):

![screen shot 2017-12-03 at 09 05 16](https://user-images.githubusercontent.com/5889984/33523493-217ee316-d809-11e7-8af3-ec59093ff1e4.png)

On the frontpage, this particular budget is shown twice. Once for the "normal" period of dec-1/dec-31 and once for the over-arching period of 2-dec/1-mar (as I've set above).

![screen shot 2017-12-03 at 09 07 09](https://user-images.githubusercontent.com/5889984/33523498-5a94a906-d809-11e7-8d5b-194d4a9f1277.png)
(I know that the chart needs some work. Few people use this feature).

Even when you change the date range to January or February (as you would normally do) the amount set for 2-dec/1-mar remains visible until it is completely finished.

In order to see the expenses on this period, go to `/budgets/show/x` or use the budgets page.

Is that something you can use?

**Comment by Aquariu** [comment]
Yes, I can use that. I still need to get used to the idea of changing the data range for this though. But I thing I get it. Thanks a lot !

**Comment by JC5** [comment]
It's not perfect, I know. When I moved, I used a tag to collect all expenses (and income etc). The tag screen can show you the sums of various elements (expenses, income) within the tag.

Of course, the tag report and budget report can also show you what you spent money on.
