### ISSUE TITLE
Negative debtor balance after incoming transaction

### ISSUE THREAD

**Issue by macer90** [firefly-iii/firefly-iii#1035]
I am running Firefly III version 4.6.11

#### Description of my issue:
When i make an incoming transaction, like my salary, he makes the transaction without any problems. But when i go to the debtor page, i'll get a negative balance for the debtor where the incoming transaction is linked to, instead of a positive balance. It doesn't make any difference if I use another debtor or transaction.

#### Steps to reproduce
- Make a debtor
- Make an incoming transaction (positive), and link it to the debtor
- Go to the debtor page, and watch the balance (negative instead of positive)

**Comment by simhnna** [comment]
That is expected behaviour. You get money, so your workplace is loosing money to you. If you go to the account of a store where you buy things, you will see that the balance is positive. That's because you loose money and the store gains your money. It's called double-entry bookkeeping and is pretty much a universal standard.

**Comment by macer90** [comment]
Thank you for the answer!
