### ISSUE TITLE
Transactions processed by rules (manually?) do not show category/budget on transactions overview page

### ISSUE THREAD

**Issue by webence** [firefly-iii/firefly-iii#1036]
I am running Firefly III version 4.6.11 (Installed via composer)

Description of my issue: Category and budget do not always show on transaction page when using rules.

I've imported a bank transaction of 2017 and now I am in progress of assigning categories,budgets and tags to each transaction (by manually running the rule). So for instance every transaction that has the target account name of "Albert Heijn" gets the category and budget "Boodschappen". While they are actually processed they do not show on the /transactions/withdrawal/ page behind the transaction (the fields are empty except just a few) however when you click on them the category and budget is just right there.

When you manually edit those entries and do not change anything, hit save and refresh the transaction overview the category and budget appear. So seems to be something with the rules.

**Comment by JC5** [comment]
Thx for reporting this!

It's a caching issue. Each transaction has several fields that are cached as soon as they accessed for the first time.

The cache relies on the "updated_on" field of the transaction itself. This field isn't updated when a category and/or budget is (un)linked to the transaction. I'm fairly sure this will work for tags as well. Or rather, it won't work :wink:

This problem will persist until you run `php artisan cache:clear` on the command line, or when you change nothing in the transaction using the edit-routine. This changed the updated_on field, so the cache is refreshed.

The reason one screen _does_ show the correct value and the other one does not, is because they use different queries to grab the data (and one of them doesn't care about the "updated_at" field).

I've pushed a fix, which will be included in the next release. This should be next weekend.

**Comment by webence** [comment]
Super, clearing the cache indeed worked for now. Thanks
