### ISSUE TITLE
SQLSTATE[HY000] [1049] Unknown database 'homestead'

### ISSUE THREAD

**Issue by lverissimo** [firefly-iii/firefly-iii#1113]
I am running Firefly III version 4.6.13

Fedora 27
4.14.11-300.fc27.x86_64
Server version: Apache/2.4.29 (Fedora)
Server built:   Oct 25 2017 12:34:45
mysql  Ver 15.1 Distrib 10.2.9-MariaDB, for Linux (x86_64) using readline 5.1

#### Description of my issue:
Unable to complete database migration step of the installation guide from https://firefly-iii.org/using-installing.html

I had to create the database using phpadmin to be able to complete this step. before I did it I ran into the following error. It is now working.

xxx /var/www/firefly-iii $ php artisan migrate:refresh --seed

In Connection.php line 664:                                                                                                                                                                 
  SQLSTATE[HY000] [1049] Unknown database 'homestead' (SQL: select * from information_schema.tables where table_schema = homestead and table_name = migrations)                                                                                                                                                                   

In PDOConnection.php line 47:                                                       
  SQLSTATE[HY000] [1049] Unknown database 'homestead'  
                                                       

In PDOConnection.php line 43:                                                      
  SQLSTATE[HY000] [1049] Unknown database 'homestead'  
                                                       

#### Steps to reproduce 
followed installation guide from https://firefly-iii.org/using-installing.html

**Comment by JC5** [comment]
You must enter valid database credentials into the .env file. I suggest you create a user called “firefly” with long password that has access to the database you created.

**Comment by n0b0** [comment]
Same exact problem with exact reported issues. Question here is whether there is a way to get SQL query for automatically creating all DBs and tables Firefly requires. That would be far more convenient. Also it would be awesome if there is docker image with integrated database engine.

Some if the errors I have got a long the way (I still haven't succeeded installing docker image of firefly)


SQLSTATE[42S22]: Column not found: 1054 Unknown column 'batch' in 'order cl
  ause' (SQL: select `migration` from `migrations` order by `batch` asc, `mig
  ration` asc)

SQLSTATE[22001]: String data, right truncated: 1406 Data too long for colum
  n 'migration' at row 1 (SQL: insert into `migrations` (`migration`, `batch`
  ) values (2016_06_16_000000_create_support_tables, 1))

 SQLSTATE[01000]: Warning: 1265 Data truncated for column 'migration' at row 1 (SQL: insert into `migrations` (`migration`, `batch`) values (2016_06_16_000000_create_support_tables, 1))

**Comment by lverissimo** [comment]
@JC5 James, I got mine to work. My problem was not the user, I just had to create the database using phpadmin and was able to complete this step. 

@n0b0 I agree with you, it would be nice to have the instalation process to create the database if it did not exist.

**Comment by JC5** [comment]
Hi guys,

First of all, thanks for the feedback!

The reason Firefly III cannot create its own database is because that would be a security issue. You would need a high privileged account to do that (ie. the root account). Firefly does not need root to function. If for some reason your credentials leaked, people could access everything. Of course I can build some routine that asks for two pairs of credentials, or a script that creates the correct database and credentials. But that would be a whole lot of work for a very small convenience. You would trust your root password to some script that could then access your entire database and everything in it. 

In the installation guide there is a reference to a Docker compose file with a database included. This is not in one image of course. Docker images must be singular. An image/container that has multiple functions violates this principle. For example, you could no longer fire up 5 or 10 instances of Firefly III that share the same database. It would be more risky to upgrade and if the images would become very large. 

There are many Docker images out there which contain a well configured and secure MySQL instance. One of them is referenced in the compose file. 

If you really want to have everything in one image I would suggest using a Vagrant or VirtualBox machine. You can also configure your Docker container to use SQLite, but it will be slow and you won’t be able to upgrade easily. 

Let me know if you have questions!

**Comment by n0b0** [comment]
Hi @JC5 , 
Thanks for detailed feedback!
I do agree with you that if Firefly III should not create database during installation,because that this my imply potential security vulnerability. However, I think I did not express my self properly, I was thinking that Firefly can actually create all tables within Database. Since you setting up database, where you provide  credentials, and that user has full right on this database, I think it would make sense, initial setup to create all tables required . Does it make sense now ?

I have not tested yet Docker compose file you're referring to, but will do that and report whether I have luck deploying .

**Comment by JC5** [comment]
Ah, in that case you are in luck! Firefly III already generates all the table it needs withing the database.

The [setup guide](https://firefly-iii.org/using-installing.html) has all the commands you need. If you update your `.env` file with the correct credentials Firefly III will generate the tables and the initial data with this command:

```
php artisan migrate:refresh --seed
```

If you are upgrading you can run this command again, together with some extra commands to verify the data:

```
php artisan migrate:refresh --seed
php artisan firefly:upgrade-database
php artisan firefly:verify
```

**Comment by n0b0** [comment]
Hey @JC5 , 
 I still had some Warnings after running 
php artisan migrate:refresh --seed

However, what I did, is to recreate database and run again, and tadaam. All good now. 

docker exec -it <container> php artisan migrate --seed
docker exec -it <container> php artisan firefly:upgrade-database
docker exec -it <container> php artisan firefly:verify

Oddly enough, I couldn't catch what was issue, but my I can assume it was database.

Thanks for the support, highly appreciated!

**Comment by JC5** [comment]
Glad to hear it works! :+1:

If you run into problems just open a new issue.

**Comment by shakilkhan12** [comment]
The solution is very very simple if you using the live server I mean "php artisan serve" then simply restart your server again

**Comment by m7moozz** [comment]
@shakilkhan12 same issue just happened to me right now using sqlite and your comment saved my life. Have a good day.

**Comment by shakilkhan12** [comment]
@m7moozz Welcome brother
