### ISSUE TITLE
How to translate Firefly III help pages?

### ISSUE THREAD

**Issue by Nik-vr** [firefly-iii/firefly-iii#1114]
I began to translate the Firefly III help pages. But I can not see the result of my work in a live copy of FireFly. Where are the files with the translation of the help stored? Or are they loaded from your server?

**Comment by JC5** [comment]
I have to sync them manually to Github. But please dont translate them yet. I am afraid many pages are old and it might be useless work to translate them. For now i would recommend some patience while I clean them up. I shall keep you posted of course :)

**Comment by Nik-vr** [comment]
OK! :)

**Comment by JC5** [comment]
All help pages have been updated! If you wish to translate, you are more than welcome of course.

https://crowdin.com/translate/firefly-iii-help/234/en-ru
Please translate this one to "Russian" (but in Russian :wink:)

https://crowdin.com/translate/firefly-iii-help/243/en-ru
Please be careful not to translate "amount:xx" and other modifiers, because they must be in English to work.

**Comment by Nik-vr** [comment]
OK! :)
