### ISSUE TITLE
Feature request : add incoming lines on budget

### ISSUE THREAD

**Issue by Zciwobukaj** [firefly-iii/firefly-iii#1163]
I` am running Firefly III version 4.7.0 

Today is possible to add expenses to budget
What about adding incomes too ?

E.g : i spend money for doctor but later my insurance refunds part of this.

**Comment by JC5** [comment]
Sorry, budgets are for income only. You can choose to expand your budget or remove the transaction from the budget.

**Comment by Ziwobukaj** [comment]
Are you sure there is nothing to do about this ?

Considering only expanses (and not discounts/refunds) can make budgets/bills wrong at the end...

**Comment by jinformatique** [comment]
You could use Tags for this.

**Comment by JC5** [comment]
Firefly III is built with budgeting in mind. You reserve a certain amount for the (next) month and that is what you can spend. If you receive money back that is nice, but it shouldn't influence your budget, because you shouldn't count on it.

When you know you get a refund there's no need to give the expense a budget.
