### ISSUE TITLE
Cash account (why not)

### ISSUE THREAD

**Issue by mirkof** [firefly-iii/firefly-iii#1176]
Hi James,

As you've probably noticed I started using your app. :) Really liked, especially when dealing with multiple accounts.

A general question, why is there no cash account? I know there is a "default" one, but it's not the same functionality as the rest of the accounts - categories them, include them in the budget, etc.
Or am I missing something?

Cheers,
Mirko

**Comment by JC5** [comment]
Because I didn’t want to track cash expenses. When I have cash I generally consider it “spent” and I don’t bother tracking it. Money gets lost, change gets shorted, it gets messy quickly so I never bothered. I try to use my card as often as possible. Many people prefer cash to budget their expenses but doing everything digitally works better for me. 

Of course, you can always add an asset account and call it “cash account”. It works just the same as a normal account. ATM withdrawals would become transfers between your bank account and your cash account. I know some users who do this.

**Comment by mirkof** [comment]
Then I'll do just that. :) I understand your point, not wanting to have a cash account, since you can download transactions and automate those with rules. 

There are countries that are not that card friendly, so you kinda have no choice. Or when you go out with friends, having only cash is a nice stopper into spending too much money on drinks. :D

**Comment by JC5** [comment]
True, true! :+1:
