### ISSUE TITLE
Language: Spanish

### ISSUE THREAD

**Issue by rogerillu** [firefly-iii/firefly-iii#1194]
I am running Firefly III version 4.7.0 

#### Steps to reproduce 
When I open firefly III and login, it gives this error: 
Invalid server configuration: Firefly III is unable to format monetary amounts because your server is missing the required packages. There are instructions how to do this. 

But the command does not work for spanish language, and in the firefly III settings i can not set up spanish because it does not appear.

**Comment by versvs** [comment]
I am starting to produce a spanish translation of firefly iii, that I would likely contribute via Pull Request when it is ready.

**Comment by JC5** [comment]
Please use Crowdin for translations. I cannot accept translations over pull requests. See the readme.

**Comment by rogerillu** [comment]
You can use this link:
https://crowdin.com/project/firefly-iii/es-ES#
to do the translation. It is almost done, but sure there will be more accurate words

**Comment by rogerillu** [comment]
The translation in Crowdin is finished. How can I select it in firefly?

**Comment by JC5** [comment]
In the next release. It wasn’t finished when 4.7.0 came out.

**Comment by rogerillu** [comment]
Ok! Perfect. Can you enable Catalan language in Crowdin too?

**Comment by versvs** [comment]
i just came to link the crowdin project, I was looking in the code where the translations were stored and found a link to that :)

Thanks!

PS. I see a lot of strings are translated but not approved. What are the requisites for that? I'm upvoting the ones I think that need no more changes.

**Comment by JC5** [comment]
OK to answer all questions: 

- Spanish will be enabled in 4.7.1
- Unapproved strings will still end up in the final product. I can approve strings manually or I can appoint somebody to be a proofreader. 
- Some strings are approved because I re-uploaded old translations. Then it happens automatically. This is not an endorsement of quality, just the way the system works.
- Strings with the most votes will automatically be included.
- To fix the error message, read [this page](https://github.com/firefly-iii/help/wiki/Missing-locale-packages).
- I will enable Catalan in a minute. Could you tell me how to say "Catalan" in Catalan? Like "Français (French)" or "Español (Spanish)".

That should cover all questions, right?

**Comment by rogerillu** [comment]
Yes, thanks for all your help.

Catalan, in Catalan is "Català"

Thanks James!! :)

**Comment by JC5** [comment]
:+1: And Catalan is enabled on Crowdin.
