### ISSUE TITLE
Transaction link types are not translated

### ISSUE THREAD

**Issue by zjean** [firefly-iii/firefly-iii#1216]
I am running Firefly III version 4.7.0, in Dutch.

#### Description of my issue:
The transaction link types in the dialog are not translated:
![image](https://user-images.githubusercontent.com/441924/36921344-56962680-1e64-11e8-8f67-bd0309ad080a.png)

#### Steps to reproduce 
Add a link to another transaction.
Exists on demo site as well.

#### Other important details (log files, system info):

Please click the version number in the right corner of any Firefly III page to get debug information.

**Comment by JC5** [comment]
Yes, I know. I'm still on the fence how to translate them. In Dutch it's pretty easy ("wordt betaald door" or something) but it gets tricky when these snippets are used on the `/transactions/show/x` page. The reason is, in some languages the construct is different per type of transaction (withdrawal is male, expense is female, stuff like that).

I've opted not to translate them for the time being and focus on the features of the links first.

**Comment by JC5** [comment]
This will be fixed in the next release of Firefly III. :+1:

**Comment by JC5** [comment]
I'm closing this since it's fixed. Look for this feature in the next release, and let me know if you encounter any problems!
