### ISSUE TITLE
Updating deposit/withdrawal with foreign currency not working

### ISSUE THREAD

**Issue by razorbenke92** [firefly-iii/firefly-iii#1236]
I am running Firefly III version 4.7.1.4 

#### Description of my issue:

Updating a deposit/withdrawal which was created with foreign currency is not working properly. After update, the foreign currency and amount disappears.

#### Steps to reproduce 

Reproducing on demo site:

Adding a withdrawal with a EUR account, but changing currency to HUF. It shows the HUF as main, and EUR under it. Set amounts and submit.
You will see a transfer with ammount xxx EUR ( yyy HUF)

Go to the edit page of this transaction:
You will see HUF still at main, and EUR under it. Edit something for eg. add a tag. Update.

Now you will only see the transaction with only yyy HUF ammount (and no EUR)

Go to the edit page again:

Now you only see the main HUF value and no EUR. 

After this, there is no scenario to set the EUR master value back. 

I think with the update, you are overwriting the native currency with the foreign one.

(please include if this problem also exists on the demo site)

#### Other important details (log files, system info):

Please click the version number in the right corner of any Firefly III page to get debug information.

**Comment by razorbenke92** [comment]
I am just starting to learn Laravel, but I sense something in TransactionUpdateService.php

$data['amount'] and $data['foreign_amount'] is used but (if these are the form values) the update form is using 'native_amount' and 'amount' where 'amount' stands for the foreign value.

**Comment by JC5** [comment]
Thanks for reporting this, and thanks for the extended bug report!

It seems the problem was in Javascript, and not in PHP. You can see in the commit that the currency for the asset account was set to HUF instead of EUR (in your example). That makes Firefly III think that HUF is the normal amount.

This fix is live on the demo site where you should be able to edit a transaction with foreign amount data without any problems.

Let me know if this has fixed it!

**Comment by razorbenke92** [comment]
Yes, fixed.

Another notice:
I don't know if it is a feature or a bug, but relates to this topic, so I will describe.

As you know, bills only work with the default currency. In my case it is HUF. I have a EUR account for my payments and company related expenses. 
What happens is, that I want to pay my phonebill (issued in HUF) with my EUR account. When storeing the withdrawal using HUF as foreign currency, and EUR as native (of course) : 
- Spent money in HUF not appearing in my monthly balance
- Bill not changing to payed
- I can only see the balance change on the EUR part of my Net Worth

BUT
If I manually swap the native-foreign currencies and values in the database for the transaction:
- Spent money appears in HUF on the monthly balance
- Bills can match automaticaly
- The net worth still calculates properly for every account

I think it is rather a bug, but I could use it as a feature, converting all my EUR expenses to HUF and solving a lot of problem with that. 
Any hints where to change the code at my local server, to save foreign and native data swapped (even on creation or on edit). Sorry, as I said I am new to Laravel, and I can hardly find the proper functions.

Thanks!

**Comment by JC5** [comment]
* Which monthly balance are you talking about, exactly?
* See also https://github.com/firefly-iii/firefly-iii/issues/833
* Yes, because the account is in EUR. So everything is measured in EUR.

If you swap out transactions I cannot guarantee things will work. I can see what you're doing but I can only do one thing, *not* both:

1. Use the EUR account in EUR, measuring your balance in EUR and your net worth in EUR, using HUF amounts as a reference only.
2. Do the same but in reverse.

You can use HUF transactions on a EUR account as main currency. It is not difficult to do this. But the charts will deviate (main balance of the account will be incorrect) and other sums could break as well.

I'm not sure what the bug is, but several features relate to this: https://github.com/firefly-iii/firefly-iii/issues/1207 https://github.com/firefly-iii/firefly-iii/issues/1071 https://github.com/firefly-iii/firefly-iii/issues/991 https://github.com/firefly-iii/firefly-iii/issues/869

**Comment by razorbenke92** [comment]
Okay, I don't want to waste your time, since it would be just a hack-fix, not a proper solution.

But if you are interested, I show what I mean:

At the beginning, this is my dashboards header:
![kep](https://user-images.githubusercontent.com/37187474/37230623-78c79750-23e8-11e8-90b1-e319d85118e9.png)

I add a 1000 EUR worth of deposit, by  300 000 HUF as a foreign currency:
![kep](https://user-images.githubusercontent.com/37187474/37230767-ec76fd12-23e8-11e8-99c9-7e6bbc7c9ca6.png)

So my header looks like:
![kep](https://user-images.githubusercontent.com/37187474/37230813-07dc7b54-23e9-11e8-9559-6076d2156fb0.png)
You can see, that the balance has not changed, and for me it is misleading.

Thats why I swap the foreign and native values in the database and hit rescan transactions at bills:
![kep](https://user-images.githubusercontent.com/37187474/37231031-e2cb3476-23e9-11e8-9223-6d790dd7f319.png)

Now the balance shows that I had 300 000 HUF worth of income, but at the Net Worth It still calculates the EUR value of the deposit.
![kep](https://user-images.githubusercontent.com/37187474/37231187-8dbb69f0-23ea-11e8-9024-747177f26980.png)

Try it again with withdrawal, using a tag for my last unpayed bill:
![kep](https://user-images.githubusercontent.com/37187474/37231306-ea07b2c2-23ea-11e8-8595-ac568eafe8c7.png)

This is my heather (notice the only change in the EUR Net worth)
![kep](https://user-images.githubusercontent.com/37187474/37231340-1570c78c-23eb-11e8-940a-49f9f46cae2c.png)

Now swapping currencies and values and rescan transactions:
![kep](https://user-images.githubusercontent.com/37187474/37231709-7c080bbc-23ec-11e8-9068-ab3b39171acd.png)

Gives a heather:
![kep](https://user-images.githubusercontent.com/37187474/37231732-91ffc27a-23ec-11e8-92e5-6e704ae94d34.png)

So in my case (I know there can be more difficult cases) I see only benefitsd from swapping the currencies.

I will find a way to use it like this until the next release. Thanks!

**Comment by JC5** [comment]
Aha, now I get what you mean. Thanks! The box for balance is not multi-currency, and that is confusing indeed. I can see that it updates as it should, but it adds 1000 EUR to your HUF balance.

I have updated the development version to fix this. There is only room for *two* currencies, but that should be enough.

![screen shot 2018-03-10 at 06 40 02](https://user-images.githubusercontent.com/5889984/37238777-ecd54c4c-242d-11e8-9201-8ccca4e82d41.png)

For your withdrawal, I also see a change in balance that is wrong. This will also be fixed.
