### ISSUE TITLE
Translation issues

### ISSUE THREAD

**Issue by simhnna** [firefly-iii/firefly-iii#1246]
The daterangepicker doesn't translate the month names because momentjs locales are not included and called.

Also when changing the locale you get a success message using two languages
![firefly](https://user-images.githubusercontent.com/33220646/37283176-4da13ec6-25f7-11e8-9891-6ed41b6db2a0.jpg)

They are both pretty minor, but since I found them, I wanted to report them :-)

**Comment by JC5** [comment]
Thanks for reporting them!

The first one can be fixed quite easily. I shall make a note to include the locales. The second one is more tricky I'm afraid. In fact, I don't think I'm going to fix it.

Setting the preference doesn't change the language right then and there. The app needs to be reloaded (aka a page refresh). However, the message is set *before* the app reloads.

So the message "Preferences saved!" will be translated in English, because that was the application's language at the time. It takes a reload to change the language which is when the application is in German. It's only then that the "Geschafft!" message is added. Which will be in German, because at that point the app is in German.

Makes sense?

In theory I can force the message to be translated in the new language before the reload, preventing this problem. But personally I kind of like this quirck. :-)

**Comment by JC5** [comment]
I had the same thing so I decided not to fix it :grin:

**Comment by JC5** [comment]
Will be fixed in the next release. The demo site already features the update. Login, change the language and check out the date picker.
