### ISSUE TITLE
Improvement: Show expected bills when settings budgets

### ISSUE THREAD

**Issue by skuzzle** [firefly-iii/firefly-iii#1270]
I am running Firefly III version 4.7.1.4

When setting my monthly budgets, I create a single one for the expected bills in this month. In order to find out the expected amount of bills to pay, I need to adjust the currently shown date range, go to dashboard, remember the amount and then return to the budget page. Maybe it is possible to display the expected bills on the budget page for the currently selected budget range?

**Comment by JC5** [comment]
I'll see where it could fit. Can't promise anything though!

**Comment by aventrax** [comment]
Hello. I'm writing here because I cannot find anything better but It's not worth a new issue.
I'm just starting with FF and it's great, anyway I cannot find a way to fit my needs on Bills.

Since I get my wage monthly, my budgets "periods" are set with this interval. That's ok for pretty much anything but not for the Bills (usually bi-monthly).

How can I set a budget for a bill that I'm receiving with a different interval? I don't get it, please clarify =)

**Comment by JC5** [comment]
https://github.com/firefly-iii/firefly-iii/projects/5#card-19937790
