### ISSUE TITLE
4.7.2.2 - Upgrade fails if php proc_close function disabled, 2FA token disabled

### ISSUE THREAD

**Issue by 4oo4** [firefly-iii/firefly-iii#1318]
I am running Firefly III version 4.7.2.2

#### Description of my issue:
Attempted to upgrade to 4.7.2.2, had the migration fail when attempting to login after the upgrade. Digging in the logs, I can see this was because I had `proc_close` in my `disabled_functions` in `php.ini`. I fixed it by temporarily enabling that, just wanted to note this in case it needed to be added to the docs. I'm guessing I'll need this going forward for upgrading Firefly?

Separate question, but I also noticed that 2FA got disabled as well during the upgrade, so I had to configure that again. I didn't recall having to do that with previous upgrades, could this be related to this in the logs?

```
[2018-04-04 20:07:55] production.ERROR: Preference #20 ("access_token") was stored as serialised object. It will be deleted and recreated.
```

Cheers

#### Steps to reproduce 
 1. Run upgrade (installed from git)
 2. Browse to login page, receive "Migration failed" error

#### Other important details (log files, system info):
```
[2018-04-04 20:08:03] production.DEBUG: Set new value for  {"name":"db_version"}
[2018-04-04 20:08:03] production.DEBUG: Does not exist yet  {"name":"db_version"}
[2018-04-04 20:08:03] production.WARNING: The current installed version (1) is older than the required version (2). Redirect to migrate routine.
[2018-04-04 20:08:03] production.DEBUG: URL is https://example.com/firefly/public/install, will NOT run installer middleware
[2018-04-04 20:08:04] production.DEBUG: URL is https://example.com/firefly/public/install/migrate, will NOT run installer middleware
[2018-04-04 20:08:04] production.DEBUG: Am now calling migrate routine...
[2018-04-04 20:08:05] production.ERROR: proc_close() has been disabled for security reasons {"exception":"[object] (ErrorException(code: 0): proc_close() has been disabled for security reasons at /var/www/firefly/vendor/symfony/console/Terminal.php:132)
```

**Comment by JC5** [comment]
Thanks for the feedback, I appreciate it!

* I will make sure that the migration will work without the function `proc_close`. It's the first version of a routine to simplify the migration. I wasn't sure what to expect. 
* Yes, losing your preferences is an unfortunate side-effect of the upgrade. I realized I use serialize/unserialize to store preferences, and this is a security risk. To mitigate this I had no choice but to delete all preferences (since I can't trust the content) and have users recreate them. This is no problem for most preferences (they have default values) but notable things like the 2FA tokens and the default currency will have to set again.

So going forward you should not need the `proc_close` function. I wasn't even aware it's being used, I think Laravel calls it. I will investigate it further :).

**Comment by gavu** [comment]
Just wanted to add to the list, somewhere between 4.7.2 and 4.7.2.2 my CLI-token changed also

**Comment by JC5** [comment]
@gavu Yep. Sorry :(

@4oo4 It's very reassuring (not), that when I google "proc_close" and "laravel" this issue is the second hit. So stay tuned, but perhaps I am going to have bad news.

**Comment by gavu** [comment]
@JC5 no problem, I read the thread and just noticed it. I added my comment just in case you need a "list" of preferences FF should keep upgrade-safe

**Comment by 4oo4** [comment]
@JC5 No worries, if it does end up being something upstream that can't be fixed right away it's a super easy workaround. Thanks for looking into it!

**Comment by JC5** [comment]
OK, I did some research this weekend and it's just about impossible to fire the migration routines programmatically. I can call commands, no problem, but that calls `proc_close`. 

So in the next release, having `proc_close` on the disable_functions list will simply stop the automatic migration. This is unfortunate but can't really be helped unless, as you say, something changes upstream.

Let me know if you have questions or comments!
