### ISSUE TITLE
Recalculate old transactions with different currency

### ISSUE THREAD

**Issue by erdelyijanos** [firefly-iii/firefly-iii#1319]
I am running Firefly III version 4.7.0

#### Description of my issue:
It is only a feature request:
An auxiliary function would be nice to have (as long as it is not possible to have combined multi currency chart and reports where everything would be shown in one "master" currency)
As I moved to another country I would recalculate all my past transactions to the new currency I use now so as a comparison of costs, earning etc would be possible.
A "hidden function" would recalculate all transactions with the closing currency rate of the transaction day. The original value with its original currency could be put at the end of description field in parentheses.
Would it be hard to implement such an extension?

**Comment by JC5** [comment]
That would be pretty hard to implement. Especially since there are currently no API's that I know of that can offer to do currency conversion for free. 

I have several issues on my list to make Firefly III more multi-currency friendly, especially surrounding the display of several currencies in one chart. However, this is still a WIP and wouldn't really solve your issue.

I think the easiest way to do is by using the category or budget report and convert the totals yourself.
