### ISSUE TITLE
Multi-currency: budgets

### ISSUE THREAD

**Issue by JC5** [firefly-iii/firefly-iii#1350]
As inspired by, amongst others, @Limezy

Let's say a budget magically contains expenses in EUR and in USD. Some questions and thoughts.

Frontpage:
- The chart on the frontpage needs a bar for both currencies.
- The green "left to spend"-box needs to be multi-currency (it might already be).

Budgets page:
- Can users set a budget in two currencies? Or just in the main currency?
- Can users set the available budget (see the top bar at `/budgets`) in multiple currencies? Or just one? If more than one: which ones?
- What will the "spent"-bar do on the `/budgets`-page? 
- What will the spent/left indicators do for each budget on the `/budgets` page?

Budget report:
- The account list and budget list (top left) must show all currencies there are transactions in.
- What will the pie chart do with multi-currency transactions? A second pie-chart? A third? Fourth?
- What will the main chart display? It's already pretty full.
- Expense accounts and multiple currencies: need multiple lines with an indicator which currency it is.
- Same for the top 10 expenses. This will always be skewed towards the currency with the smallest conversion rate. Ie. the RMB and various others.

---

I am very much inclined NOT to do any currency conversions but to leave these amounts side-by-side. I would rather have the user do this themselves to preserve accuracy. There are currently no unpaid currency conversion services that could do this anyway.

**Comment by pkoziol** [comment]
@JC5 I've found one day via [StackOverflow](https://stackoverflow.com/questions/3139879/how-do-i-get-currency-exchange-rates-via-an-api-such-as-google-finance) that Fixer.io uses data published by [European Central Bank](https://www.ecb.europa.eu/stats/policy_and_exchange_rates/euro_reference_exchange_rates/html/index.en.html) as one of the sources (they claim they use 15 sources).

Quick check: conversion 1 USD -> EUR -> PLN results in 1 / 1.2370 * 4.1627 = 3,3652 PLN. That differs from rate published by my National Bank (3,3666) by 0,0014 PLN and by my exchange ((3.3712 + 3.3478)/2 = 3.3595) by ~0,0057 PLN. Close enough I think. Exchange fees will be greater.

Another matter that exchange rates constanty change and you would need to remember historical rates somwhere.

For me, budged using one currency would be enough.

**Comment by pkoziol** [comment]
That's why I was looking for free API and found ECB ;)

**Comment by Limezy** [comment]
@JC5 Thanks for launching this thread !
Let me take some time to think and give you a clear answer !

**Comment by JC5** [comment]
@pkoziol What they offer is agains the base currency, EUR. This is workable, but requires two conversions. Plus, their list is not that extensive. Nevertheless, something to think about. Same goes for Fixer.io. They also offer against EUR only (for free).

**Comment by Limezy** [comment]
## One or multiple currencies in a budget ?

I believe this is the most important question as it has a huge impact on the design, as you pointed it out.
Just to make things clear, we have two questions here :

1. Should we be able to set a budget in different currency that the base one ?
2. Should we be able to input transactions with different currencies in the same budget ?

#### Why multiple currencies ? Because Firefly is to organize your _real_ money

Correct me if I’m wrong but I think Firefly’s philosophy is to be based on your life reality. You want know where your money goes. One € is one €, you want to give it a meaning (groceries or new camera savings), not an abstract $ value based on a moving rate. You will give it a $ value the day you have really transferred it to your $ account !


With this in mind, I would say that a multi-currency Firefly user wouldn’t care about any real time conversion rates or what **would** be the value of an account **if** it was transferred into another currency. This is not a software for currency traders!

This is exactly why I think multi-currency support is important : if you have some €, you want to organize them as €. If you have $, you want to organize them as $, not as an abstracted € values.

> I am very much inclined NOT to do any currency conversions but to leave these amounts side-by-side. I would rather have the user do this themselves to preserve accuracy. There are currently no unpaid currency conversion services that could do this anyway.

As you can see, I ***strongly*** agree.

#### Who are the typical multi-currencies users ?

I could think on several examples :

1. The traveler. This guy lives in Europe and goes for a holiday or business trip to USA.
2. The foreigner employee. This guy is European but works in USA. He is paid (or partly paid) in $ but still has assets / buisness / expenses in €
3. The cryptominer. This guy is paid in € but has some expenses or income in BTC or ETH. This is actually a variation of number 2.

#### Do they need several currencies in their budgets ?


Let's start with guy number 1. He will open a budget or piggy bank `Travel to USA` in € to save for his trip. His trip will include some € expenses (flight tickets, for example) and some $ expenses (lunches, museums, subway...). But does this guy really need a €-$ budget ? 

* The standard guy will just buy his flight tickets, change what he has left to $ and burn them in USA before coming back. No need for multpiple currencies budget.

* The ultra orginized guy will make a budget for his trip (actually this is a budget within a budget) to plan exactly how to burn his $ in USA. This guy really wants to have a great control so he will open several budgets like `Food in USA`, `Museums in USA`, `Transport in USA`... If he opens several budgets, what is the point to have several currencies in one budgets ? He will just have one €-based budget `Flight to USA` and all other will be $-based. This is the best way to do, it sticks to reality, it looks like Firefly's (or all other YNAB things) philosophy.

What about guy number 2 or 3 ? These guys have incomes in two or more currencies on a regular basis. I cannot see why they would like to have a single budget, `Food` for example, that would support those currencies. It's easier and more natural to open `Food in France` as a €-based budget and `Food in USA` as a $-based budget. Same for piggy-banks. It's likely that you will spend your piggy bank in one single currency. Therefore, you can open one $-based budget `New camera`, transfer the money to your € account and put that mony into your `New camera bank` piggy bank.

#### In a nutshell


* My answer to question one is **yes, we sould be able to set budgets in different currencies than the base one.**
* My answer to question two is **no, multiple currencies in the same single budget doesn't seem to add any interesting value to the software.**

## Design changes on the software

#### Front Page

> * The chart on the frontpage needs a bar for both currencies. **Yes**
> * The green "left to spend"-box needs to be multi-currency (it might already be). **Yes**

But I think a better option would be to add a dropdown list under "Dashboard" (just like "Accounts"!) to get two options : Dashboard [€] and Dashboard [$]. I don't think it's a big deal to have those dashboards separated. As I already said you want to stick to real life. In real life you have two sets of accounts. It will look way less messy like that. I believe it's also easier to code as it is basically two times the front page without any modifications. Just need to sort out which budgets / accounts / expenses are in the base currency, which are in the alternate currency.

Good thing is that with this systen, you could even allow to use more than two currencies (hello heavy cryptocurrencies miners) because you basically just provide as many dashboards as alternate currencies the user wants.

#### Budget Page

We can just do the same ! Instead of getting messy with one mixed budget page, two budget pages. One is base currency budgets, other is alternate currency budget page. Easier to read, easier to code...

Same, this will allow the use of even more than two currencies.

#### Budget Report

/!\ Beware I'm not a longterm user of Firefly and didn't use this kind of report for time being. 

Yet I think you can use the same strategy and make a separation between currencies. When doing a report, you will have to choose a currency and will be able to choose only accounts and budgets within this currency.

**Comment by Limezy** [comment]
Note : some might argue that multi currencies users like me might use different Firefly instances, one for each currency, but it would make us loose the transfer between accounts function, which is a critical function in cases like mine where I you want to control very precisely when you can (or need to) make a transfer and how much !

**Comment by JC5** [comment]
> But I think a better option would be to add a dropdown list under "Dashboard" (just like "Accounts"!) to get two options : Dashboard [€] and Dashboard [$]. 

That’s a good idea! Will reply to the rest later but it’s good! :+1:

**Comment by anastas78** [comment]
Some thought on the multicurrency problems from my experience with Firefly III in the last couple of months:
@Limezy has well identified the multicurrency users:
1.	Travellers 
2.	Foreigner employee – in real life people earning and/or spending money in different currencies for some reason 
I would say there is also a combination of the both above, but the only thing which really matters is the view of the program is: what you get as **regular** income (accounts in one or many currency) and also **regular** expenses (in one currency or many currencies).

**One currency income or Traveller** – one will have his income in the default currency and most probably he has all his budgets in that currency. If he has expenses on the credit card the bank will automatically convert them to his card default currency /Firefly default currency/. If he has converted 100 EUR in USD most probably he will create an account “USD dollars” to follow his spending in dollars. In all cases we have a precise rate of the second currency as it will be a transfer from one account to another in Firefly. That rate could easily be used in the budgets and the budget reports in default currency. “At the end of the day” for that guy will be more useful to see that his “trip to USA” has costed him XXX EUR as this is the currency he lives with. 
In this scenario are also all people having their income in one currency and expenses in different currencies (online purchases, bank loan in other currency and so on). 
So definitively we don’t need multicurrency budget. In this case we really don’t need even a budget in different currency. But we need to use the real “buy” rate and have all budgets and reports show the “other” currencies expenses converted to the default and then summed up. (Not the way it happens now in the reports – just mathematically sum EUR and USD per nominal).

**Many currencies income or Foreigner employee**
There are two subpoints here:
-	all expenses (budgets) are in the default currency – this is similar to the case above – we will have a known rate for conversion i.e.  an USD account won’t accept EUR expense without rate. Then all budgets and reports should be converted to default currency and then summed up. 
-	There are **regular** incomes / accounts in default currency and any other currency (i.e. default currency EUR, regular incomes also in USD) and **regular** expenses / budgets in EUR and USD. In my opinion this is the only case where real multicurrency implementation is needed. 

Income </br>(Nr of currencies) | Budgets</br>(   (Nr of currencies) | Multicurrency mode
-- | -- | --
One currency | One currency | NO - Firefly is already   really good
One currency | Two / many | NO - We have to use   the real rate and show everything in default currency
Two / many | One currency | NO - We have to use   the real rate and show everything in default currency
Two / many | The same two / many | YES - Show information per  currency

**Do we need a multicurrency budget?** 

> If you can save money every month on a certain subject, it’s a budget. Groceries are budget. Bills are a budget. If you travel by train occasionally, it’s not a budget.
The rule of thumb is: would you make a real life envelope for it? If yes: budget. If no: category. 

In real life do you have to have two different envelopes for groceries or just one? Let’s have one – with 100 EUR and 100 USD inside. We bring it with us wherever we shop. If the bill is i.e. 105 USD – can we pay it from the envelope? Sure thing – pay 100 USD and change some EUR for 5 USD. But then we have a transaction with rate – a proof we are defaulting to one of the currencies.
If we have two envelopes “USD groceries” and “EUR groceries” – with a bill of 105 USD we have to “touch” some other “USD envelope” to pay the bill and we don’t have a “rate”. 

It could be reasonable to have budgets in different than the default currency, but not multicurrency budget. Nevertheless, we can have expenses in a different currency than the budgets' one – in that case we always have conversion rate inside Firefly and can recalculate to the budgets’ currency.

**The summary of that long post:**
If there is only a conversion of currencies everything except the balance on the front page (in case we have more than one currency account) should be recalculated to the default currency. 
If we have both accounts and budgets in two or more currencies – the “per currency” approach of @Limezy is really good. The “which currencies” question – ones we have in both accounts and budgets.

But as a first step I would imagine it will be easier to correct the budgets and reports to show correctly the first three cases based on saved in Firefly III conversion rate in the default currency and then to extent it to the real multicurrency scenario.

**Comment by JC5** [comment]
Thanks for the extensive post!

To explain what I'm going to do a quick technical explanation. In Firefly III, budgets are separated from "budget limits". Budget limits are the "envelopes" with both a start date and an end date.

This allows you to make a budget "Groceries" with a new envelope every month:

Start | end | amount
--|--|--
1 sep | 30 sep | 250
1 oct | 31 oct | 250

Or perhaps per week or per day or whatever.

My plan is to expand as many charts and views with currency information, in case the user adds a transaction in another currency. So if you have a USD credit card but EUR is your default, these USD transactions should show up separately from EUR transactions. This is already the case for categories (in some places):

![multi-currency](https://user-images.githubusercontent.com/5889984/45749982-ae51e700-bc0d-11e8-87de-b70d1703b2cf.png)

Of course this info is missing in many places (it would say EUR 175 instead of EUR 75 / USD 100). So if you see obvious places, just let me know.

Anyway, likewise, budget charts will show multiple currencies side by side with the caveat that transactions in USD will not affect budget limits in EUR. To enable this the next Firefly III version will have some extra information in the database:

Start | end | amount | currency
--|--|--|--
1 sep | 30 sep | 250 | EUR
1 oct | 31 oct | 250 | EUR

You won't be able to edit it in the beginning.

Later on though, if you wish, you can add multiple budget limits, per currency, if you feel you need them.

Let me know what you think!

**Comment by mikymigs** [comment]
Hello,
This post is very interesting with a lot of good ideas! I stumbled upon it because I wanted to suggest some improvements in the multi-currency support and saw it was already done ;-)

From what I can read, it looks like that the multi-currency issues could be split in different topics:
- support of multi-currency on the front-page dashboard
- support of multi-currency for budgets
- and maybe support in other sections such as reports...

I would personally also add: support of multi-currency for categories. One of the issues I have is that if get gas in France for 70€ and then in the same day, I park my car in Switzerland and pay 4 CHF, if I put these transactions in the same category "car", the graph of the car category expenses will show "74€" of car expenses for that day which is wrong.

FYI: I live in France and work in Switzerland with bank accounts on both sides of the border so this feature is critical to me :-) I'll be glad to help by explaining my real life use-case if that's helpful.

**Comment by mikymigs** [comment]
Hello,

Just found another issue with multi-currency: when creating a transfert between accounts of 2 different currencies, the transfered amount appears in the currency of the source account on the target account and the balance is not updated.

Suggestion: add an option in the transfert to specify the rate that was applied, or even better, allow to select the corresponding entry in the target account and calculate the rate automatically.

Allowing to select the corresponding entry on the target account would also be usefull in general not just for multi-currency use-cases.

**Comment by JC5** [comment]
I’m not entirely sure what you mean, but I will do some digging and bug fixing. 

Automatic currency conversion is already available.

**Comment by JC5** [comment]
I did some experiments but it seems to work fine for me. Could you elaborate?

Since the demo site resets every four hours I've added some screenshots.





![screenshot 2019-02-08 at 04 13 35](https://user-images.githubusercontent.com/5889984/52457040-1622b300-2b58-11e9-94ac-940829ff0cb2.png)
![screenshot 2019-02-08 at 04 13 44](https://user-images.githubusercontent.com/5889984/52457039-1622b300-2b58-11e9-8f7a-c9ea2aede27e.png)
![screenshot 2019-02-08 at 04 13 50](https://user-images.githubusercontent.com/5889984/52457038-1622b300-2b58-11e9-9686-5aa0188bb1d1.png)
![screenshot 2019-02-08 at 04 13 59](https://user-images.githubusercontent.com/5889984/52457037-1622b300-2b58-11e9-8aac-03350de8b04a.png)

![screenshot 2019-02-08 at 04 14 08](https://user-images.githubusercontent.com/5889984/52457036-158a1c80-2b58-11e9-9a20-26f933dc9bc5.png)

**Comment by mikymigs** [comment]
Thx for testing. I should have specified that I created the transfert by converting a withdrawal into a transfert. I never create transfers manually because I import everything from my banks export files and I often have to transform withdrawal into transfers after the import. During the process, even if I specify an account in a different currency, it keeps the source currency in the target account.

**Comment by JC5** [comment]
That's a good one, I'll pick it up. It's a bit of a unicorn because nobody every runs into this. Firefly III can create the transfers automatically, if the accounts are mapped correctly. Is that not working for you?

**Comment by mikymigs** [comment]
Yes, I saw that we can have transfers automatically "recognized" at import but as far as I understand, it requires to have the banking info of the target account in the export file and I don't have that. I guess my bank sucks :-)

**Comment by JC5** [comment]
https://github.com/firefly-iii/firefly-iii/projects/5#card-19937854
