### ISSUE TITLE
Best practice for mixing budget periods

### ISSUE THREAD

**Issue by skuzzle** [firefly-iii/firefly-iii#1357]
What is a little unclear to me is, how to mix different budgeting periods (besides switching between periods is a little inconvenient).
Is there some best practice or advice on how to use different periods? What is especially unclear to me is, how does firefly handle the 'amount available' value for different periods? If I put in a certain value for a year but do most of my budgeting month wise, there could arise some inconsistencies if the monthly values do not add up excatly to the yearly value.

**Comment by JC5** [comment]
The "available budget" box takes its value from the /budgets page (top bar). Then, any amount spent _inside_ budgets is subtracted from it.

And yes, such consistencies could arise, so Firefly III doesn't really handle them at all. The box with "amount available"-amount is not divided / 12 (yearly viewed per month) or multiplied * 4 (weekly viewed by month).

If the available amount is set for the same period as the one you're viewing (ie. same month) it will work. Otherwise, it won't.
