### ISSUE TITLE
Use Spectre api to import from multiple banks (feature request)

### ISSUE THREAD

**Issue by Chluz** [firefly-iii/firefly-iii#1358]
I am running Firefly III version 4.7.2.2

#### Description of my issue:
Not an issue, more of a feature request: possibility to import from multiple different banks in Spectre api

#### Other important details (log files, system info):

docker install

**Comment by JC5** [comment]
I'm not sure if this is something I influence. You pick your bank and login at the Spectre-side, not at Firefly III. Right?

**Comment by Chluz** [comment]
Hi JC5, 
that was a very quick answer.

I got prompted to select a bank the first time that I clicked spectre import.
For every time after that it didn't prompt me to select a bank through spectre anymore, it just showed the list of accounts from the previously selected bank.
Am I using it wrong ?

Thanks !

**Comment by JC5** [comment]
No, I'll have to check it out. I remember it would ask again.

**Comment by Chluz** [comment]
Hi JC5, 

I've just realised that if I restart the docker container, firefly will then ask spectre to select a new bank again. 
The only issue then is that if you try to reimport from a bank you already used in spectre, it will tell you the bank is already registered (and you need to delete it from spectre before being able to import from it again).

I also have a question about the imports: what happens when the same transactions are being imported, are they detected as duplicates ? I think they are currently being imported again

Thanks again for your help !

Charles

**Comment by JC5** [comment]
Thanks for the feedback Charles, I'll do some digging this week. Won't be before Wednesday I'm afraid but I'm on the case!

**Comment by JC5** [comment]
OK so Firefly III is currently programmed to re-use previous "logins", which is why it's simply downloading from the same bank again.

Until I fix this, you can go [here](https://www.saltedge.com/clients/customers), select "default_ff3_customer" and list all the logins connected to the customer. After you delete them, Firefly III will ask you again which bank to connect to.

You can follow issue #1388 for progress on a new feature where you'll be able to select other banks.

Let me know if this works for you!

**Comment by Chluz** [comment]
Hi JC5, thanks for the info ! 
I'll try what you suggested and report back, and thank you very much for looking into the topic.
