### ISSUE TITLE
How to handle erroneous transactions?

### ISSUE THREAD

**Issue by ErikFontanel** [firefly-iii/firefly-iii#1370]
I am running Firefly III version 4.7.2.2

#### Description of my issue:
I use firefly to manage a bank account shared with my girlfriend. We both transfer money in this account. Sometimes I accidentally transfer the wrong amount or transfer the same amount twice. What is the best way to correct these transactions so that it does not 'inflate' the monthly income/spending amounts? I could always delete them, but my knowledge of double-entry bookkeeping is not good enough to know if that's the right way.

#### Steps to reproduce 
- Create two transactions with the same amounts

**Comment by JC5** [comment]
The easiest way is to simply delete the incorrect one. In double-entry bookkeeping you can do this, as long as both parties do this, so the books are balanced again. Since Firefly III handles this for you, it's the easiest.

If you make errors in your real life transactions, for example moving the wrong amount and correcting it later (using internet banking for example) it is a good habit to copy these "mistakes" into Firefly III. That makes it easier to compare Firefly III's records with your bank's records.

**Comment by ErikFontanel** [comment]
Thanks, scenario 2 is how I currently do it. Although the values for spent/earned this month are technically correct, it conveys a 'wrong' message. Eg. if I erroneously transfer € 200 instead of € 100, and I transfer € 100 back, it looks like I earned € 200 and spent € 100 instead of € 100. I might delete those transactions then. But will they be skipped with the next import?

**Comment by JC5** [comment]
Ah OK, I see. That cannot be avoided. I believe that deleted transactions will be imported again, but I have to check it to be sure.
