### ISSUE TITLE
setting date ranges explicitly when creating a budget

### ISSUE THREAD

**Issue by SimonHoenscheid** [firefly-iii/firefly-iii#1422]
I am running Firefly III version 4.7.3

#### Description of my issue:

Currently it looks like a budget is created for the time range currently set. It would be easier if the date range would be asked for during creation

**Comment by JC5** [comment]
Yes, and this is intentional. Most users browse Firefly III using the date-range they're most comfortable with, either weekly, monthly or even longer. Budgets will be created accordingly for usability. I could add the question, but 99% of the users would use the default values anyway.

I can expand the table at /budgets so it will say "applies to date range x - y" to make it more clear what the budget is set for?
