### ISSUE TITLE
Transactions: "SEPA Mandate Identifier" not visible in edit mode

### ISSUE THREAD

**Issue by gavu** [firefly-iii/firefly-iii#1428]
I am running Firefly III version 4.7.3

#### Description of my issue:

My importer adds transactions to the "SEPA Mandate Identifier" since it was not able to add to the notes field some time ago. I can see the field and it's contents on `show` pages but not on edit.

I would move everything from `SEPA` to `Notes` since I only use this field to add custom information. Is there any way to do this? even manually?

#### Steps to reproduce 

the field is not visible on the demo page also

**Comment by JC5** [comment]
Yes, I remember that. It would be appended to the notes. I completely forgot about it, until now. Sorry about that!

You can find the SEPA fields in the table `journal_meta`. IIRC their contents are not encrypted. You should be able to lift their contents to the notes of the particular journals.

The fields are read-only by design.

**Comment by gavu** [comment]
thanks for the hint, however, I just checked the `journal_meta` table and only found `data` and `hash`, among other columns... any help as to where I can find the SEPA fields would be greatly appreciated.

**Comment by JC5** [comment]
The content of the table itself should list all the data you are looking for.
