### ISSUE TITLE
Paying back budgeted expenses

### ISSUE THREAD

**Issue by skuzzle** [firefly-iii/firefly-iii#1448]
Hi,

I have again a question on how to best use firefly in a certain use case: 
* I have a yearly budget for vacations
* Now I do some booking (flights, hotel, etc.) which also includes expenses for my wife
* Later on, she pays me back some of the money I laid out for her

Now the budget in firefly still states that I have spent the whole amount, while I actually got some money back.
I believe that firefly _could_ follow the links on transactions to update the budgets, but that would lead to different problems like: what happens if the linked incoming transaction happens in a later budget period? It would then need to update a budget from an earlier period though the transaction itself happened later. I'm not sure if this feels right.

What is your point on this, @JC5 ?

**Comment by JC5** [comment]
Basically, I've decided to ignore the problem. It's not productive for Firefly III to be opinionated about this. I had a similar problem (even within the same month) when you split a dinner bill with friends, and they send you money.

* Enlarge the budget, so it goes from 100,- to 100,- + whatever your friends send back?
* Shrink the expense, so it seems you only paid 30,- (or whatever your share is)?

Neither solutions really solve the problem. It gets even more complex when, as you say, the expenses and deposits are spread over multiple periods.

What I do right now is the following. It isn't perfect but it adds the least amount of "magic behaviour" while still solving the problem. What I do is, I increase the budget with the amount I expect to get back, and I increase the amount of money in the "available between" bar with that same amount.

This results in the following effects:

- The budget is decreased with only my own expenses.
- I still have the "correct" amount on my checking account (thanks to the income)

The disadvantage is that budgets grow and shrink according to external events, as opposed to shrinking because I spend less money.

**Comment by skuzzle** [comment]
That sounds like a reasonable work around. Thanks.
