### ISSUE TITLE
Allow duplicates during csv import

### ISSUE THREAD

**Issue by Bullenj01** [firefly-iii/firefly-iii#1456]
I am running Firefly III version 4.7.3.2

#### Description of my issue:
I'm seeing an issues where I'm losing a few transactions during import of csv.  I've tracked them down and found that they are transactions that are probably being flagged as duplicates.  For example, going to lunch with the wife we paid separately but the price was the same.  The other time I found it was when my employer paid me twice on the same day for the same amount.  

#### Steps to reproduce
import in something like this, you should only see one 400 dollar transaction
Account,01/22/18,check stub,400
Account,01/22/18,check stub,400

**Comment by JC5** [comment]
This is by design, and unfortunately it will not be changed.

If you want to make sure your CSV transactions are treated as unique entries, they _must_ have unique data. Either you or your bank must include some kind of unique field: transaction ID, line number, time of transaction, anything.

If your bank doesn't provide enough meta data to actually distinguish transactions there's nothing I can do.

A solution would be to add a column to your CSV files yourself using Excel or Numbers. You could simply call it "line-number" (if your CSV file has headers) and fill it with 1,2,3,4 etc. If you map this column to the "external ID" field in Firefly III it will register as unique, thus solving your problem.

**Comment by pommetjehorlepiep** [comment]
I tried to import a CSV and ran into exactly the same problem: duplicates.

Your comment, @JC5, I find a bit of an easy way out.
At least an option to either ignore / include duplicate transactions would a simple solution to this problem i would think.

The idea of just manipulating the CSV file, adding a column etc to make it unique is just a crap solution.
Duplicates happen and therefore the import should be able to handle it.

**Comment by techytuppers** [comment]
@pommetjehorlepiep there are more constructive and less aggressive ways to phrase your comment

**Comment by pommetjehorlepiep** [comment]
Sorry, didn't mean to.

**Comment by Bullenj01** [comment]
I did the random column thing and it wasn't bad just enter a random number generator formula and drag it to the bottom.  Takes 10 seconds.  You can ignore the column during import and it will still work.  What may work better for this is to allow duplicates when the duplicate exist on the CSV being imported, because its coming from a bank so is obviously not a typo, but do not allow duplicates with existing transactions in the database.  Or just leave it as its not a huge inconvenience.

**Comment by JC5** [comment]
It's OK, I understand the frustration. It is indeed a cop-out, and there is no technical reason not to do it. 

The thing is that duplicates should _not_ happen. Transactions are unique. I know several banks have started to add identifiers to their transactions (Rabobank for example) for this exact same reason. Their use case was slightly different: If you would but the same chocolate candy bar in the same minute using your contactless card, the file wouldn't show a notable difference between the two lines. 

I need transactions to be unique because it allows users to upload the same transactions twice. Some users download transactions daily and have Firefly III take care of the duplicate entries. There are banks with crappy export routines that will export lines twice.

Right now you can run into one problem: you have "double" transactions, and you want Firefly III to import both. But it doesn't.

If I add an option, you can have two problems: either Firefly III won't import your double transactions, but you want it to, or Firefly III has imported all your double transactions, but you didn't want it to. This can potentially break two use cases instead of just one.

If you want me to, a script to add a unique identifier to a CSV file is easily written and shared with you all.

**Comment by pommetjehorlepiep** [comment]
When transactions are already existing (ie. entered/loaded previously) then it would make sense to ignore duplicates. 

I like the script option, but why not put this in the UI. Just a checkbox and firefly will make all entries being loaded unique (current time + row no does the trick)

This takes the pain away from altering the CSV file after trying to work out where the duplicate is. 
At the same time, user will have the option to in/exclude duplicates.
