### ISSUE TITLE
age of money

### ISSUE THREAD

**Issue by pvinis** [firefly-iii/firefly-iii#1485]
**Description**
Please describe your feature request:

- I would like Firefly III to have a report for "age of money", similar to what ynab has.

**Solution**
Describe what your feature would add to Firefly III.

I dont know exactly how it is calculated, but im sure we can figure it out. Then we could have it as one report in the reports page.

**Comment by JC5** [comment]
Where can I find that report in YNAB?

**Comment by pvinis** [comment]
its on the top right on the main page.
<img width="1021" alt="screen shot 2018-06-15 at 07 54 43" src="https://user-images.githubusercontent.com/100233/41452306-981b763c-7071-11e8-9e14-8da2f042489e.png">

two links also:
https://www.youneedabudget.com/how-old-is-your-money/
https://www.youneedabudget.com/guides/age-your-money/

**Comment by JC5** [comment]
That won't work with Firefly III, because your income is not directly tied to your budgets. In YNAB, that what isn't budgeted is "transferred" to the next month (thus aging your money). In Firefly III, it doesn't work like that.

Firefly III assumes that you will budget for each month in advance. July is coming up, so you would set up your budgets (based on this month perhaps?) and come out at amount X. Let's say 1000,-.

You should then place exactly 1000,- on your checking account. The rest of your money should be in your savings account.

Spend that amount. What's left goes back to your savings account. Any income that month? Also goes to your savings account. You can read about this in the [grand theory](http://firefly-iii.readthedocs.io/en/latest/about/grand-theory.html).

Money doesn't "age" in Firefly III like it does with YNAB.
