### ISSUE TITLE
Missing translations and/or translatable strings on Crowdin

### ISSUE THREAD

**Issue by lucavallerini** [firefly-iii/firefly-iii#1504]
Hello!

I'm revising the Italian translation and I can't manage to find these strings in the user profile page anywhere on Crowdin (see screenshot).

![ff3-missing-string](https://user-images.githubusercontent.com/2808166/41810261-f07c8cc2-76fb-11e8-8df9-46e088b35065.png)

On the 2FA authentication dialog instead, the dialog is completely in English even though on Crowdin all strings are translated.

![ff3-2fa-missing-string](https://user-images.githubusercontent.com/2808166/41810343-32546830-76fd-11e8-8186-5e841127181a.png)

**Comment by JC5** [comment]
The OAuth translations are not yet included in the page, because it's built using Javascript. I am not proficient enough to fix that. I've tried several solutions but no luck so far.

Once I know _how_ to translate them, they will be included in the files.

As for the second example: at that moment I do not know yet who the user is, so I can't access their preferred language. I know the strings are on Crowdin but unfortunately they're not usable.

**Comment by lucavallerini** [comment]
OK for the first issue.

> As for the second example: at that moment I do not know yet who the user is, so I can't access their preferred language. I know the strings are on Crowdin but unfortunately they're not usable.

Do you mean that you need the user authenticated to retrieve its language preference?

**Comment by JC5** [comment]
Yes. I need full authentication before I can access their preferences.

**Comment by lucavallerini** [comment]
OK, nothing you can do then, good to know.
