### ISSUE TITLE
Someone selling Firefly III?

### ISSUE THREAD

**Issue by issmirnov** [firefly-iii/firefly-iii#1507]
While looking for third party reviews I stumbled upon https://openitstore.com/product/firefly-iii/. It's unclear what this site is offering, and I didn't find any links with attribution to James Cole or this github repo. The way the text is phrased it makes one believe they are the ones who made it.

Seems sketchy, so flagging it here.

**Comment by JC5** [comment]
Yep. I've been contacted several times by users who want to sell hosted instances of Firefly III. Given the license of Firefly III, this is totally possible and there's not much I can (or want to) do about it. Most of them promise a kickback but as you can see, I'm still not driving a Ferrari :wink:

I would personally not recommend using such hosters, but nowadays the magic of Docker, Heroku and other hosted systems allow you to do this fairly securely. What I'm missing on this particular site though is a reference to the GPL and a link back, which I think is mandatory. Overall, it does not seem to be a very professional site.

I'll get in touch with them about the lack of links. Otherwise, I hope my users are smart enough to make their own choice.

Thanks for bringing this to my attention! :+1:

**Comment by ndecaris** [comment]
hi there,

i work for openitstore : so i can explain our point of view. We don't sell firefly-iii, we just sell the hosting of firefly-iii with installation software, upgrade software to the last release, secure communication (ssl), location depending on the customers care, Backup/restore users data, monitor access, ...

Sorry to not respect the mandatory "things", like gpl reference => we will make it clear for visitors. We also make clear that James Cole is the major contributor.
There is 2 links back to the project : one for the features, and one for the demo.

Our site is not so professional because we just become to be a foss provider, so people who can't use and don't understand self-hosted systems like :docker, heriku, ..., can access to such great softwares.

If you need help james to get your own cloud version of firefly-iii : fell free to ask us !!! So this is perhaps the way to drive a ferrari.

and like others providers, if we have enough customers to give back to the project, we will do it !!!

the best, NIcolas
