### ISSUE TITLE
Reports: Cannot select revenue account

### ISSUE THREAD

**Issue by gavu** [firefly-iii/firefly-iii#1516]
**Bug description**
I am running Firefly III version 4.7.4

I was trying to see how my salary evolved during the past years, went to `reports`, selected `Expense/revenue account report` and tried to select the revenue account matching my employer's transactions

The SelectBox shows 5 Accounts + `(no name)` + `Select all` and in reality I have over 200 expense and revenue accounts. Even using the built in search box provides no results.

**Bonus points**
![2018-06-30 07_19_45-reports firefly iii](https://user-images.githubusercontent.com/3742238/42121818-986d1c64-7c36-11e8-8546-2074b37ea3a2.png)

**Comment by JC5** [comment]
The expense / revenue report is meant for accounts that are listed **both** as expense accounts AND as revenue accounts. Examples include: the tax services because you could receive and pay taxes or the store you work at (because you could buy lunch there for example).

The easiest way to see what you're looking for is either the category report (if Salary is a category) or the account page itself.

**Comment by JC5** [comment]
You could trick the system however by manually creating an expense account with the same name as your employer.

**Comment by gavu** [comment]
Thanks for the hints.

The account page itself doesn't really help, I mean the graph part, because the line is showing only negative values (as we already had this discussion, I see your point in showing the negative values), however maybe add the option to show a graph for the values to help users create such reports, it's just a perk, or course. The transaction table is accurate, of course, but not easily readable.

I do not have a category for my income account is actually a good idea!

Thanks and have a great weekend

**Comment by gavu** [comment]
Cancel that. I found it under `categories/show/*/all`
