### ISSUE TITLE
Deleting transaction brings you back to home page

### ISSUE THREAD

**Issue by lucavallerini** [firefly-iii/firefly-iii#1517]
Version 4.7.4, issue replicable to the demo site as well.

When I delete a transaction directly from an account or category overview, after deletion Firefly III does not bring you back to the previous screen but to the home page.

There is no such problem on the "Transactions" section and it seems to me that this is the right behaviour. 

If instead this is the behavior intended I apologize.

**Comment by JC5** [comment]
Often when you delete an object Firefly III cannot send you back where you came from: the object is gone.

This is assuming you delete a transaction from this page: `/transactions/show/*`.

When the URL contains "show", Firefly III will assume this is the page of the object you just deleted. Firefly III knows this object no longer exists so it redirects you to the index instead.

However Firefly III cannot see that `/accounts/show/*` is different from `/transactions/show/*`, which is why the redirect is incorrect.

There is a solution but it has low priority to implement it. So it is not exactly intended but a fix won't be in the next version, I'm afraid.
