### ISSUE TITLE
Customization of colours

### ISSUE THREAD

**Issue by Ircghost** [firefly-iii/firefly-iii#1518]
Would it be possible to customize colours as a user? For example right now I would rather see income as green and expense as red / blue. Having expenses as green confuses me at first sight.

Also, I can imagine that the current colours, light green and light blue, could be difficult for colour blind people.

Keep up the good work and thank you for your time!
Mark

**Comment by JC5** [comment]
Expenses are red, income is green and transfers are blue. 

Any specific pages where this is reversed could be expense account pages such as stores or shops. That is because transactions are displayed from the perspective of the store: and for the store they are income. 

If you share specific examples I can look into them.

**Comment by Ircghost** [comment]
Hi James,

Please find attached example of the reports. Where income is light blue and expenses green.
![exampe 1](https://user-images.githubusercontent.com/36815609/42131908-3631a010-7d0d-11e8-9931-a6cc528b4142.png)

Same setup for other reports.

Both in reports and other pages I do of course see the actual numbers in red and green as expected.

**Comment by JC5** [comment]
Aha, the reports! Those can be confusing, yes.

Firefly III uses a default color sets for each next bar. I believe the order is blue, green, yellow, orange, etc. All charts use the same code for portability. So, first bar is blue, then it's green, etc.

I'll try to see if it is easy to customise this. It won't be an option but the colours can make more sense indeed.
