### ISSUE TITLE
Pre-filled budget amounts

### ISSUE THREAD

**Issue by Ircghost** [firefly-iii/firefly-iii#1546]
Hi James,

**Description**
Currently I have a few budgets assigned, one is for example gaming. I have set myself a limit of i.e. 30 Euros. No matter what.  Currently I need to manually go forward to coming months and add my default amounts.

I think it would be convenient if based on some logic (see below), this amount would be automatically filled in.

**Solution**
I was trying to think of a solution, and with every idea it becomes more difficult. Maybe in a far future it would be great to have predictive budget settings.

In the meantime possible solutions could be:
- Copy budget amount per category from previous month
- Copy budget amount per category from a set standard
- Copy budget amount per category from actual used budget previous month (the more you expand on this last one the more difficult it becomes... what about seasons, exceptions, averages, means... ;) )

What do you think? I can imagine that this also is against the idea of Firefly, as in, being aware of your budget.

**Comment by JC5** [comment]
It used to be possible in the past but I removed it again. I ran into the problems that you no doubt are thinking about. Budgets can be set for arbitrary amounts. When to do this, and when not to do this? Many edge cases popup making it very difficult to do this reliably.

Instead of adding more complexity I decided to move the task to the user.

**Comment by Ircghost** [comment]
I understand your reasoning!
