### ISSUE TITLE
Quick actions for repeated similar transactions?

### ISSUE THREAD

**Issue by claudius-hubig** [firefly-iii/firefly-iii#1567]
Dear developer,

I just started using Firefly III (version 4.7.5.1) and so far I am very impressed by its extended capabilities. One thing somewhat missing for me are “quick actions”. The main purpose of this for me would be me repeating lunch expenses which I’d like to quickly report. The category, payee and description stays the same whereas I’d like to change the amount.

**Solution**
Configurable quick actions with shortcut buttons from the overview screen. When clicked, they take you to a pre-filled transaction entry window where additional data can be filled in and the transaction submitted.

**What are alternatives?**
At the moment, I have a rule to set the category if payee and description match the expectations. This still requires filling in the payee and description in addition to the current amount. In place of a quick action from the overview, I have a link directly to the transaction entry page on my phone’s home screen.

**Comment by JC5** [comment]
Hey, I'm glad you like the app!

Because of the increased complexity and the small use case, I've decided some time ago not to add quick-links, buttons or shortcuts other than the ones present already.

I appreciate the problem, because I have it myself as well.

The solution you've suggested yourself can be extended to set any field you want for your particular use case: you can set the source and destination amounts, description, category and budget.

In theory, it should be enough to make a rule that triggers on description "lunch-work" with a specific amount. The actions could include setting all other fields, including a more user friendly description (ie. "Lunch at work").

**Comment by claudius-hubig** [comment]
OK, that’s of course understandable!

For what it’s worth, I’ve amended the `create.js` in `public/js/ff/transactions/single` just now to include a function

```
function setTemplatedValues() {
    console.log("Setting templated values.");
    let url = new URL(location.href);
    let searchParams = new URLSearchParams(url.search);
    let params = ["description", "destination_name", "category"];
    var param_id;
    for (param_id in params) {
	let param = params[param_id]
	val = searchParams.get("templated_"+param);
        if (val != null) {
	    $('input[name="'+param+'"]').val(val);
	    console.log("  '"+param+"' set to '"+val+"'.");
	} else {
	    console.log("  '"+param+"' not set.");
	}
    }
    {   val = searchParams.get("templated_focus");
	if (val != null) {
	    $('#ffInput_'+val).focus();
	    console.log("  Focus set to '"+val+"'.");
	} else {
	    console.log("  Focus not set.");
	}
    }
}
```

which is called at the end of the document.ready-block. I honestly have no idea how Javascript works and can imagine that there’s a big cross-site-scripting problem there, but with this, a link like e.g.

`firefly-iii/transactions/create/withdrawal?templated_description=Lunch&templated_destination_name=Lunch Restaurant&templated_focus=amount&templated_category=Lunch Category`

seems to pre-propulate the fields and set focus to the `amount` field. Since I can just add a quick link to that URI to my homescreen, I’m happy :-)

**Comment by JC5** [comment]
That should work! Make sure you re-apply that piece of code when you upgrade. :+1:
