### ISSUE TITLE
Budget period setting is unclear & deficient

### ISSUE THREAD

**Issue by BinarySpike** [firefly-iii/firefly-iii#1581]
It looks like setting the budget period is done via Preferences->Layout->View Range.

The description states:
"Some charts are automatically grouped in periods. What period would you prefer?"

This is unclear that it affects the budget period, especially when the budget help page says you can change the period in preferences.

Additionally, I have a need for a bi-weekly (once every two weeks) and semi-monthly (1st-15th and 16-28|30|31st) period.

**Comment by JC5** [comment]
I will expand the info to mention the budgets, good idea! This wasn't the case in the past, and I never thought to edit it. I have pushed new strings to Crowdin as well.

Bi-weekly and semi-monthly are not periods I'm going to support I'm afraid.

**Comment by BinarySpike** [comment]
Bother,

Is there any reason why?  Is the budget period tied to something else hard to manage?  I'd be interested in taking a poke at it.

**Comment by JC5** [comment]
Are these the periods you get paid, by any chance?

It's not about difficulty. Although the periods are irregular,  jump over months _and_ years, and need a lot of manual calculations to get right, but it could be managed. If you're sure that you have the right set of two weeks, because when the year changes these periods overlap.

This is less of a problem for half-months but I just don't see the advantage of the periods you suggest. It could be useful when you follow your paycheck but that's a bad habit so it's not a valid reason. 

Most bills arrive monthly. Exceptions are duly noted (my gym charges once a week and it's very annoying). Months have different lengths but they won't change, can easily be compared over time and are tied in with most, of not all bill periods for all major insurance companies, land lords, and employers.

Having said that a lot of temp agencies pay weekly or bi-weekly but I would suggest shifting your own financial rhythm to a monthly one is easier to do and will save you money in the long run. It disconnects you from your income which allows you to save money too.

This ties in with the [way Firefly III is build](http://firefly-iii.readthedocs.io/en/latest/about/grand-theory.html).

**Comment by JC5** [comment]
Thanks man, appreciate it. Thanks for the feedback too. I see your issue, I've written it down, but be aware that the list is long :wink:
