### ISSUE TITLE
Create or Import backup from user interface

### ISSUE THREAD

**Issue by MichelFreund** [firefly-iii/firefly-iii#1602]
**Description**

I intend to deliver an install of Firefly III to a not-so-much IT expert as myself. A critical feature would however be, an easy way to make a backup file to local machine which you can later import back as a failsafe. 

**Solution**
Create an create backup file button and an import backup button with according functionality

**What are alternatives?**
I would be able to make a database dump myself, but thats rather complicated for someone who doesnt understand the technique

**Comment by JC5** [comment]
I'm sorry, but I think it's of the scope of Firefly III.

I know it would be more user friendly, and that's certainly something I can appreciate, but I feel that data(base) backups are ultimately the user's responsibility. It would basically mean that I have to copy what database software can do faster and better.

There are instructions in [the documentation](http://firefly-iii.readthedocs.io/en/latest/installation/backup.html) which can be made more user friendly of course, but that will be the extend of it.

**Comment by MichelFreund** [comment]
Hi JC5,

I surely do understand your statement on the scope of Firefly III. My argument is though, that you have got a seriously good financial product (the core scope of Firefly III) which might even be the best around. 

At this moment however, it is only available to IT specialists, who can do database dumps. To my perspective, thats a pity because you miss a huge potential in users who might have been able to save money using your program if only a few workarounds for IT processes like backupping an administration are available.

**Comment by JC5** [comment]
You have to realize that Firefly III will never be "easy to install" (this is a relative term of course). A button in the user interface is always going to be pointless because any user who can install Firefly III can make backups themselves.

Users who cannot make database backups and still manage to install Firefly III use services like Sandstorm, Heroku, Yunohost or Softaculous. And these services come with backups provided.

There is no installation method where the button would be useful. Either you can install it yourself and you won't need the button, or you can't and you rely on your installation provider.
