### ISSUE TITLE
Cron job on web hosting with restrictions

### ISSUE THREAD

**Issue by Bubka** [firefly-iii/firefly-iii#1603]
I am running Firefly III version 4.7.5.1

Hello,

I use several recurring transactions so I need to set up the cron job. My firefly instance run on a web hosting on which I can set cron job but with some restrictions:
- commands have to be embedded in a php file
- jobs cannot be run every minute but every hour at best

Regarding the php file, is it possible to directly call one of the Laravel files instead of using the artisan cmdline?
Regarding the cycle, is it an issue to set hourly execution?

Thanks

**Comment by JC5** [comment]
The cycle will probably not fire when you set it to every hour. I have a few cards to make this process easier because frankly, the tools provided by Laravel do not work. Firing up the entire site every minute is not very resource-friendly.

I hope to come up with a new cron job (next release, perhaps the one after that) that will only need to be fired once a day to work.

I am not sure if I can "embed" them in a PHP file, but there might be trick there as well.

**Comment by Bubka** [comment]
Ok, thanks for the answer.

I have 20 recurring transactions so I would be very happy if i could get a workaround since you release a modified feature.

Is there a way to generate [a batch of] recurring transactions « manually », without the scheduler? i.e using another artisan command or one of the API end-point.

**Comment by JC5** [comment]
No there's nothing else available yet. I've focused on releasing the actual feature first. I'm afraid they'll have to wait a bit before they can be fired.

**Comment by Bubka** [comment]
Just for the record : i don’t expect the solution to come from you, i am willing to code something (i know php) if necessary. I just need some advise|help to identify a way to get a workaround.

**Comment by JC5** [comment]
No problem. I'm working on a special URL that does the same. The only difference will be that it requires the "command line token" from `/profile` to work. It'll be mentioned in the next changelog, so keep an eye out for it.

**Comment by JC5** [comment]
The new release has a better cron job function:

https://firefly-iii.readthedocs.io/en/latest/installation/cronjob.html

**Comment by Bubka** [comment]
Hi James,
Thanks for the head up.

The new dedicated url `/cron/run/<token>` is great, i was able to set my cron job on my webhosting while it has restricted capabilities.

Just a question: the <kbd>curl</kbd> command returns me a webpage saying i don't have permission to access `https://<myWebsite>/cron/run/<myToken>`

Is it the expected behaviour ? Does it trigger recurring transactions anyway ?
If I open the cron url in my browser (being authenticated) the response in different, something like
> Recurring transactions have been created sueecefully

**Comment by JC5** [comment]
There's no difference from Firefly III's perspective. I've tested it and curl seems to work.

Perhaps your webserver blocks cURL requests. It's a common enough thing. 

Try ` curl -A "Mozilla/5.0" <url>` and see what it says.

**Comment by jinformatique** [comment]
Hi James,

I'm running my FF3 locally. I just upgraded to 4.7.9. Whether I run the cronjob or the curl, I got the message:
_The recurring transaction cron job did not fire._

```
curl http://localhost.home/firefly-iii/public/cron/run/32…
The recurring transaction cron job did not fire.%
curl -A "Mozilla/5.0" http://localhost.home/firefly-iii/public/cron/run/32…
The recurring transaction cron job did not fire.%
```

```
sudo /usr/bin/php /home/jean/web/firefly-iii/artisan firefly:cron
The recurring transaction cron job did not fire.
More feedback on the cron jobs can be found in the log files.

```
Which log files is it talking about? Because there is nothing new in firefly-iii/storage/logs


Debug information generated at 2019-01-29 12:08:46 UTC for Firefly III version **4.7.9**.

| Variable | Content |
| --- | --- |
| FF version | 4.7.9 |
| FF API version | 0.9.0 |
| App environment | local |
| App debug mode | true |
| App cache driver | file |
| App logging | , daily |
| PHP version | 7.2.10-0ubuntu0.18.04.1 |
| Display errors | Off |
| Session start | 2019-01-01 00:00:00 |
| Session end | 2019-01-31 23:59:59 |
| Session first | 2018-01-01 00:00:00 |
| Error reporting | ALL errors |
| Host | Linux |
| Interface | apache2handler |
| UserID | 1 |
| Attempt at "en" | false |
| Attempt at "English" | false |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| DB drivers | mysql, sqlite |
| Current driver | sqlite |
| Login provider |   |
| Storage disks | local-upload  |
| Using Sandstorm? | no |
| Is Sandstorm (.env) | false |
| Is Docker (.env) | false |
| bunq uses sandbox | false |
| Trusted proxies (.env) |  |
| User agent | Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:64.0) Gecko/20100101 Firefox/64.0 |
| Loaded extensions | Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, sodium, session, standard, apache2handler, mysqlnd, PDO, xml, bcmath, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, iconv, intl, json, ldap, exif, mysqli, pdo_mysql, pdo_sqlite, Phar, posix, readline, shmop, SimpleXML, sockets, sqlite3, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xmlreader, xmlwriter, xsl, zip, Zend OPcache |

**Comment by JC5** [comment]
The job will not fire until there is something to do. I expect it will give you a response after about a day.

**Comment by jinformatique** [comment]
Still, I runned it every other day and I got the same message:
```
The recurring transaction cron job fired successfully.
More feedback on the cron jobs can be found in the log files.
```

I have a recurring transaction set on the 1st and it did not fire.

**Comment by JC5** [comment]
Wait, do you run it every day or do you skip a day?

**Comment by JC5** [comment]
Sorry, Firefly III really needs a daily occurring cron job. I’ll think about a manual mode but I can’t give it a lot of priority I’m afraid.
