### ISSUE TITLE
Password reset issue

### ISSUE THREAD

**Issue by MacPaille** [firefly-iii/firefly-iii#1611]
I am running Firefly III version 4.7.5.3

**Description**
I did a mistake and lost my account password. For sure I never setup the mail part so my installation can't send my reset password email.

As I have access to the database I can get the token to be used to reset my account. Could you give me the link I should use to be able to reset my password?

Thanks!

**Comment by MacPaille** [comment]
I tried with the token I find in the DB but it says it's invalid...
I'm also checking the logs in /storage/logs but I have nothing except a PHP error

> [2018-08-15 09:28:20] local.ERROR: Connection could not be established with host  [php_network_getaddresses: getaddrinfo failed: Name or service not known #0]

Do I need to do something special to the token I get from the table password_resets?

**Comment by JC5** [comment]
You're right, I apologise. The link in your database is encrypted.

In order to read the message and get the link, the easiest way to go is (in this order):

- Delete the entry from `password_resets`
- Open your `.env` file and change `APP_LOG_LEVEL` to `debug` (if not already the case)
- Open your `.env` file and change `MAIL_DRIVER` to `log` (if not already the case)
- Open directory `/storage/logs` and delete all files except `.gitignore`.

Then fill in the password reset form again. The email that Firefly III will try to send is in your `/storage/logs` directory. Just open the log files, and the link will be there.

**Comment by MacPaille** [comment]
It worked thx a lot. My bad I forgot the .env file and I was changing the values in the php files (in /config) but did not help :)

I was able to recover my account! Thanks!

**Comment by MacPaille** [comment]
Ha and by installing sendmail on my Pi and changing the driver to sendmail I get the reset email :)
