### ISSUE TITLE
Shared budgets

### ISSUE THREAD

**Issue by dicastro** [firefly-iii/firefly-iii#1612]
In the same way that there are shared accounts, I would like to have shared budgets. And to be able to differentiate between shared expenses and personal expenses.

What I have thought is to prefix the budgets with something that tells me if it is personal or shared.

Is there a more elegant way of achieving this?

Is Firefly multi-account? Can I have an account (login) to manage my personal expenses and another account to manage my shared expenses

**Comment by JC5** [comment]
I'm sorry, this isn't possible. Shared accounts are only an optical illusion. Changing the status to "shared" is just a name, nothing else. I never built something like that for budgets because it's not that useful to do. My own shared budgets (I have them too) are simply called "Shared groceries", "shared bills", etc.

What I do to separate shared expenses and my own expenses is using the report functions for both my own accounts and for my shared accounts. I have a bookmark like this:

`/reports/default/1,2,3/currentMonthStart/currentMonthEnd`

and this:

`/reports/default/4,5/currentMonthStart/currentMonthEnd`

For my own and my shared accounts respectively. And yes, all the budgets will end up in both reports but personally it's something I can live with.

Firefly III is multi-user, which means that you can add as many user accounts if you want to. It's just that by default this is disabled, to prevent abuse if people put their Firefly III installations online.

To enable the registration of more than one account, go to `/admin/configuration` and remove the checkbox at "Disable user registration". If you then logout you will see that the button "Register" appears again.

Please keep in mind that users cannot share anything in Firefly III. There is no way to join two administrations together. It's all strictly separated.

**Comment by dicastro** [comment]
Ok. For the moment I am going to do it as you say. I've just started using Firefly and I'm still used to my old way of organizing my finances.

Thank you!

**Comment by dicastro** [comment]
I would like to create another account in Firefly III, but I do not find the option "Disable user registration" anywhere. I've already tried to access "/admin/configuration" and I've already looked for it in "options > preferences"

If I try to access "/admin/configuration", I am redirected to the home page, I do not understand why.

Should I have to have https configured to be able to access "/admin/configuration"?

**Comment by JC5** [comment]
You might not be an administrator in your own installation. That prevents you from making yourself admin.

The quickest way to do this is directly in the database. Go to the table `role_user` and add a new line with `role_id` = `1` and `user_id` = `1`.

Then, login and logout and you should be able to access `/admin` as well as change this option.

**Comment by dicastro** [comment]
Thank you so much!

That was easy!

**Comment by JC5** [comment]
This should be fixed in the new release, which came out today :+1:
