### ISSUE TITLE
Splitting transaction changes the currency you set

### ISSUE THREAD

**Issue by alekstrust** [firefly-iii/firefly-iii#1615]
I am running Firefly III version 4.7.5

Say you have USD as default currency. If you create a transaction in EUR and check the "split transaction" option, you will do it without problems, apparently.

When you see the transaction you have created recently, you will note the currency is USD actually and not EUR as desired.

**Comment by JC5** [comment]
Where are you viewing the transaction, after splitting? I don't seem to be able to replicate this on the demo site.

**Comment by alekstrust** [comment]
Demo version has EUR as default currency.

Inserting the transaction, in USD:
![screenshot 2018-08-16 a la s 8 53 57 a m](https://user-images.githubusercontent.com/4238486/44212863-19515f00-a132-11e8-84a3-cf974e6678bd.jpg)

When reviewing after saving, it's in EUR with the same values:
![screenshot 2018-08-16 a la s 8 54 30 a m](https://user-images.githubusercontent.com/4238486/44212940-4d2c8480-a132-11e8-9ec3-6bf77dbd96f9.jpg)

Maybe you can see the test in https://demo.firefly-iii.org/transactions/show/641

**Comment by JC5** [comment]
Thanks, I'll check it out!

**Comment by JC5** [comment]
Yes, this is a bug, and I found it. It will be fixed with the next release. Unfortunately, I cannot fix previously botched transactions: you must recreate those yourself.

In order to to fix the code before the next release is out, check out the commit (see the entry above this reply).

I apologise for the mix-up!
