### ISSUE TITLE
Possible bug in budgets report

### ISSUE THREAD

**Issue by Kyle9982** [firefly-iii/firefly-iii#1617]
I am running Firefly III version 4.5.7.3

I am not sure if this is on purpose, but when I get a "Default financial report". There seems to be a issue under the budgets section. If you have set a budget to $0, and spend $100, it doesn't say that you overspent $100. It just remains at $0

![untitled](https://user-images.githubusercontent.com/42327407/44244222-b4285880-a187-11e8-9ec9-5ea19aee4323.png)

**Comment by Kyle9982** [comment]
I also just found that if you try to generate the "Tags Report" I get the Error 404

**Comment by JC5** [comment]
Hey, thanks for opening these issues.

So if there's nothing budgeted, there is no overspending. It's only when you budget money it can be overspent (or not). So that should explain that one.

The tag report is tricky. As far as I can tell it works, but it's possible to (try to) open the tag report without selecting any tags or any accounts. Do you have tags in your installation already?

**Comment by Kyle9982** [comment]
I was thinking it might have been the slash because it actually shows "/" instead of "%2F". The code for the slash like "%20" is for the spaces

**Comment by JC5** [comment]
The forward slash is the issue, and it's a major headache for the framework I'm using (Laravel). See also: https://github.com/laravel/framework/issues/22125

I can fix everything else but the forward slashes are the problem. I'll think of a work-around.

**Comment by JC5** [comment]
OK, new version of Firefly III can handle both tag names and tag ID's, but will default to tag ID's. That way the forward slashes will be out of the URI but users can still append the URI with their own tags if required. Thanks for letting me know!

**Comment by JC5** [comment]
New release is live. Please open a new ticket when the problem persists. Thanks!
