### ISSUE TITLE
Duplicates handling at import

### ISSUE THREAD

**Issue by hamuz** [firefly-iii/firefly-iii#1653]
**Description**
Please describe your feature request:

I would like to be able to import / add duplicated transactions (as currently detected) upon manual inspection.

It appears to be duplication is based on description (and maybe date), but not amount, which is bug, in my opinion.

**Solution**
Describe what your feature would add to Firefly III.

I would like Firefly III to show detected duplicate transactions and to offer the user option to import each, anyway.

**What are alternatives?**
Please describe what alternatives currently exist.

Once imported/added - Kaching highlights both transaction it detects as duplicate (different color for each), and upon inspection allows to remove the highlight of duplication, and it become regular transaction.

In the import screen of Kaching there is checkbox whether to import detected duplicate transactions or not.
(I would import duplicate I know it is a different transaction, usually it is matched to old transaction with same description and amount. I would NOT import when it old transactions when they overlap with the same transactions - for example when importing the current month transactions, in different dates)

**Additional context**
Extreme scenario (actually happen to me once, and I even went to request refund, only to be proven it was legit):
- On the same day, same store, same amount.

**Comment by JC5** [comment]
Firefly III can recognise two different types of duplicate transactions. It will refuse to either of them.

When you import from a certain source and a specific expense is an exact duplicate of an earlier imported expense, Firefly III will refuse to import the transaction. An exact duplicate transaction is a transaction where *every* field is equal to another transaction. For example, if you import the same CSV file twice, or when you import from Spectre but you reset your settings in the meantime. So date, amount, description, everything must be the same.

You can only import such transactions if you add unique data, such as another column that identifies the actual transaction (an ID or something). Make sure you map this column to the "external ID"-field.

The other type is duplicate transfers, which isn't really applicable here.

**Comment by hamuz** [comment]
I had an CSV with external ID, which although looked like an ID (random-ish), labeled the same transaction ("withdrawing the same amount from ATM on the same day") with the same external ID, so in that cause you had nothing to differentiate the transactions, beside the knowledge inside my head, which knew it is legit.

**Comment by hamuz** [comment]
And on a different note, firefly refuses to import same csv, with same config, although I've deleted the transactions from the system (and not only the tag, which happen to me earlier) - so there is no real duplicate here.

**Comment by JC5** [comment]
I'm sorry, but if there is absolutely no difference in the data, Firefly III won't import it. You'll have to make sure the data is clean before you do an import.

And indeed, Firefly III won't re-import, even when the transaction is deleted. This is to prevent "cleaned up" transactions from being imported again and again. In order to make this happen, you will have to delete the row from the database by hand.

**Comment by JC5** [comment]
Actually, most are perfectly capable of doing so. Firefly III's installation isn't that simple. Most know how to set up a database, because the installation requires them to do so.

But it's just a design choice. I could go either way. I've decided to work with what other users have suggested before. Many banks add dummy transactions and cleaning up those transactions through the interface of Firefly III is a common scenario.

**Comment by hamuz** [comment]
using specifics?
