### ISSUE TITLE
Pie charts by category does not work as intended

### ISSUE THREAD

**Issue by lucavallerini** [firefly-iii/firefly-iii#1667]
I am running Firefly III version 4.7.6.2.

See here: [https://demo.firefly-iii.org/accounts/show/1/2018-08-01/2018-08-31](https://demo.firefly-iii.org/accounts/show/1/2018-08-01/2018-08-31)

The pie charts do not show what they should. Furthermore, the currency glyph is not shown correctly on the hover text.

**Comment by JC5** [comment]
The currency glyph is correct, it's a generic currency icon. Not the best solution so that requires work anyway. But the grouping is broken. Strange, I though I tested it.

**Comment by JC5** [comment]
Alright first of all, thanks for reporting this. I've made some changes that should also be visible on the demo site. If not, clear your cache and refresh. You should see the € symbol instead of the ¤ and it should change with the currency. Could you verify?

https://demo.firefly-iii.org/accounts/show/1/2018-08-01/2018-08-31

**Comment by lucavallerini** [comment]
Yes, now it works correctly :)

**Comment by JC5** [comment]
Closed pending the next release this weekend.
