### ISSUE TITLE
Show rules that run when transaction updated

### ISSUE THREAD

**Issue by hamuz** [firefly-iii/firefly-iii#1678]
**Description**
Please describe your feature request:
I would like Firefly III to show rules that run when transaction updated in success alert.

**Solution**
Describe what your feature would add to Firefly III.

1) you might be surprised why there are changes you didn't make, and find which rule is responsible.
2) or, you want to confirm rules work as intended.

**What are alternatives?**
Manually check is some rule was applicable to updated transaction.

**Comment by JC5** [comment]
I am not a fan. I think that it would only add clutter. I understand your use cases, but adding the extra visibility is not necessary to see if the rules fired and why.

**Comment by hamuz** [comment]
> but adding the extra visibility is not necessary to see if the rules fired and why.

So what is the expected solution in this use case? how can you see?

**Comment by JC5** [comment]
Well assuming you know what actions you have just set, the changes would not be so subtle that you're in doubt if they fired or not.

Failure of a rule action (looking at your other issue) is rare but also difficult to give feedback on. My preferred way of preventing these from happening would be at the front-end (feedback when you try to create impossible actions) instead of feedback from the backend.
