### ISSUE TITLE
Issues with /bills page

### ISSUE THREAD

**Issue by hamuz** [firefly-iii/firefly-iii#1695]
**Bug description**
I am running Firefly III version DEMO 4.7.6.2

(please give a clear and concise description of what the bug is)

Looking at: https://demo.firefly-iii.org/bills
1) why the currency on the different amounts, not all in EUR?
2) how will it be able to handle several bills with different currencies?
3) why "Sum (active bills only)" is summing the minimum of all bills, and not actual bills in period?
4) I don't know what is the meaning of ¤1,770.00
5) What is the use-case behind "average per bill (active bills only)"? How is the average between the insurance and rent helps the user to understand it's financial situation?
6) In regards to 5, I think the average (sum of bills) per month (active bills only) in current period, is an interesting figure to show.
7) I don't know what is the meaning of ¤885.00
8) I think "**maximum** expected total (active bills only)" is more descriptive of the figure calculated.

**Steps to reproduce**
What do you need to do to trigger this bug?
Go to https://demo.firefly-iii.org/bills

**Bonus points**
Earn bonus points by:
- Add a screenshot
![image](https://user-images.githubusercontent.com/550499/45558909-b397e600-b849-11e8-8dbd-30d6d91371ea.png)

**Comment by JC5** [comment]
Here we go. Let's see if I can match the list :wink:

Oh, and I found a typo in the code that should clear things up already.

1. Because bills can be in multiple currencies.
2. See nr 1.
3. This is shown on the default report, not in the bill overview.
4. See above. It's the sum of all maximum bill amounts. 915 (in your screenshot) is the sum of all minimum amounts.
5. Average minimum and average maximum for all bill amounts.
6. This is shown on the default report, not in the bill overview.
7. See above. 995 is the average amount of all bills put together.
8. It's not the maximum.

See this screenshot. There is one bill, with a minimum of 10 and a maximum of 100.

<img width="941" alt="screen shot 2018-09-14 at 17 44 52" src="https://user-images.githubusercontent.com/5889984/45560746-459def80-b846-11e8-8479-3dcb9b818117.png">
