### ISSUE TITLE
Change Revenue/Expense to Asset account

### ISSUE THREAD

**Issue by rhtenhove** [firefly-iii/firefly-iii#1700]
**Bug description**
Unable to change a revenue/expense account to an asset account

**Steps to reproduce**
1. Add 1st asset account
2. Import transactions for 1st asset account
3. Add 2nd asset account for which transactions with 1st account already exist
4. Find out the 2nd account exists as revenue/expense account, and be unable to add 2nd asset account due to IBAN being in use

**Expected behavior**
Able to change such that a revenue/expense account can be set as an asset account

**Suggestions/Workarounds**
- Remove revenue/expense account, which also removes associated transactions
- Add asset account
- Re-import transactions (duplicates will be ignored)

I can imagine this doesn't happen often, and I should have added all asset accounts beforehand, so I'll go for the workaround.

edit:
After going through the workaround, I see that the transactions are transfers. This may add to the complexity of this feature, and the workaround isn't all that bad.

**Comment by JC5** [comment]
I'm sorry, this is indeed the way Firefly III works. It will automatically create revenue and expense accounts, but it won't create asset accounts. Like you say, creating the asset accounts beforehand is what you'll have to do.

In the next release, you will be able to use rules to change the transaction type from (for example) withdrawals to transfers and link them to an asset account.

If you wish to re-import transactions even though they are duplicates (even deleted ones count as duplicate) you must remove them from the database by hand.

Since Firefly III will not create asset accounts for you, there is not much I can do.

**Comment by rhtenhove** [comment]
Reimporting all transactions after removing the expense account with its transactions, has created transfers as expected. No need to do anything in the database.

I then encountered a different issue, with transactions being added to the wrong IBAN, it seems it might be due to duplicate account names. I'll look into it, see if I can reproduce it with a fresh instance of firefly, and open a new issue if needed.

Thanks!
