### ISSUE TITLE
Invalid handling of 'Stop processing' for rules group

### ISSUE THREAD

**Issue by ms32035** [firefly-iii/firefly-iii#1747]
**Bug description**
I am running Firefly III version 4.7.7

The UI states: `When you check this box, later rules in this group will not be executed.`

However, looking at the code:
https://github.com/firefly-iii/firefly-iii/blob/master/app/Jobs/ExecuteRuleOnExistingTransactions.php#L183

if the checkbox is selected, the batch job just stops after the first transaction.

**Comment by JC5** [comment]
Nice find! I'll push a fix and do some debugging to make sure it works as intended.

**Comment by JC5** [comment]
Alright, I've pushed some fixes. In the cases where you fire a set of individual rules the "stop processing" instruction will be ignored because the context of the group is lost. This happens when you fire one single rule or when you fire a selection of rules over the command line (new in 4.7.8).

In all other cases, the "stop processing" instruction will be respected.
