### ISSUE TITLE
Auto mail financial report at the end of the month

### ISSUE THREAD

**Issue by Mazzz81** [firefly-iii/firefly-iii#1810]
Would it be possible to build in a function to receive a financial report by mail after the end of the month. For example, I can inform my wife of the financial situation with a handy readable report.

Don't know if this a lot of work, but it can help me a lot.

Im using firefly just a few week now and really like it. Great job!

**Comment by JC5** [comment]
There is a financial report that you can configure on the `/reports` page. Since you can adjust the dates for the report in the URL, you can preconfigure the reports and visit them anytime you want:

https://demo.firefly-iii.org/reports/default/34,1,32,33,2,3/20181001/20181031
https://demo.firefly-iii.org/reports/default/34,1,32,33,2,3/20180901/20181030

You can even use [the current periods as a place holder](https://firefly-iii.readthedocs.io/en/latest/advanced/reports.html):

https://demo.firefly-iii.org/reports/default/34,1,32,33,2,3/currentMonthStart/currentMonthEnd

Unfortunately Firefly III cannot send out the report as email, but if you print it and save it as a PDF you have the exact report you want.

**Comment by Mazzz81** [comment]
thanks for your reply. i will go try something with wkhtmltopdf and cron to automate PDF and email.

**Comment by JC5** [comment]
You'll have to submit your authentication cookie. Try adding the `firefly_session` cookie and the `remember_web_` cookie. Take the values from your web browser.
