### ISSUE TITLE
Own exchanges rates

### ISSUE THREAD

**Issue by churchill1869** [firefly-iii/firefly-iii#1842]
Hello. I'm new on Firefly III... and I speak primary french...

I would like to bypass Fixer.io to put in Firefly my own exchanges rates.
I can grab the official Swiss Customs exchange rate [from internet](https://www.ezv.admin.ch/ezv/fr/home/infos-pour-entreprises/declarer-des-marchandises/taux-de-change--devises-.html) once a day, in a nice xml format. 

What could be the best way to use those exchange rates on Firefly ?
I was thinking to update directly the currency_exchange_rates table . It's that a good solution ?

François

**Comment by JC5** [comment]
That should work, if you use the correct Firefly III currency ID's (see the `transaction_currencies`) table. 

I'll think of a way to add multiple currency sources to Firefly III.

**Comment by churchill1869** [comment]
Hum... it's seems not so easy.
Firefly seems to ask to fixer.io for each currencies combination you use at the day you need it (example chf>eur AND eur>chf). So if I want to prefill the table, I need to make it for each combination possible, each days... not very efficient :-)

So, I need to simulate the fixer json website locally.
I think if I modify the fixer.io url in "FixerIOv2.php" to a local json webservice I could get the result I want...

**Comment by JC5** [comment]
Let's take a step back here, because this might not be necessary.

First, create a new class next to FixerIOv2 that is called SwissCustoms

```php
class SwissCustoms implements ExchangeRateInterface {
// code
}
```

In it, you must implement `getRate` and `setUser`. `setUser` you can copy from the other class.

If the list of currencies from the Swiss customs administration is always the same, you can do something like this in the code of `getRate`:

```php
$available = ['EUR', 'USD', 'VEF']; // etc....
if(in_array($fromCurrency->code, $available) && in_array($toCurrency->code, $available)) {
// continue ...
}
```

Then, you need to program something like this. This is all pseudo code of course.

```php
// download XML file uzing guzzle
$client = new Client;
$client-get('https://xml-file');

// parse XML file using basic class
$simpleXml = parse_simple_xml($client->body);

// for each entry store the rate (both ways):
foreach($simple as $entry) {
$rate = new Rate('EUR', 'USD', $entry);
$reverse = new Rate('USD','EUR', 1/$entry);
}
```

And finally return the one the user asked for.

To implement this into Firefly III you can update your [local configuration](https://github.com/firefly-iii/firefly-iii/blob/master/app/Providers/FireflyServiceProvider.php#L188) to point to the correct class.

**Comment by churchill1869** [comment]
Great. I've already done the first option, but I think I will make it "cleaner" creating a new class.
Thank you for your help !

**Comment by lastlink** [comment]
https://exchangeratesapi.io/ might need to be added to this list
