### ISSUE TITLE
Pre-set ranges

### ISSUE THREAD

**Issue by whoang44** [firefly-iii/firefly-iii#1897]
Firefly III version 4.7.8 on Ubuntu 18.04

Description - Question (Not bug)
Hi James, I am new to Firefly III app (Btw, it it pretty impressive so far in comparison to other self host budget apps) . I have a quick question regarding the Pre-set ranges (on the report page) - By default it always show year 18 to 2018 (2000 years) for some reasons on my report page. Are there anyway to customized it to different pre-set ranges?For example I just need the page to display 2 years 2016 to 2018 (similar to Firefly demo site). I tried to Google for this info and so far nothing.

Thank You Very Much

Firflyiii 4.7.8 Stable Version
OS: Ubuntu 18.04LTS
Web Srv: Apache2 (No SSL nor Rewrite - simple testing setup)
PHP: PHP and modules: 7.2
Db: MySQL 5.7
Server - Selft Host VM
Browser: Firefox and Chrome
Docker: No

**Comment by lucavallerini** [comment]
I think there is something wrong on your installation or data stored, I only see ranges from the month/year of the oldest transaction/account (August 2013 in my case) to the present month/year.

I suggest you to check your transactions/accounts to see if you entered by mistake year 18 instead of 2018 on some of them.

**Comment by JC5** [comment]
Like Luca says, if it shows that many years one of your transactions must be off. If you find it and correct it, the list will reset to normal.
