### ISSUE TITLE
Announcement: New API for Firefly III v4.7.9

### ISSUE THREAD

**Issue by JC5** [firefly-iii/firefly-iii#1912]
@sqrtroot @tonicospinelli @flyingchewbacca @elamperti @Findus23 @nekromoff @evinjon27 @pkoziol @codethief @gavu @4oo4 @8bitgentleman @matiasdelellis @tomazzinko @tornoz @philthynz @techytuppers @emansih @mconway @Ditti4 @filipe-silva @mrahmadt @hamuz @miyoyo @itpony @GeoffreyFrogeye @ogkevin @may-cat @lverissimo @may-cat @mrahmadt @bartonp

Hi guys,

First of all: sorry for the rude alert. I decided to tag all of you to give you a heads-up on some major API changes coming up around the 31st of December. You've all been involved in API related issues in the past.

These last few weeks I've been focusing on rewriting all API documentation, and improving all endpoints in general. The largest changes include:

- Removing the "include"-parameter which always felt awkward.
- Added extra info (amounts and sums) to several objects.
- Finally do some proper documentation.
- Focus on workflow, not on data.

This means a massive backwards compatibility break with previous versions: Firefly III **v4.7.9** will advertise API version **0.9.0**.

To compliment the upgraded API I've finally taken the time to write [a Swagger YAML doc (v3)](https://api-docs.firefly-iii.org/). You can submit your improvements to [this repository](https://github.com/firefly-iii/api-docs-generator).

My request to you is: read through the documentation and let me know if you see potential bugs, issues or problems. If you're up for it, feel free to clone the current `develop`-branch and do some testing. You could also use the demo site but it resets every four hours.

I am currently in the process of testing and updating all end points myself to make sure it all works as expected. Some end-points in the API are still empty but these will follow in future updates.

Cheers, and thanks for your efforts!
James

**Comment by tonicospinelli** [comment]
I took a quick look on API doc and I need to give you congrats for your effort to make it!!

**Comment by GeoffreyFrogeye** [comment]
Thanks! An API revamp is all I could hope for.

Will working with the API in the past, I've noticed a few inconsistencies/bugs that made working with it harder. I never had the time to verify them and turn them into issues, though... So since this is a big change, now is a good time to test if those are still arround. I'll list them below, test if they are fixed with the new API, and check them along.

- [ ] Unable to get the description of the parent of split transactions (unless by getting what's inside the parenthesis)
- [x] No endpoint for tags
- [x] Sometime stuff is magically included
- [ ] Parameter `transaction_currencies` should be 'currencies`
- [ ] Sometimes it's `dp` sometimes it's `decimal_places`
- [ ] `account.type` is sometimes plain english ('Revenue account` instead of `revenue`)
- [ ] `account.include_net_worth` is asked for creation/update but never given back in a GET
- [ ] `account.account_number` is sometimes denoted as `account number` (note the space)
- [ ] `monthly_payment_date` / `cc_monthly_payment_date` inconsistencies
- [ ] `credit_card_type` / `cc_type` inconsistencies
- [ ] Documentation for `available_budgets` tells its endoint is `transaction_currency`
- [ ] Unable to POST an `available_budgets`
- [ ] `piggy_bank.current_amount` seems to be unused even though required. Also POST fails
- [ ] `category.active` required for update but not given back in GET, also have no effect
- [ ] `user` cannot POST
- [ ] `user` cannot change role
- [ ] General fuss between transactions and transaction journals.
- [ ] `Transaction` amount update leaves DB in inconsistent state
- [ ] `Transaction` changing source / destination have no effect
- [ ] `Transaction` changing the description doesn't work and produces a `Twig_Error_Runtime` when opening the page of the destination account details
- [ ] `Transaction` removing a transaction makes an error happens when fetching all transactions (fix: re-run upgrade procedure)
- [ ] API version doesn't follow semver

Please don't be afraid of all of this. Those are the notes I took during my works with the API : some issues might already be fixed in released versions, and some might just be my mistake. In any case if some issues are still present I'll state  them in a more formal way. This list is just a memo and a state of my work in progress.

By the way, I think you can increment a major version on the API side or even better on Firefly's side. Dealing with user support for the already existing clients will be easier by mentioning Firefly ≥ 5 rather than Firefly ≥ 4.7.9 (but I'm not one of those client dev so do tell me if I'm wrong).

**Comment by emansih** [comment]
How about simply leaving the old API as it is and use `/v2/xxx` for new APIs?

**Comment by JC5** [comment]
@emansih That would also mean I have to leave all the buggy code in there. Once 0.9.0 (and its successors) proves to be working I will elevate it to 1.0.0.

@GeoffreyFrogeye Yes, and formally I would have to do that for each API change. If this is complete, the API will go to 1.0.0. Then I will work on a new layout, and that will become 5.0.0.

**Comment by mconway** [comment]
Thanks @JC5. Just out of curiosity, what's the timeline for the new release? I'm going to start testing the mobile app against the new endpoints, but having a timeline to get everything fixed would be great :)

**Comment by JC5** [comment]
Thanks @mconway! I am currently in the process of testing each endpoint.

**Comment by lverissimo** [comment]
@JC5 first of all let me thank you for your continuous effort. This is a great solution, and it is a pleasure to help. You have done a great job with documentation. I will be glad to test it over around Christmas time. I will let you know.

**Comment by JC5** [comment]
Guys, I plan to release this version of Firefly III before Christmas. So either today, or tomorrow.

I'm just telling you this so I can also tell you that the demo site now has a persistent OAuth2 token: `tfWoJQbmV88Fxej1ysoooFireflyIIIDemoToken`. You still have to swap it every four hours for a bearer token but it should make your workflows a lot more easy.

**Comment by OGKevin** [comment]
Hey @JC5, 

Thanks for this! There is one little thing that I find annoying me about the API. The fact that it redirects to the login page instead of a 401. Would it be a nice idea to just return 401 on `/api/*` and redirect on all "UI" facing urls ?

**Comment by JC5** [comment]
It should, but make sure you add accept=application/json to your requests. 

I’ll pick it up and see if I can’t make it default.
