### ISSUE TITLE
Possibly missing transactions when using finTS

### ISSUE THREAD

**Issue by dun3** [firefly-iii/firefly-iii#1937]
**Bug description**
I am running Firefly III version 4.7.9

When using finTS to import transactions: If during retrieval the transaction limit for a given time period is reached (usually 50 transactions may be downloaded in one batch), no warning, etc. is displayed and no further transactions are being downloaded.

Subsequent requests on a smaller time range claim that there are no transactions to be imported.

**Steps to reproduce**
- Have an empty account
- Import a large target date range from a busy account, with more then 50 transactions to fetch

**Expected behavior**
- All Transactions in the time period should be downloaded

**Extra info**
Seen on HypoVereinsbank account.

Let me know if I can help further, I am willing to Skype, etc. with you.

Thank you so much for this awesome tool and the finTS integration. Much appreciated!

**Comment by JC5** [comment]
You're very welcome! I am tagging @bnw to see if he know the answer, perhaps.

Generally speaking, there is not much I can do. If the protocol and the library I use don't support pagination or some kind of resume functionality, Firefly III doesn't know that there is more to be downloaded.

**Comment by bnw** [comment]
The library we use already uses some sort of pagination. I have sucessfully imported hundreds of transactions in one go. So I am not convinced that pagination is the problem here.   

   


> Subsequent requests on a smaller time range claim that there are no transactions to be imported.

This seems weird. Maybe your bank has some sort of flood controll?   
To rule out that your bank does something funny, could you try around with the the underlying library to see if the retrieval of the transactions work as one would expect?  To do this, checkout https://github.com/mschindler83/fints-hbci-php, run `composer install`, modify `Samples/statement_of_account.php` accordingly and call it from the command line.   
Could you check if:
* Retrieval of the smaller time ranges works
* Retrieval of the larger time range works and is not cut off after 50 transactions
* Retrieval of the smaller time ranges still works after you tried to retrive the large time range

If this all works, maybe your firefly-iii ran into a timeout/memory limit while importing. In this case, @JC5 might now what to do.
