### ISSUE TITLE
Gift card support

### ISSUE THREAD

**Issue by lastlink** [firefly-iii/firefly-iii#1958]
**Description**
Please describe your feature request:

- I would like Firefly III to allow us to do gift card expenses

**Solution**
Could be a budget that comes from an asset category or piggy bank

**What are alternatives?**
Everydollar has budget categories, but some can be "savings" categories that when taken out of don't necessarily affect the budget amount allocated.

**Comment by JC5** [comment]
I'm not sure what you mean. You want to track the balance of gift cards? Use them as the source for a payment?

**Comment by lastlink** [comment]
yes, we should be able to have gift cards as asset accounts and have some sort of an empty budget category that is unaffected by the budget amount for the month.

**Comment by JC5** [comment]
The whole budget thing is a different problem altogether. As such I'm not a fan of adding gift card accounts. It seems a lot of administration for something like this.

What I do is the following. Either I register the expense as the amount left after applying the gift card (ie 10 instead of 60) or I register an income + an expense.

I increase the budget if necessary.

**Comment by lastlink** [comment]
so forgo the budget completely and just charge straight from the gift card this works. I'm familiarizing myself with the system and couldn't find another similar issue on this. You can close this issue then.

**Comment by JC5** [comment]
Righto :+1:
