### ISSUE TITLE
End-to-End (Client-Side) Encryption

### ISSUE THREAD

**Issue by ajvsol** [firefly-iii/firefly-iii#2039]
I couldn't find any information in the documentation about this, I have seen a few references to encrypted databases scattered around the issues list but nothing explicit. So what is the extent of the encryption in Firefly? Ideally I'd like all personal data to be encrypted at rest so I'm curious what is available currently.

**Comment by JC5** [comment]
That's an interesting story actually. My original idea (this was in 2013, mind you) was to encrypt all the things. Amounts, names, dates, etc. But alas, it's impossible to manage data that way. You would have to download it to the app, decrypt it, search it, sort it, use it, etc. It would be a nightmare. So I settled for just the text fields. Names, titles, etc. 

Over time however, I've dropped encryption for most of those fields again, and I will continue to do so in the future. The reason is that database encryption is not really my problem. It's the database responsibility to do encryption. It can do that infinitely better, faster and more efficient than I can from my app. It is also impossible for me to do certain operations, a fact that limits many features of Firefly III to this day. So in the future, I intend to drop the encryption on my end completely.

This also applies to the encryption of uploads and exports.

I can only advise you to get a database system that uses encryption (transparent database encryption). There are several commercial tools on the market. If these are expensive or lacking, I would suggest encrypting your data at the file system level. All major operating systems support this and it would encrypt the database as well.

Does that answer your question?

**Comment by ajvsol** [comment]
It answers my question about the current state, though your reasoning seems to not be referring to client-side encryption but instead server-side encryption.

E2EE uses libraries like [sjcl](https://github.com/bitwiseshiftleft/sjcl), [OpenPGPjs](https://protonmail.com/blog/openpgpjs-4-streaming-encryption/) or [nacl](https://github.com/dchest/nacl-stream-js) to encrypt data on the web app side _before_ it gets sent to the server (e.g. database). The idea behind it is that allows people to use untrusted cloud servers whilst safe in the knowledge that when the data left their device they can prove it was encrypted. 

It's an important enough distinction that web apps like Nextcloud have integrated client-side encryption despite having server-side encryption already for years. It ensures that there's no way a malicious server adminstrator, hacker or bug can result in leaked personal data - and as a layperson myself I'd trust E2EE way more than my own server security hardening skills. 

Some web apps that you might be interested in seeing their E2EE implementation are [EteSync](https://github.com/etesync/etesync-web), [Laverna](https://github.com/Laverna/laverna) and [Cryptee](https://github.com/cryptee/web-client).

**Comment by ajvsol** [comment]
> I need the data to be readable by the server.

I think this is possible, I've seen Wire for example uses an [E2EE bot API](https://github.com/wireapp/lithium/wiki/API-Service). But much of what Firefly does could be moved into the client-side anyway for better security, like syncing via the Spectre API. 

> HTTPS with perfect forward secrecy already allows you to do this, by the way.

This is only [encrypted in-transit, not at-rest](https://zimamedia.com/how-exposing-your-api-creates-vulnerability-without-end-to-end-data-encryption/) though, so as soon as it reaches the server you can't ensure it'll maintain integrity.

**Comment by JC5** [comment]
Wire only reads the meta data. But again, I need everything. That makes client side syncing pointless as well.

**Comment by JC5** [comment]
Let me give you a longer answer (aka not one from a mobile phone). 

The use case for client side encryption (because that's what it is) can be made when you want to store immutable blobs on an untrusted server. That's all they do over at Nextcloud, Wire, Signal, Laverna and many others. Encrypt a blob, dump it at an untrusted source and retrieve it later for your viewing pleasure. You see this in Wire, where they transmit encrypted messaged back and forth, using unencrypted metadata to manage the source and destination. Cryptee is doing the same thing. Ultimately, the encrypted blob is unreadable by their storage system and all interaction is done at the client.

Firefly III needs full access to the data you submit. Transaction amounts, meta-data, dates and numbers are required for it to do its magic. Encrypted blobs, client-side or otherwise, are impossible to manage. As such, any client side encryption is useless because the data will be stored "unencrypted" on the server anyway. And TLS already covers encryption when transferring the data, if you enable it.

So, if you want to add encryption to the data in Firefly III, you must do it at a level where it will remain accessible for Firefly III itself. Either encrypt the database (TDE), encrypt the filesystem (FDE) or use TLS. Preferably all of them.

You shouldn't run Firefly III on a server you can't or won't trust. That's the gist of it. I built Firefly III because I didn't want to store my personal financial records in the cloud. Running Firefly III in the cloud and then complaining about trustless servers is kind of the opposite of what you should want to do with personal information. The fact that people still do this, well 🤷‍♂️

I understand the use case and it's interesting as heck, but for Firefly III it doesn't really fit I'm afraid.

**Comment by ajvsol** [comment]
I think there's still some confusion here. 

> Firefly III needs full access to the data you submit. Transaction amounts, meta-data, dates and numbers are required for it to do its magic. Encrypted blobs, client-side or otherwise, are impossible to manage.

The whole point is that the data is decrypted client-side, which makes all that data accessible to web app. The app wouldn't be using encrypted blobs client-side. I'm not understanding why you think that client-side encryption would be a hindrance here. 

> You shouldn't run Firefly III on a server you can't or won't trust.

I'd be surprised if I was the only one who prefers self-hosting on a cloud VPS to running a home server. It's just way easier to manage. 

But even using a home server I just don't think my security skills are better than all these Fortune 500 companies you hear about getting hacked these days. I'd rather rely on software I can be certain is secure, especially for sensitive financial information.

**Comment by JC5** [comment]
Where is the web-app running exactly, in your example?

**Comment by ajvsol** [comment]
A thin Javascript client which does the decryption and data display, with [Signed Pages](https://github.com/tasn/webext-signed-pages) to ensure that the code the web app is using hasn't been altered.

**Comment by JC5** [comment]
You also have the expectation that the data is never decrypted in any form on the server, right?

**Comment by ajvsol** [comment]
I'm not an expert in these matters but like I said previously it seems to have already been accomplished on the server like how Wire have accomplished it, or it could just be moved into the client. 
> I've seen Wire for example uses an E2EE bot API. But much of what Firefly does could be moved into the client-side anyway for better security, like syncing via the Spectre API.

I think the links I gave earlier would be a better demonstration of how it could be done. I understand it would require significant rewriting but it would be a good goal to aim for in making the app secure. It could certainly be an incremental project as well, encrypting more parts of the web app over time.

**Comment by JC5** [comment]
Sorry, but you can't do this client side unless you write a completely new application. There are a lot of things that Firefly III does that you can't "just" move to the client. Like I said, it's way more complicated than just handling encrypted blobs and some meta data or running static web-apps. If you can't or won't see that, this discussion is fruitless.

Please don't imply my app is not secure because I am not using client side encryption. Security isn't an absolute scale. You can't say that encrypting more stuff makes it more secure. That's dangerously naive and adding crypto-complexity like that will make your app more vulnerable, not less. 

The solutions you're pointing to are brilliant and beautiful but once again: Firefly III is doing significant server-side processing that cannot be reasonably moved towards the client without building an entirely new application. I won't stop you however, and all my server-side processing code is open source and it's probably possible to rebuild it in Javascript.

The only motivation you could possibly have for doing such a thing would be when you want to run that new application on a server that you do not trust, or using a storage backend that you do not trust. Which is NOT something you should do with sensitive data in the first place.

Your argument about not being able to secure a server from hackers is valid but thinking your browser is safe is naive. More security flaws are found in browsers than there are in Ubuntu.

Ultimately, this discussion is about key management. Where is the key stored that encrypts and decrypts the data? It would be nice if you could guarantee that this key is never present on the server but once again: Firefly III needs to be able to access the data in order to actually work. You need the processor to be able to access the data, whoever that processor is.

There are already (self-hosted) solutions to be found online that store all financial data in your browser using a client side app for rendering and parsing. Feel free to use them.

Thank you for your contribution.

**Comment by MacPaille** [comment]
Nothing on the main discussion but just about your point:

> So in the future, I intend to drop the encryption on my end completely.

What will happen to the current installations that are using encryption? I know there is a PHP script to decrypt most of the data but it's not possible to go 100% unencrypted.

**Comment by JC5** [comment]
It's possible to decrypt all values in the database, as long as Firefly III knows about it. The demo site currently has this (running a beta of 4.7.10). The host is protected using full disk encryption and the connection is https.

**Comment by MacPaille** [comment]
As I'm hosting my FF container on my NAS (with MySQL DB export every night as bakckup) I would prefer to know how to completely decrypt my installation to be sure I will not run in trouble later :)

How can I perform this?

As a site note, I totally agree with your PoV on the above topic!

**Comment by JC5** [comment]
> How can I perform this?

You can't, not yet. The next update will do this automatically (I've been testing this).

**Comment by MacPaille** [comment]
That's the best answer I could have dreamed of :) Thanks!
