### ISSUE TITLE
Apply rules using a job queue ?

### ISSUE THREAD

**Issue by SteffanH** [firefly-iii/firefly-iii#2065]
**Description**
You warn for it yourself, and I regularly experience time-outs when applying a rule to a large(r) set of transactions.

Especially in the phase when you _just_ started using ff3 it happens (at least for me it did) that you want to re-apply a rule to all transactions because you -for example- want to use a different category and/or assign a different tag or budget.

The way I've dealt with it so far is to select a smaller timeframe where the time-out doesn't occur, and move that timeframe until the rule is applied to all relevant transactions.

**Solution**
Using a (background) process or [ job queue](https://en.wikipedia.org/wiki/Job_queue), ff3 could 'schedule' applying the rules without the risk of running into a time-out

**What are alternatives?**
The workaround i described above
Getting *everything* right the first time ;)

**Additional context**

**Bonus points**
sorry, no bonus points, other than compliments for what has been achieved so far !

**Comment by JC5** [comment]
Thanks for the compliments! There is a command line thing you could use:

`php artisan help firefly:apply-rules`

It's on my list to document this :grin:

**Comment by SteffanH** [comment]
Thanks, that'll help next time I change my mind about categorisation 👍
I assume this won't suffer from the time-out issue 

What do you think about the queue idea ?

**Comment by JC5** [comment]
Not a fan, but mainly because it's not practical. The queue drivers offered by laravel require extra packages and extra configuration. Another solution is to simply allow PHP to run more than 30 seconds at a time.

I want to avoid giving people all these extra dependencies just for one feature. This is already the case for the LDAP integration which maybe 2 guys use. I regret that as well.
