### ISSUE TITLE
Add prometheus metrics

### ISSUE THREAD

**Issue by skuzzle** [firefly-iii/firefly-iii#2108]
Hi,

I know this might be a bit special, but I'll ask anyway. I like to monitor the services that I'm running/self hosting using prometheus and grafana. There are _prometheus exporter_ implementations for various languages and frameworks (Laravel here: https://github.com/Superbalist/laravel-prometheus-exporter) that are usually easy to integrate.

As a start, we would not need to report any custom metrics. The `/metrics` endpoint being present alone is sufficient for monitoring the service's _up status_ (that would be enough for my personal use case)

**Comment by JC5** [comment]
I'm not sure if the application Firefly III is the best place to monitor if it's up or not. Shouldn't you monitor the docker instance / nginx instance / web server?

**Comment by skuzzle** [comment]
A `/metrics` endpoint in firefly itself might be the best indicator that the service is actually up and running (I must admit that it would also be the easiest for me to configure :D). If the app is up, it means that all the infrastructure below is working properly too. 

Monitoring the lower level infrastructure could however help in finding the problem in case there is an outage.

**Comment by JC5** [comment]
Yes, I can see that.

When you're using docker, the host monitors the instances and can give you a health report. The latest image has no supervisor so if Apache crashes, the docker container is down. Most users go for auto-restart but this can be handled by Prometheus maybe? The database container is monitored the same way by Docker, so that should cover that part. Added monitoring from Firefly III itself seems to add little value.

When you're running Firefly III in a self-hosted environment, you'll have to keep an eye on Apache/nginx/Traefik, and on the database itself. Perhaps the php-fpm process as well. When it's a shared machine this saves effort for all other services as well. 

I know that monitoring from Firefly III itself would be the easiest, but I'm not going to add vendor-specific monitoring solutions. Keeping a close eye on the underlying services will tell you what you want to know. `tail -f` on the Apache log files is all you need. ;)
