### ISSUE TITLE
Can't change currency of existing expense

### ISSUE THREAD

**Issue by vitobotta** [firefly-iii/firefly-iii#2155]
Hi,

**Bug description**
I am running Firefly III version 4.7.15, and my problem is:

after making a purchase in USD I created an expense using USD as currency (my default currency is EUR), then I got the email from PayPal telling me the amount in EUR. So I was trying to update the expense changing to EUR with the correct amount, but when saving I get the error:

"The native amount must be a number"

And it restores the previously selected currency (USD) but leaving the new amount in the text field. The dropdown and text field for the second currency are not shown, so I am not sure of what native amount I have to amend. 

**Steps to reproduce**

- Create an expense using a non-default currency
- Edit the expense and change the currency to the default currency, with the correct amount
- Save

**Expected behavior**

It should allow me to change the currency of the expense instead of returning an error.

**Extra info**

- macOS Mojave
- Firefox 65.0.1

Debug information generated at 2019-03-07 22:04:14 Europe/Helsinki for Firefly III version **4.7.15**.

| Variable | Content |
| --- | --- |
| FF version | 4.7.15 |
| FF API version | 0.9.2 |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | , daily |
| PHP version | 7.3.2-3+ubuntu18.04.1+deb.sury.org+1 |
| Display errors | Off |
| Session start | 2019-03-01 00:00:00 |
| Session end | 2019-03-31 23:59:59 |
| Session first | 2019-03-02 00:00:00 |
| Error reporting | ALL errors |
| Host | Linux |
| Interface | fpm-fcgi |
| UserID | 1 |
| Attempt at "en" | false |
| Attempt at "English" | false |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| DB drivers | mysql |
| Current driver | mysql |
| Login provider |   |
| Storage disks | local-upload  |
| Using Sandstorm? | no |
| Is Sandstorm (.env) | false |
| Is Docker (.env) | false |
| bunq uses sandbox | false |
| Trusted proxies (.env) |  |
| User agent | Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:65.0) Gecko/20100101 Firefox/65.0 |
| Loaded extensions | Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, sodium, session, standard, cgi-fcgi, mysqlnd, PDO, xml, apcu, bcmath, bz2, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, iconv, igbinary, imagick, intl, json, ldap, exif, mysqli, pdo_mysql, apc, posix, readline, redis, shmop, SimpleXML, smbclient, sockets, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xmlreader, xmlwriter, xsl, zip, Phar, libsmbclient, Zend OPcache |

Thanks!

**Comment by vitobotta** [comment]
**Update:**: there is another problem. The expense in the non-default currency (USD) is ignored in the account balance. I have two expenses on that card, with an initial balance of 0. The first expense is in the default currency (EUR) with amount 55.40, while the second expense is in USD with amount 35.40. 

But the account balance in both the dashboard and the accounts list shows -55.40, not -88.45 as expected (33.05 is 35.40 USD in EUR).

Thanks.

**Comment by JC5** [comment]
Two questions:

- I assumed the account you're talking about has the Euro currency?
- It might be a Javascript error. Can you clear your cache and do a hard refresh?

Here's what happens when I do this on the demo site. I assumed the account had the Euro as the default currency:

If I change the currency to USD I must also submit a EUR amount:
![screenshot 2019-03-08 at 05 39 31](https://user-images.githubusercontent.com/5889984/54007988-e53c9a80-4164-11e9-8b7c-90b3dbcb5689.png)

The EUR amount influences the balance:
![screenshot 2019-03-08 at 05 39 40](https://user-images.githubusercontent.com/5889984/54007992-ecfc3f00-4164-11e9-9e33-7f878c00eee0.png)

But both are displayed:
![screenshot 2019-03-08 at 05 39 50](https://user-images.githubusercontent.com/5889984/54008022-07361d00-4165-11e9-8004-f646448a77e7.png)

I can remove the USD amount and set the EUR amount only:
![screenshot 2019-03-08 at 05 40 08](https://user-images.githubusercontent.com/5889984/54008029-1026ee80-4165-11e9-87cd-fdcb24739ec1.png)

This works
![screenshot 2019-03-08 at 05 40 15](https://user-images.githubusercontent.com/5889984/54008044-1ae18380-4165-11e9-911b-4826b91fe8fa.png)

**Comment by vitobotta** [comment]
Hi again. I finally had a chance to try this again and had the same issue with that one transaction. No errors in the console and I cleared the cache etc. In the end I just deleted that problematic transaction and recreated it directly in EUR to fix the account balance. Thanks for looking into it!
