### ISSUE TITLE
Setting tags on bulk edit does not work

### ISSUE THREAD

**Issue by RobinWeitzel** [firefly-iii/firefly-iii#2189]
**Bug description**
I am running Firefly III version 4.7.17, and my problem is:

When selecting multiple transactions and editing them via bulk edit, it is not possible to set a new tag.

**Steps to reproduce**
* Select multiple transactions
* Got to bulk edit
* Insert a tag
* Click save
* None of these transactions got the tag

**Expected behavior**
Each activity should get the tag.

**Comment by JC5** [comment]
Confirmed, thanks for letting me know.

**Comment by JamborJan** [comment]
Just to let you know: for me bulk editing is not working either. I also have v 4.7.17 and run it in Docker with MariaDB. I want to set categories instead of budgets, so I select 50 transaction of a budget, add a category and remove the budget like shown below.

![5E81CA12-44AA-49B3-9F3A-8F16E20F5274](https://user-images.githubusercontent.com/7508960/55293605-7d424280-53f8-11e9-9ac4-1d6fa2a38203.jpeg)

But when I only set the new categories and unselect the other two check-boxes it works. It also seems to remove the budget which is exactly what I want but I guess is wrong for most of the other people who expect that nothing is changed for unelected attributes.

**Comment by RobinWeitzel** [comment]
I not sure I understand, which part did not work for you?
I tested updating categories (after finding out that updating tags does not work) and this does work for me. I only had issues with tags...

**Comment by JamborJan** [comment]
When I use it as shown in the screenshot nothing happens. No budgets get removed no categories get added.

When I only select to add categories, budgets get removed but categories get not added. So all additional information get lost.

**Comment by RobinWeitzel** [comment]
Did you uncheck the checkboxes next to the fields you want to update?
Because in the screenshot, you have the "Don't update category" field checked and as long as this field is checked, the category is ignored.

So it should look like this:

![image](https://user-images.githubusercontent.com/12135433/55333939-e4b3cd00-54a0-11e9-86d1-106695244ca1.png)

This works for me.
Hope it helps.

**Comment by JamborJan** [comment]
I apologize. In German language it says "Kategorie nicht aktualisieren" and I misread it. 🙈 My brain blurred out the NOT. Sorry. Everything works as expected.

**Comment by 0x3333** [comment]
Same issue here, cannot update Tag on bulk. Docker + Postgresql.

**Comment by JC5** [comment]
Will be fixed in the next release.
