### ISSUE TITLE
Add an advanced search for transactions

### ISSUE THREAD

**Issue by kaunt** [firefly-iii/firefly-iii#2220]
**Description**
- It would be nice and usefull if firefly has an enhanced search/filtering capability for Transactions, maybe filtering on different fields (like account/category/date/description .....)

**Solution**
- Add an "advanced" search, where user can filter on different columns

**What are alternatives?**
- as of now I don't see workarounds than using the standard search

**Comment by JC5** [comment]
I think the search is pretty advanced already, but I’m open to suggestions. 

https://github.com/firefly-iii/help/blob/master/en_US/search.index.md

**Comment by kaunt** [comment]
Thank you for pointing to the documentation and must say: yes, search is very advanced. However from user perspective it would be nice to make it more .... user friendly!  :-)

**Comment by AndrewSav** [comment]
@JC5  Here are concrete suggestions:

- Support spaces in the search parameters. Currently, according to the page you linked to, if you have a space in your search term, you are hosed. If there is an easy work around, the documentation should say that.
- Support search on all possible fields, not just on the narrow subset listed on the page you linked to. This includes but not limited to: 
  - **Multiple tags**
  - Notes
  - Processing Date
  - Interest date
  - Book date
  - Due date
  - Payment date
  - Invoice date
  - Internal reference

I'm presonally interested in searching on `Processing Date` and Notes, since I'm planning on using Notes, for putting extended information that `Description` does not fit for, and it would be useful for me to search on that information. Processing Date is important for me, because the way my banking works the Date and the Processing Date can be a week apart, so often searching by Date does not retrun the expected result set. Multiple Tags search is also extremely desirable, since certain tags that I'm going to be using will be on many transaction, but not so if three or four of them combined.

Could you please let me know if this is feasible, or if some of this already possible with the existing functionality. Thank you in advance!

**Comment by JC5** [comment]
Thanks, I’ll put this on the roadmap.
