### ISSUE TITLE
Edit Directly From Line Items

### ISSUE THREAD

**Issue by fictitiousexistence** [firefly-iii/firefly-iii#2250]
**Description**

I would like Firefly III to be able to edit transactions directly from the line items. 

For example on the withdrawal/ show everything page:

https://demo.firefly-iii.org/transactions/withdrawal/all

You can see all sections such as category, budget, bill, etc. 

It would be great to have some sort of "edit mode" where you can change these options directly from this page in the line items. 

This would make editing multiple transactions easier even if one by one. 

Currently I have to go into each transaction and click edit to be able to edit the details. 

Thanks! 

**Additional context**

**Bonus points**

**Comment by JC5** [comment]
That's a very nice idea. Unfortunately, it's not going to be put on the todo-list. There are plenty of other improvements I want to focus on first. The API however would support it after 4.8.0

**Comment by iwalucas** [comment]
I like this idea. When I need to do this, I select the transactions I want do edit and choose `edit` instead of `bulk edit`, which gives me a similar functionality.

<img width="1152" alt="image" src="https://user-images.githubusercontent.com/3654783/56919289-99d4a780-6a96-11e9-989b-ae90dff2054e.png">

<img width="1163" alt="image" src="https://user-images.githubusercontent.com/3654783/56919305-a0631f00-6a96-11e9-88df-89a18a4c050e.png">

**Comment by fictitiousexistence** [comment]
> I like this idea. When I need to do this, I select the transactions I want do edit and choose `edit` instead of `bulk edit`, which gives me a similar functionality.
> 
> <img alt="image" width="1152" src="https://user-images.githubusercontent.com/3654783/56919289-99d4a780-6a96-11e9-989b-ae90dff2054e.png">
> 
> <img alt="image" width="1163" src="https://user-images.githubusercontent.com/3654783/56919305-a0631f00-6a96-11e9-88df-89a18a4c050e.png">

Thanks for pointing this out. This is what I was looking for. And it was already there...I need glasses.

**Comment by JC5** [comment]
:+1:
