### ISSUE TITLE
Have an option on deposits to automatically add to budget

### ISSUE THREAD

**Issue by alexjyong** [firefly-iii/firefly-iii#2309]
It would be helpful if on the new deposit screen, you could go and check a box where The total was automatically added to your monthly budget. bonus points if we could also get that amount not only be added to the entire total for the budget, but a specific category.

Right now you have to do it manually from what I can see. This isn't a big deal, just a quality of life improvement and reducing the chances of me fat fingering the result of a basic addition problem. :)

**Comment by JC5** [comment]
No, sorry.

You're budgets should be set in stone for the current period. If you have a windfall that's nice, but you should save that money for the *next* period.

Of course you're free to change your budgets during a period. It happens when friends pay you back or something. But it's not going to be automated by Firefly III.

**Comment by alexjyong** [comment]
Thank you for your reply.  That makes sense. I'll just make my own fork
then for it. It is an excuse to learn a bit about the software framework. :)

**Comment by alexjyong** [comment]
>It happens when friends pay you back or something.

FWIW, this is what I was interested in for this purpose.
