### ISSUE TITLE
Autofill full details of a transaction when selecting from the suggestion box

### ISSUE THREAD

**Issue by simophin** [firefly-iii/firefly-iii#2340]
**Description**
I use the same description for same kind of transaction. For example, "Barbershop" for having a haircut. It's really nice that I can type "Bar" and the word barbershop would appear in the suggestion box because I have entered "Barbershop" before. What if the rest of the Barbershop transaction details can also be populated into the form? Because I always use the same asset account, same category, same expense account, even the same amount! 

In fact thinking about the most of expenses I have in my life, most of them are just the same thing over and over again, maybe a difference in the amount, but the categorizing stays the same.

Wouldn't it be nice to have this feature on Firefly? Typing and selecting account sucks. I used Bluecoins before, it does this and it is wonderful.

**Solution**
Populate the rest of the transaction form when a past transaction description is selected from suggestion box.

**Bonus points**
The transaction type can also be populated! Even I started typing "Barbershop" in the "Transfer" section, selecting Barbershop will take me to Withdrawal automatically! And vice-versa.

Not sure if this is in a roadmap, but I can definitely help with coding.

**Comment by JC5** [comment]
It's a good idea and it's been suggested before. For the time being however, you'll have to use the Rules option to auto-fill the details after you created the transaction. I'll have to think about the best way to manage this. 

On a whole, I try to avoid "system magic". Although it makes Firefly III easier to use for power users, it also makes it unpredictable and difficult for new users. There's always a balance to be sought.

For the time being, I suggest you use rules while I think of the best way to implement this.

**Comment by iwalucas** [comment]
One good solution for this is to have a "speedkey" entry.

Basically it would be another field (instead of using description) that would control this behavior.

Its common in some accounting systems, one speedkey brings all kinds of pre-populated fields.

Typing: Barbershop would bring the desired fields. And one could edit this to choose the behavior, like, not bringing the "asset account" and just the category and budget, for example.

This way, this wont affect new user experience and will definitively be a good feature for power users.
