### ISSUE TITLE
Make autocomplete case-insensitsive

### ISSUE THREAD

**Issue by agilob** [firefly-iii/firefly-iii#2386]
**Description**
Latest release changed behaviour of form, as of now when clicking on account -> new transaction, source account is no longer auto-populated, it's also case insensitsive, which makes it worse user experience compared to previous version.

**Solution**
* Auto populate account when clicking on new transaction on an account
* Remember how accounts were named 

**Bonus points**
Would be great if searching all of:

* account
* category
* description 
* tags

were case insensitive

**Comment by JC5** [comment]
I'm not sure if I can change that, unfortunately. Previous versions of Firefly III would load the _entire_ table and search by hand. This was relatively resource intensive, but necessary because the database could be encrypted. So the loading was necessary to decrypt the data.

The data is no longer encrypted, so Firefly III uses the database and asks the database to do the search. If your database is case sensitive (like Postgres) it will be more strict in what it returns.

Are you running PostgreSQL, by any chance?

**Comment by agilob** [comment]
Yes, I'm running postgesql 11.4

**Comment by JC5** [comment]
Then I'm afraid case sensitive it is.

**Comment by spaetz** [comment]
"The key word ILIKE can be used instead of LIKE to make the match case-insensitive according to the active locale. This is not in the SQL standard but is a PostgreSQL extension." (https://www.postgresql.org/docs/8.0/functions-matching.html)
I guess the DB abstraction does not allow for something like this???

**Comment by JC5** [comment]
I'm afraid not, I checked.

**Comment by viharm** [comment]
I use _PostgreSQL_ as my database. The search is case-sensitive everywhere but not for categories in the optional information for recurring transactions.
![image](https://user-images.githubusercontent.com/2663937/71783838-6f9f9600-2fe4-11ea-98d3-5e239fb69267.png)

I am intrigued as to how this might be possible. And if it's possible here, then may be elsewhere too.

Any thoughts?

**Comment by spaetz** [comment]
That's funny. I would want my search to be case insensitive and cannot imagine how somebody else could have a different preference. I really don't want to remember if I named my tag holiday or Holiday :-).

**Comment by JC5** [comment]
If you need something from me please open a new issue instead of replying to closed ones.
