### ISSUE TITLE
Custom bank integrations

### ISSUE THREAD

**Issue by maksympetrenko** [firefly-iii/firefly-iii#2570]
**Description**
In FAQ https://firefly-iii.readthedocs.io/en/latest/support/faq.html#why-can-t-i-import-data-from-insert-bank-here
You say that don’t have the resources to build import-code for all of the banks.
But may be you have a some instructions how I can write a provider for needed banks for me?

**Comment by julian-goldsmith** [comment]
Support for OFX/QFX files might help a bit here.  Almost all of the banks I use support exporting to QFX, which is apparently an OFX file with some additional fields.  An OFX importer would mitigate the need to map CSV files.

**Comment by JC5** [comment]
Both were on the table in the past, but no longer. Firefly III features an API that can be used to create transactions, which I suggest you check out.

The next big step for Firefly III is to replace the import functionality with separate applications that can do the same thing. They would no longer be a part of the application itself, but have their own update and change track.

With the API, you can already import from any source you want, if you have the know-how. The first app I want to build myself is the CSV importer. No doubt that leads to API improvements I hadn't thought of. Once that's done, other importers can follow.

**Comment by RobinWeitzel** [comment]
Ohhh, that's awesome.
I wrote my own syncing application for firefly based on NodeJS some time ago.
It would be amazing if it would be possible to integrate such things into firefly (maybe have an "Addon" page where compatible applications could display there own you within firefly so that users do not need to visit separate website).
Did you imagine something like this?

**Comment by JC5** [comment]
Yep, something like that.
