### ISSUE TITLE
Unable to import a deleted transaction a second time

### ISSUE THREAD

**Issue by mlafon** [firefly-iii/firefly-iii#2582]
**Bug description**
I am running Firefly III version 4.8.1, and my problem is that it is not possible to delete transactions and import them later.

**Steps to reproduce**
- Import a set of transactions
- Delete all imported transactions using the created tags
- Verify that the transactions have been deleted by going to the 'Transactions' view
- Import the same set of transactions
- Import fails with the following error: Row #x ("...") could not be imported. It already exists.

**Expected behavior**
I would have expected that we can do a second import of these transactions.

**Notes**
Transactions are still in the database with the deleted_at field set. I don't know if this is expected or not.

**Comment by JC5** [comment]
Yes, this is by design. This is important when importing CSV files that come with garbage, like in-between lines with your balance.

There is a quick query which you can use to delete these journals, after which you can re-import them if you want to.

`delete from transaction_journals where deleted_at is not null`

Make sure you backup your database before you execute this query.

**Comment by mlafon** [comment]
Thanks for the information. The query has helped me to import the transaction one more time.
