### ISSUE TITLE
Can't update my transactions, gives me a red box with an error message, but no error

### ISSUE THREAD

**Issue by TobiasDev** [firefly-iii/firefly-iii#2584]
**Bug description**
I am running Firefly III version 4.8.1, and my problem is: Can't update my transactions, gives me a red box with an error message, but no error?

**Steps to reproduce**
1. Add a transaction
2. Try edit this transaction (I wanted to update the "Description"
3. Get red error box, but no error showing anywhere

**Expected behavior**
I expected my transaction to update with a new description

**Extra info**
Firefox, version: 69.0

![image](https://user-images.githubusercontent.com/5912371/64769965-8cebb880-d54c-11e9-873d-9110d6c0fe0b.png)

**Comment by nbgannet** [comment]
I am experiencing the same issue since updating to 4.8.1, no php errors being logged and the Apache logs are not showing any POST actions:

`88.97.17.100 - - [13/Sep/2019:08:45:46 +0100] "GET /budget/public/accounts/liabilities HTTP/1.1" 200 24897 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.132 Safari/537.36"
88.97.17.100 - - [13/Sep/2019:08:45:46 +0100] "GET /budget/public/v1/jscript/variables?ext=.js&v=4.8.1 HTTP/1.1" 200 2457 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.132 Safari/537.36"
88.97.17.100 - - [13/Sep/2019:08:45:49 +0100] "GET /budget/public/accounts/show/38 HTTP/1.1" 200 37122 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.132 Safari/537.36"
88.97.17.100 - - [13/Sep/2019:08:45:49 +0100] "GET /budget/public/v1/jscript/variables?ext=.js&v=4.8.1&account=38 HTTP/1.1" 200 2457 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.132 Safari/537.36"
88.97.17.100 - - [13/Sep/2019:08:45:49 +0100] "GET /budget/public/chart/account/period/38/2019-09-01/2019-09-30 HTTP/1.1" 200 2078 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.132 Safari/537.36"
88.97.17.100 - - [13/Sep/2019:08:45:49 +0100] "GET /budget/public/chart/account/income-category/38/20190901/20190930 HTTP/1.1" 200 29 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.132 Safari/537.36"
88.97.17.100 - - [13/Sep/2019:08:45:49 +0100] "GET /budget/public/chart/account/expense-budget/38/20190901/20190930 HTTP/1.1" 200 29 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.132 Safari/537.36"
88.97.17.100 - - [13/Sep/2019:08:45:49 +0100] "GET /budget/public/chart/account/expense-category/38/20190901/20190930 HTTP/1.1" 200 29 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.132 Safari/537.36"
88.97.17.100 - - [13/Sep/2019:08:45:53 +0100] "GET /budget/public/accounts/show/38/2019-03-01/2019-03-31 HTTP/1.1" 200 38508 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.132 Safari/537.36"
88.97.17.100 - - [13/Sep/2019:08:45:54 +0100] "GET /budget/public/v1/jscript/variables?ext=.js&v=4.8.1&account=38 HTTP/1.1" 200 2457 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.132 Safari/537.36"
88.97.17.100 - - [13/Sep/2019:08:45:54 +0100] "GET /budget/public/chart/account/income-category/38/20190301/20190331 HTTP/1.1" 200 144 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.132 Safari/537.36"
88.97.17.100 - - [13/Sep/2019:08:45:54 +0100] "GET /budget/public/chart/account/expense-budget/38/20190301/20190331 HTTP/1.1" 200 192 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.132 Safari/537.36"
88.97.17.100 - - [13/Sep/2019:08:45:54 +0100] "GET /budget/public/chart/account/period/38/2019-03-01/2019-03-31 HTTP/1.1" 200 1990 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.132 Safari/537.36"
88.97.17.100 - - [13/Sep/2019:08:45:54 +0100] "GET /budget/public/chart/account/expense-category/38/20190301/20190331 HTTP/1.1" 200 190 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.132 Safari/537.36"
88.97.17.100 - - [13/Sep/2019:08:46:00 +0100] "GET /budget/public/transactions/edit/100 HTTP/1.1" 200 21714 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.132 Safari/537.36"
88.97.17.100 - - [13/Sep/2019:08:46:00 +0100] "GET /budget/public/v1/jscript/variables?ext=.js&v=4.8.1 HTTP/1.1" 200 2457 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.132 Safari/537.36"
88.97.17.100 - - [13/Sep/2019:08:46:01 +0100] "GET /budget/public/api/v1/transactions/100?_token=xH44n1FR4EyQxx58WAcPwc3VOka4CUntYDsauf3U HTTP/1.1" 200 1477 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.132 Safari/537.36"
88.97.17.100 - - [13/Sep/2019:08:46:01 +0100] "GET /budget/public/api/v1/preferences/transaction_journal_optional_fields HTTP/1.1" 200 432 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.132 Safari/537.36"
88.97.17.100 - - [13/Sep/2019:08:46:01 +0100] "GET /budget/public/json/currencies HTTP/1.1" 200 2435 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.132 Safari/537.36"
88.97.17.100 - - [13/Sep/2019:08:46:01 +0100] "GET /budget/public/json/budgets HTTP/1.1" 200 6055 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.132 Safari/537.36"
88.97.17.100 - - [13/Sep/2019:08:46:10 +0100] "GET /budget/public/transactions/edit/99 HTTP/1.1" 200 21729 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.132 Safari/537.36"
88.97.17.100 - - [13/Sep/2019:08:46:11 +0100] "GET /budget/public/v1/jscript/variables?ext=.js&v=4.8.1 HTTP/1.1" 200 2457 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.132 Safari/537.36"
88.97.17.100 - - [13/Sep/2019:08:46:11 +0100] "GET /budget/public/api/v1/transactions/99?_token=xH44n1FR4EyQxx58WAcPwc3VOka4CUntYDsauf3U HTTP/1.1" 200 1479 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.132 Safari/537.36"
88.97.17.100 - - [13/Sep/2019:08:46:12 +0100] "GET /budget/public/json/currencies HTTP/1.1" 200 2435 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.132 Safari/537.36"
88.97.17.100 - - [13/Sep/2019:08:46:12 +0100] "GET /budget/public/api/v1/preferences/transaction_journal_optional_fields HTTP/1.1" 200 432 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.132 Safari/537.36"
88.97.17.100 - - [13/Sep/2019:08:46:12 +0100] "GET /budget/public/json/budgets HTTP/1.1" 200 6055 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.132 Safari/537.36"
88.97.17.100 - - [13/Sep/2019:08:46:17 +0100] "GET /budget/public/json/accounts?types=Cash%20account&search=Cash%20account HTTP/1.1" 200 2 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.132 Safari/537.36"
88.97.17.100 - - [13/Sep/2019:08:46:18 +0100] "GET /budget/public/json/accounts?types=Cash%20account&search=TIm%20 HTTP/1.1" 200 444 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.132 Safari/537.36"`

Appears to be occuring on any transaction edit irrespective of the details modified.
New transactions and deletions are working fine.

Firefly also installed via softaculous on a cPanel platform.

**Comment by mrdanleey** [comment]
I have exact the same issue after upgrading to version 4.8.1.1.
So it looks like it's a bug that needs to be fixed.

**Comment by mrdanleey** [comment]
I enabled debug and created a transaction. After that I edited the transaction and the following error occured:

 Hi there,

Firefly III v4.8.1.1 ran into an error: round() expects parameter 2 to be int, string given

The error was of type "Symfony\Component\Debug\Exception\FatalThrowableError".

The error occured on/at: Sun, 22 Sep 2019 15:52:12 +0200.

This error occured in file /firefly-iii/app/Http/Controllers/Chart/CategoryController.php on line 156 with code 0. 

And:

 Firefly III v4.8.1.1 ran into an error: Argument 1 passed to FireflyIII\Api\V1\Requests\TransactionUpdateRequest::getOriginalData() must be of the type int, string given, called in /firefly-iii/app/Validation/TransactionValidation.php on line 99

The error was of type "Symfony\Component\Debug\Exception\FatalThrowableError".

The error occured on/at: Sun, 22 Sep 2019 15:52:35 +0200.

This error occured in file /firefly-iii/app/Validation/TransactionValidation.php on line 308 with code 0. 

BTW: Please update the PHP requirement, with PHP 7.2 it won't work. You have to use PHP 7.3 now.

**Comment by JC5** [comment]
What database are you using?

**Comment by mrdanleey** [comment]
I use MySql

**Comment by JC5** [comment]
I can’t replicate it but I’ll check it out later.

**Comment by mrdanleey** [comment]
I hope you'll find it soon cause it's bothering me a lot.

**Comment by JC5** [comment]
I pushed a fix that should work.

**Comment by mrdanleey** [comment]
Thannks for the fix, it works! I discovered another fix for the file:
/firefly-iii/app/Http/Controllers/Chart/ReportController.php

It needs the same fix as the file app/Repositories/Category/OperationsRepository.php 
to show the charts when pressing balance button

**Comment by JC5** [comment]
You'll need to be a bit more specific than that.

**Comment by mrdanleey** [comment]
When pressing the Balance button on the dashboard I saw that there was no chart created. I debugged again and discovered the error was in the file: /firefly-iii/app/Http/Controllers/Chart/ReportController.php

The error is the same as the one in  the file app/Repositories/Category/OperationsRepository.php
The error i got is : round() expects parameter 2 to be int, string given

I fixed it to change line 179: 'currency_decimal_places' => $journal['currency_decimal_places'],
Into : 'currency_decimal_places' => (int)$journal['currency_decimal_places'],

Now the chart is generated again. So this is the same fix as in the file app/Repositories/Category/OperationsRepository.php

**Comment by JC5** [comment]
There's a root cause here we're missing. Nobody is having this issue but you. There's something weird about your database.

Can you run `show create table transaction_journals;` and show the result here?

**Comment by mrdanleey** [comment]
![afbeelding](https://user-images.githubusercontent.com/55659208/65449398-38ddaf80-de3b-11e9-9dcf-24a741272e96.png)
