### ISSUE TITLE
Could not be imported. It already exists. When reimporting a file after deletion.

### ISSUE THREAD

**Issue by Joshhua5** [firefly-iii/firefly-iii#2645]
In the event that I incorrectly import a file and I delete the transactions to re-import.

I get an exception for every transactions: 
    Row #0 ("IDP PURCHASE - 2289") could not be imported. It already exists.

They exist in the table with a deleted timestamp.

**Comment by Joshhua5** [comment]
Deleting the deleted transactions from the table didn't help.

**Comment by Joshhua5** [comment]
Deleting the deleted transactions from transactions and transaction_types let me finish my import.
Although the import fails when I have two seeming identical but separate transactions.

Chequing,###,9/16/2019,,"C-IDP PURCHASE-8796","7 DAY CONVENIEN ",-2.25,,
Chequing,###,9/16/2019,,"C-IDP PURCHASE-9418","7 DAY CONVENIEN ",-2.25,,

**Comment by JC5** [comment]
Deleting the deleted entries from the “transaction_journals” will work.

Deleting stuff from the “transaction_types” table will probably destroy your installation.

**Comment by Joshhua5** [comment]
I do still believe this is a bug, since you can't re-import the transactions once deleted.
and two identical but different transactions, fail to be imported.

**Comment by JC5** [comment]
Both of those are by design.

1. Not allowing you to re-import deleted transactions fixes the issue that many people have, where banks insert "dummy rows" into their CSV files which otherwise would be imported again and again.
2. If Firefly III can't tell the difference between two rows or entries, it won't be imported. This allows you to import overlapping files without having to worry about importing things twice.

**Comment by Joshhua5** [comment]
Maybe a option to clean up the database from deleted transactions inside the settings, could be a viable solution for people with this problem.

or an option to force the import and replace deleted transactions.
