### ISSUE TITLE
Localise API errors

### ISSUE THREAD

**Issue by JC5** [firefly-iii/firefly-iii#2695]
See title.

**Comment by JC5** [comment]
@dguhl, I pulled in your code. Some things I noticed after merging may need some work.

- Firefly III won't translate exceptions because it doesn't know the language preference for the user. Either a new layer of middleware or another piece of code must indicate the user's language before Firefly III crashes so the error is localized.
- Localized errors make it more difficult for developers to do their work. If a user reports "翻譯服務器錯誤" it's difficult to know what ails them.
- The API is aimed at machine-to-machine usage; apps and web services. If exceptions are translated, they may have to manage 15 different translations for each possible error in order to do error catching and management on their end.

So when I'm talking about localizing API errors, I'm looking for:

- A way to satisfy users (more front-end parts of Firefly III will be using the API in the future) so they don't need to see English errors when submitting new transactions.
- A way to keep machines happy, which means errors must be English, uniform and static.

A few ways to do this are:

- Give every possible error its own error code. This works for the FireflyExceptions but is impossible to maintain with validation errors. 
- Respond with both the localized error text _and_ the English text. There are no standards for this though.

In it's current form the localized API errors are not really functional, and I fear the volunteers will translate them without ever seeing the fruits of their labour. I welcome your input :)

**Comment by dguhl** [comment]
That's why I found your issue a little unusual, but I didn't think about it much though, as I always see my PRs as a production-ready draft in code so people can check and see how their idea would play out. 

So I agree with you on introducing error codes; and maybe responding with the localized error message on a separate field next to the message field in english, to maintain backward or API client compatibility, would be better for the current time being. In regards to localization of middleware, more often are client applications left with the task of interpreting error and other codes and keying them to a string or a behavior. Take HTTP code 302: there is no technical way the HTTP-responding server could force the client to go to another site, yet most HTTP User Agents react that way to follow the Location the web server responded with in the header, as the protocol describes that behavior. 

So in the case of your scenario where the frontend becomes the client of the API middleware, which is an excellent way to go, the frontend, just as any other client, would key all API error codes to an according translation or behavior on its own.

And regarding HTTP: Language preference for anonymous users, however, can be determined by the `Accept-Language` header sent by the requesting HTTP client, if that header would be available in your scenario?

**Comment by JC5** [comment]
> That's why I found your issue a little unusual, but I didn't think about it much though, as I always see my PRs as a production-ready draft in code so people can check and see how their idea would play out.

This seems contradictory. Since you haven't asked how I would build this myself, the implementation is your idea, not mine. And it doesn't work: errors are still in English.

I'll go over the errors in the API that currently throw a FireflyException. I suspect some of them could be validation errors, empty arrays or response codes. That would save on translation work too. If Firefly III must throw an exception, it'll probably be a combination of error code and English sentence. I'll see what I can do.

Thanks again for your contribution :grin:

**Comment by dguhl** [comment]
>This seems contradictory. Since you haven't asked how I would build this myself, the implementation is your idea, not mine.

I have not much experience in contributing to open source projects yet, so I currently trust on the elder maintainer's best judgement to accept or decline a pull request. The errors are in english, because english is on the fallback language on one hand. And on the other hand, english is currently the only language in which the errors are localized.

> I'll go over the errors in the API that currently throw a FireflyException. I suspect some of them could be validation errors, empty arrays or response codes. That would save on translation work too. 

Imho, every error I translated in this PR would be qualified to be assigned to an error code. Except for the errors `error_delete_link_type` and `error_edit_link_type`.

**Comment by JC5** [comment]
This will get no further changes.
