### ISSUE TITLE
php no longer supports php-mysql, only php-mysqli or pdo_mysql

### ISSUE THREAD

**Issue by tonyofpureevil** [firefly-iii/firefly-iii#2743]
Trying to fresh-install 4.8.1.4 using Mariadb 10.0.38 which is a binary equivalent to mysql.
php-mysql has been long deprecated and is now completely gone.
As far as I can tell, .env doesn't support DB_CONNECTION=mysqli or DB_CONNECTION=pdo_mysql.
I have searched the docs at the URL in the .env file, but can find no listing of other database types!
I'm already using mariadb for three other apps and I don't have the space to add PostgreSQL
I would prefer to use mysqli as that works for everything else.
What can be done?

**Comment by JC5** [comment]
You can use "mysql".

**Comment by tonyofpureevil** [comment]
mysql does NOT work because php-mysql does not exist anymore. It was replaced with php-mysqli.
The DBAL used by firefly does have a driver for mysqli, but it is not configured.  Or I'm not able to discover the configured DB_CONNECTION name that specifies it.

**Comment by JC5** [comment]
"mysql" doesn't refer to php-mysql per se. It refers to the driver supported and configured in Laravel.

https://github.com/laravel/framework/blob/6.x/src/Illuminate/Database/Connectors/ConnectionFactory.php#L242

https://github.com/laravel/framework/blob/6.x/src/Illuminate/Database/MySqlConnection.php#L5

**Comment by tonyofpureevil** [comment]
https://stackoverflow.com/questions/21797118/deprecated-mysql-connect
It doesn't work for any modern version of php

**Comment by JC5** [comment]
My personal instance is running MariaDB on the latest php7.3 so I’m not really sure what your question is :)

**Comment by BobWs** [comment]
Mariadb works just fine with Firefly! I'm using Mariadb with Firefly in docker without any problems.
Just use e.g.:
`--env DB_CONNECTION='mysql' \
--env DB_HOST='firefly-db' \
--env DB_PORT='3306' \
--env DB_DATABASE='firefly' \
--env DB_USERNAME='firefly' \
--env DB_PASSWORD='<yourdbpassword>' \
`
This is my setup in docker and everything works fine with Mariadb database.

**Comment by tonyofpureevil** [comment]
Your configuration uses the tcp network stack.  Mine has networking disabled in mariadb and so requires Unix socket communication. This is a security issue.

**Comment by JC5** [comment]
What would your connection parameters be?

**Comment by GaryQ** [comment]
I don't understand your logic regarding security and TCP vs UNIX socket or any other transmission  communication protocol. MySQL is a database server. You don't normally disable all TCP connections for security you just lock it down. I use MySQL. Connection layer is setup and locked down to only accept requests from specific local IPs (not all) on my LAN, same for APACHE24. PHP only uses MySQLi or PDO. Laravel and Firefly III use PHP. And thankfully 7.3 as a minimum now. The concept around using TCP/UDP or whatever protocol is that your web server, database server and any other server (or pool of) can be located all on the same physical computer and segregated or at totally different locations around the world. I can disconnect from the outside world completely and still use MySQL and apache just fine. Only my stupid smart TV complains if it's disconnected from the outside world.

I've always said: The only secure device is one that has been passed through a device to ensure it's totally disintegrated and spit out into  "bits and pieces" so that it can no longer spit out any "Bits and Bytes:"  :)
