### ISSUE TITLE
Ability to remove / add transaction during the reconciliation

### ISSUE THREAD

**Issue by chevdor** [firefly-iii/firefly-iii#2791]
**Description**
The fact that Firefly supports reconciliation is great!
It seems however impossible atm to add / edit / remove transactions during the reconciliation process. This ticket describes a few options.

**Solution**
The most elegant solution would be to be able to add / remove / edit any non reconciliated transaction from the reconciliation page. That may be a bit out of the scope of this page though.

**What are alternatives?**
What would probably but the easiest is to let the user open a second browser tab (we could add a 'special button' for that, and add / edit / remove transactions there. For this option to work, some kinda of 'refresh' button is required in the reconciliation page in order to reload the reconciliations data and the transactions list after the user changed them. 
Removing transactions is even not completely critical as the non reconciliated tx could be removed afterwards and don't really get on the way of reconciliating. 

**Additional context**
Today the process is rather cumbersome as the user needs to add / edit / remove transactions, reload the page (which loses all dates and amounts) and redo the process from scratch.
Having to redo an entire reconciliation because of one missing transaction is just very laborious but happens often. 

**bonus**
Add a brave partner channel with your github account so people can donate BAT tokens for the awesome work you are doing!

I am using brave and I can see the button to do so:
![image](https://user-images.githubusercontent.com/738724/68046094-5411c980-fcdb-11e9-95e7-6e7bed8e9e45.png).
So tipping is a click away but you don´t accept tips :)
![image](https://user-images.githubusercontent.com/738724/68046129-655ad600-fcdb-11e9-8e0d-f6cb3715347a.png)

**Comment by JC5** [comment]
I like the idea of being able to add or remove transactions, but it feels like a lot of effort for something that shouldn't happen all too often. A tab for a new page, a refresh button.. it feels way too complex for something that can be fixed by simply cancelling your operation and starting over. You have to set off the time you'll lose versus the time I have to invest in building the feature. I don't think it'll ever work out, sorry about that. 

I'm always very happy about people wanting to donate some money but I'm sticking to the channels I currently have. If you choose GitHub, they'll match your donation!
