### ISSUE TITLE
Import using Spectre no longer detecting duplicate

### ISSUE THREAD

**Issue by iwalucas** [firefly-iii/firefly-iii#2793]
**Bug description**
I am running Firefly III version 4.8.1.6, and my problem is:

Since I upgraded to 4.8 I have been having trouble with Spectre API. Whats bothering me now is that it keeps importing ALL transactions on every import run I do. On last version it used to throw away the duplicated ones.

**Steps to reproduce**
Import transaction using Spectre API.
Import again same account.

**Extra info**
This is happening to all my accounts using Spectre API

**Comment by JC5** [comment]
Thanks for letting me know. I'll pick it up and see what I can find.

**Comment by JC5** [comment]
I haven't been able to reproduce this, sorry. Of course I only have test bank access, but everything I import is correctly marked as a duplicate the second time around. There has to be a difference between both transactions: the trigger seems to work perfectly.

Can you check if there are no extra fields or changed ID's in either transaction?

**Comment by diegombeltran** [comment]
If you change the category of the transaction to something more human readable, does it count as extra-field or changed-ID? Because that happened to me first time I run it.

It happened again the other day. The first time I run the importer it got 21 transactions from October, but the second run they were 43 transactions.

If I can help with debug logs, please let me know which of them could be useful.

**Comment by JC5** [comment]
No, it shouldn't, because Firefly III tests the original transaction and it ignores any subsequent changes.

In the reply below, I'll mention how to get the debug logs. What's interesting for me are references to the "hash" of the transaction. If everything fails, just show me a screenshot of the double transactions (and feel free to email it to me because I want to see *everything*) so I can compare it.

**Comment by JC5** [comment]
Hi! This is a canned reply that tells you how to get more debug details.

1. Please collect some log files. Go to `storage/logs` and open the latest log file. It should be called something like "ff3-fpm-fcgi-*.log". In it, you should be able to find the error along with its "stacktrace": this will tell me where Firefly III broke down. If you run Docker, use `docker logs <container>`.
2. You may also [enable debug mode](https://github.com/firefly-iii/help/wiki/Enable-debug-logging-and-debug-mode) to make sure the log files catch everything and try again.
3. Make sure you clear your browser cookies and clear Firefly III's cache files by running `php artisan cache:clear` or by visiting `/flush` on your installation.

If you do not want to share log files or other details on GitHub, please [send them to me over (encrypted) email](https://firefly-iii.org/contact-information.html).

**Comment by iwalucas** [comment]
Another symptom that may help.
Before this upgrade my account was refreshed on spectre. Now I have to login there, and manually ask for a refresh.
