### ISSUE TITLE
Imports and rules execution on background (message queue)

### ISSUE THREAD

**Issue by bontiv** [firefly-iii/firefly-iii#2862]
**Description**
Many feature need an important execution time such as imports or rules execution.

In my instance, I've about 40 rules. For 30 days execution with 300 operations, the execution takes about 5 minutes.

In my browser, I always reach the max execution time. I use a cronjob to execute rules on operations in the last 30 days, but it take a lot of CPU resources and is slow. Rules may be executed only if needed.

**Solution**
I think, you should implement a message queue to do jobs in background mode. My first solution is RabbitMQ with a consumer running with a cron job or with an AJAX call.

For rules execution, you can use a message queue with all operation you want to apply rules. When operations is imported, you add a message for all operation. The consumer executes rules on each operation while there are a message in queue.

If the process stop (max execution time in browser for example), only remaining operations will be executed on the next run.

**What are alternatives?**
You can simulate the message queue with a simple MySQL table.

**Comment by JC5** [comment]
Several queue operators are supported by Laravel, the underlying framework, but none of them will work without significant changes in the code. Luckily, I'm rewriting the import routines to use the API which would remove this problem.

Because I want to limit the number of packages and configuration users must do, I won't expand the MQ capabilities of Firefly III further.
