### ISSUE TITLE
Import configuration vs. import settings

### ISSUE THREAD

**Issue by JC5** [firefly-iii/firefly-iii#292]
The current CSV importer distinguishes between "configuration" and "settings" which is confusing and unnecessary. Code-wise and display-wise, the importer should show the number of steps needed to properly configure the import and call everything "configuration".

**Comment by dennisdegreef** [comment]
Sorry to maybe 'hijack' this issue, but would that ease standardizing banks/formats as well?
I think a lot of people will have similar configurations if they import CSVs from the same source.

**Comment by JC5** [comment]
I think I'll either provide configurations with the installation, or put a link to the wiki where they may be added by users. It a good idea to collect them!

**Comment by Cheaternl** [comment]
As a developer I thought about the same. I thought, Rabobank does not change it's CSV format from day to day. It remains the same for a looong period. Long enough to store the configuration within the sourcecode of Firefly itself. This way, (if you (JC5) collect some configurations (or bank-exports) from various users) you can embed them an users can just select 'Rabobank' or ABN-Amro or whatever banks are popular in the import interface.

I must say the current configure interface (with that 'direct related' checkbox') is kinda hard for a newcomer. I didn't understand some settings and fields. Now I have some transactions imported, but I don't still have all fields properly configured. Maybe someone can put the Rabobank configuration here already for me??

**Comment by JC5** [comment]
I will not put stuff in the source code, because there are a lot of of banks around and updating three configurations would become a daily chore. 

However, for the Rabobank, please see:

https://github.com/JC5/firefly-iii/wiki/Import-configurations

:)

**Comment by Cheaternl** [comment]
"would become a daily chore"
You must be kidding.
And yes there are a lot of banks, but for the most popular ones they should be 'in the software'.
Importing transactions is a KEY feature of your software, but now, the key to use (unlock) this feature, is placed outside the software on some page.

I know you are critical on your software and what code comes in and what not, but keep in mind that you write this software for yourself AND for others (= assumption because you share it on GitHub).
Your users of FireFly (which includes me) would be pleased to use a feature straight away from the box.

**Comment by JC5** [comment]
I appreciate your enthusiasm, but it's not going to happen.

I repeat my point that including any kind of configuration would be a chore to maintain. Errors in such configurations, updates and new additions would all warrant a new release of Firefly. I will make sure it's easy to find the wiki page, and I will put the configuration files in a repository so it's easy for everybody to create pull requests, but that will be it. These two things must stay separated.

Personally, I don't consider the importer a key feature at all. I built it because somebody asked me and I liked the challenge. For those of you who know JIRA, it's a total rip off. You know, selecting column roles and data. The challenge I like is building it. I don't even use it. 

And originally I only put it on Github because it was free ;).

**Comment by Cheaternl** [comment]
Ok, no problem with that. BTW: we use JIRA at work (with Stash and Confluence) :-)

Well than there is something I don't understand. How do you keep track of those expenses which are not in budgets (because budgets are planned expenses which most of the time match the envelop amount). How do you put them in Firefly? By manually enter them?

**Comment by JC5** [comment]
I enter all my transactions manually. Most of them are caught by rules, which add categories and budgets. Some are caught by bills, which is incidentally something I wish to change: rules should be able to set a bill as well, and all the extra settings for bills should disappear.

But otherwise it's all old fashioned manual labor. It's not that bad actually, one or two transactions a day. Keeps me on top of things really.
