### ISSUE TITLE
CORS issue when using API

### ISSUE THREAD

**Issue by adrianviegas** [firefly-iii/firefly-iii#2928]
I am developing a web app using the api. However CORS blocks this request, I have tried using PAT auth. Let me know if this is the correct way to do this, or is there another way to use the api in a web app

[Sample Code](https://jsfiddle.net/hgbL71ds/)

**Comment by JC5** [comment]
In order to make this work, the server on the other side, in this case demo.firefly-iii.org must set Cross-Origin Resource Sharing that accept your request.

As you can see in the headers coming from the demo site, it will only accept requests coming from https://api-docs.firefly-iii.org/:

```
HTTP/2.0 200 OK
server: nginx/1.14.0 (Ubuntu)
content-type: application/json
access-control-allow-origin: https://api-docs.firefly-iii.org
access-control-allow-headers: authorization
vary: Origin
```

Without those headers, other sites won't be able to easily access the demo site's API's.
