### ISSUE TITLE
Accounts with multiple currencies

### ISSUE THREAD

**Issue by GinoPane** [firefly-iii/firefly-iii#2939]
Hi!

Just wanted to clarify the conception. Is it possible to have one account (let's say "Cash") and track/store transactions in different currencies on it? Or it is required to create different accounts per currency? Like "Cash (USD)", "Cash (EUR)", "Cash (GBP)" etc?

Thanks.

**Comment by JC5** [comment]
You can always track transactions with multiple currencies on one account, because ultimately the currency is stored in the transaction, not in the account itself. So theoretically, it's possible.

The current user interface does not allow you to do so however. It will always default to the account's currency. This makes for a more consistent user interface and makes it easier for me to display the balance. Very few banks have true multi-currency bank accounts anyway ([Franx](https://www.franx.com/en-nl) comes to mind) so it's not much of a problem.

For cash accounts specifically, there are two ways to go about this. Firefly III features a special "cash" account that works if you leave the source/destination empty. The transaction will then just say "(cash)" and be counted as an expense. Those are always in the currency of the account you withdrew the money from.

If you want to keep track of cash as well, you'll have to make separate cash accounts like you suggest, that track each currency separately. Personally however, I wouldn't bother tracking cash.
