### ISSUE TITLE
Crypto Currency Portfolio

### ISSUE THREAD

**Issue by raviolican** [firefly-iii/firefly-iii#2982]
**Description**
Due Cryptocurrency getting more and more attention I would like that we can ad a cryptop portfolio into the accounts tab of FireFly III.

**Solution**

We add a new account option called "cryptocurrency" where we can add token like ETH, BTC, Ripple etc.

Then it automatically adjusts the net worth based on current exchange rate (fetch data from Binance, Kraken, Index prices etc...)

(It would also allow us a implementation of a stock market portfolio because its almost the same,  aka. kill two birds with one stone)

**What are alternatives?**
Add a new Asset account called "Cryptocurrency" and update that accordingly.

**Additional context**

![cryptop](https://user-images.githubusercontent.com/20302303/72083932-df729100-3302-11ea-9268-dcaef54a359a.PNG)

**Bonus points**
Can help with an implementation if accepted.

**Comment by JC5** [comment]
Hi! Thanks for the suggestion.

Firefly III already supports crypto currencies. Two of them are present but not enabled by default. You can create normal asset accounts with those currencies if you like.

Firefly III [isn't going to support stock options](https://docs.firefly-iii.org/support/features) I'm afraid. I'm also not a fan of live currency conversions. Although informative, they're never accurate because of bank and crypto currency fees.

So what you see is what you get. If you want live (crypto) portfolio management, you'll have to look at other tools I'm afraid.
