### ISSUE TITLE
Update bill rule when updating bill range

### ISSUE THREAD

**Issue by AlexKalopsia** [firefly-iii/firefly-iii#2985]
This is not a very big deal but perhaps a small improvement. 

I created my first bill, and gave it a range of 180-240 euros. I was positively surprised when Firefly asked me to create and attach a rule since it was super smart at picking up my old bills from history. 

Now, I then realized few bills didn't get imported because they were a bit below 180, so I edited the bill and changed 180 to 140. 

I then pressed the "run rule" (assuming that the edited field also updated the rule), but it turns out it didn't. So I was thinking it could be nice to have a prompt to also update the connected rule.

**Comment by JC5** [comment]
Good idea :+1:. Shouldn't be hard to do.

**Comment by zombiehoffa** [comment]
This applies to more than just bill ranges for rules (and probably other spots, I just haven't run into it yet because I'm so new to this program). The same problem happens for me when I create a rule sending a transaction to an account and then go and change the account name. in the rule the account name should change as well but it doesn't. Basically anything in the "trigger on value" or "action value" that corresponds to something in the system should probably persist across changes. I am not experienced enough to say with authority what those things are but I would think they would be stuff like categories, destination/source accounts, and tags but there are probably more.

**Comment by JC5** [comment]
I have no idea what you’re trying to say.

**Comment by zombiehoffa** [comment]
In the rules (and probably other places) if someone sets an action value that is an account, a category, or a tag the rule should know that it is pointing to a specific account, category, or tag and keep pointing to that category, account, or tag if/when a user changes the name of the account, category, or tag elsewhere in the system.

Right now if you, for example, make a rule that says if an incoming transaction matches something,  set destination account to Amazon, then you go change your account called amazon to amazon1. the rule will create another account called "Amazon" if it is triggered and set the destination account to that instead of the desired behavior of realizing the user changed the account name and setting the destination account to "amazon1".

both the OP and the above are a symptom of the same issue. Things that probably should be linked are not linked.

**Comment by JC5** [comment]
Ah yes. Thanks for explaining!

Ironically I probably won't be able to fix accounts, because for most rule actions and triggers, it could be any type of account (which can all share names). But the others yes, absolutely.

**Comment by zombiehoffa** [comment]
No problem, sorry for not making it clear the first time. You could fix destination/source account because those have to point to only one thing don't they?

**Comment by JC5** [comment]
The next release of Firefly III will update rules automatically where possible when editing bills, budgets, categories and tags. Unfortunately, there are several different types of accounts that could match to the name you've entered, so those can't be updated unfortunately.
