### ISSUE TITLE
To high balance with credit card.

### ISSUE THREAD

**Issue by Crupuk** [firefly-iii/firefly-iii#3004]
Hi,

First of all thank you for this project ! 
I only know the existence of FF III since yesterday and for now I really love it ! 

I have a a question about balance .

I have a Visa account with a virtual balance set to 2k ( the limit of my card like already said in one other issue ) .

But when I do a transfer between my normal account to the visa account ( for reimbourse ) , the amount of this transfer is not substracted to my balance .

![image](https://user-images.githubusercontent.com/670728/72440805-d32a8000-37a9-11ea-87f1-01452ed62a0c.png)

The transfer to the Visa is not interpreted as a expense 

![image](https://user-images.githubusercontent.com/670728/72440914-053be200-37aa-11ea-94ac-b349dbfc1922.png)

I will try to explain my case, so you can tell me what i'm doing wrong .

1. On my visa for the last month I have a expense of 750€ for a friend.
2. This friend give me back my 750€. I have added this amount with a deposit on FF III to my personal account. ( This give me a income of + 750€ ) 
3. On the 11/01 , Visa take the money back. ( on FF III a transfer from my personal account to my visa with the same amount ) .

This transfer is not interpreted as a expense .

My balance should be 221.03€ and not 971.03€ . 

How can i andle this ? 

Thanks for your help

**Comment by JC5** [comment]
The transfer is not an expense. The expense is when you bought something with the VISA card. If you pay it back with a transfer, this is just moving money around.

Otherwise, your administration would show that you spent 1500,-. This is not the case of course.

You spent 750,-. You also earned 750,-. The transfer to the VISA card does not count.

I will do some double checking on the virtual balance, but generally speaking it is *not* added to your overall balance. It is not added to your net worth. It's just a visual clue.

**Comment by sea-odoo** [comment]
Hi, 

Thanks for your reply ;-)

I understand the difference between a transfer and a expense but in fact my Visa is more like a expense account than a savings account.

It's a black hole where all the money disappear.

In my principal account view, the amount of 750€ is taking into account for the net revenue ( seems logical for me ) but ( the transfer ) it's not taking into account in my expense .

750 € earned : Ok
But also
750€ lost and not visible 

So the only way to do this is to create a external account ( like Bank Visa refund ) and make a expense to this account instead of a transfer to my Visa ? 

Thanks to you again

**Comment by Crupuk** [comment]
Hi,

Thanks for your reply ;-)

I understand the difference between a transfer and a expense but in fact my Visa is more like a expense account than a savings account.

It's a black hole where all the money disappear.

In my principal account view, the amount of 750€ is taking into account for the net revenue ( seems logical for me ) but ( the transfer ) it's not taking into account in my expense .

750 € earned : Ok
But also
750€ lost and not visible

So the only way to do this is to create a external account ( like Bank Visa refund ) and make a expense to this account instead of a transfer to my Visa ?

Thanks to you again

**Comment by Crupuk** [comment]
Ok, with much more investigation, it's not the transfert not taking into account my problem.

It's the fact that in balance the difference between the start of the month and today is taking into account for the credit card .

![image](https://user-images.githubusercontent.com/670728/72524965-5b209080-3863-11ea-89c2-bfb124d48976.png)

For me the problem is maybe a problem of translation .

In english , the first box on the dashboard is "Balance" 

![image](https://user-images.githubusercontent.com/670728/72525964-9f149500-3865-11ea-8ec0-e658c3c2b91e.png)

Each month  I have some expense on my visa and i pay back on the 10 th of the month.

The balance tell me that i have spend 687€ to repay my Visa. And it's indeed correct.

In french, this box is named : "Solde" 

For me "Solde" is what left on my account. And is why I don't agree with this amount.
On my account, I don't have 964€ but 289.93 ( the sum of the 2th colomn withut the Visa line. )  

There is a little difference between "Balance" and "Solde" in french.

Where can i see my solde  ( what it's left on all my account without visa ) ? 

Thanks to you

**Comment by sea-odoo** [comment]
Ok, uncheck "Include in net worth" and check the 4th boxes...

Thanks we can close this issue

**Comment by Crupuk** [comment]
Ok, uncheck "Include in net worth" and check the 4th boxes...

Thanks we can close this issue
