### ISSUE TITLE
Multiple currencies ignored

### ISSUE THREAD

**Issue by alexjj** [firefly-iii/firefly-iii#305]
Firstly - nice project! It looks awesome. I've given up on various programs I've tried so far and am just back in a spreadsheet, which is fine but meh.

It seems that whatever currency used for transactions is ignored when displaying charts or summaries etc. and it just displays the amount with the default currency symbol instead.

e.g. if I have the default currency as $, and make a transaction for £100. The graph of this account will show $100. 

Just using the trial on your website, and it seems there's no place for exchange rates, so I guess multiple currencies isn't supported?

**Comment by JC5** [comment]
Hi! First of all, thanks for the compliments. I appreciate it :) 

Yes, it is supported for a given type of "support". Mostly I added it so multiple users could use different currencies. The charts will fall back to this currency, mainly because it is easier. 

Adding exchange rates is something I haven't worked on yet, even though there are libraries that can automatically import the data live. 

The main problem is that the raw exchange rate is rarely the actual exchange rate. Banks add a percentage to the exchange rate as well as the amount itself to cover costs and make a profit. 

So, each exchange rate would be have to be added manually to each transaction (banks often mention the used exchange rate). This could be based on a 'global' web based exchange rate. Assuming no other factors influence what the final amount is the bank will charge you (transaction costs, etc). 

The alternative would be to split the actual amount of each transaction and store it separately from the transactions. This would mean you would be able to specify amounts in many currencies (using the one most relevant at any point). For example, an Amazon purchase could both be 100,- USD and 89.66 EUR.

Both options are doable but need a lot of work. I'll think about and get back to you, let me know what your thoughts are. What would you prefer? What could work force you?

**Comment by alexjj** [comment]
The reason I'm back in a spreadsheet is that multiple currencies isn't easy and when it is implemented it doesn't always fit the users needs. GnuCash, for example, has a base currency and any time you enter a transaction in a different one it asks you for the exchange rate for that transaction. This can be pulled from yahoo/google or manually entered. In all the summaries/reports it then uses the base currency and you never see what you spent in that other currency.

Ledger and [similar](http://plaintextaccounting.org) programs keep everything separate and show you each currency in all reports. They make use of a prices file and then you can give it an option to convert to a single currency. The prices' file is a list of dates and exchange rates and it uses that to compute.

In my situation I only ever move money one way, and in lumps. So for my spreadsheet I take the exchange rate I actually got for my lump sum movement and then apply it to all my spending until I move some again. I also never move money back again so I'm not interested in the exchange rate at the moment I make the transaction. I like to see both currencies in reports as then I can budget transactions in both countries, and I like to see overall spending in my base currency.

I think automatic exchange rate data is nice as an indicator, but for each transaction the user needs to enter the specific one to them - either the exchange rate or the actual amount in base currency.

**Comment by JC5** [comment]
Alright, let me think about some features the application could use.

- The ability to set a default currency for an asset account. This would mainly be cosmetical at first, changing the default selection when creating a new transaction.
- The ability to set the exchange rate when entering a transaction.
  - Firefly must be able to suggest the exchange rate.
  - Firefly will display the resulting amount.

Now, for the currencies involved. Assuming the default currency is EUR and the account is also in EUR (see above, first point). The user selects GBP.

- Firefly displays:
  - The actual amount in GBP as the user fills it in (no change to user input) in the original input box.
  - Firefly suggests an exchange rate of ~1.19 (EUR for every GBP) in a new input box.
  - Firefly shows the calculated amount in EUR in a new input box.
  - User has the ability to overrule both the exchange rate and the calculated amount. If the user overrules the calculated amount, changing the exchange rate does not do anything, until the calculated amount is released again.
  
If the account is in GBP and the default currency is EUR, Firefly will:
  - When the user selects GBP, the same routine as above, converting to EUR.
  - When the user selects EUR, the same routine as above, converting to GBP.
  - When the user selects USD or others, the same routine as above, converting to GBP (the account).
  
That should allow some basic input / output for multiple currencies.

As for the reports, please help me by telling me specifically which pages / charts should show double or foreign currencies.

**Comment by alexjj** [comment]
Sounds like a good way about it. 

For the reports/charts, it would be nice to duplicate each one per currency - keeping all transactions in the inputted currency only, i.e. no converting - and then a single one just as base currency with everything converted to default currency. Perhaps a toggle or something to keep it from being overwhelming with charts?

**Comment by JC5** [comment]
Converting should / must only happen when:

- the transaction "knows" in which currency it needs to be displayed, and this one is different from the one it has been stored with.
- the transaction knows its alternative amount in the requested currency (see above) OR it knows the exchange rate.

Then, each transaction can be converted / displayed in a preferred currency. Using perhaps a drop down or URL parameter (for reports). Select transactions would appear in GBP instead of EUR. 

The result of sums depends greatly on the final set of transactions. Especially mixed content will be difficult.

But one step at a time. Don't expect big changes too soon, but it's definitely something I'm going to work on.

**Comment by JC5** [comment]
Good idea, I'll save those links! Thanks =)

**Comment by tomazsustar** [comment]
I am also very interested in the multi currency support.

Where the multi currency support comes in question on the transaction level is only with transfer transactions. I think that once can assume that one asset account is always in one currency, at least I have not found anything else. On the bank you can open lets say GPB or EUR account, but not mixed one. So asset accounts should "accept" only their currency. Usually what you do is you transfer money from one account with one currency to another account with another currency. At that point the exchange rate should be defined and stored together with the transaction. 

All the rest is just of informative nature. Of course you could buy something in CNY, but it will still be booked as an expense in EUR if you have EUR asset account so the amount in CNY does not have any meaningful information to me as I do not have any assets in CNY...

For reports: if you ask yourself how much assets do I have and you have assets in different currencies the answer is always in multiple currencies:
xxxxx EUR and xxxxx GPB. 

The exchage rate between assets is never fixed because I keep them in different currencies.

So one could ask himself another question. How much EUR I would have if I would convert all my GPB in EUR today (at the exchange rate valid today). This basically means that reports need to:
- either display separate amounts for each currency. (e.g. xxxxx EUR and xxxxx GPB)
- or convert the amounts to the selected currency with selected (automatically obtained) exchange rate on the fly. 

So until now I was just complaining... so where can I start coding?

**Comment by JC5** [comment]
Yes, asset accounts already contain a designated default currency. It's step one in this process. However, expenses on that asset account (and income as well) can be set to another currency, and Firefly will not complain. That should change first. Or, Firefly should indicate the discrepancy and offer to do the currency conversion themselves.

I'll have to think of some use cases and stuff.

**Comment by tomazsustar** [comment]
Since we kind of agree on that matter I can take a look into that if you want.

**Comment by JC5** [comment]
The [demo site](https://firefly-iii.nder.be/) contains some basic code that handles foreign currencies.

- Creating a deposit / withdrawal gives you the option to select a different currency (as it always has). New is the ability to set the amount in both currencies (foreign and native) based on the currency the account is in. Firefly will suggest an exchange rate but you're free to change the result.
- Transfers may also be between accounts with different currencies.

There is a "foreign" checking account in British Pounds which should service as an example.

**Comment by JC5** [comment]
About 99% of the software now supports multiple currencies.

**Comment by Ekvilog** [comment]
Hi, I am wondering if you are going to add the exchange rates in the upcoming new version? It would be fantastic!

**Comment by JC5** [comment]
They are already present. If you create transactions and use foreign currencies, Firefly III will suggest the correct exchange rate.
