### ISSUE TITLE
Budgets with categories or sub-budgets

### ISSUE THREAD

**Issue by ae-mo** [firefly-iii/firefly-iii#3069]
**Description**

My budgets are something like macrocategories:, e.g. I have a 'house' budget where all the expenses for my house go, such as rent, bills, new furniture, etc.

I would like to keep track of the categories where the money goes within a budget. For instance I would like to be able to say something like "this month I'm going to spend 300$ in furniture".

**Solution**

Budgets should let the user add categories (could reuse Firefly categories maybe) or sub-budgets, to which the user could assign money from the parent budget.

**Additional context**

I'm asking for this because sometimes I know in advance what I need to buy during a given month, but right now I have to keep track of this manually. 

Moreover, categories shouldn't carry over from month to month, or at least this should be optional.

If something similar can already be achieved in Firefly I apologise for not finding out before and I would like to know about it.

PS: I love Firefly, thank for all the work!

**Comment by JC5** [comment]
Thanks for the compliments!

Regarding sub-budgets and sub-categories: https://docs.firefly-iii.org/support/features#often-requested-features

You can use the "budget report" on the reports page to get a monthly overview of your budget(s) and the categories within it. Use the magic words to make this easy to bookmark: https://docs.firefly-iii.org/advanced-concepts/reports

I'm not really sure what you mean with "categories shouldn't carry over" because categories don't carry over anything. Transactions are linked to categories and that's it. Could you clarify?

**Comment by ae-mo** [comment]
I meant in the hypothesis of having budgets with categories, let's say I want to spend 300$ on category 'furniture' in the 'house' budget. If at the end of the month I have spent only 250$, I think it wouldn't be appropriate to automatically assign the remaining 50$ to the same category of the budget next month, I'd rather have them in the budget but without category. But I guess that would be configurable.

Thanks for your answer, I will check the provided links.

**Comment by JC5** [comment]
Check out: https://github.com/firefly-iii/firefly-iii/issues/2578
