### ISSUE TITLE
Typo in welcome e-mail for new users

### ISSUE THREAD

**Issue by MadWalnut** [firefly-iii/firefly-iii#3075]
Pretty minor thing, but I noticed a typo in the welcome e-mail for new users in 5.0.4. It says _Welkome_ instead of _Welcome_.

Should be easy to change here:
https://github.com/firefly-iii/firefly-iii/blob/3864855967ac24a86d451eb60814f4afbc23541a/resources/views/v1/emails/registered-text.twig#L2

**Screenshot:**
![Screenshot_1](https://user-images.githubusercontent.com/33835479/73614477-b2fb1d80-45ff-11ea-8ab6-a95e99214d59.png)

**Comment by JC5** [comment]
Nicely spotted. That must have been there for years. I'll pick it up.

**Comment by scar45** [comment]
Not to jump on the spelling error bandwagon, but I recently noticed one in the error e-mail subject line (says _Firely_ III instead of _Firefly_ III):

https://github.com/firefly-iii/firefly-iii/blob/4d6ae7e0ecf79959ec71a7d76c6f56c510a17666/app/Jobs/MailError.php#L86

Lumping into this existing issue as it's still open and it's a minor thing of course.
