### ISSUE TITLE
Discount Field / Stats

### ISSUE THREAD

**Issue by Betteraw** [firefly-iii/firefly-iii#3089]
**Description**

- Possibilty to define a discount or the original prize (of something)
- And stats about total discount achieved

-->

**Solution**
- a field for discount / original prize (absolut or %) for a new withdrawal

**Alternatives**

- Buggy Workaround Split-Withdrawal and no stats #1918

**Additional context**
Would be awesome feature!

**Bonus points**
Firefly III is awesome!! I really enjoy working with it.
Incomparable to all "alternatives" I found on the web.
-->

**Comment by JC5** [comment]
Hi,

Thanks for the suggestion. It's always good to see when people submit stuff like this. Especially since it seems you joined GitHub specifically to post this!

Keeping track of discounts however, I don't really feel it fits the Firefly III use case. I like discounts as much as the next guy but I don't see the usefulness of tracking the percentage. It doesn't give you extra financial insights, although I guess it could be a bragging factor.

But having said that, I'm afraid I must decline the idea. Thanks again for posting :grin:
