### ISSUE TITLE
Question regarding Database tables

### ISSUE THREAD

**Issue by GaryQ** [firefly-iii/firefly-iii#3166]
Could you please clarify a couple database related questions?

1 - The following tables seem redundant and unused:
 budget_transaction 
category_transaction 
group_journals

2 - There's also rt_meta which has a foreign key with no descriptive name to it's linked key.

3 - transactions table has a description field all entries are null. 

4 - The journal_meta table What's it's purpose? All the entries there have a deleted at date set.

Thanks

**Comment by JC5** [comment]
Yes. `budget_transaction` and `category_transaction` were used when transactions (not journals) had budget and category information. `group_journals` was created but never used. If you want to delete them, feel free. Because of possible migration issues from previous versions I won't delete them outright.

Table `rt_meta` [links back](https://github.com/firefly-iii/firefly-iii/blob/master/app/Models/RecurrenceTransactionMeta.php#L78) to 'recurrence transaction' objects which in turn are used in recurring transactions (which are called "recurrences" in the database).

The description field in `transactions` had a purpose before 4.x (can't remember which one). One of the migrations cleans them out and migrates the data to another field.

The `journal_meta` contains all transaction journal related meta-data. One simple way to add data to this table is by setting the "interest date" on a transaction.

**Comment by GaryQ** [comment]
Thanks, Much appreciated and pretty much what I though. 
That's a lot of tables for the recurrences... 5 in all. 2 separate metas.

On another note the Vue optimizations seem to be working OK!?

**Comment by JC5** [comment]
Yep, lots of tables for that one :grin:

Vue seems to work just fine! :+1:
