### ISSUE TITLE
Bug with decimal comma separator

### ISSUE THREAD

**Issue by Agraphie** [firefly-iii/firefly-iii#3203]
**Bug description**
I am running Firefly III version 5.1.1, and my problem is:

Hi,

when entering an amount with a comma decimal separator (",") I get the following error:
<img width="399" alt="grafik" src="https://user-images.githubusercontent.com/2665370/77309627-434f0800-6cfd-11ea-93df-61c33a600adf.png">

My browser language and firefly language is set to German. I could swear it worked before, but maybe I'm wrong?

**Steps to reproduce**
Have your browser and installation set to German (possible other languages with use "," as separator work as well), enter a decimal number and try to save.

Any ideas?

**Comment by Agraphie** [comment]
Just found #3178 and I thought I searched for corresponding issues. Closing this in favour of the other.

**Comment by JC5** [comment]
I appreciate that you self-diagnosed your issue, but I've made some changes in Firefly III for this issue regardless.

The issue you describe has to do with HTML number inputs and it can be a bit weird. So as far as the fix is concerned:

- If you use Firefly III in (US) English and try to submit "1,2", it won't work because your browser blanks out the input. This is part of the (very annoying) standard. This causes the error "the amount must be a number"
- If you use Firefly III in German and submit "1,4", Firefly III will auto-correct to "1.4" so the backend is happy.

**Comment by Agraphie** [comment]
Cool, thanks! Do you know why this bug appeared? Because I'm fairly certain I didn't have this problem before. Also I think that suddenly when saving a transaction I'm seeing the English word "Create" and not the German translation anymore. Everything else is in German though. I'll investigate and if there's an issue I'll create a new ticket. Thanks!

**Comment by JC5** [comment]
I have no idea. Keep me posted about the translation thing though! :+1:
