### ISSUE TITLE
IBAN already in use

### ISSUE THREAD

**Issue by bramboe** [firefly-iii/firefly-iii#3217]
**Bug description**
I am running Firefly III version 5.1.1, and my problem is:

I have many different accounts from the same bank (Bunq). When I try to add the IBAN to these accounts I get the following message: "It looks like this IBAN is already in use."

I understand the first part of the IBAN is the same but the acount number is different. Is there a work around?
<img width="829" alt="Screenshot 2020-03-29 at 18 22 28" src="https://user-images.githubusercontent.com/37293908/77854386-617ba300-71ea-11ea-9709-5eb589f69819.png">

**Comment by JC5** [comment]
I'm afraid not. Bunq should give new "sub-accounts" their own IBAN. At least, that's what happens for me.

**Comment by bramboe** [comment]
Hey JC5, I don't understand, each sub account has it's own IBAN.

**Comment by JC5** [comment]
So... I don’t get it? 

Although if you tried the import once before there’s a good chance you have either expense or revenue accounts with those IBAN’s.

**Comment by bramboe** [comment]
I just showed the accounts as an example, that sub-account _have_ their own IBAN's. When I click on an account within Asset accounts, I can't add the IBAN that belongs to that specific asset account, with the 'error' that the IBAN already is in use. IF I could add it, it would make the import much easier, because it would automatically select it.

**Comment by JC5** [comment]
Check your database. You may have deleted accounts or other account types with this IBAN. I'll do some debugging on my end.

**Comment by JC5** [comment]
I double checked. There's no way to store a double IBAN unless the first account is an expense account *and* the second one is a revenue account. If you try any other combination, it breaks.

If you delete any existing accounts with your bunq IBAN's it'll work just fine.

**Comment by bramboe** [comment]
👋🏻 I removed my DB and started from scratch. I can now add all accounts.

**Comment by bramboe** [comment]
So I started from scratch, imported all my bank data. Now trying to align my current balance per account and I get the same error. Please see the clip. (I removed my data from the movie)
![error](https://user-images.githubusercontent.com/37293908/77965449-4cce0680-72e1-11ea-81a8-ea5f6d994009.gif)

**Comment by JC5** [comment]
Mmmm. So let me get this straight, the movie isn't entirely clear: 

- the balance of one or more accounts is incorrect, despite you having imported from day 0?
- editing an asset account created before the import won't work, because the IBAN is in use?

**Comment by JC5** [comment]
OK you found a pretty interesting flaw in the Firefly III API. So stay tuned for an update, this could take some time 😅 

Basically, when you submit a transaction with name and IBAN, like the bunq importer, the data is validated using the transaction type you submit. The bunq importer always submits a "withdrawal" because it doesn't know any better.

So two courses of action are valid:

1. The bunq importer should search and list all of the user's asset accounts and make sure to submit a "transfer" when the IBAN (not the name) is found in the asset accounts.
2. Firefly III should auto-change the user's suggested transaction type when it sees, based on the IBAN, that existing accounts *would* fit if only the user had suggested the right transaction type.

**Comment by bramboe** [comment]
> Mmmm. So let me get this straight, the movie isn't entirely clear:
> 
> * the balance of one or more accounts is incorrect, despite you having imported from day 0?
> * editing an asset account created before the import won't work, because the IBAN is in use?

1. yes, this is related to the bunq importer and I believe it has to do with error duplication. But taking it for granted. 
2. I added all my accounts manually, incl. the IBAN. After the import, I try to align my balance (on FF) for each account with actual bunq balance.

**Comment by JC5** [comment]
Ok. Don’t balance using a virtual balance, use the opening balance instead to correct it. Having said that: even with some improvements (see my other comment) the bunq importer isn’t perfect yet. Some transactions are stored twice. Stay tuned. It should never be necessary to manually correct the balance of your accounts.

**Comment by bramboe** [comment]
Good morning JC5, I'm aware it's not perfect yet. I'm only grateful that this tool exists. Thank you.

**Comment by JC5** [comment]
Thanks! And thank you for testing and trying it 😊

**Comment by JC5** [comment]
Alright, I consider the original issue fixed: I've just built a new image of the bunq importer that will correctly link transactions to the right account, if all IBAN's are filled in correctly beforehand. 

However, another issue still exists where Firefly III will store specific transfers twice, because apparantly bunq gives transfers between bunq accounts different ID's (coming from A and coming from B). It's a work in progress.

**Comment by JC5** [comment]
The importer works for me™.

It will detect duplicate transactions, it won't run twice and import everything again, and in my personal case, all balances are correct after importing. 

It requires you to double check that you have no personal bunq accounts in your expense/revenue account list. Not even inactive ones. I'll write something in the docs about this. 

The develop image is up to date with these changes so you should be able to test this. Let me know!

**Comment by bramboe** [comment]
The original issue is fixed. Thanks

**Comment by Syphdias** [comment]
Crap, I just ran into that bug and the images are from a few days ago. Is there a good way to delete an account or more than 50 transaction at a time?
Currently, I am still at the import/migrating point where I don't mind tossing the database but that will change if I more actively start using it.
