### ISSUE TITLE
support case insensitive search

### ISSUE THREAD

**Issue by kevbob1** [firefly-iii/firefly-iii#3230]
**Description**
I would like Firefly to support case insensitve search for transactions.  It would streamline searching for a transaction and not need to remember how a description was capitalized.  (Please don't close this right away like #2742,  if i have time this weekend i will implement and send a PR)

**Solution**
It would make the user experience more intuive and save time.

**Additional context**
example for postgres and sqlite db:
select * from transaction_journals where UPPER(description) LIKE UPPER('micro%');

example for mysql db:
select * from transaction_journals where UCASE(description) LIKE UCASE('micro%');

**Comment by JC5** [comment]
Yes, me too. I'm as annoyed by it as you are.

However, I'm not going to add a if/else statement for different database types. It feels hacky and it isn't future-proof. I look forward to a PR if you have it.

**Comment by sephrat** [comment]
I have no idea how mainstream my proposed solution is, but here it goes:
You could add a column dedicated for searches in each table and populate it during the update. All searches should use this column instead of the one dedicated for display.
Doing like so also allows to ignore accents and special caracters (µ translates as U, éèêëÊË translates as E, etc.)

It's the technique used for decades on a major ERP software I work on, which works independent of a database platform.
I'd really love to contribute, maybe one day I'll find time to learn PHP...

**Comment by JC5** [comment]
Let me just say that's a very corporate solution for this particular problem. I'd rather live with the issue than implement that solution to be honest.

**Comment by jesmiatka** [comment]
I see you are using LIKE, can't you replace this with ILIKE?

https://github.com/firefly-iii/firefly-iii/blob/master/app/Repositories/Bill/BillRepository.php#L653

**Comment by JC5** [comment]
That only works in Postgresql.

**Comment by kevbob1** [comment]
I looked into implementing this.  The "no if/else statements per database" rule makes it challenging.  I understand why.   You are using the ORM and QueryBuilder apis heavily and don't want to break what is there.  I found a few extension libraries for Eloquent ORM that might do the trick.  it will take some more investigation to find something that fits.
