### ISSUE TITLE
Silent fail of split transaction from different source accounts 

### ISSUE THREAD

**Issue by Loosper** [firefly-iii/firefly-iii#3265]
**Bug description**
I am running Firefly III version 5.2.1, and my problem is:

When creating a transaction with 2 splits I can select different source accounts. However after saving it, it silently converts both of them to the first one.

My understanding from other issues is that this should not be possible. However I think it should at least be explicit (ex. grey out the second source or something along those lines).

**Steps to reproduce**
1. Create a new transaction and add a split
1. Select source account for first split
1. Select a different source account for second split
1. Enter amounts and budgets
1. Submit

**Bonus points**
- [x] I was able to replicate it on the demo site https://demo.firefly-iii.org/

**Comment by JC5** [comment]
It depends a bit on whether or not you're actively selecting the accounts. When Firefly III can predict what you're doing, this works:

<img width="466" alt="Screenshot 2020-04-15 at 16 03 49" src="https://user-images.githubusercontent.com/5889984/79346653-2683aa00-7f22-11ea-8e8c-dd5a77aba67d.png">

However, this isn't always the case. I'll write it up as an enhancement, and see if Firefly III can't warn you about this stuff.

**Comment by Loosper** [comment]
Ah, I see what you mean. But then it still doesn't update if the destination is left empty:

![image](https://user-images.githubusercontent.com/15300034/79498709-a80e3180-8021-11ea-8afb-183627c748e1.png)

Would this be a case of 'using it wrong'? In my use case I do not care where the money went, as long as it checks out as 'spent'.

**Comment by JC5** [comment]
No it's not about using it wrong. What you're doing is fine.

The form is very flexible. You can enter whatever you want and Firefly III will try to handle it. There's a few limitations but nothing really solid. 

In many cases, Firefly III isn't able to predict what you're trying to do (it could go both ways) so you're getting the freedom to do it either way. If it turns out (after you press submit) you hit some kind of limitation, Firefly III should warn you. That's something I want to add.

There are some users who don't use destination/source accounts to indicate where the money came from or went to, just that it did. That's OK, it works fine either way.

**Comment by Loosper** [comment]
I've been trying to wrap my head around how it works, but it seems really incosistent, as an example:
![image](https://user-images.githubusercontent.com/15300034/79696909-68408780-8277-11ea-94e3-56b6eb85d342.png)

Visually it is locked into two accounts, but again, it is submitted as the same. The warning would be nice as a feature, but I find this silent conversin to be a serious bug.

Anyway, thank you for doing this, hopefully it's fixable!

**Comment by Zsub** [comment]
I run into a similar issue, where I try to split a transaction (deposit, or that's how I see it) coming from a single 'expense' account to two different liabilities.

Concrete: I try to split the 'betalingskorting' I get as a deposit coming from DUO across both parts of my study loan. The split works, just both splits are deposited into one part of my study loan. My workaround now is to create two transactions, but I was wondering if this was by design.

**Comment by JC5** [comment]
I've added a warning to the form.
