### ISSUE TITLE
How to handle accounts that have both expenses and revenues

### ISSUE THREAD

**Issue by niekvanderkooy** [firefly-iii/firefly-iii#328]
Some accounts I sometimes transfer money to, while other times I get money from that account.

After an initial import from my bank the account got categorized as a revenue account since I have gotten more money from the account than I have paid to it (with both withdrawals and expenses connected to that account). However, now I cannot add a withdrawal to the account since the typeahead for a new transaction only shows me expense accounts. If I put in the name of the existing account, then a new (expense) account is created.

Is there a way to connect withdrawals to a revenue account, or deposits to an expense account?

**Comment by JC5** [comment]
No, there is not. Pretty much intentionally, the system will create two separate accounts.

Firstly, this helps maintain the internal consistency by making sure that deposits, withdrawals and transfers connect to the correct account types.

Secondly, this is done because the _role_ of the account is vastly different, even if it's the same party. Examples include the Belastingdienst or a super market or something. Payment of taxes and return of taxes are different things.

It is confusing yes, because this way it is difficult to get an overview of a "double-named" account, such as the Belastingdienst. It's either the withdrawals or the deposits and never both.

That last thing is something to build or add. Either a connection between them, or a report kind of view that shows both of them. A filter or a search option even.

But alas, you cannot "combine" accounts.

**Comment by niekvanderkooy** [comment]
This makes sense.

However, in that case I think the CSV import needs to be altered to reflect this. Currently if you import a CSV and map an opposing account number to a Firefly account, then both credits and debits to do with this opposing account number will be ascribed to this Firefly account. Thus, I currently have a revenue account with both withdrawals and deposits, which should not be possible (correct?)

**Comment by JC5** [comment]
Yes, the import needs some changes. It is annoying enough that the import show stuff like this:

![image](https://cloud.githubusercontent.com/assets/5889984/18809475/8652a14e-827c-11e6-8715-852872572d63.png)


And it should at least select the correct account type when importing. I am not sure why it does not do so, and I'll search for the problem and fix it.

**Comment by niekvanderkooy** [comment]
To fix that you could append the account name with "(expense)" or "(revenue)" or something along those lines.

In addition, for the mapping as a whole, couldn't you make the user select two mappings: one for debit and one for credit? So that for each line in your CSV it checks if it's a credit or a debit, and picks the one you selected for that situation.
In that way you could select two totally different accounts depending on if it's a credit or debit, if that makes sense in your situation.

**Comment by JC5** [comment]
True, but the mapping is applied to both. As you say, you would have to make the distinction between those two somehow. Because I could map to "expense" but every time a deposit pops up it would break again.

That doesn't even include the possibility of having three account types with the same name. Which isn't unheard of if you work at a bank, for example. So it won't catch transfers.

For now, the solution will become something like this:

- The list of opposing account names is filtered so double entries will not exist any more.
- This will mean that users will select revenue accounts with withdrawals and vice versa.
- Instead of saving those entries, the validation routine already in place will keep an eye on such entries (it should do this already) and re-map them to either new opposing accounts, or the other opposing account with the same name.

That way, the mapping is more or less "name" based and not "ID"-based. But that should not be a problem.

**Comment by niekvanderkooy** [comment]
> Because I could map to "expense" but every time a deposit pops up it would break again.

I think I meant it the other way around - when you for example map "opposing account number" to an account, for every account number you map you would have to select two accounts: one expense account for when that specific transaction happens to be an expense, and a revenue account for the times it happens to be a credit transaction.

> That doesn't even include the possibility of having three account types with the same name. Which isn't unheard of if you work at a bank, for example.

I guess that's true, but then I would say that it's the user's responsibility to realise he can't map names to accounts, since that would not work in his situation.

But I guess your solution would work as well.

**Comment by JC5** [comment]
I'm referring this to the discussion about the account report, which I still need to build.
