### ISSUE TITLE
Bills creation enhancements

### ISSUE THREAD

**Issue by kungfu71186** [firefly-iii/firefly-iii#3303]
**Description**
some features that would be nice are:

- Custom repeats (every x day, first day of the month, every 2 weeks, so on.)
- Allow one-time bills

**Solution**
Add more options to repeats. The one-time bills make more sense if you have some kind of invoice attached to this. #3302 

**What are alternatives?**

**Additional context**

**Bonus points**

**Comment by JC5** [comment]
The goals of bills isn't to be that accurate, nor is it meant to keep track of one-off bills. The idea is that it gives you at least some idea of what's coming in the next period: ie. rent, utilities, the gym. I built it because I would think I was home safe at the end of the month, only to be surprised when a recurring bill would hit me.

You can do bi-weekly bills if you want to, by selecting "weekly" and skipping 1. 

One-time bills and very accurate repetitions just aren't the use case for these bills.
