### ISSUE TITLE
Suggestion: "outstanding" amounts, and transfers between categories

### ISSUE THREAD

**Issue by niekvanderkooy** [firefly-iii/firefly-iii#331]
I want to give the foundation for a suggestion which would seem useful in my mind. This is something that might not be applicable to a lot of people, and goes more into the realm of actual accounting than personal finance, but there are situations in which it would seem useful to me, so I wanted to discuss it anyway.

I hope the two ideas make sense as I describe them below, with the small examples of how you would use it. If you want, I could also write up a use case for where this would seem useful to me.

1) A way to track 'outstanding' amounts, either which you need to pay or are payable to you.
When giving someone an advance, it is currently kind of possible to track money due using tags. For example, if you pay for a dinner and need to get money back from other participants, you can create a tag for the expense and any repayments you get, and you know you will have gotten your money back when the tag gets a balance of 0. However, there is no way to keep track of _who_ is supposed to pay you back. In addition, the tag interface currently does not make it easy to see which tags have been balanced out and which still need payment. (In addition, tags might not always have to be balanced out exactly: if you pay €50 for yourself and 4 friends, the balancing is 'completed' when your tag is €10 negative - your own portion).

What I would suggest is a system where you are able to add an outstanding balance, and be able to give it all the properties of a withdrawal/deposit (depending if you are expecting money or still need to pay money), except for assigning it an asset account (since the money has not been received/spent yet, so it cannot be assigned to a asset account). This 'transaction' would then be able to be booked on a date, and would for example show up as income in the category you assigned it to. In addition you could already assign it to a revenue/expense account, to be able to keep track how much is owed between you and a person and/or company.
Of course this needs to be balanced financially, which would be done with the automatically maintained "debtors" or "creditors" categories.

2) A way to virtually 'transfer' money between categories / paying outstanding amounts (see point (1)) using a different category.
This is most useful for, for example, clearing advances. For example, you pay €10,10 for someone. This 'should not' have been an expense for you, so you don't categorise it (or perhaps you add it to an 'advances' category), and you add an outstanding amount of this €10,10 which you assign to this person, so you remember that he still owes you this amount. Later, he transfers €10 to you, because he forgot the €0,10. You use this deposit to pay off the outstanding amount, as described as a possibility in (1), but this of course leaves €0,10 open as an outstanding amount. You decide you do not want to bother him for the last €0,10, since this would be too much hassle. This however leaves you with a debtor who owes you €0,10 which will never be paid off. To fix this, you could edit the original transaction to split the €10,10 into an outstanding amount of €10 and €0,10 of an extra expense. However, if this payment occurs a while after the original advance, then editing an old transaction is considered bad practice. A better way would be to virtually transfer €0,10 from a category (Say "Unexpected expenses") to pay off the open transaction / get your "Debtors" category back to €0.

**Comment by JC5** [comment]
1) is a small-time small-amount loan or debt. Correct? Ideas have been raised to manage "huge" loans / debts such as mortgages and student loans. But this would be a small one, which doesn't need the large amount of managing a mortgage would need. In a sense, it is like "You borrowed it" where you keep track of the things you've lent your friends. And vice versa. Only this time, it's with money.

In a sense this is also a bill, presented to you or by you. A "factuur" to use the Dutch word. Only it's a smalltime one.

As for the asset account: 

> When giving someone an advance

if you spend money it has to come from somewhere. It's still spent even though you'll get it back. It needs an asset account.

2) shows how complex this system would become. Partial repayments mean there are losses, which you write off. Likewise, if a friend clears a debt you have, it's a gain. Categories can't really hold money, but I understand what you're trying to do. The money seems to come from nowhere.

---

What Firefly would need to handle this is a system to handle "facturen" or bills. This I think, must start with a feature where incoming bills can be registered, and payments assigned to them.

For example, an unexpected repair bill could be stored (with attachments and what-not) somewhere as a separate object. Payments towards this bill (let's say 3 installments) would count towards the bill. The rest of Firefly doesn't need to know this: the 3 payments are regular expenses with a regular expense account. Firefly would present you with the outstanding amount and the ability to close the bill (when the amount has not been paid in full). Likewise, the bill can be expanded with extra payments (rent or fees) enlarging the bill.

Likewise, when somebody pays for you, they present you with a "bill". A simple bill, but a bill none-the-less. You pay that bill and presto.

Or, you present other people with a "bill". All the same thing. It's just that the amounts are smaller.

What do you think?

**Comment by niekvanderkooy** [comment]
> 1) is a small-time small-amount loan or debt. Correct?

Yes, correct. Actual 'loans' come with interest etc which needs to be taken into account. This would be a simple "I need to get this exact amount back from you", exactly like you describe.

> As for the asset account:
> > When giving someone an advance

> if you spend money it has to come from somewhere. It's still spent even though you'll get it back. It > needs an asset account.
Yes, true, but you would only assign that once the money comes in.
So you would have a workflow like this:

1. Have an actual withdrawal, from one of your asset accounts, which is the advance. This indeed needs an asset account. I would personally assign this to the category "Advances", which then becomes negative by the amount of debt we have (since it's an expense by me at this point).
2. I would create the outstanding transaction, and this would possibly be assigned to a revenue account (your friend) and a category (In my case, the Advances category. This means my Advances category gets back to a balance of 0 - since I have balanced my expense with the income I am still expecting - and the virtual category "Debtors" goes to the amount I am expecting since I have not actually received it yet). There would be no asset account on this transaction yet, since we do not have the money yet
3. When we get the deposit from our friend, we are able to tell the system that this deposit pays back the money owed to us. This brings up the balance on our asset account we select at this point in time (since only now we actually get the money), and it brings the balance of the "Debtors" category to 0, since the debt is paid.

> Categories can't really hold money

> The money seems to come from nowhere.

You are right, a category doesn't hold money, but it has a balance in the sense that it sums up all the transactions assigned to it. What I would thus like to do is create a transaction on a "virtual" asset account. This account does not exist, so it would always have to have a balance of 0. However, one side of the transaction would then be assigned to one category, while the other side is assigned to a different one, which is basically moving balance from one category to another. 

>  The rest of Firefly doesn't need to know this: the 3 payments are regular expenses with a regular expense account. 

Your explanation sounds almost like what I mean, except I want to clarify something about the above.
For the "Asset account" part of firefly your above statement is correct. However, not for the "Categories" side of Firefly. Here, the expense on the category would be one single total amount on the day that the open transaction is booked, while the payments do not influence that category anymore (Only the "Debtors" category).
So to make it more clear, an example: I buy tickets for a concert for myself and 3 friends for a total of €100 (€25 is my own part). My asset account had exactly €100.
> Category Concerts: 0
> Category Advances: 0
> Category Debtors: 0
> Asset account Rabobank: 100

1. On 1-8-2016 I have an expense of €100. I split the transaction into €25 on the category "Concerts", €75 on "Advances".
> Category Concerts: -25
> Category Advances: -75
> Category Debtors: 0
> Asset account Rabobank: 0

2. On 2-8-2016 I create 3 bills for €25, assigned to advances (On the revenue accounts of my friends names). This action is what influences the Advances account, not the payments themselves
> Category Concerts: -25
> Category Advances: 0
> Category Debtors: -75
> Asset account Rabobank: 0

3. On 3-8-2016 two people pay their bill. On the asset account side this is indeed a regular expense and Firefly does not need to know any different. However, it is of importance that this is not assigned to a regular category like Advances, but used to pay off the bills which influences our virtual category Debtors
> Category Concerts: -25
> Category Advances: 0
> Category Debtors: -25
> Asset account Rabobank: 50

4. For some reason I decide to write of the last bill / no longer have my friend pay for it on 4-8-2016. Here, I would then use the transfer over a virtual account to clear the bill, and expend it "myself"
> Category Concerts: -25
> Category Advances: 0
> Category Unforseen expenses: -25
> Category Debtors: 0
> Asset account Rabobank: 50

Does that make sense?

**Comment by JC5** [comment]
It makes sense, but I'm not sure some of your choices are the best ones. There's a difference between administrating loans and debts and managing the transactions that are a part of them. In your examples, you're doing both of these things simultaneously. The system to manage transactions (Firefly) does not match your system to handle advances, so you're twisting Firefly to match your administration.

It doesn't really fit.

First of all, creating an incoming transaction without an asset account is impossible in a double entry booking system, because you're creating an imbalance. There is money coming in that doesn't fit anywhere. You record your friend giving money to thin air. You balance your books when he pays. That is incorrect. Your books should always be balanced. The transaction cannot exist in Firefly until he actually pays. You can cheat of course with virtual asset accounts but again, it doesn't fit.

Recording unrecoverable loans is something Firefly cannot do. Using categories doesn't really fit. Excluding yourself from a loan only makes sense in Firefly's transaction system because it is included in the _transaction_. But your ticket was never part of the _loan_. Different thing.

What you need to do in order to get a simple loan/debt management system fitted with Firefly is simple: forget Firefly. Don't think about expense accounts. Forget categories and transactions.

If you advance three tickets, you create three short-term no-interest peer-to-peer Loans to three different Debtors or Borrowers. These three people all owe you amount X. This amount does not change.

Whenever they pay back, you remove amount X from the debt. This event _may be_ connected to an incoming deposit from that person, but that does not have to be the case. It's up to you. Forget Firefly.

If they default, the debt is "closed" and the money written off as a loss. Firefly can't even handle that, so don't bother.

This process of debts, loans, payments and everything else exists outside of Firefly. Certain events are connected to transactions in Firefly, but that's it. In turn, Firefly could use events from your system to display information, but they shouldn't really touch each other.

That's the only way to set this up.

**Comment by niekvanderkooy** [comment]
> First of all, creating an incoming transaction without an asset account is impossible in a double entry booking system, because you're creating an imbalance.

Not true. An open transaction (one without an asset account) would credit one category (one of your choice, or 'uncategorised') and debit an automatic category ('debtors') for the same amount. Nothing changes in any asset account (because none is selected), the sum of all transactions remains equal, as does the sum of all categories.
Looking at it in a more 'finance-y' way: your liabilities go up (Equity in the form of positive categories could be seen as falling under a liability, even though the comparison doesn't _really_ work in this situation), while your assets go up by the same amount (A debtor owing you is an asset).

> You can cheat of course with virtual asset accounts 

That's not what I was using the virtual asset accounts for in my example. This was purely to 'move money around' between categories, which again does not change the balance (although the implementation can be used to make the whole system work)

>If you advance three tickets, you create three short-term no-interest peer-to-peer Loans to three different Debtors or Borrowers. These three people all owe you amount X. This amount does not change.

> Whenever they pay back, you remove amount X from the debt. This event may be connected to an incoming deposit from that person, but that does not have to be the case. It's up to you.

This would also work. In this case, you're not really making the debt part of your bookkeeping but more as your personal reminder list. Which is of course a possibility.

IMO this is technically less correct accounting wise, since _this_ is in fact a way in which you create an imbalance: A transaction has been registered which you should not have paid for, but the repayment of the 'loan' will not be registered until a later time when your friends pay you back. The time in between these two events your equity will be lowered by the amount of the loan, and will come back up once it is paid. Doing it in my way I described before does not have this drawback - since registered debt is counted as an asset, your equity remains the same in the period you are expecting the loan repayment. However, this equity would then be built up of a (lowered) asset account + the balance of your debtors, instead of the full asset account which it will again be once the debtors have paid off their debt.

However, I realise this is technically the more simple solution, and might also be more intuitive for the average user with less of an accounting background.

**Comment by JC5** [comment]
> Not true. An open transaction (one without an asset account) would credit one category (one of your choice, or 'uncategorised') and debit an automatic category ('debtors') for the same amount.

In Firefly, categories are used as meta-data. So crediting categories and debeting others doesn't really make sense. Let's forget about those as a method to balance things, please. A one-ended transaction is unbalanced.

If you borrow somebody 25,- and register this in a basic withdrawal Firefly is already balanced. You lose 25, the other party gains 25. There, balance. That's the balance of a double entry bookkeeping system. Every transaction journal has two transactions: one party gains, one party loses. That is also how Firefly balances the books. It takes all ``amount`` fields in the ``transactions`` table and if the sum is not zero, the books are not balanced.

The fact that you want your money back is a whole different kind of imbalance and not something Firefly can register at this moment. It's important to make this distinction.

> IMO this is technically less correct accounting wise, since this is in fact a way in which you create an imbalance: A transaction has been registered which you should not have paid for

"You should not have paid for it" is way out of scope for Firefly. It doesn't care what you intended to do. It registers an expense. The fact that your money is at a Borrower and you want it back doesn't really matter to Firefly.

So to register _that_, you should either use an external system (leaning on FF's database) or find a way to register the intention of wanting it back.

Right now, Firefly III couldn't even do that because the repayment would be a deposit and would end up in a revenue account, which is different from the expense account you borrowed the money to.

**Comment by niekvanderkooy** [comment]
> In Firefly, categories are used as meta-data. So crediting categories and debeting others doesn't really make sense. Let's forget about those as a method to balance things, please. A one-ended transaction is unbalanced.

Fair enough, but the same could be done with a virtual/automatic asset account instead of a category, balancing an expense done for a debtor against a 'deposit' on some "Debtors" asset account. Then "wanting money back" would automatically be translated to a balance on this account. But I understand this would be too unintuitive for most people.

> "You should not have paid for it" is way out of scope for Firefly. It doesn't care what you intended to do. It registers an expense. 

True, that is what I would use a separate category for, I wouldn't suggest baking this into firefly - this would have to be the user's own administration.

> Right now, Firefly III couldn't even do that because the repayment would be a deposit and would end up in a revenue account, which is different from the expense account you borrowed the money to.

That shouldn't really matter right? This implies wanting to balance a revenue and/or expense account, but there is no reason this should be the case.
