### ISSUE TITLE
Using recurring transactions for Forecasting

### ISSUE THREAD

**Issue by fbka** [firefly-iii/firefly-iii#3361]
**Description**
Having an overview over upcoming recurring/planned income and payment streams would be extremely helpful in order to detect bottlenecks easily in advance. 

**Solution**
Judging from earlier tests and having a short look into [/app/Jobs/CreateRecurringTransactions.php](https://github.com/firefly-iii/firefly-iii/blob/4dea3a5f55d9b971d02db7260349bdac0148524a/app/Jobs/CreateRecurringTransactions.php), it looks like recurring transactions are only then being utilized, when their scheduled date equals today's date. However, I could imagine a scenario in which we check the scheduled date (SD) vs. current date (CD) and decide accordingly:
SD > CD: Create a transaction item of type "forecast"
SD = CD: Delete forecast item and create "usual" transaction item instead

Forecast items can then be included in dashboards etc. with special styling (50% opacity/ dotted lines/etc.). 

When recurring transactions are being changed or deleted, their forecasting item siblings are being deleted and re-created if needed. 

**What are alternatives?**
I currently see no good alternative solutions, neither within firefly-iii nor in competing solutions. The only way to plan/schedule future transactions in firefly-iii is to manually add each and every transaction with a future date. That's a pity, since firefly-iii has extremely powerful configurations for recurring transactions already built-in. 

**Bonus points**
I think firefly-iii is AMAZING! Adding this feature would make me - and most likely a lot of other folks as well - incredibly happy. Will buy you a few coffees, if this will be operational. Additionally, if you want to brainstorm on the solution or need a beta tester, I'm happy to help at any time.

**Comment by JC5** [comment]
Thanks for the compliments! 

Right now forecasting is explicitely **off** my roadmap. I'm not going to add or enable anything like this. The reason is simple: developing a tool that you can use to manage the present is complicated enough. I'm deliberately limiting the feature set of Firefly III.

You can use the recurring transactions to create future transactions, that's no problem. Either force the cron job to act as if it's the future already or build something using the API. And remember that you can see the future for each individual recurrence when you edit it.

An alternative would be to use the API to read and analyse the future dates for each recurrence.

This doesn't really solve your problem, and I'm well aware, but forecasting is off the table I'm afraid.

**Comment by srpnor** [comment]
> An alternative would be to use the API to read and analyse the future dates for each recurrence

FWIW this is how I kludge it.  I have a script which uses the API nightly to create future recurring transactions in a "forecast" account which I don't include in net worth (I also fudge some other things, like giving "fake" destination accounts so they don't appear in real spending accounts).  It lets me draw a balance graph into the future.  The script also deletes anything that is now in the past from that same account.

It's a big hack, but it works for my use cases, and one of the things I love about firefly-iii is the comprehensive API which lets me automate all sorts of things like this (I also have my mobile phone card spend notifications from Monzo, Starling, Revolut and AMEX being captured in real time and automatically creating transactions in firefly-iii where rules tidy them up and categorise them - awesome!)
