### ISSUE TITLE
Wrong calculation for Net worth?

### ISSUE THREAD

**Issue by daften** [firefly-iii/firefly-iii#3374]
**Bug description**
I am running Firefly III version 5.2.5, and my problem is:

I am not sure if this is a bug, I think it's a conscious choice, but it does confuse me. For asset accounts, you can enter a virtual amount. E.g. you always want to keep 100 in your account, enter virtual amount -100.

When calculating the net worth on the home page, I traced it and found out the virtual amount is only subtracted for credit cards. But IMO that's wrong. E.g. I have a credit line account in my bank. It goes below zero, but it's money I can take out. So I entered a virtual amount of X because I can go X below zero. However, that X is not my net worth. The same applies for asset accounts where you do what is mentioned in the descriptions. If you enter -100 in that field, for a regular checking account, your actual net worth is atm 100 more than what is shown.

So I would think that the virtual amount would need to be subtracted from all asset accounts, if it's entered, to have the correct value for net worth. If that is not possible, maybe it can be made a configuration option somehow? On the account itself or in general? If that is not possible, maybe it can be added in the help text when virtual balance is taken into account?

**Steps to reproduce**
* Create an asset account of type Default asset account
* Add a virtual balance of -100, no starting balance
* Check your net worth: you're worth -100, while I think it should be 0

**Extra info**
/

**Bonus points**

- I searched and nobody reported this bug before
- I have added a stack trace from my log files 
- I have added a screenshot.
- I was able to replicate it on the demo site https://demo.firefly-iii.org/

**Comment by JC5** [comment]
Thanks for reporting this. For clarity, I think I'm going to drop the "virtual balance" from all accounts. The virtual balance is just a gimmick for the user interface, it's not used in any meaningful calculations.

**Comment by daften** [comment]
I actually find the virtual balance quite useful tbh. It helps me manipulate accounts in a meaningful way. It makes it more clear how much money I have available easily. E.g. on CC's but also on credit line accounts like that.

It's just not money I actually have :D 

Thanks for the quick fix. Other issue I'm looking at this week, last week wasn't too great to do that.

**Comment by mehalter** [comment]
The way I have set up my Firefly-iii for credit cards, say with a $15,000 credit limit. I set it as a virtual balance of -15,000 and a starting balance of 15,000. This puts the net worth at 0 and I can keep track of the credit limit. Without the virtual balance, what would be the appropriate way to keep track of credit limits?

**Comment by JC5** [comment]
Set up the virtual balance, and leave out the starting balance.

**Comment by mehalter** [comment]
It seems to me that using it that way, when I look at the "current balances" on my asset accounts, it makes it appear as if my credit cards have a balance of the credit limit (lets say $15,000). Instead of starting at a balance of $15,000 and going down, it seems like it would be more useful to show the balance as the negative balance (starting at 0 and counting down until you pay it off) since with credit cards it isn't really "your money", you actually owe the negative balance.

**Comment by daften** [comment]
I add the limit as a positive virtual balance. This means it shows I have e.g. 15k available (for me, it's much less, but doesn't matter :P). That way the current balance shows me how much I have available on that CC at all times. My bank shows me the similar number.

It was already the case before the fix for this issue for CC's, but not for other accounts, but the virtual balance is not picked up in your net worth. So let's say in your case you have a virtual balance of 15k on your CC. You've spend 100 dollars on a restaurant and 200 on a household applicance. Your balance will show 14.700, but it counts as -300 for your net worth.

If you want everything to show up as a negative balance, don't enter a virtual balance.

Does that explain? I've explained it how I used it, but of course, everybody can adapt within the system as they see fit.

**Comment by mehalter** [comment]
Yeah totally understand, before this net worth fix my set up of doing a negative virtual balance of the credit limit and then setting the opening balance of a positive credit limit made sense to me. It is basically saying the starting balance on the card is $15,000 but that isn't really mine so show the balance at $0 and then go negative to show how much I owe on the card at any given moment. This makes it easier for me to understand how much I am currently in debt for all my credit lines at once without having to do a bunch of math and always think about how much the credit limits actually are. 

This worked before this net worth fix, but now since the net worth isn't calculated off the virtual balance, it puts my net worth at the summation of all of my credit limits instead of subtracting what I owe on the credit cards.

For now, with the 5.2.6 update, I have just moved my credit limit to the notes section and am not using the virtual balance. But to me at least, how I was using the virtual balance before made a lot of sense to express "this is how much money I have on the card, but it isn't my money". Understandable that everyone using the system will have different view points. Thanks for explaining how you use it

**Comment by daften** [comment]
@mehalter I think you're using the system wrong, as far as I can see at least. Unless you actually have a positive balance of +15k, you're not supposed to use the starting balance like that.

Also, for credit cards, nothing changed for net worth calculation. It deducted the virtual balance before, and it still does that. The main thing is also has that behaviour for default asset accounts, savings accounts, ...

The balance of 15k that isn't yours, THAT is your virtual balance. I think you'll need to remove your starting balance (so you start with an actual amount of 0) and add a virtual balance of 15k which is basically the credit line you get on that card.
