### ISSUE TITLE
There is a plan for Desktop application?

### ISSUE THREAD

**Issue by baruchiro** [firefly-iii/firefly-iii#3375]
Hi, this is an excellent application!

I saw it a long time ago, and I missed how good is it, so I created my own desktop application, with bank importers, and my plan was to add some features that I see are already implemented in Firefly III.

But I think there is one huge problem- this app is a website. As such, regular users can't install and use it, and we missing a lot of potential users.

So my question is if there is a plan for developing a Desktop application?

**Comment by JC5** [comment]
Hi, thanks for the compliments! I have no plans of developing a desktop application.

**Comment by psychowood** [comment]
@baruchiro as long as you don't need offline access (i.e. save then sync later), it could be done with a simple Electron wrapper (e.g. [nativefier](https://github.com/jiahaog/nativefier) or similar projects).

It is worth, tho? I suppose it could be in a strict environment where you can't control the browser used but you want to.

**Comment by baruchiro** [comment]
@psychowood I think I don't understand you. Do you suggest wrapping the client-side at Electron?

This is, of course, possible, but it does not solve the problem that a normal user should be concerned with DB & PHP installations.

**Comment by JC5** [comment]
Building a desktop app is a whole new project. It has very little to do with Firefly III in its current form.

**Comment by psychowood** [comment]
@baruchiro Yep that was my suggestion, since I don't believe that handling a completely offline mode is really feasible without a major review, especially in the sync part. 

Maybe just limiting to some specific operations (e.g. inserting transactions, creating tags/categories) could be done, but you would always be limited a bit. For example, what would happen if you create a transaction and in the meanwhile the account was deleted/disabled?

**Comment by baruchiro** [comment]
@psychowood  I see no significance in creating Electron for the client-side. As you said, the only meaning of this is browser enforcement.

@JC5  I don't yet know the Firefly III community.
Do you think it is relevant to start a new project that will have one executable file (for example, full Firefly functionality in an Electron app)?

**Comment by JC5** [comment]
Nah. Firefly III is a web-app. I don’t see the use case or the added value of a desktop app.

**Comment by kwm1800** [comment]
@baruchiro

What you can do is running docker on Windows and run firefly-iii as a docker container. Then you can access via browser with 0.0.0.0:<port>. It will still work if you go offline. Just make sure set up username and password if the computer is using shared network.

It is rather clunky way to run things "offline" but surprisingly a lot of apps choose this way. Things like my webcopy program and some sync programs are just installed as server and can be only accessed via web browser or just simple GUI mapped.

**Comment by baruchiro** [comment]
@kwm1800 Right, but still, you can't give this solution to regular user.

**Comment by kwm1800** [comment]
> @kwm1800 Right, but still, you can't give this solution to regular user.

That is true... Though I doubt "a regular user" would even attempt to use this software in the first place...

Well... errr I mean installing docker is not that hard on Windows for normal peeps. Just set WSL and.... *runs away*

**Comment by baruchiro** [comment]
I don't know if I prefer the **WSL** or **Docker Desktop**, don't know which is more reliable.

But maybe we can use **Docker** to create a quick Installation guide for semi-standard users.
For example, tell them to install **Docker**, then create a minimal software/script that will run the **Docker** commands for them.

**Comment by JC5** [comment]
Guys, I want to interrupt you for a moment here. Because @kwm1800, you've hit the nail on the head with this comment.

> That is true... Though I doubt "a regular user" would even attempt to use this software in the first place...

I want to stress I'm not really interested in regular users. 

> But I think there is one huge problem- this app is a website. As such, regular users can't install and use it, and we missing a lot of potential users.

I'm not sure who the "we" is here, but *I* really don't care about missing potential users.

---

If you want to make Firefly III into a desktop application, you going to offer a solution that is going to be needlessly complex because Firefly III is **not** built to be a desktop application. It's built to be a self-hosted web-application and I can't stress that enough. In it's core, Firefly III is not a desktop application. Not a single piece of code has been written to support desktops, no part of the workflow is useful for desktops and 0% of the programming languages I've used to build Firefly III are meant for desktop usage.

And I *know* that in theory you could fuck around with Docker desktop and Electron for a long enough time that you would have a working installation on your desktop. And it would suck. It would be terrible. Because apart from the huge effort you've just made to turn Firefly III into a web application, all you did was give people a massive unmaintainable headache with a window around it. Just the support software will over 2GB. That's insanity. 

There is no room for a Firefly III desktop application. There is no effort well-spent on turning Firefly III into a desktop application. It's a dead end. 

---

IF you like building desktop applications *and* you like the features in Firefly III feel free to copy the way they work. You can even recycle the code, provided that you release *your* code under the GPLv3. But turning Firefly III into a desktop application? Nope.

**Comment by baruchiro** [comment]
Thanks so much for the detailed response. I think a good maintainer need to know what his project limitations are, and you seem to know this well.
