### ISSUE TITLE
Treat `Net-Worth` as an account

### ISSUE THREAD

**Issue by nemosmithasf** [firefly-iii/firefly-iii#3384]
In accounting, there's this concept of `Shareholder's Equity`, which is essentially the same idea as `Net Worth`.

However, we seem to have no way to directly manipulate `Net Worth`. This makes it hard to map our existing personal finances to the program.

For example: 
1. I just started using FFiii
2. I have a $3000 laptop I want to add as an asset.
3. The double-entry would normally be: `Asset`: 3000 // `Net-Worth`:3000.
4. However, since we don't have access to `Net-worth`, we can't make this entry.

There's a work-around by just making `Net-worth` part of the liabilities account, but that's not as clean mentally and the dashboard's "net worth" indicator would be off.

I realize the current design is likely as an accommodation to people who aren't familiar with accounting, though I thought it'd be nice to have this as a power feature.

**Comment by JC5** [comment]
Nah. It's a typical accounting thing that has no relation to the real world. It could be part of #3269 but it's not going to influence your net worth.

**Comment by nemosmithasf** [comment]
Out of curiosity, in Firefly's paradigm, how would you account for the following two transaction?

- I have a `$60,000 car` that's an asset
- I have to depreciate the car by `$5,000` every year

**Comment by JC5** [comment]
Ehm, I don’t?

**Comment by nemosmithasf** [comment]
Hmm, maybe I've misunderstood the purpose of this program.

Is the `assets` and the `net worth` accounts meant only for cash transaction?

**Comment by JC5** [comment]
What you could do is create a piggy bank and save money to replace your car in 12 years time. Because other than that, you really don't have 60K to be added to your net worth, unless you have a magical car that will sell for 60K guaranteed. What you have is a car. 

So the answer to your original question is: you don't. Not in Firefly III. And not in real life, because just like with your car example, you don't actually have 3K to be added to your net worth. You have a laptop you paid 3K for which is an entirely diffent thing. 

If you want to do accounting, use GnuCash.

**Comment by nemosmithasf** [comment]
I think there's some confusion between us,

1. I think we can both agree that in real life, an asset should be counted in `net worth`. Especially since the vast majority of most people's worth-worth is their house.
- e.g. A person with a `$1,000,000` mortgage doesn't have a net-worth of `-$1,000,000` if their property can be sold at `$1,000,000`

2. I'm not saying that if I add an asset, we should increase the `net-worth` by that amount. That's obviously wrong.
- e.g. We can probably both agree that if I buy a $60K car, our net worth doesn't change (since the `+60K asset` is balanced by the `-60K debt`).

3. But when you first get started using Firefly, there needs to be a way to put your existing assets into the system (if you agree with #1, which is to say that assets do have value and should be accounted for).

4. My suggestion is the ability to make balancing-entries in the `net worth` account. So you can make these asset entries.

**Comment by JC5** [comment]
I'll think about it when I work on #3269 but I don't really see the added value.

**Comment by nemosmithasf** [comment]
The added value is that it allows you to make financial decisions rather than just tracking inflows and outflow.

e.g.:
- Retirement when I have net-worth of $10MM
- I can start a company once I have a net worth of $5MM
- Get married when I have a net worth of $2MM

Anyways, thanks for the good work.

**Comment by sschimmel** [comment]
I'd like to add my 2 cents as I've just started using Firefly and ran in to the same problem when entering my mortgage.

I just entered my mortage and my net worth has just dropped wel in to negative terratory. That mortgage is backed by a house that I can sell with the result of having cash. It should be added to my net worth because of that. One can argue that any asset that can be turned in to cash should be added to your net worth.

Same for the car. I can sell it and get cash in return. In my case the resale value is guaruanteed by the car manufacturer but normally one could use the trade-in value lists that are available.

I'm also missing a way of adding a stock portfolio to add to my net worth. Using a standard bank account could work except that stock appreciation isn't income and depreciation isn't an expense but both do impact net worth.

**Comment by markbibi** [comment]
On the same vein, but in the opposite angle, I see missing the inclusion of budgets in calculating a sort of net-net-worth summary (unless I didn't look deep enough).

When I allocate a budget, I would expect having a summary of what I have in assets minus what I spent, including what I allocated to spend. If I had 1000, and spent 600, net-worth shows 400, fair, but if I allocated 700 in budgets, would be useful to know that my net worth (further money to spend or save) for any practical purpose should be 300. The 700 are getting spent day by day and the current net-worth figure is just reporting what has been spent so far.

Any chance to have that further entry in the dashboard?

**Comment by bernikr** [comment]
I know this is am old issue, but I just started transitioing from YNAB to Firefly III and this is the thing I am missing the most.

In YNAB I had an "off-budget" account for stocks, in which I manually added a inflow/outflow each month to adjust the current value. This however is not accounted as income or an expense and only changes the net-worth. But transfers between off-budget accounts and budget accounts are counted as income or expenses.

These off budget accounts seem like a simple feature with much flexibility for users, who want their whole net-worth accounted for.

I really wish Firefly had something similar, since I don't think it will be the right tool for me and many others, when we can't see our actual net-worth.
