### ISSUE TITLE
Expenses are not allocated to the right period

### ISSUE THREAD

**Issue by krispek** [firefly-iii/firefly-iii#3418]
**Bug description**
I am running Firefly III version 5.2.6, and my problem is that expenses are not allocated to the right period. 
<img width="1259" alt="Screenshot 2020-06-01 at 10 41 36" src="https://user-images.githubusercontent.com/11836876/83392581-a2b04f00-a3f5-11ea-813c-87ac0faa4be0.png">

**Steps to reproduce**
- have a yearly view 
- Have a budget for jan 1st until dec 31th. 
- Add a budget for a limited period (in this case: June)

Current result:
- all expenses are applied to all budgets, regardless of the period 

Expected result:
- expenses are only applied to the budget for that period

Workaround:
Being able to set the period in which a budget is applicable. 

**Extra info**
There's some ambiguity here. The view determines the period of the budget you set. So if you selected a default period of a year, budgets are automatically set for one year. That's fine, but it gets confusing as soon as you also have montly budgets. In the screenshot, you see a yearly bidget and a monthly budget. Effectively, they are conflicting with each other. 

**Bonus points**

- [x] I searched and nobody reported this bug before

- [ ] I have added a stack trace from my log files 
- [x] I have added a screenshot.
- [x] I was able to replicate it on the demo site https://demo.firefly-iii.org/

**Comment by JC5** [comment]
Yes, that's pretty much what's supposed to happen. I haven't had inspiration yet for the best interface for overlapping budget amounts.

The transaction is applied one budget: "Boodschappen"; it's pretty simple link in the database. For the amounts, "limits" are created for each range separately: in your case two limits: one for the year and one for the month.

So yes, the transaction is applied to "both" because in truth it's the same single budget.

Did you have specific plans for the yearly/monthly combination?

**Comment by krispek** [comment]
I ran into it because I have monthly budget, whereas my default overview is a yearly one. That combination is not a good one. :) 

Especially in cases where it makes sense to have yearly budget (f.e. maintenance of your car, taxes that you pay once a year) the monthly view is a bit... off.

**Comment by krispek** [comment]
What I did for now, is to make budgets piggy banks look-a-likes. By creating roll-over budgets, I 'save' enough money to pay my yearly expenses.
