### ISSUE TITLE
Information requirment on features and usage

### ISSUE THREAD

**Issue by chanakaDe** [firefly-iii/firefly-iii#3433]
### I tested the demo version and trying to get used to FireFly

**Description**
I need to make sure this system has following features. 

1. Double entry accounting.
2. Daily, Weekly & Monthly reports. (Income, Expresses, Loss and Profit)
3. Journal entry management.
4. Receipt management. 

And also in the demo, when I click on `currencies`, the language is changing automatically. What is the reason for that? (I'm using Firefox latest update). And I don't see where I can change the language. 

Is there any way to add a new currency ? (For example, Sri Lankan Rupees) 

![Screenshot from 2020-06-05 00-09-33](https://user-images.githubusercontent.com/7803591/83797843-de326e00-a6c0-11ea-8530-eed7a8edf83d.png)

**Comment by JC5** [comment]
Hi!

I'm glad you like Firefly III. Let me answer your questions.

1. This is probably just a coincidence. Many users use the demo site at the same time, and when one demo user changes the language of the demo site, it changes for everybody who is logged in. This is because you share the same account.
2. You can change the language under [preferences](https://demo.firefly-iii.org/preferences). If you cannot read what the page is saying, simply [logout](https://demo.firefly-iii.org/logout) and login again: the demo site will reset to English.
3. You can add currencies on the [currencies page](https://demo.firefly-iii.org/currencies) although this may be blocked for the demo user.

**Comment by chanakaDe** [comment]
Thank you so much @JC5 
Can you please verify following features:

    1.Double entry accounting.
    2.Daily, Weekly & Monthly reports. (Income, Expresses, Loss and Profit)
    3.Journal entry management.
    4.Receipt management.

Are these available in this system? Specially `double entry accounting` ?

**Comment by JC5** [comment]
1. Yes. This is something you can verify in the database itself:
2. [Custom range reports in every flavour.](https://demo.firefly-iii.org/reports)
3. Not sure what you mean, but you can [add transactions](https://demo.firefly-iii.org/transactions/create/withdrawal) with all the details you want to.
4. You can add attachments to each transaction.
