### ISSUE TITLE
Cannot install on Raspberry Pi via docker-compose: error on mariadb

### ISSUE THREAD

**Issue by noisemaker00** [firefly-iii/firefly-iii#3464]
I'm trying to install FireflyIII on raspberry pi using docker-compose, but I got this error:
```
pi@raspberrypi:~/firefly_iii $ docker-compose -f docker-compose.yml up -d
Pulling fireflyiiidb (mariadb:10.4-bionic)...
10.4-bionic: Pulling from library/mariadb
ERROR: no matching manifest for linux/arm/v7 in the manifest list entries

```

**Comment by JC5** [comment]
Thanks for letting me know. That version of the Docker file wasn’t supposed to go out yet. I’ll push an update.

**Comment by JC5** [comment]
Please download the [docker-compose.yml](https://raw.githubusercontent.com/firefly-iii/docker/master/docker-compose.yml) file again.

**Comment by noisemaker00** [comment]
Something does not work as expected, seems containers crashed due to segmentation fault (error 139)
```
CONTAINER ID        IMAGE                     COMMAND                  CREATED             STATUS                        PORTS               NAMES
9c4af3ec4d98        jc5x/firefly-iii:latest   "/entrypoint.sh"         2 minutes ago       Exited (139) 14 seconds ago                       firefly_iii_fireflyiii_1
861a7b93e441        postgres:10-alpine        "docker-entrypoint.s…"   2 minutes ago       Exited (139) 21 seconds ago                       firefly_iii_fireflyiiidb_1

```

**Comment by JC5** [comment]
Make sure you remove all old images and try again. I don't know what the error means exactly.

**Comment by noisemaker00** [comment]
No success. I removed all containers and images and run
`docker-compose -f docker-compose.yml up -d`
packages has been download and extracted but with
`docker ps -a`
the result is the same as before, with error 139

**Comment by JC5** [comment]
I have an RPi4, seems to work just fine. What's your model?

**Comment by noisemaker00** [comment]
I'm using a RPi Zero with Raspbian 9 (stretch) 
Docker version 19.03.11 (build 42e35e6)
docker-compose version 1.26.0

**Comment by JC5** [comment]
Mmm, sorry. This is kind of out of my league. I've always experienced the RPi Zero's as the bare minimum voor Firefly III though. Shouldn't stop you from running the image but I'm afraid I can't help you further.

**Comment by leander091** [comment]
Segmentation faults with docker are in most cases related to architectural differences of the image and the underlying operation systems. In this case the base image of FF3 is based on the core image [arm32v7/php:7.4-apache ](https://github.com/firefly-iii/docker-base-image/blob/11977e49ab7f1de12411fff8de50b185d89e13a7/Dockerfile.arm#L1).  So the core image is ARMv7 32 bit. 

However the RPi Zero is based on the 32 bit ARMv6 architecture. So this mismatch causes the segmentation faults. 

It is possible to build an image for ARMv6 but I'm not so sure if an ARMv6 image is worth the maintenance burden.  

@noisemaker00  If it is possible I would recommend to try the docker image on a newer Raspberry PI. Every mainline PI since the Raspberry PI 2 model B are based on the ARMv7 architecture,

**Comment by noisemaker00** [comment]
I have a Pi 3 but by now is used in another project, so I cannot use it.
I'm do not know docker very well, so I read something online in these days. I found this base image:
[https://hub.docker.com/r/arm32v6/php/](https://hub.docker.com/r/arm32v6/php/)
If I clone this repo [https://github.com/firefly-iii/docker-base-image/blob/11977e49ab7f1de12411fff8de50b185d89e13a7/Dockerfile.arm#L1](https://github.com/firefly-iii/docker-base-image/blob/11977e49ab7f1de12411fff8de50b185d89e13a7/Dockerfile.arm#L1)
and replace the 'from' image with the v6 one, shoul it work?

**Comment by JC5** [comment]
In theory, yes. Building it on the zero should work. But it'll be some trial-and-error.
