### ISSUE TITLE
Hungarian locale date format missing

### ISSUE THREAD

**Issue by pbartyik** [firefly-iii/firefly-iii#3472]
**Description**
Firefly III Hungarian locale currently does not support Hungarian date format (YYY/MM/DD), would be nice to have it.

**Solution**
It'd enable Hungarian users to use the Hungarian date format.

**What are alternatives?**
Firefly III could also implement ISO date format which is the same :)

**Comment by JC5** [comment]
As far as I can see all relevant strings have been translated: https://crowdin.com/translate/firefly-iii/141/en-hu

Where are you missing the Hungarian locale? Can you provide a screenshot?

**Comment by pbartyik** [comment]
Sure, here you go:
![example3](https://user-images.githubusercontent.com/39059618/85007477-e0cea200-b15b-11ea-9d1f-4442af645031.png)
![example4](https://user-images.githubusercontent.com/39059618/85007484-e2986580-b15b-11ea-9022-03e31ad5135c.png)

**Comment by JC5** [comment]
Ah yes. That’s up to your browser I’m afraid. I hope to improve this in the next release but if the language is English, the forms are too.

**Comment by pbartyik** [comment]
Hmmm, this is odd. When I set language to Hungarian I still get the form in English format:
![example5](https://user-images.githubusercontent.com/39059618/85009158-46bc2900-b15e-11ea-879b-cdf677b54cde.png)

In the logs with debug I also get this:

> Could not set locale. The following array doesnt work:  ["hu.utf8","hu.UTF-8"]

I do have the locales installed:

> root@host:/opt/firefly-iii/storage/logs# locale -a | grep hu
> hu_HU
> hu_HU.iso88592
> hu_HU.utf8
> hungarian
> root@host:/opt/firefly-iii/storage/logs# 

I have also restarted the server.

Am I missing something painfully obvious?

**Comment by JC5** [comment]
Try Hungarian (Hungarian) is that combo is in the list.

**Comment by pbartyik** [comment]
Yep, thanks! That does the trick to get the locale loaded. Date formatting is still wrong tho :/
![example5](https://user-images.githubusercontent.com/39059618/85011541-f5ae3400-b161-11ea-8f0c-fd7ce0d2835b.png)
![example6](https://user-images.githubusercontent.com/39059618/85011544-f777f780-b161-11ea-8109-f23dafc6218f.png)
![example7](https://user-images.githubusercontent.com/39059618/85011548-f8a92480-b161-11ea-8aaf-91ba3a63ca30.png)

**Comment by JC5** [comment]
I see what you mean. I can't replicate this in Chrome (on the demo site). I don't have Firefox available at the moment. But the date input box is a browser thing that I can't really influence I'm afraid.

**Comment by pbartyik** [comment]
might be something wrong with my setup, same symptom is present in Chromium, Firefox and Qutebrowser. No worries, thanks for checking this out!

**Comment by Ettemlevest** [comment]
I've just checked this topic a bit deeper cause I also wanted to know what is the root cause of this date presentation. This is because of Carbon's formatLocalized() usage with a format string that is not what we mostly use in Hungary.

For example in the _transactions.show_ template the date is presented in an almost proper format for Hungarian. Only dotes missing after year and day part ([line 34](https://github.com/firefly-iii/firefly-iii/blob/5.2.8/resources/views/v1/transactions/show.twig#L34)):
```php
{{ first.date.formatLocalized(dateTimeFormat) }}
```
![kép](https://user-images.githubusercontent.com/1035942/85133584-404faf00-b23b-11ea-916c-a586318fe8bc.png)

But in _list.groups_ there is a different format ([line 166](https://github.com/firefly-iii/firefly-iii/blob/5.2.8/resources/views/v1/list/groups.twig#L166)):
```php
{{ transaction.date.formatLocalized(monthAndDayFormat) }}
```
![kép](https://user-images.githubusercontent.com/1035942/85134257-7e010780-b23c-11ea-8f54-f62503d63b85.png)

This **dateTimeFormat** and **monthAndDayFormat** variables set in the base [Controller](https://github.com/firefly-iii/firefly-iii/blob/5.2.8/app/Http/Controllers/Controller.php#L89) which is configured from the translation's [config](https://github.com/firefly-iii/firefly-iii/blob/5.2.8/resources/lang/hu_HU/config.php#L29) file.

Hungarians never represent dates in the format of [month] [day], [year] (június 16, 2020). Official Hungarian spelling rules for dates: https://helyesiras.mta.hu/helyesiras/default/akh12#F11_0_0_2

@JC5:
I will check the other date format configs and create a pull request to fix this. Btw FireFly III is pretty great. Thanks for your work! 🏆 🥇 


@pbartyik:
With HU localized Firefox I have the proper format for the date inputs. The input's date format is determined by the browser's localization setting. Check your language settings in the browser. 
![kép](https://user-images.githubusercontent.com/1035942/85137128-01245c80-b241-11ea-88d5-cc62cc330a33.png)

Settings / Language:
![kép](https://user-images.githubusercontent.com/1035942/85137526-a8a18f00-b241-11ea-8155-5cf6bb10d868.png)

**Comment by JC5** [comment]
Thanks for the compliments and thanks for the deep dive! I'll do a long reply later.

Just want to tell you, don't do PR's on language files. Instead, submit your changes here: https://crowdin.com/translate/firefly-iii/141/en-hu

**Comment by JC5** [comment]
Wait there's not much more I would need to add. :D

**Comment by Ettemlevest** [comment]
Thanks for the link. Suggested some changes for the date format via Crowdin.

**Comment by JC5** [comment]
I've approved them, and they'll be part of the new release! :+1:

**Comment by pbartyik** [comment]
thanks guys :)
