### ISSUE TITLE
Inactive budgets adds to budgeted amount

### ISSUE THREAD

**Issue by pbartyik** [firefly-iii/firefly-iii#3500]
**Bug description**
I am running Firefly III version 5.2.8, and my problem is:

Setting a budget to inactive does not exclude it from calculated budgeted amount for given month.

**Steps to reproduce**

Create budget
Add X amount to it
Set budget to inactive
Observe that budgeted amount is increased by X

**Bonus points**

- I have added a screenshot.
- I was able to replicate it on the demo site https://demo.firefly-iii.org/
![example1](https://user-images.githubusercontent.com/39059618/86094099-574e9680-bab0-11ea-87ec-faedfc36bf5f.png)

**Comment by JC5** [comment]
Yes. This is confusing but intentional. It means that if you archive a budget the previously set amounts won't disappear into a black hole. 

In my case, this applies to the budget "Cigarettes". I quit a few years ago so the budget is inactive and no longer used. The amounts however are still valid and displayed in charts and views whenever it's relevant.

**Comment by pbartyik** [comment]
I understand the benefit of this for reports, but it should not play a role in available budget calculation.
When setting a budget with available 500, adding 500 to Groceries, and an 'invisible' budget of 500 will cause you to think that you've over budgeted when in fact you didn't.
This is purely cosmetic for me as I just empty the budget before setting it inactive.
