### ISSUE TITLE
Locale not working (Windows 10) - possible workaround?

### ISSUE THREAD

**Issue by Crotha** [firefly-iii/firefly-iii#3519]
**Bug description**
In every Firefly-III version from 2.4.2 and up I encounter the same Problem:

"Invalid server configuration: Firefly III is unable to format monetary amounts because your server is missing the required packages. There are instructions how to do this. "

**Steps to reproduce**
Well, probably just using Windows

**Extra info**
So, I assume it is known already and from what I remember you said there is quite a problem with windows not using standard format locales or something like that.   
In any case, I wanted to make another Issue here, because the previous one rovided a (for now?) working solution: In #3306 @scottsousa described how he solved it for Windows 7.
After me stumbling and fumbling around, I finally found the string and commenting out the first two lines and adding in the one mentioned, it works for windows 10 too.

This is the change in the php-file:
![Change_Steam php](https://user-images.githubusercontent.com/47434645/86444775-97608400-bd11-11ea-9314-ab2b19f1e1cb.png)

I mainly wanted to mention it, because it seems like this is a windows-own problem that may be easily solved/bypassed in that way, if anyone else has this problem.
 
I couldn't find any other possible way to resolve the invalid server configuration otherwise, which is why I used version 2.4.1 or so until yesterday.
(I am using en-gb as main language, and en-ca as locale setting (because otherwise umlauts are shown wrongly, and en-ca has the preferred date-format))

I hope this wasn't to far off, and hope you have a nice day.   

Thanks for reading and also thanks a lot for firefly-iii :)

**Comment by JC5** [comment]
You're very welcome. I'll write this down as an enhancement and pick it up in due course. This should work on Windows as well. Thanks for diving into this!

**Comment by hoshsadiq** [comment]
@Crotha if you can try the latest dev branch, I reworked the way numbers are formatted. It would be good to get some feedback on it.

**Comment by Crotha** [comment]
@hoshsadiq I downloaded the develop-branch, unpacked it and copied it over the old installation (of course, there are backups), I hope that is a correct way to do that...
FYI, just so you know, where my level of knowledge in these regards is.    

The "Invalid server configuration" thing is still there, BUT the numbers are formatted correctly (to US/UK standard).    
When setting the locale (not the language - language is still English(GB)) to German (Austria), the numbers formatting changes correctly everwhere but in one place: whenever you have to put in a number. 
E.g. budgeted amounts:     
![budgeted amounts](https://user-images.githubusercontent.com/47434645/87919824-a74dc700-ca78-11ea-9708-01eca3b1f495.png)
Formular for adding a transaction:     
![transaction](https://user-images.githubusercontent.com/47434645/87919882-baf92d80-ca78-11ea-93c9-f7c5748a8d54.png)

I assume, this is a completely different thing to change?     
Though this would be, for me, the important one, as my numblock has a comma, not a dot :D      

That all assumes that my way of installing it worked correctly. The number format did change correctly, so there's that.       

I hope this helped a bit.

**Comment by JC5** [comment]
It may be that those numbers aren't formatted correctly because your browser is set to "English (US)". I had the impression that comma's would be replaced by dots automatically  (the API only accepts dots only).

For example, this is the demo site when the browser is set to NL and the demo site is English (US)

![image](https://user-images.githubusercontent.com/5889984/87923470-d581d580-ca7d-11ea-8292-b11cb7132a6f.png)

**Comment by Crotha** [comment]
That's strange.  
My web page language setting in Firefox is german [de_at] first:      
![firefox](https://user-images.githubusercontent.com/47434645/87923985-8f794180-ca7e-11ea-8db8-17db1a55361a.png)

But even when using Firefox in german, my own Firefly-III installation stays the same (and changes only with the internal settings).

For funsies, I opened the demo-page in Edge: the language is still depending on the "language"-setting in firefly-iii itself, not of the browser. 
[I also want to add here for fun: Firefly (both the demo and the self-hosted page) are basically not working in Edge, can't open menus and such. Not that this is something that needs any fixing, mainly found it funny :D It is my only other installed browser.]       

This language-thing is puzzling, tbh.

**Comment by hoshsadiq** [comment]
Aah yeah, the changes I made are only about presenting the output. This issue is input related. Happy to try and address this at some point this week.

@JC5 any pointers on where the conversion and validation is done?

**Comment by JC5** [comment]
> But even when using Firefox in german, my own Firefly-III installation stays the same (and changes only with the internal settings).

Yes, this is correct. I always hate it when websites decide they can be in my local language because my browser accepts it. So it's all down to user preference.

Edge is broken because they don't really like Content Security Policy headers.

Using commas in the inputs is normally up to your preferences and your browser. Firefox looks at the preferred language of the browser. Other browsers only use the website's locale. It's a mixed game. So often, using comma's in an English browser doesn't work.

An exception is the edit / create transaction screen. In this screen, you should be able to use both. This is client side btw, and must remain there. Here it is.

https://github.com/firefly-iii/firefly-iii/blob/main/resources/assets/js/components/transactions/CreateTransaction.vue#L382

The reason this code exists, is because some browsers submit localized number fields as "123,45" instead of "123.45".

**Comment by JC5** [comment]
However, I just discovered that if you enter "123,45" in a US browser with US language as preference, the browser (Firefox) won't actually submit the number but return an empty string.
