### ISSUE TITLE
Authentication in importers

### ISSUE THREAD

**Issue by bpatath** [firefly-iii/firefly-iii#3539]
Currently, the CSV importer (and also other importers I think) require the personal token to be passed when starting the container. It is convenient if you're using the auto-import or running the web server on your personal machine, but not so much if you want to host the importer for multiple users.  
Is there a reason for this choice ?

An alternative would be to add a personal token input page if the environment variable is empty ?
Or using OAuth to authenticate against Firefly-III without the use of a personal token ?

**Comment by JC5** [comment]
Excellent question!

It was a design choice to do it like this. First choice: don't use a separate database. Second choice: don't use Firefly III's database but use the API only. That rules out user/password management and most authentication methods that can be easily managed by some administrator.

Since most (not all, I know) people use Firefly III for themselves this was the choice I made.

So then it's a choice of API authentication. The OAuth flow is very nice but is more complex than the Personal Access Token (PAT) flow to initialize. So PAT it is. Especially since I'm storing the PAT in the environment variables anyway.

Of course the choice could be to allow the user to input their own PAT every time the CSV importer starts. But this is error prone and inconvenient. Your users would have to save their PAT somewhere; it's almost a 1000 characters long. Not very user friendly I'm afraid.

So I ended up where the CSV importer is now. What you could do to set up the CSV importer for multiple users is use basic authentication in your reverse proxy (if you have it) and/or set up multiple CSV importers

**Comment by bpatath** [comment]
I completely understand and agree with you on those choices.

If I look into adding OAuth as an alternative, would consider such a PR ?

> What you could do to set up the CSV importer for multiple users is use basic authentication in your reverse proxy

What do you mean by this ? I have a reverse proxy and use it as a remote_user provider. But since the web server has to be started with a fixed and valid PAT, I don't see how any form of web server authentication would help ?

**Comment by JC5** [comment]
This requires more than a PR I'm afraid, but I promise to look into it.

For the reverse proxy; why not set up multiple CSV importers?

**Comment by bpatath** [comment]
> This requires more than a PR I'm afraid, but I promise to look into it.

What do you mean by that ?

After looking into it, the OAuth Authorization flow is not that complex from a client perspective:
* Redirect the user to `http://firefly/oauth/authorize`
* The user logs in and get redirected to `http://firefly-importer/oauth/callback?code=...."
* The controller for this page uses the authorization code it just received, its client id and client secret to send a request to `http://firefly/oauth/token` to convert the authorization code to an access token.
* You store this access token into a session and you're now ready to use the rest of the importer.

Laravel Passport provides a [guide](https://laravel.com/docs/7.x/passport#requesting-tokens) with example codes.

> For the reverse proxy; why not set up multiple CSV importers?

Having configured one importer per user and redirecting requests to the good one based on the authenticated user ? That would work but it looks more like a workaround than an actual solution...

**Comment by JC5** [comment]
You're absolutely right re: the process, but the rest of the code needs some work too. Wherever the token is required, you'll need some kind of an if-else to select either the PAT or the OAuth token. It might also be necessary to take some kind of an exit / sidestep when the token is expired (because that could happen with OAuth). 

If you'll let me, I'll do some research what would be the most user friendly and the most sustainable when it comes to code changes.

**Comment by bpatath** [comment]
> If you'll let me, I'll do some research what would be the most user friendly and the most sustainable when it comes to code changes.

Sure, it's your project ! I was just offering my help since I guess it's not really a top-priority feature.
If after researching you want to provide me with guidelines and let me try to do the changes/testing, just let me know.

**Comment by bpatath** [comment]
By any chance, have you had the time to look at this ?

**Comment by JC5** [comment]
Nothing solid until https://github.com/firefly-iii/firefly-iii/issues/3651, which is something I'm going to research. Send some karma to @forcaeluz 😉
