### ISSUE TITLE
Reconciliation of accounts

### ISSUE THREAD

**Issue by totti4ever** [firefly-iii/firefly-iii#3571]
I am running Firefly III version latest.

**Description**
I use Spectre to import both, my Paypal and my main account. Usually when paying something with Paypal they start a direct debit to my main account.
This leads to two transactions in Firefly:
1. 1€ transfer from main account to Paypal, imported from Paypal's Spectre import
2. (2 days later) 1€ transfer from main account to Paypal, imported from main account's Spectre import

**Question**
Any best practices on how to cope with this issue?
It is apparently a duplicate, but not in the narrow sense as the descriptions and dates differ!
1. One could add a rule to delete of them automatically
2. or just map the target accounts to a ghost account in Firefly, so 1. would be booked against that ghost account of the main account and 2. against a Paypal ghost account. That would help to keep the balances of all accounts in sync with reality (while they would differ when deleting on of the two transactions...) - although with this solution of would loose the nice link in Firefly itself between those accounts...

What do you guys think?

P.S.: Should affect all transfers between main/asset accounts shown in Firefly, not only Paypal

**Comment by totti4ever** [comment]
Nobody else is coping with this issue?! :-(

@James, not looking at you!

**Comment by JC5** [comment]
I am coping with this issue though, so maybe I can help 😉 . I decided to remove Paypal as the "middle man" and make the transaction between my bank account and the shop directly. I don't really track Paypal anymore.

**Comment by psychowood** [comment]
Just my two cents on a similar issue.

My bank has this bad habit (1st imported from bank transactions, 2nd imported from card transactions):

<img width="1450" alt="image" src="https://user-images.githubusercontent.com/115389/89732960-84e51300-da52-11ea-8f02-5312a27e34e3.png">

In short: different accounts, same amount, slightly different date, end of the description matches the start of the other, beginning of the bank description has the date of the transaction on the card. The worst is that the real and most informative description is on the card list, similarly to what happens with Paypal, and moreover there's no positive amount tracking the transfer, leaving with a double charge.

Since I know I can't hope to automagically match the transactions, especially considering that I have different cards (actually, working on some SQL wizardry :) ), I was wondering if a better approach would be this one:

<img width="1779" alt="image" src="https://user-images.githubusercontent.com/115389/89734029-bdd4b600-da59-11ea-9a28-b327ad1b255c.png">

- Convert the bank transactions to internal transfers
- Categorize/tag/set destination account only on the card transactions

What do you think?

The approach suggested on previous comments (skipping the middle man) is working as long as there's only one person involved, imho does not really works if you are managing a family because you lose track of the channel (i.e. the individual) that made the expense.
