### ISSUE TITLE
[Question] Mail from cronjob

### ISSUE THREAD

**Issue by bannisdale** [firefly-iii/firefly-iii#3600]
Hi!

After setting up a cronjob for firefly, I now get a daily email with the info

"The recurring transaction cron job fired successfully.
The auto budget cron job fired successfully."

Given that the mail is sent by my "cron daemon", I'm not entirely sure if this mail is (strictly speaking" created by firefly, but I already have cronjobs running for other applications where I don't get an e-mail.

So I guess my questions are:
* Is firefly "responsible" for this e-mail or do I have to change some web server configuration to get rid of it?
* If firefly sends the info, how can I get rid of those mails? :)

Thanks!

**Comment by JC5** [comment]
Good question! The mail is sent by your cron daemon, not by Firefly III. If you suppress the output from the cron job, the mail will not be sent.

The reason it's sent is because the cron job produces output. To prevent this append the job with the following: ` > /dev/null 2>&1`

So, `php artisan firefly-iii:cron > /dev/null 2>&1`.

That should prevent the output.

**Comment by bannisdale** [comment]
Yeah, I figured it might because of the output. Thanks for output addition to the job. :)
