### ISSUE TITLE
Custom header to mass apply value in Edit Multiple Transactions grid

### ISSUE THREAD

**Issue by psychowood** [firefly-iii/firefly-iii#3689]
I was thinking about adding like a new row like this one, below the header:

<img width="1652" alt="image" src="https://user-images.githubusercontent.com/115389/89890260-55114900-dbd3-11ea-9d4e-60cdc0097ac1.png">

It would make very easy to change values on a multiple transactions without a major overhaul to the UI.

I'm currently doing it by hand, by running on the console `$( "[name^='destination_name']" ).val('Amazon')`, and is working quite well, so code wise it should not be too complex.

As a bonus, probably adding something `.has-warning` on the td/span container of the field would help highlight the values what would be changed on commit.

**Comment by JC5** [comment]
That's tricky, because you never know what transaction types people combine in that form. It needs an overhaul anyway. So this isn't going to happen,but I'll think about something that could work.

Properly allowing people to mass edit transactions is a massive effort because of all of these edge cases and it's rarely used. There's not much value in expanding it. I'll see what I can do!

**Comment by JC5** [comment]
I'm making this a part of the new layout. It's on my list to overhaul the mass editor.
