### ISSUE TITLE
CSV importer crashes when `Amount (negated column)` column contains a zero

### ISSUE THREAD

**Issue by matejdro** [firefly-iii/firefly-iii#3706]
**Bug description**
I am running Firefly III CSV Import Tool version v2.0.5 (posting here since CSV tool does not have its own issue tracker), and my problem is:

**Steps to reproduce**
1. Select a CSV that has a numeric column with zero value in it
2. Set that column to "Amount (negated column)"
3. Start import

Import will eventually crash with the following error:

```
Line #0: Internal error: Argument 1 passed to App\Services\CSV\Converter\Amount::positive() must be of the type string, null given, called in /var/www/html/app/Services/Import/Task/PositiveAmount.php on line 42 in file /var/www/html/app/Services/CSV/Converter/Amount.php:38 
```

**Comment by JC5** [comment]
Thanks for letting me know. A fix is ready for the next release. In the commit above my post, you can copy/paste it yourself if you need it in the mean time.

**Comment by JamiePhonic** [comment]
Hi there,

Thought it worth mentioning; I ran into this issue and applied the change manaully as suggested, however this has resulted in transactions (Debits) failing to create with CSV's which have seperate Credit/Debit colums because the "Debit" value is passed as a negative value. (Deposits were fine)

I had to ammend the line to re-add the `Amount:Positive()` function back in.

**Comment by JC5** [comment]
Ah good point. I have to release this still anyway. I'll amend my code as well!
