### ISSUE TITLE
firefly-iii / docs : 

### ISSUE THREAD

**Issue by PackElend** [firefly-iii/firefly-iii#3760]
**Description**

https://docs.firefly-iii.org/importing-data/introduction
https://github.com/firefly-iii/spectre-importer

telling that you need either to pay or have only limited access time-wise.

I'm going through the registration process now and it looks like that you can only fake banks when after initial registration. You can ask for a test account what gives you 100 connection. 
That should be enough for personal use.
![image](https://user-images.githubusercontent.com/3542031/92105407-155d0c00-ede3-11ea-8c99-7deab5d7f659.png)

**Solution**
update documentation and reference to SaltEdge documentation
https://docs.saltedge.com/general/#your_account
https://docs.saltedge.com/partners/v1/#connections

**What are the alternatives?**
causing confusion 😄 

**Additional context**
nothing to add

**Bonus points**
I will ask for live to figure out what it would cost

**Comment by JC5** [comment]
I had several users reporting to me that after they requested test access, they had to pay or lose test access after a specific period. Which is exactly what it states in the docs. 

Pricing starts at $500,- per month.

**Comment by PackElend** [comment]
just got the release for testing, 90 days limit still exists. 
![image](https://user-images.githubusercontent.com/3542031/92116696-74774c80-edf4-11ea-8d25-5e7f9a10d0ed.png)
There is nothing about this in https://docs.saltedge.com/
I find "90 days" only here: https://www.saltedge.com/products/psd2_account_info

I'll ask what happens after 90 days

**Comment by PackElend** [comment]
I got kind of answer 
>  The "test" status can be extended, or granted again, if you fail to reply after the notice. 

I asked for more details, will see.
I'm wondering if the other users were able to get it extended or reapplied for test status successfully.

**Comment by PackElend** [comment]
a bit talking later:

>The standard pricing for a year contract, with one country only, is 12000€ in commitments, 1000€ per month.
>
>However, depending on the agreed terms, we provide a lower commitment for the first 2-3 months.

but at least my testing lasts now for 6 months.

Is there experience on reapplying for testing?

**Comment by JC5** [comment]
I'm not a fan of that direction, so I if you can avoid it, please.

At the end of the day Salt Edge is a commercial company. Their product isn't meant for this use case, it's as simple as that. And they don't mind up to a point. I've been in touch with them over the years and they tolerate us mooching of their API. They're not idiots, they see us registering with firstname.lastname@gmail and company name "none" and then a Firefly III client starts connecting to banks. Because on the other hand, we give them direct feedback on missing transactions and broken connections etc. for a variety of banks.

But they need to make money too and they tolerate us because we play nice and don't cost too much. But if they see you re-applying, making new accounts, circumventing their limits, they'll put a stop to this whole circus and cancel all of our access. Because it's pretty easy to recognise the Spectre Importer on their end and even easier to block it outright.

If your Spectre trial stops working and you don't feel like forking over EUR 1000,- for access you'll have to use either CSV files or import the old-fashioned way: by hand.

**Comment by PackElend** [comment]
> They're not idiots, they see us registering with firstname.lastname@gmail and company name "none" and then a Firefly III client starts connecting to banks. 

No worries, I referred to a different project I would like to create an importer for, firefly-iii is not mentioned. Autofill was too quick in the case as well, so it put my companies email in :).
It is good to know the details instead of dealing with the vague.
