### ISSUE TITLE
csv-importer: specify custom key to avoid duplicates

### ISSUE THREAD

**Issue by psychowood** [firefly-iii/firefly-iii#3788]
The current hashing algorithm is a nice feature, but after importing a transaction, if this is modified, the hash would change and that would result in a duplicate transaction in the system.

I was thinking about a checkbox "Avoid duplicates" on the column, meaning "search for a transaction with that very same metadata and avoid inserting the new one if found".

Something like this:

<img width="933" alt="image" src="https://user-images.githubusercontent.com/115389/92749128-1b745f00-f386-11ea-9bb9-96e834619a29.png">

**Comment by JC5** [comment]
The hash isn't changed when you edit transactions, so changing the transaction afterwards shouldn't be an issue.

The use case for the duplicate detection is pretty narrow; it works when you're importing the exact same data twice but that's about it.

Are you running into anything specific?

**Comment by psychowood** [comment]
> The hash isn't changed when you edit transactions, so changing the transaction afterwards shouldn't be an issue.

Thanks, I had no idea. I'm quite sure previously (few months ago) I experienced duplicate imports using the same csv twice (btw the import tag is a real life saver), but I'm not sure which version I was using. I'll retry it during the next import.

> Are you running into anything specific?

Not recently, see above.

I was thinking about importing from a specific source (e.g. Paypal, Bank, etc) periodically, and not remembering either when the last import was done or not being able to select a specific date of export , for example.

On the other side, considering that most systems have a unique key, being able to discriminate a transaction by using a specific metadata would be way easier.

Either that, or a transaction view / search filter to show duplicates by metadatas, which might be a little overkill :)

**Comment by JC5** [comment]
The behavior has been the same for a while now, not even sure it was ever different. As long as the original line is intact you should be fine.

I'm reluctant to expand this behavior due to experiences from the past. Firefly III used to have some pretty fancy duplication detection. The problem is that it doesn't make it any more clear why the tool does or doesn't import specific transactions.

- Turns out one of the `n` checks in the code is buggy.
- Turns out the case falls outside of the duplication detection.
- Turns out it is a duplicate but the user doesn't expect it to be, because obvious field `X` isn't included.

In that sense, the goal of "duplicate detection by hash" moves the responsibility away from Firefly III, and away from the CSV importer, baring some exceptions.

- If the data is the same, the transaction is the same. Easy, predictable, cool.
- If the source data changes the transaction changes and that's not "my problem".

The exception is of course changed behavior in the CSV importer or Firefly III itself, and [this has happened in the past as well](https://github.com/firefly-iii/csv-importer/releases/tag/1.0.15).

I like the idea of selecting duplicates based on meta data but give me some time to see if and how this could be implemented. I prefer simplicity of flexibility.

**Comment by psychowood** [comment]
Can you give me directions to see how current hash is calculated, code-wise?

**Comment by JC5** [comment]
https://github.com/firefly-iii/firefly-iii/blob/main/app/Factory/TransactionJournalFactory.php#L532

It takes the entire array, removes existing hash and the original source (to prevent issues when upgrading the version), turns it into JSON and gets the sha2 hash.

**Comment by psychowood** [comment]
With "entire array" you mean the complete CSV line, or only fields with selected roles?

**Comment by JC5** [comment]
Whatever is submitted to the API, so it also works across import routines. Every part of Firefly III uses the API, so theoretically it can also detect duplicates in Firefly III itself. Although it's turned off for local transactions.

**Comment by psychowood** [comment]
Makes sense, if you change something (like adding and additional metadata) you probably want to reimport it anyway.

**Comment by JC5** [comment]
Indeed, although a downside is that when you map data, you may switch from category_name to category_id and that breaks the duplicate detection. Although surprisingly few people ran into that so far.

**Comment by JC5** [comment]
I have taken the time to build something like this, it's now in the `develop` branch and in the Docker image (`fireflyiii/csv-importer:develop`).

When you create a new import over the UI, you will see some new options.

- Select the type of duplicate detection. If you want the new option, select "identifier-based".
- You must indicate the index in which the unique value resides.
- You must indicate which type of field this is (four options)

During the mapping and processing you will see some changes as well. Most importantly, import will be slower due to a search action that will see if your field is indeed unique in the database.

Let me know if it works, I plan to release this in the next version.

**Comment by JC5** [comment]
2.5.0 is out :+1:
