### ISSUE TITLE
Bug: multiple budget limits dateranges in the budget view

### ISSUE THREAD

**Issue by lastlink** [firefly-iii/firefly-iii#3804]
**Bug description**
If I go and create several limits for a single budget across several weeks and then change the period to a higher range such as monthly or quarterly only the first 3 appear and sometimes the date doesn't show.

**Extra info**
version 5.4.0-alpha.3Firefly III © James Cole, AGPL-3.0-or-later.
range in view in july 1st  dec 31 2020.

**Bonus points**
![fireflymultiplelimits](https://user-images.githubusercontent.com/6679425/93605104-51bc6a80-f994-11ea-86fe-3458aeefc95b.PNG)
![limitsdb](https://user-images.githubusercontent.com/6679425/93605106-51bc6a80-f994-11ea-9a7b-1def788fc128.PNG)

**Comment by JC5** [comment]
Beta 1 fixes some of these issues. https://github.com/firefly-iii/firefly-iii/issues/3759

I'm curious to hear if this fixes some of the issues. I've added some cosmetic changes for the new release but otherwise I can't replicate the issue (anymore). Especially the "only the first 3 appear" problem seems unrelated to the code; there's no limit set anywhere.

**Comment by lastlink** [comment]
I pulled from develop. It also looks like multiple currency isn't working in the budget view. I add another one like brazilian real and the dollar signs all look like $ us dollar.

**Comment by JC5** [comment]
I don't see that:

<img width="781" alt="Screenshot 2020-09-20 at 19 27 41" src="https://user-images.githubusercontent.com/5889984/93717636-9b5caf00-fb66-11ea-97a4-fb68c2a1eb97.png">
