### ISSUE TITLE
Firefire Unable to Maintain DB Connection: `SQLSTATE[HY000] [2006] MySQL server has gone away`

### ISSUE THREAD

**Issue by Ryonez** [firefly-iii/firefly-iii#3838]
**Bug description**
I am running Firefly III version docker:latest (23/09/20, entrypoint.sh version 1.0.9), and my problem is:

Server does not start, drops db connection. Logs show `SQLSTATE[HY000] [2006] MySQL server has gone away` as the issue. Database is up and responding in a timely fashion.

**Steps to reproduce**

Update from 5.3.3 to 5.4.x
I use Postgres.

**Extra info**

Docker Log: https://pastebin.com/QsrGMaYS

**Bonus points**

- I searched and nobody reported this bug before
- I have added a stack trace from my log files 
- I have added a screenshot.
- I was able to replicate it on the demo site https://demo.firefly-iii.org/

**Comment by JC5** [comment]
Since the error is saying "MySQL" but you indicate you're running PostgreSQL, I suspect you're missing "DB_CONNECTION=pgsql" in your environment variables or Docker run command.

**Comment by Ryonez** [comment]
I don't have that, as it's explicitly state to leave the variable blank. Is that changed?
![image](https://user-images.githubusercontent.com/16157130/94038559-b7887680-fe1a-11ea-8c8d-2b1d22acc638.png)

**Comment by niklas2810** [comment]
This should be `pgsql`, as mysql is the default (via [changelog.md, since version 5.3.0](https://github.com/firefly-iii/firefly-iii/blob/229479b7edf0a94e224d5a55888595043dacda15/changelog.md#changed-2) and [here](https://github.com/firefly-iii/firefly-iii/blob/229479b7edf0a94e224d5a55888595043dacda15/changelog.md#changed-3)). What kind of software are you using to setup Firefly III? Specifying `pgsql` should solve your problem.

**Comment by JC5** [comment]
I have no clue, that piece of documentation isn't mine. If that's Unraid the template you're using is behind.

**Comment by Ryonez** [comment]
Great. I've added it it, not sure why it was still functioning for so long. Looks like the remote_user_guard file was changed, so have to jury rig that again. Thank you.

And it's running on unraid @niklas2810
