### ISSUE TITLE
Cloud-based Firefly III

### ISSUE THREAD

**Issue by ivanboytsov** [firefly-iii/firefly-iii#3886]
**Description**
Firefly iii is high quality software and I wonder why there is no paid cloud-based service. There is nothing bad in proposing paid service along with self hosted option.
There are plenty of people who completely unable to install it by themselves. And they would use cloud instead. Also not many of them consider their financial information as sensitive in any way.

Of course anybody able to do that, but it's would be fair if exactly you get profit out of it.

**Comment by sephrat** [comment]
> Also not many of them consider their financial information as sensitive in any way.

I'm pretty sure most of the people that use/know of Firefly III do consider their financial information as sensitive. That's the point of willing to selfhost anyway.
The potential users you're talking about are not the target of Firefly III curent user base.

Also, as Firefly III database isn't encrypted on user level, anyone with access to the database (any admin selfhosting a Firefly III instance) can freely access all of the users data. This is a major security concern.
I would definitely discourage people from using any Firefly III public instance.

**Comment by ivanboytsov** [comment]
But many people would trust "official" instance from the developer.

**Comment by JC5** [comment]
I had a discussion with another user about this subject recently, so I'm going to recycle parts of my answer.

I built Firefly III because I like to code. I don't care for installers or user guidelines or integrations with bank X or Y. The only thing I really look at when I extend Firefly III is myself: will it be a fun challenge to build? Will it be something I use? If the answer is no, that's the end of it.

It's also the reason I made Firefly III open source under the AGPL. Making Firefly III open source under the AGPL means that any change or addition to Firefly III must be open sourced under the AGPL as well. And for Firefly III to be business ready it needs a few changes. Those changes will allow you to host Firefly III for other people, for example.

* Firefly III as it is right now requires strict database controls or something auditable outside of Firefly III, because any database administrator can see everybody's administrations. There are no controls in Firefly III against insider threat. That alone makes it totally unworthy of being used in a "hosted"-fashion.
* There is nothing in place to do proper user management, except some half-finished admin pages I built for the demo site 3 years ago. These pages are a part of Firefly III, so if Firefly III breaks so does your user admin.
* More security and scrutiny is required to make sure the tool is bug-free and hassle-free. It's pretty easy to lock yourself out, for example.
* There is no payment module or anything; you'd have to develop something on the side.
* The development pace is too high to offer a stable product. I like to tinker and I break stuff all the time. My users accept this, if begrudgingly. But if they pay AND it breaks? No dice.
* I built Firefly III specifically because self-hosting is the only way to guarantee your data is (fairly) safe. At least, out of the hands of nefarious corporations. So hosting a public instance for everybody to use is kind of exactly against that idea.

But having said that: feel free to host Firefly III and sell access. If it's you and a few friends, all the better. You can keep it low key without needing strict privacy policies or payment services. If there's a kickback for me all the better ;). But make it larger, and I fear you run into the situation where you have to build a second system next to Firefly III to manage users, manage payments, etc etc. And the parts in Firefly III that you change must be open sourced.

Between us, I've had about a dozen approaches for a commercial venture with Firefly III. One or two were pretty serious. But it's hard to see a profitable outcome when you're bound to the AGPL. Which is fine by me, to be honest.

Personally, right now I'm just not interested in turning this into a business. Pro-users with a Docker installation get very far hosting Firefly III for themselves and once they get it up and running, they're invested. That makes for better users, which is good for me. Otherwise, I'm as happy I can be with the way things are right now.

**Comment by newrol** [comment]
Guys, what you are talking about here is very revealing. I've been using firefly for two years and it's my favourite software to control personal finances 😄. I have it deployed in a free instance on google cloud using docker. Would it be crazy to offer it as a service to non-technical users trying to completely isolate a runtime environment for each one?

I mean, instead of modifying the firefly code to adapt it to a large number of users, respect to the maximum its philosophy and development path using system administration tools, facing the problem as an operations task and not pure development.

Perhaps, from a bird's eye view, a possible structure would be:

- Deploy a robust mysql environment. Inside will be created a user and a separate database for each new user that user the being. There is no limit to the number of databases that can support a mysql cluster and the performance would be defined by the hardware that will host it, and the way firefly interacts with the database engine.

 
- Make available a variable number of physical nodes, where for each new user of the service a "instance" of firefly would be deployed in virtual host form, connected to its database.  A subdomain could be assigned to each user and requests could be redirected to each of them by means of a reverse proxy.

- Manage new users and their subscriptions to the service using any system in the market similar to the one used by the member site side s that are integrated with payment gateways as stripe and do all that work for you. 

- Perform scripting tasks to integrate the user manager  and their subscription status provided by third party software with the creation of a firefly environment for each user (database user, virtual host and CNAMES, and traffic enrollment), perhaps based on ansible or any other operations tool.

Surely, such a system would not be viable, either technically or economically, but it is fun to think how this great software could be adapted as a service, minimizing the changes on it.

**Comment by sgofferj** [comment]
I'm not sure if you guys realize the compliance nightmare a commercially offered financial management software is going to be for the developer and the operator. I don't even pretend to know US regulations but if the service is even accessible from the EU, you're subject to the GDPR and a whole host of other things. You're basically standing with one leg in prison all the time or at the very least have the sword of bankruptcy hanging over you, cause GDPR fines can go up to €20M.
Besides GDPR, you will very quickly get loads of mail from police departments or other agencies, wanting the data of your users and you're in hell again, because YOU have to know if your can give that specific data out. If not and you do, GDPR strikes again. If yes and you don't, you might face obstruction charges.

Seriously, I wouldn't touch such a project with 3m long tongs as developer, nor as operator...
However, one thing @JC5 , Nextcloud is AGPL and they seem to make pretty good money with their business model... ;).
