### ISSUE TITLE
cashflow predictions / estimates

### ISSUE THREAD

**Issue by nekromoff** [firefly-iii/firefly-iii#393]
This is probably non-trivial (or based on chosen algo, it might be trivial), but it would be nice if Firefly could also do reports with predictions, e.g. based on income/expenses during previous period (month, three months, six month, year) estimate income/expenses for upcoming 30 days (or any other selected period).

Both individual or companies have regular monthly income and expenses on certain days etc. These could be taken in account for the estimates.

**Comment by JC5** [comment]
The original Firefly had this, but it wasn't very good. It started by averaging the amount taken from / added to your account each day, and extrapolating from there. 

This was difficult because eventually each day of the month would be crooked because a large expense happened to have hit that day some time in the past.

So if you ever bought an expensive new laptop, your predictions would be off for years on that day. Or when you receive your salary on different days of the month, eventually this meant that you would see weird bumps around pay day. 

This was solved by marking transactions as "do not use in predictions" but that only went to show how bad these predictions were. 

But this is all a thing of the past and I'm merely being nostalgic now. 

What exactly would you want to know? Are you interested in knowing if your balance will dip below zero this month? Do you want to predict how much money you can save in a year? Do you want to guesstimate your new worth over the course of your life? 

Please describe to me exactly what you would like to see predicted, and where you would be able to see this prediction. 

Together we can come up with one or two ideas I can implement.

**Comment by nekromoff** [comment]
Actually, I was thinking in a small business terms. Nothing concrete on my mind regarding how to calculate, but I guess there are standardized formulas for these (e.g. taking set of values around median to limit extremes?).

I can think about this further.

**Comment by JC5** [comment]
Based on your bills it can be easy to predict what expenses to expect in a month. The boxes on the index already do this. I'm thinking of a modal dialog or a page somewhere that would tell you what your next [period] would look like. Perhaps showing you a calendar, or the days of the month.

Not based on bills could be any account hit more that x times in the last x months (skipping one time purchases) which would fill out the rest nicely. The exact formula can be googled. 

Any other predictions would be something to do in Excel yourself.

**Comment by JC5** [comment]
I've closed this issue for the time being. Firefly will not be featuring financial future management for the foreseeable (haha) future.
