### ISSUE TITLE
Logo idea

### ISSUE THREAD

**Issue by hendrikbl** [firefly-iii/firefly-iii#3941]
I tried to make a logo for firefly since i found the piggy image does not fit the new, more clean design.

I'd be happy to hear what you think :)

![firefly_logo](https://user-images.githubusercontent.com/9558391/96142839-cedeef00-0f02-11eb-886a-815679dea593.png)

Edit.: The "slogan" is just something i came up with so it looks a bit better :D

**Comment by IceflowRE** [comment]
Good work, but some of my thoughts:

- looks a bit retro at all
- i would advise to create two types on with text and one without
- the firefly at the top seems to be displaced and hard to see, also the firefly itself is quite nice
    - the unique point of the logo should be centered and clearly visible
    -  the yellow covers the most space and also has the same color as the firefly
    - a logo and it's product should be recognized within a second
- is it a firefly?
    - even if the back is yellow like a lamp, it could be a normal bug (ignoring the fact that `firefly` is written there)
    - probably symbolize the light with rays

**Comment by JC5** [comment]
Hey man, this is pretty rad! The logo as such isn't really what I'm looking for though. But you had a false start. Although I expressed interest in getting a logo in one of the monthly updates (for backers mainly), I never followed up on it.

Not many people know Firefly III wasn't named after the insect or the series (sorry Nathan) but after British WW2 era airplane the [Fairey Firefly](https://en.wikipedia.org/wiki/Fairey_Firefly). Which in turn was my choice because it starts with an F like finance.

The name is "Firefly III", because it's the third version. I built the first version using SVN on my own machine. Somewhere in 2013, because that's where my own administration starts. I started "mark 2" in Groovy but it never went anywhere. Firefly III was hosted here on GitHub to try out Git. They had free hosting, even though it meant I had to make my own crappy code open source. And here you all are!

For a logo, I'm not yet sure what I want. I like the piggy, but the fact it's a photo doesn't really fit. It doesn't really need a slogan I think. If a currency symbol is going to be part of it, it's got to be the € of course. 

Rather than rely on community effort though, I might outsource it as a paid job. I'm a big fan of r/ChoosingBeggars and I would like to reward somebody for their efforts. And no, not with exposure 😅 .

**Comment by hendrikbl** [comment]
> Not many people know Firefly III wasn't named after the insect or the series (sorry Nathan) but after British WW2 era airplane the Fairey Firefly. Which in turn was my choice because it starts with an F like finance.

Oh that's interesting. I was indeed wondering why you would name a finance manager firefly and my only guess was the F but never thought it was because of an airplane :D

> For a logo, I'm not yet sure what I want. I like the piggy, but the fact it's a photo doesn't really fit. It doesn't really need a slogan I think. If a currency symbol is going to be part of it, it's got to be the € of course.

I thought a piggy + the name firefly is a bit confusing. Thats why I didn't go with a pig. Regarding the currency: I didn't check where you're from. But since I'm from Germany I also like € more :p

> Rather than rely on community effort though, I might outsource it as a paid job. I'm a big fan of r/ChoosingBeggars and I would like to reward somebody for their efforts. And no, not with exposure 😅 .

I wasn't sure if paying someone for it is an option. But if it is, it sure is the better option I think. I'm not a professional designer at all (not even close). This was just me playing around with an idea and that's what I got in like 30 minutes or so :D

**Comment by psychowood** [comment]
There are options for piggy+airplanes ... :D

![image](https://user-images.githubusercontent.com/115389/96226743-62600080-0f93-11eb-8747-2f23b2100045.png)
