### ISSUE TITLE
devops, snyk security scan

### ISSUE THREAD

**Issue by lastlink** [firefly-iii/firefly-iii#3955]
**Description**
* https://snyk.io does security scans for dependencies. Please login and authenticate github and add this project to get it scanned. It's unlimited scans for open source projects. I've started using it for some of my other projects. They will even do fix pr's if they support that language, otherwise it's manual. If you can add a secret to github and give the token a name such as snyktoken, I can setup a github action that will output snyk html report artifacts on security issues.

**Comment by JC5** [comment]
Hey man, thanks for the suggestion. I'm already using Dependabot to do security scanning. This has the added advantage of being integrated with GitHub as well.

I did set up Snyk, but all it found was old Firefly III vulnerabilities. Which makes sense, because it's scanning Firefly III. :D

<img width="1158" alt="Screenshot 2020-10-18 at 10 36 31" src="https://user-images.githubusercontent.com/5889984/96362467-0c1ec900-111d-11eb-9ea6-22e1ad598bd7.png">

**Comment by JC5** [comment]
FYI, Snyk is now running and reporting correctly. It took a few tries. It refuses to make it's PR's on the `develop` branch so I've opted to send me email notices instead.

The results are slightly different than Dependabot. Not sure if this means more security or more paranoia 😅 . Thanks for the suggestion, it's much appreciated :)

**Comment by lastlink** [comment]
great thanks. I've been using it for some of my projects now. b/c they are closed source I do weekly rather than daily. It is nice to know right away after the scan when a version needs to be updated for security flaw from their security database.
