### ISSUE TITLE
Missing docker images

### ISSUE THREAD

**Issue by SerialVelocity** [firefly-iii/firefly-iii#4010]
**Bug description**
I am running Firefly III version 5.3.3, and my problem is:
My host just restarted and cannot pull 5.3.3 anymore.

**Steps to reproduce**

1. `docker pull  jc5x/firefly-iii:version-5.3.3`

**Extra info**

It seems old docker versions are being cleared for some reason?

I try to update firefly-iii when I can but having the update forced is a real pain. I've had my csv-importer container failing for about at least a week because of the same issue.

**Bonus points**

- I searched and nobody reported this bug before
- I have added a stack trace from my log files 
- I have added a screenshot.
- I was able to replicate it on the demo site https://demo.firefly-iii.org/

**Comment by JC5** [comment]
Yes. This is not something I intend to keep doing, but sometimes I have no choice. Please update to 5.4.x at your earliest convenience. For the versions before 5.4.5, I had to drop versions because of quality concerns in the images themselves.

Dropping the images so soon wasn't intended though. 5.4.x is out for about a month now. I'll try to prevent this in the future.

Having said that, I'm reserving the right to drop these images. Rebuilding the images locally isn't difficult and shouldn't impede on your local installation.

**Comment by SerialVelocity** [comment]
Even if the older versions have quality concerns, wouldn't it be fine to keep them around?
- New users will just use the latest version
- Older users will just upgrade directly to the latest version when possible

**Comment by JC5** [comment]
You'd be surprised how many people download old images, despite newer being available ;).

Normally I would but this really warranted an intervention. Sorry for the inconvenience.

**Comment by SerialVelocity** [comment]
Ok, no problem. Shall we close the issue then?

**Comment by JC5** [comment]
Alright I'll do that. Thanks for keeping me sharp re: the old images. I'll write something down in my personal checklist to make sure it doesn't happen again.
