### ISSUE TITLE
Date in New IP address email is not localized

### ISSUE THREAD

**Issue by sephrat** [firefly-iii/firefly-iii#4013]
**Bug description**
I am running Firefly III version 5.4.5, and my problem is:

The email sent upon login from a new IP address is all in my configured language, apart from the actual date of login. It says "October" instead of "octobre".
It seems Carbon doesn't know of the locale settings at this stage.
It can lead to a weird behaviour as it uses the localized format settings properly  (`trans('config.date_time')`) but won't print the month in the correct language (29 October 2020 = mix of October 9 2020 + 29 octobre 2020).

I debugged it and found a solution but I'm not sure where to implement it cleanly.
My dirty hack I wouldn't dare to submit as pull request:
just before https://github.com/firefly-iii/firefly-iii/blob/e6c0bbf082c64ed7a2794930baf0861e1199d1fd/app/Mail/NewIPAddressWarningMail.php#L58
add this:
`setLocale(LC_TIME, app('steam')->getLocale());`

Hope this helps.

**Comment by JC5** [comment]
I'll do some digging. Basically, due to the fact how these emails are handled, you have zero control over the context outside of that class. It's asynchronous. It just works in Firefly III because it defaults to a simple synchronous queue. 

But if an adventurous user would config Redis the emails probably wouldn't even translate right. 

I'll pick it up. Advanced queue management is necessary for webhooks anyway.

**Comment by JC5** [comment]
<img width="582" alt="Screenshot 2022-03-27 at 19 06 16" src="https://user-images.githubusercontent.com/5889984/160292478-fad843e1-305a-42d9-a60c-15199b20f614.png">


Will be fixed in 5.7.0
