### ISSUE TITLE
Transaction merge

### ISSUE THREAD

**Issue by juansalvatella** [firefly-iii/firefly-iii#4017]
I believe that it’s a common scenario when you pay something for someone else and they eventually pay back. They are small amounts so it doesn’t really make sense to create a liability to track them down and they also mess up your budget. As documented on the docs: https://docs.firefly-iii.org/faq/financials this can be fixed by hand editing transactions manually.

I’ve thought about it and this is a really common scenario for me. I would like to have an option to automatically merge selected transactions into one and have traceability of what happened in the description.

For example, I paid 40 eur in a restaurant and later my girlfriend payed back 20 euros. I would like to edit the first transaction and leave it as a 20 eur expense in restaurants and add to the description the details of the previous transactions.

What do you think about it? I would be glad to develop it and make a pull request if you think it would be useful for everyone. The closest thing I’ve seen with what I would like to see are transaction links but I don’t think they are working yet.

Thanks and regards,

**Comment by JC5** [comment]
This feels like something that can be whipped up using the API. Assuming for example you've tagged both transactions `merge-me` you can [search](https://api-docs.firefly-iii.org/#/search/searchTransactions) for them with the `tag:merge-me` query. 

If you find two transactions, and one is a withdrawal and the other is a deposit (easy check) you can update one amount and delete the other.

**Comment by juansalvatella** [comment]
In terms of UI, I was thinking about integrating it as a bulk option like this:

![image](https://user-images.githubusercontent.com/4377347/97809534-a6c6ee00-1c6d-11eb-857a-17149f12062b.png)

I haven't thought much on how it should be done programatically but instead of searching for a custom tag that should be added by hand I'm assuming that I could get all the transactions selected with the before-mentioned method and perform the check you just mentioned to determine the final quantity.

I will work on it and make a pull request. Do you like the fa-compress icon for the merge menu option?

Thanks for your hard work James.

**Comment by JC5** [comment]
Sorry, but I'm not going to accept a PR to add this.

**Comment by JC5** [comment]
Merging transactions sounds like a good idea but it's difficult to bring into practice. Your happy flow works pretty well of course. A withdrawal from asset account X is offset by a deposit to that same asset account.

Too many things can happen in all the other flows, especially when you're adding multi-select. What if the deposit is more than the original withdrawal? What if I merge two transfers? What if none of the accounts involved in the merger match?

Either you add a merge function that works in 5% of the cases or you add a merge function that does the thinking for the user or you add a merge function with a massive wizard attached. Neither option feels like something I want to add to Firefly III.

Which is why I suggested to build something using the API instead.

**Comment by juansalvatella** [comment]
I understand your decision. There are quite a few complexities around this.

So that I can provide my two-cents about it, my thinking was the following. Create a merge summary page in order to review the transactions that meet the conditions to be merged and those that can't. Explain in the docs what can be merged and what can't.

![image](https://user-images.githubusercontent.com/4377347/97810999-01fdde00-1c78-11eb-8665-a6e021eeeb6c.png)

- **What should be allowed?**
Merging deposits and withdrawals. No transfers as it wouldn't make sense (as far as I know).

- **What if the sum of deposits is higher than the sum of withdrawals?**
The resulting transaction is a deposit. And a withdrawal, vice-versa.

- **What happens if different accounts are involved?**
This should be a common scenario where I pay a common expense using my VISA but my friends pay me back using some other payment method like Bizum or such). If it's a simple scenario (like the one I initially described) the account with the highest amount is the one being offset with the other. If it's a complex scenario where there are multiple accounts being merged and no sensible default can be defined, all transactions will be deleted and a new transaction will be generated with the resulting operation (a deposit if the sum is positive and a withdrawal otherwise) and the summary in the description.

This should cover scenarios such as:
- N withdrawals or N deposits
- 1 withdrawal/deposit and N deposits/withdrawals
- N deposits/withdrawals and N withdrawals/deposits

In my opinion, this should be OK if users know what they are doing and why but I would like to know your opinion on this. Feel free to not answer as you already said what you thought about it. I just feel that this is one of the reasons why budgets never worked for me as I always had expenses accounted that weren't really expenses and I never had the time to manually change them. Of course, this was long before I used Firefly III and I used Excel for my personal finances. Thanks for your hard work.

**Comment by JC5** [comment]
I like the idea, I'll mull it over. I'm not a fan of wizards and documentation and guidelines and everything. Firefly III is full of those, ironically. Trying to catch all the use cases is impossible and it makes the solution feel like magic. In practice, these kinds of wizards tend to be used by exactly zero users. Or maybe one or two power users which is equally pointless. 

GnuCash is filled with options 5 people know about and 2 people use. I don't want Firefly III to be like that. At the end of the day, I got to maintain this into eternity.

Most budget programs can't really handle the payback scenario and Firefly III isn't an exception. Maybe instead of making it bigger (documentation, exceptions, etc) make it smaller. What *you* need is a basic trigger and a reaction. It could be a tag, it could be a keyword. That's why I suggested the API.

Thanks for the expansive request, I really appreciate your input.
