### ISSUE TITLE
Concept question: bill vs budget

### ISSUE THREAD

**Issue by totti4ever** [firefly-iii/firefly-iii#4034]
So, I like the implementation of the bills as it is kind of great to see how things developed over time and which things are still tom come this month.

But I don't quite get how they should be used or distinguished from budgets.

Let's take rent plus electricity plus gas bills. I would want them to be part of my overall budget as well to not have to look at budget for a part of my monthly expenses and at bills for others.

So I thought, it'd be nice to be able to tick bills to be available in budgets as well. Or even better, bill groups.

What I'll do now is to assign every transaction which is assigned to a bill to a budget as well.
It would help a lot if I could look for bill groups in the rules section!

But with this ticket I wanted to mainly ask people how you/they use these concepts!

cheers

**Comment by sephrat** [comment]
In my case I have one of my budgets called "bills" that I manually set to the expected amount of bills for this month. 
It is quite tedious at the moment to use Firefly-III to get this amount as I need to deal with yearly bills as well. /bills sums do not consider if the yearly bill is expected this month, it just takes 1/12th of the amount, when I would like to budget the entire bill amount only if it is expected this month. I end up using a spreadsheet to get the right amount.


I agree that budgets and bills could be better integrated with each other. Now the big question is "how", this requires a lot of thinking and designing.

**Comment by JC5** [comment]
Originally, I started with budgets only. I also have "bills" and also "shared bills". These are pretty basic budgets that never really change. They're budgets only to group transactions because it's hard to cut back on rent the same way you would on candy.

I introduced bills when I got some monthly bill halfway through the month I kept forgetting. So the frontpage tells me what the expected nr. of bills is.

The 1/12th amount is kind of a hack and I don't like it myself. But for the whole of Firefly III, monthly and yearly doesn't really mix well. It's an architecture kind of a decision to merge (or not) everything into 1/365 parts or keep it strictly separated.

> What I'll do now is to assign every transaction which is assigned to a bill to a budget as well.

I do this as well. I use three things simultaneously to achieve the same thing. 

- Rent is a recurring transaction.
- Rent is part of a budget called "Bills"
- Rent is linked to bill "Rent".

It all ties into each other, especially with rules as well. Not sure yet how this combines into one thing. Basically, it's distinct, grouped, has multiple parts that form one thing, one "blob".

The example blob is your bills. Fictional amounts.

- Budget: 500/month but also room for yearly expenses without breaking the budget.
- Transactions: mostly fixed but some incidentals.
- Recurring transactions: same thing, pretty easy to manage, not every incidental needs a bill.
- Bills: keep track of expected transactions, needs a merge with recurring transactions maybe?
- Categories & tags are nice to have and out of scope.

Each part of this needs careful rebranding and rethinking to work. Keep in mind Firefly III has always been a sloppy conglomeration of ideas.

Something to think about indeed.
