### ISSUE TITLE
Multi-Language Documentation 

### ISSUE THREAD

**Issue by starkyller** [firefly-iii/firefly-iii#4111]
Hi there! 
In many help pages people get asked to read the official documentation which is in English.
Is there any though about providing the documentation (docs.firefly-iii.org)  in more languages? Since the application it self is multi-language it seams to me that would only make sense to also provide the documentation in more languages.

**Comment by JC5** [comment]
The documentation will remain English only.

**Comment by JC5** [comment]
As it turns out, translating is a pain. It's difficult, it's boring and most translators give up about 1/3rd of the way in. The only reason we have a few completed languages is because multiple people are persistent enough to see it all the way through and make sure that everything is finished (easy), correct (hard), consistent (very hard) and not too much English translated directly (impossible).

Firefly III now has about ~20 languages, painstakingly translated by volunteers in various stages of completeness. Most languages see very little activity, just 3 or 4 are up-to-date and reasonably complete. Another 15 languages are dead. This means effectively that any language you view you will see a lot of terrible translations and lots of English content. Exceptions are duly noted, but for the majority this is the sad truth.

I'm not subjecting myself to the same maintenance and upkeep nightmare for the documentation for Firefly III and all of the importers.

**Comment by starkyller** [comment]
oh ok, it makes sense. Thank you for the input!
