### ISSUE TITLE
Reverse proxy with subfolders

### ISSUE THREAD

**Issue by Johan3F** [firefly-iii/firefly-iii#4243]
**Description**
I would like fireflyiii to be able to be hosted behind a reverse proxy with subfolders, not only subdomains.
I know that this is a topic that has been coming and going (#2514 and #3439), but I want to revive it because it's contra-productive that this project must live on it's own subdomain instead of a subfolder. I think that we could all agree that nowadays, a web app should be able to be hosted both on subdomains and on subfolders.
I believe you have some strong opinions regarding the solutions, but I would ask you to reconsider and go for any that would make you less uncomfortable. 

**Solution**
Posibility to host fireflyiii in a subfolder

**What are alternatives?**
subdomains, but not everybody prefers or can

**Comment by JC5** [comment]
Technically speaking, there's nothing stopping Firefly III from being served using a reverse proxy under a subfolder. The [docker image](https://github.com/firefly-iii/docker) can be customized easily.

There are a few solutions that you can explore.

- Change the default Apache config so the container already serves from a subdirectory (ie. by alias). Then, a reverse proxy serving /firefly-iii/ under /firefly-iii/ will work just fine. Calls to / will not be forwarded by the reverse proxy.
- Customize the reverse proxy so it rewrites the request to the default Apache from `/firefly-iii/` to `/` so the Docker container understands.
- Build an image with FPM instead of Apache.

**Comment by Johan3F** [comment]
Thanks for being so quick replying!

For the first option and the third:
I understand that I can do it myself, but then I would be having to keep up with your updates, and having to do it every time you deliver a new update to the product, merging your changes into my own repo. 
All this only for having to change or the entry point, or FPM instead of apache (I'm not familliar wiht PHP related development nor deployment either). I'm sure there's a better way to provide support for this without having to modify these kinds of things.

I've tried the second of those options:
Even when the reverse-proxy gets only `/` to firefly, firefly then redirects using `/` and then my reverse proxy cannot find `/firefly` throwing a 404 (I've spend some time trying to get this to work, and I failed miserably).
Sounds like you have a fair idea by now of the different tries that people have done in order to achieve this

**Comment by JC5** [comment]
> Sounds like you have a fair idea by now of the different tries that people have done in order to achieve this

Yes I do. What do you expect me to do, exactly?

**Comment by Johan3F** [comment]
I guess that having documentation of how to do those would be of great help for the ones, like myself, that are not that familiar with it

**Comment by JC5** [comment]
But neither am I. And I have little interest in building a reverse proxy with subfolders, it's just not my use case. 

When you figure it out, you're welcome to open a PR as to how you did it.

**Comment by Dreomite** [comment]
I don't think this issue should be closed. There's currently no way to proxy Firefly with subdirectories, and all other issues/PRs are closed as well. We need some place to discuss this.

Redirecting `/firefly-iii/` to `/` inside a reverse proxy doesn't work. Setting up all the necessary redirections in response/request headers does not affect links in page's content. Meaning, internal links, images, css, etc. are broken, because they point to `/contents` instead of `/firefly-iii/contents`. And this is not fixable outside of Firefly.

All the possible solutions were already listed in @TimCinel's [comment](https://github.com/firefly-iii/firefly-iii/pull/2514#issuecomment-526568910): either use relative URLs for everything, or append predefined ROOT_URL to all the links. That's what all the other services do to be subdirectory-compatible. Using relative links doesn't seem like an option for a project like Firefly, because of its complexity, which leaves us only with base URL overriding option.

It would be nice to hear @JC5's opinion of the possibility of implementing this approach in the future, if somebody will be willing to do so. Because after #2514, it's uncertain if this implementation would be even merged.

**Comment by JC5** [comment]
> Setting up all the necessary redirections in response/request headers does not affect links in page's content.

The only option I can suggest is that you build an image specifically configured to serve Firefly III under `/firefly-iii`. When served by a reverse proxy under the same subdirectory, it'll work. It's a hack but it works.

Although the new layout will have a lot less absolute URL's I won't be able to guarantee a full-relative-url experience at any point in the future.
