### ISSUE TITLE
Reduce left_to_spend by bills_to_pay

### ISSUE THREAD

**Issue by devfaz** [firefly-iii/firefly-iii#4382]
**Description**

would be great if "left_to_spend" would only include really "left to spend"-money.

In my opinion/use-case it should not include money which will be spent in the future by planned bills (bills_to_pay)

**Solution**
Reduce the amount "left_to_spend" by the amount of "bills_to_pay"

**Alternate solution**
* add both values to the output.
or
* allow configuration of calculation (include bills_to_pay or not) in the config.

**Comment by JC5** [comment]
Great suggestion! I thought about this before and ultimately I decided to do neither.

First, because the bills_to_pay amount is always relative and it's not reliable enough to say much about your left_to_spend. Second, because I felt more comfortable doing the calculation in my head. Having the view was enough for me to be relatively sure what money I had left and since the bills had some leeway, it gave me more trust than an absolute number I knew would be incorrect (because inaccurate) anway.
