### ISSUE TITLE
Any plans to support HBCI or FinTS?

### ISSUE THREAD

**Issue by TwizzyDizzy** [firefly-iii/firefly-iii#448]
Hi folks,

I was wondering, whether you plan to implement HBCI or FinTS to get accounting data directly from the bank.

Cheers
Thomas

**Comment by JC5** [comment]
Yes. I'm unable to find a version of those specs not in German though :P

I am currently waiting for the upcoming Directive on Payment Services (PSD2) and how banks will respond to it. With a little luck, a European standard will rise from it.

Otherwise, pretty soon, 90% of FF3 code will be interfacing with banks :P.

**Comment by TwizzyDizzy** [comment]
Here are the speccs for HBCI 2.2 in english: https://www.hbci-zka.de/english/ ... and on the same page the FinTS speccs are in preparation.

But I'm with you that one should maybe wait for a europe wide approach.

Cheers
Thomas

**Comment by JC5** [comment]
Yes, I found those as well. However, the 4.0 version of the specification has been released (in German) in 2004. The 4.1 version in 2014. I'm not sure if they will ever translate these versions ;).

However, libraries supporting FinTS in PHP are also available.

When I have something to show, I will post here!
