### ISSUE TITLE
Sum of all revenue accounts & available balance

### ISSUE THREAD

**Issue by stratoss** [firefly-iii/firefly-iii#4753]
**Description**
In the `Asset accounts` page, it will be helpful to see the total amount across all accounts, and the available amount (total amount - the sum of all piggy banks).

**Solution**
- [ ] Showing the sum of all available balance across the revenue accounts
- [ ] Subtracting the sum of all money in the piggy banks from the sum above

**Comment by JC5** [comment]
I can look at the sum of the balance (aka your net worth?), but I don't really see the value of the piggy banks.

**Comment by Dettorer** [comment]
I was thinking about making a feature request for the "sum of all assets minus piggy banks" or "amount on asset account X that isn't allocated to piggy banks". I often find myself wanting to know how much savings I have that isn't put towards some piggy banks, this is what I consider my security savings and I like to keep an eye on it.

This rather personal need lead me to imagine a much more complicated feature: letting the user add arbitrary extra views on the landing page with custom calculations, like "sum of last month expenses in the 'food' category" or "average sum of deposits every months since the beginning", the thing with the piggy banks, etc. Maybe just consider it an "advanced" feature and let the user choose a title, a color, and a SQL request (though I guess this is way simpler / more reasonable in my head than in reality)

**Comment by JC5** [comment]
> I was thinking about making a feature request for the "sum of all assets minus piggy banks" or "amount on asset account X that isn't allocated to piggy banks". I often find myself wanting to know how much savings I have that isn't put towards some piggy banks, this is what I consider my security savings and I like to keep an eye on it.

This is available on the bottom of the /piggy-banks page.

> This rather personal need lead me to imagine a much more complicated feature: letting the user add arbitrary extra views on the landing page with custom calculations, like "sum of last month expenses in the 'food' category" or "average sum of deposits every months since the beginning", the thing with the piggy banks, etc. Maybe just consider it an "advanced" feature and let the user choose a title, a color, and a SQL script (though I guess this is way simpler / more reasonable in my head than in reality)

It sounds simple, that's for sure 😉
