### ISSUE TITLE
Notifications (email) when subscriptions are about to expire/renew

### ISSUE THREAD

**Issue by rocribera** [firefly-iii/firefly-iii#4893]
**Description**
I would like Firefly III to send an email notification X days prior to a subscription renewing/ending. This would help anyone keep in check when they have to spend more to renew or cancel a subscription.

**Solution**
A feature to indicate the days before a subscription you'd like to be notified of it.

**What are alternatives?**
Using other alarms in other software, I don't think I've seen a software that implements both the budget part of subscriptions (like this one does) **and** management whenever they are about to expire.

**Comment by JC5** [comment]
Firefly III doesn't track the end of a subscription, so it can't warn you about them. But it's something I can think about, thanks!

**Comment by rocribera** [comment]
This under Bills or Recurring Transactions is what I was thinking. I've just downloaded the software since I love it, but I'm still getting used to everything, so I don't know exactly what goes where yet, but this is something I was looking for and thought it could be helpful! Thanks for the quick reply!

**Comment by savyajha** [comment]
This is actually a brilliant idea. If you don't object to votes, please take mine for this feature as well!

**Comment by JC5** [comment]
<img width="810" alt="Screenshot 2022-03-28 at 10 31 10" src="https://user-images.githubusercontent.com/5889984/160358360-68c49a22-31af-40e5-b4d7-cffee7138159.png">

Only partially translated because it's not uploaded yet to crowdin. System will mail at 90, 30, 14, 7 and 0 days (not configurable). Two fields can be set, and you will get a message about both: the "end date" and the "extension date".

Will be part of 5.7.0
