### ISSUE TITLE
After viewing an attachment and editing, you are returned to the attachement

### ISSUE THREAD

**Issue by pwsoftwaredesigns** [firefly-iii/firefly-iii#4901]
**Bug description**
I am running Firefly III version 5.5.3, and my problem is:

After opening a transaction's attachment, you are redirected to that attachment after making changes to that transaction.

**Steps to reproduce**
1. Select/open a transaction for viewing
2. Click on an attachment to view it
3. Press the browser's back button to go back to the transaction view
4. Edit the transaction
5. Apply the changes (update transaction)

**Extra info**
Using Google Chrome and Safari on iPhone

**Comment by JC5** [comment]
Thanks, I'll check it out!

**Comment by JC5** [comment]
Found and fixed.

**Comment by marinbernard-pep06** [comment]
Hi,

I think this issue may be part of a bigger one involving how Firefly III deals with several opened tabs.

For instance, if you edit aud submit a transaction in one tab, then edit and submit another in another tab, the second tab is always redirected to the transaction from the first tab. The same thing happens if you edit a transaction in tab 1, and clone another in tab 2: tab 2 is redirected to the edited transaction from tab 1 instead of the cloned transaction.

Hopefully, the link included with the success banner always leads to the correct transaction. I took the habit to always click on this link after each edit to avoid messing up with the wrong transaction.

Do you think this bug is related or should I create a dedicated ticket ?

Thanks!

**Comment by JC5** [comment]
Feel free, but I'm afraid it's not something I'm going to fix. Firefly III saves the second-previous URL in the session, so it can redirect you correctly. From page X, you edit an object, and the redirect is back to page X. 

Since this is shared in the session, and your browser shares the session with other tabs, the redirect may point to stuff you do in other tabs.

**Comment by marinbernard-pep06** [comment]
Thank you for the quick answer! Why not pass the source URL with form data ? Would it have security implications ?

**Comment by JC5** [comment]
Not really, since you have to be logged in anyway. But I'm working on a new layout and in that one, I may be able to incorporate something.
