### ISSUE TITLE
Subcategories

### ISSUE THREAD

**Issue by RaphaelJenni** [firefly-iii/firefly-iii#4911]
Before starting: I know, it had been discussed already many times before. But as this still is a feature that would be useful to many people, and it is a few years later, I want to open that discussion again.

**Description**

As described in previous issues (#163, #626, #1629) and against what is described in https://docs.firefly-iii.org/firefly-iii/about-firefly-iii/what-its-not/, adding the possibility to have sub-categories would be huge.

Samples of how the categories and their subcategories should look like can be found in the linked issues.

To tackle the question "Why do you want them? You don't really gain that much of an insight.":

For me, subcategories give you the option to break down costs into smaller buckets.
For example, I do many different sports. Now for all those sports, I have different areas where I spend money.

- Sports
- Sports/Skiing
- Sports/Skiing/Equipment
- Sports/Skiing/Tickets
- Sports/Skiing/Food
- Sports/Climbing
- Sports/Climbing/Equipment
- Sports/Climbing/Tickets

At the end of the day, I want to know how much money I spent on skiing in total and in the different areas.
The same goes for climbing. And at the end of the year, I wonder how much money I've spent overall on sports activities, including sports other than skiing or climbing.

You see where I'm going with that.
Now I understand that it would need some changes in the database and the UI.
But if we keep it simple, it should be manageable and should not affect users that don't want to use subcategories.

**Solution**

As seen in other finance tools, the most simple option would be to handle subcategories and categories equally.
Just prefix the subcategory with the name of the parent (like in the example above).
The data model would just need to have a field with a parent category relation (of course there needs to be a cycle detection, but that isn't that hard). If the parent is `null` it is a top-level category.

I would have created a PR, but I don't work with PHP, so it's up to you.

**What are alternatives?**

Sadly, in my eye, there aren't any viable alternatives currently available.

**Additional context**

I currently work with Finanzmanager from Lexware and have aggregated transactions over the last 8 years, all carefully categorized. I want to switch to something web-based and your solution is the closest alternative I could find.

Additional posts:
- https://www.reddit.com/r/FireflyIII/comments/au1nta/accounts_or_categories_tree/

**Bonus points**

Sorry, no bonus points for me. But I'm happy to help conceptually or to review something.

**Comment by JC5** [comment]
Sorry, it's not going to happen.

**Comment by niklas2810** [comment]
@RaphaelJenni  This feature would be nice, but there's also a convenient way (which I came up with, having a similar goal in mind) to solve your grouping issue in another way:

- You can already see in your example that there are many duplicates, e.g. "Equipment" and "Tickets" (and I think you'll have "Food" transactions for other activities as well). Use these as your categories, since they are not related to an activity. Other examples are "fees", "shopping" or "rent".
- Then, tag the created transactions with the appropiate detail tags (e.g. "Sports" and "Skiing"/"Climbing").
- If you now want to analyze how much you spent for certain activites, let Firefly III generate a report based on the specific tags. You can select the tags individually, so only choose "Skiing" and "Climbing" if you want to compare the two. If you want to compare how much you spend on Sports and Drinks, just tick these two boxes.

I know this isn't as intuitive and straight-forwars as subcategories, but it does the job and isn't too much of a hassle 😄
