### ISSUE TITLE
How should this balancing tag-thing work?

### ISSUE THREAD

**Issue by zjean** [firefly-iii/firefly-iii#492]
Hi,
I am trying to setup balancing tags to achieve the following.
Let's say I spend 150€ at a webshop and after retrieval I decide to return some items (worth €50).
I would like my category overview and report to reflect only the expense of €100 (I use a category and not a budget because I don't envelope for clothing).
I created a balancing tag, and linked both transactions:
![image](https://cloud.githubusercontent.com/assets/441924/21456523/f61947ec-c928-11e6-9b45-38857c37801b.png)

My category overview just shows the expense of 150€. 
![image](https://cloud.githubusercontent.com/assets/441924/21456540/2115c966-c929-11e6-9d49-02ce92cf91f6.png)

It doesn't change that much when I add the revenue transaction to that category as well, as it is reported as income.
![image](https://cloud.githubusercontent.com/assets/441924/21456552/39bfdede-c929-11e6-8d46-bb0f1afc25ad.png)

Do you know what's going wrong? Do I need to perform some extra steps?

Besides that: since a balancing tag can only have one expense transaction, it is quite a job to find good tag names. I tend to use the shop name, but can only use it once. The next time I do a purchase and return stuff, I need to find another tag name..

**Comment by JC5** [comment]
Let's see, three things to answer here.

Your last point is indeed very annoying, I suffer from the same problem. Firefly used to feature "transaction groups" but it was very unclear which transactions were grouped. Transactions need to be linked together somehow. Tags are technically useful, but really not user friendly in this context. Tags are not for grouping together like that. Rather, Firefly should offer to "link" the other transaction and don't bother with tags at all. That would mean you could link a deposit to a withdrawal and offset the withdrawal with it transparently. Maybe a split transaction could include both deposits and withdrawals. I'm not sure yet what would be the correct solution. I tend to use "abc 2016" or "abc March 2015" but it's not perfect yet.

Having said all that, the use case for balancing act is slightly different. Let's say your just going through your routine like a regular guy. You have budgets and categories and what-not. You've been saving up on your savings account for something expensive, and one day you buy it. This means two transactions will have to be created:

![screen shot 2016-12-23 at 16 29 26](https://cloud.githubusercontent.com/assets/5889984/21457111/04c04bc0-c92d-11e6-8367-a7b68dc6e344.png)

The expense does not fit any of your budgets. Nor is is something you should budget for. Instead, you don't give it a budget at all, but give it a category only. This means your budget report is messed up, because 1200,- is unaccounted for:

![screen shot 2016-12-23 at 16 30 20](https://cloud.githubusercontent.com/assets/5889984/21457124/28048560-c92d-11e6-9b04-9a9eac8550ea.png)

The balancing act is meant to remediate this. Give both the transfer and the expense the same tag, and make it a balancing act:

![screen shot 2016-12-23 at 16 31 16](https://cloud.githubusercontent.com/assets/5889984/21457147/428161b0-c92d-11e6-8ee3-908e264286bb.png)

The report is now corrected:

![screen shot 2016-12-23 at 16 31 48](https://cloud.githubusercontent.com/assets/5889984/21457157/54141d6e-c92d-11e6-90ff-d43e54dcd9f9.png)

Tadaa!

As a side note: the problem this causes is that expenses outside your budgets are effectively hidden so honestly this is not a solution to spending outside of your budgets. But it works pretty well to keep the budget reports clean.

As for the third point, the problem remains that a return would be income, and the original expense would not be changed, or compensated. This is something I have decided _not_ to solve. You're right that effectively you spent only 100,- and not 150,-. But _technically_, you spent 150,- and got 50,- back. So Firefly tries not to judge and stays as close to the "truth" as possible.

**Comment by zjean** [comment]
Thanks for your detailed response!
I really appreciate your efforts in answering my questions and continuously improving the software!
I mentioned the incorrect type of tag: in my example I used the advanced payment type of tag, but it doesn't matter for the shown end result.

I would like some sort of linking transactions together like you mention in the first paragraph.
I understand that Firefly tries to stay as close to the truth as possible, but something that might help in the meantime is to show the net spending in the category overview and reports.
In that case the chart in the category overview would show an extra bar containing expenses - income. That gives an easy overview to see the net result of the category.
I don't know if that's a lot of work to implement though.

**Comment by zjean** [comment]
Any updates / thoughts on this?

**Comment by JC5** [comment]
Nothing substantial yet. 

I'm thinking of adding the ability to link two accounts if they have the exact same name for #328. And linking transactions just like JIRA does it: a link type ("is return of", "returns money from"?) and two issues are linked.

Any "response" from FF (showing the net amount / net spending) would be limited to reports only.

**Comment by JC5** [comment]
With your permission, I'm closing this one in favor of this issue:

https://github.com/firefly-iii/firefly-iii/issues/616
