### ISSUE TITLE
[Suggestion] Carry over negative budgets from previous months

### ISSUE THREAD

**Issue by crameth** [firefly-iii/firefly-iii#5102]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/firefly-iii/about-firefly-iii/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been discussed before.

### Description

**Current Behavior**
- Negative (over-spent) budgets do not carry over to the next month, but positive (under-spent) budgets do.
- Not sure if this is the intended behavior.

**Suggested Behavior**
- Negative (over-spent) budgets should carry over to the next month too.

**Example**
Budget is $100 per month, with unspent budget from the previous month carrying over to the next (auto-budget set to "Add an amount every period"). 

`Jan`: Budget is $100 (initial). Spent $80, $20 left.
`Feb`: Budget is $20 (January) + $100 (auto-budget) = $120. Spent $60, $60 left.
`Mar`: Budget is $60 (February) + $100 (auto-budget) = $160. Spent $200, -$40 left.

**Current Behavior in April**
`Apr`: Budget is **$0** + $100 (auto-budget) = $100.

**Suggested Behavior in April**
`Apr`: Budget is **-$40** + $100 (auto-budget) = $60.

### Solution

The idea of having budgets is to discourage spending too much on a particular category. Unfortunately sometimes we can still overspend. It seems weird that budgets can accumulate positively over time, but get reset to 0 the next month if there are negative values involved.

This suggestion would help to:
* Encourage us to spend less in a budget in subsequent months after exceeding it
* Plan ahead for our budgets (e.g. saving up for "heavier" months)
* Discourage huge, 1-time impulsive purchases, as negative budgets will not be "forgotten"

The implementation for this should be straightforward, seeing that:
- Budgets can be carried forward (current behavior)
- Budgets can hold negative values as well

![Screenshot from 2021-09-21 04-27-55](https://user-images.githubusercontent.com/2794843/134070927-dbedf2f7-6182-4b22-ba31-9cf5757b8acd.png)

### What are alternatives?

I understand that budgets are just arbitrary values that can be changed on-the-fly any time we want. However from a _user perspective_, it is harder to factor in negative values from previous months (suggested behavior) than "resetting" our budgets to what we have in mind (current possible alternative).

Using my previous example, if my budget is $100 per month, "resetting" my budget to $100 manually if I overspend is much easier than calculating the budget I _should_ have if I overspent last month:

1. Check that I overspent, for example, -$42.84
2. Add that value to $100
3. Set the budget to the calculated value
4. Repeat the same for other budgets

**Comment by Extarys** [comment]
I didn't have the chance to test the "Add an amount every period" yet as I don't use Firefly as much as I would, but it is something I'm very interested in.

Having this feature would allow families with a more tight budget to make sure money is spent in their respective categories easily. To add a use case here: I put $120 per month in a Cats category. I now need to go to the vet and put $350 on my credit card for them. I do want to make sure I then don't spend too much money into toys and treats for a little while until the balance of that category is stable again.

**Comment by JC5** [comment]
Yes, budgets rollover so you can save money for expenses. That allows you to save up money for a big expense or save monthly for something bought once a year. This is something a lot of people use. It's basically a useful counter.

If you need to drop money from a budget for reason X, you have to to set up your next month(s) budget yourself. It could be spending less or spending zero, that's up to you. The automated budget static/rollover amount settings are a small convenience; most users change them after the system sets them on the 1st because of a specific month's unique bills. I do so, often in January.

I'm not interested in adding code the other way around. For me, overspending money is never static. Yes, I can overspend a budget but that doesn't mean bills won't keep coming in. I still need to buy food, even when I splurged on expensive takeout. 

Adding code that will automatically change the amount of next month's budget will not change the core activity: I have to reconsider next month's budget to accommodate the expenses of the past month. The system's static "money overspent = no budget for you" is just one of the solutions.

**Comment by crameth** [comment]
Hi @JC5.

> The automated budget static/rollover amount settings are a small convenience; most users change them after the system sets them on the 1st because of a specific month's unique bills. I do so, often in January.

> I'm not interested in adding code the other way around. 

> The system's static "money overspent = no budget for you" is just one of the solutions.

If I am understanding you correctly, whether the budget becomes negative or gets reset to 0 after the end of every month is insignificant, as it is just one of many solutions, and most users will change them manually at the start of every month anyway (including you). Adding this feature is considered extra effort on your part since most users will not need this.

I have reviewed your code here: https://github.com/firefly-iii/firefly-iii/blob/d55ff5735e23c51677a1741a461b130b74a6bb23/app/Jobs/CreateAutoBudgetLimits.php#L288

This feature can be implemented by removing the if block on line 288. There is no addition of code, only removal.

Will you accept a pull request to implement this feature with the considerations above?

**Comment by JC5** [comment]
But that would imply the system would set a budget for "-35" for example, right?

**Comment by crameth** [comment]
@JC5 Yes, that is correct.

Looking through the logic, it seems that the budget will reset to 0 only if the total amount is _still_ negative after adding the new month's budget in (through auto-budget). I also did a quick check to ensure that negative budgets are supported, and it seems that all is working well:

![Screenshot from 2021-09-27 13-48-34](https://user-images.githubusercontent.com/2794843/134851645-379e1d06-68d4-4af3-80f7-148eb8dbcac5.png)

Would it be okay to still suggest that, out of convenience and code simplicity, we leave negative budgets as-is (without the if block)? It is a minor change, but will greatly benefit users like me who would like their negative budgets to persist without affecting the behavior of most users, and might even serve as a reminder of how much we are overspending when reviewing our budgets at the start of every month.

**Comment by JC5** [comment]
I don't want to add negative budgets. It's a no from me.

**Comment by crameth** [comment]
Noted. It will be good for everybody else involved if you can be more succinct with your (personal) reasons for not implementing features/suggestions, instead of making it out to be additional complexity in implementation (which turned out to be false).

Closing this.

**Comment by JC5** [comment]
I'm sorry you feel that way.

It's absolutely true that you can overspend a budget and thus be "negative". But scheduling money for a budget, which is what we're talking about, is not something that you can do with negative amounts. In envelope based budgeting, you can't add a negative amount to an envelope. You can add either nothing, or a positive amount.

**Comment by Extarys** [comment]
I understand this is closed - No worries. But to refer your point @JC5 

> In envelope based budgeting, you can't add a negative amount to an envelope. You can add either nothing, or a positive amount.

I understand that - I used to prefer real life envelopes :smile: but if I take money from my pay that was supposed to go in envelope X and spent it on Y because of emergency, I would write on the back how much I overspend and instead of putting money into it I would deduct that amount each week.

Another simple example: My favourite clothing brand have a -50% sale and I only have 20$ left in the envelope for cloths. I spent 100$ on the sale. I usually put 20$ each month in that category, so it means for the next 4 weeks I won't buy cloths cause I have -80$ in cloths - except if I need socks because I have a hole in it which might be an emergency :laughing: 

@crameth Thanks, I might do the modification and test it - I'm afraid I'll forget it on the next update though. I might resolve to paper and pen for a chunk of my budgeting needs in that case.

**Comment by moritzj29** [comment]
I just started using firefly III and despite all the well-thought and complex features, this is a real limitation in functionality. so sad it won't be implemented. This issue contains numerous valid, real-life examples, even including a basic "envelope budget" analogy, so it appears to be a quite random choice to not implement this. But in the end, it's always up to the code owner...

Thanks for the hint on the position in the code! I will consider forking... (still less work than handle all negative budgets manually 🤣 )

Despite this, thanks for creating and maintaining such a great application!

**Comment by crameth** [comment]
https://www.reddit.com/r/FireflyIII/comments/njru5j/comment/h0p3lvr/?utm_source=share&utm_medium=web2x&context=3

**Comment by depahk** [comment]
I come here to ask the this implementation can be a chooise under User Preferences or single Budget.
If a budget end the period with negative value, given the possibility between: reset the value or continue by subtracting the value.

If @JC5 don't like negative budget you can store the value for next period and display 0 as value to show you that this period there aren't money to spend.

**Comment by crameth** [comment]
Hi @depahk, just a friendly reminder that you're responding on a closed issue. This is probably why you could not find this issue recently. You might want to start a new issue or re-open your existing one.
