### ISSUE TITLE
Few ideas regarding new transaction window

### ISSUE THREAD

**Issue by skibbipl** [firefly-iii/firefly-iii#535]
1. Make firefly remeber last used Asset Account (source). I often create transactions in bulk and I have to select last account every time.
2. Amount field could support some basic math transactions like 22+13, 34-11, 24/3, 15*3. When saving firefly will just calculate the value from the fomula. No need for support for parentheses - just basic math.
3. Date could have a date picker - for example by clicking on the calendar icon. Also pressing up/dow arrows on keyborad could change date +-1 day.
4. Category and tags could be automatically selected based on expense account. When I buy groceries at my local store the category and tags are always the same. Why entering them all the time?
 
And If we talk about transactions - duplicate existing transaction option would also be a nice feature.

**Comment by JC5** [comment]
Hey, 

Thanks for your ideas! Let me reply point by point.

1. If you use the "After storing, return here to create another one." option, Firefly should remember your previous choices. Otherwise, it won't. I think I can make Firefly _always_ remember the last used source account, but the checkbox is meant for these kinds of bulk-actions.
2. Supporting even basic math is a complicated thing to build. Either you execute user input without regards for the content, or you include an entire library to do parsing, validating, running, etc etc. It's going to be a lot of work for a small feature, so I'm not inclined to do it.
3. This is dependent on your browser. Chrome already has a datepicker built in. Other browsers do not. They should get one as well, I agree!
4. You can create rules to do this for you. Personally, I have a rule that puts transactions with description "Groceries" in the correct budget and category automatically.
5. It should be a notice of some sort, I think. And it should only detect _exact_ duplicates. Then, you could tell the user "Transaction X is exactly the same. You may have created two duplicate transactions". Part of this feature must also be that the "Submit" button will be disabled the moment you click it.. so you cannot click it twice.

**Comment by skibbipl** [comment]
1. Fair enough. If it works like this there is no need to extend it.
2. Yeah, this is tricky, but would make this app more "lazy" firendly :)
3. I hate chrome, and I don't plan to use it in nearest future. My default browser is firefox.
4. Yes, but I will have to create a new rule every time I create a new expense account. But as a workaround it will do the trick. Still I think default category and tags per expense account are more "lazy" friendly.
5. What I meant is an option to create a duplicate of selected transaction with changed amount and date. Just an option to create new transaction with pre-filled values form another transaction.

**Comment by skibbipl** [comment]
Regarding point 4. How to create a rule that will match Account 1 OR Account 2:
![obraz](https://cloud.githubusercontent.com/assets/4746858/21964743/5b609368-db52-11e6-8875-0583dad51947.png)
It seems that I have to create one rule per account which is quite cumbersome.

**Comment by JC5** [comment]
I think it works when you check the checkboxes. It's a "bug" I don't intend to fix.

**Comment by JC5** [comment]
Let's see:

1. Check.
2. I'm sorry, it's not going to be implemented.
3. Firefox now has a date dropdown for all date fields. Will be included in the next release.
4. Yes, but that implies that you only buy one thing at that store, namely groceries. Which may not be the case. Rules are more flexible and cover everybody's use case.
5. Ah, I see. That's very lazy indeed ;-). I'm not a fan honestly, it seems a lot of work just to be able to skip filling in three fields.

**Comment by skibbipl** [comment]
1. Sweet!
2. I'm not going to cry - however I'm too lazy to open calculator :)
3. In fact in recent nightly builds Mozilla provided native date picker. But it will take a while until it's enabled. So this change is very welcome.
4. Fair enough.
5. Please consider it. All budgeting apps that I used had this feature.

**Comment by JC5** [comment]
Mmm, I'll see what I can do about nr. 5. Peer pressure is a hell of a thing ;-).

**Comment by skibbipl** [comment]
And regarding suggestions - is it possible to create typeahead fields for rules (accounts, categories, tags etc.)? It's probably more complicated than point 5.
And don't feel too "pressurized" ;)

**Comment by JC5** [comment]
Oh that's a good idea and may not be too difficult. Only when changing trigger type perhaps. I'll look into it!

**Comment by skibbipl** [comment]
Another GUI suggestion: instead of creating simple checkboxes (for example on reports) use some kind multiselect field (for example http://formvalidation.io/examples/bootstrap-multiselect/). It will make UI less cluttered, especially if someone has 10 accounts and 30 categories.

**Comment by JC5** [comment]
Nice, absolutely.

**Comment by JC5** [comment]
I think I have everything now.

The "clone" feature is available on every transaction:
https://firefly-iii.nder.be/transactions/show/496

The multi-select thing is partially included in reports (and will be extended to other pages):
https://firefly-iii.nder.be/reports

Rules have autocomplete as suggested. It will change depending on which type of trigger / action you select:
https://firefly-iii.nder.be/rules/edit/1

Let me know what you think!

**Comment by skibbipl** [comment]
Clone works perfect!
Multiselect is awesome but I miss select all and invert selection option. If you wish -  tweak it a little bit more.
Autocomplete does not work for budgets and categories. And maybe add tags as trigger?

**Comment by JC5** [comment]
Can be fixed! I can't find the invert selection function but filtering + select all is certainly possible.

**Comment by JC5** [comment]
Alright I'm closing this on the assumption all of these things have been implemented. Please let me know if something is missing!

**Comment by davidglezz** [comment]
Supporting math in input fields could be done with the javascript eval() function before sending to the server, it seems easy.
