### ISSUE TITLE
docker: Error response from daemon: Could not get container for firefly-iii-db.

### ISSUE THREAD

**Issue by nwwy** [firefly-iii/firefly-iii#537]
After running 

    sudo docker build -t firefly-iii .

i tried to create a database with

    sudo docker run --name firefly-iii --link firefly-iii-db:db -v /data/firefly-iii/env:/var/www/firefly-iii/.env:ro firefly-iii

like described [here](https://firefly-iii.github.io/installation-guide-docker/)

But i just get this response

    docker: Error response from daemon: Could not get container for firefly-iii-db.
    See 'docker run --help'.

I get the same Error when i try to run

    docker run --name firefly-iii --link firefly-iii-db:db -v /data/firefly-iii/env:/var/www/firefly-iii/.env:ro firefly-iii

Here is my output of ``sudo docker images``

    REPOSITORY            TAG                 IMAGE ID            CREATED             SIZE
    firefly-iii           latest              60f6dbebac3e        26 minutes ago      586.4 MB
    php                   7-apache            62001e0da76d        3 weeks ago         385.7 MB
    hello-world           latest              c54a2cc56cbb        6 months ago        1.848 kB

Could you point me to the right direction here? Docker is still kind of new to me and running the commands from your installation guide didnt work after building the image.

Should i have build it with ``    sudo docker build -t firefly-iii-db .``?

**Comment by JC5** [comment]
The command assumes there is a database present. Try

`docker run --rm -it --link firefly-iii-db:db -v /data/firefly-iii/env:/var/www/firefly-iii/.env:ro firefly-iii php artisan migrate --seed --env=production`

**Comment by nwwy** [comment]
I already tried this and get the same Error:

    (ssh) flipp@phobos ‹ master › : ~/git/firefly-iii
    [0] % sudo docker run --rm -it --link firefly-iii-db:db -v /data/firefly-iii/env:/var/www/firefly-iii/.env:ro firefly-iii php artisan migrate --seed --env=production
    [sudo] Passwort für flipp:
    docker: Error response from daemon: Could not get container for firefly-iii-db.
    See 'docker run --help'.

**Comment by JC5** [comment]
Mmm, then I don't know. I didn't supply the Docker files, I know too little about them.

**Comment by nwwy** [comment]
Maybe @schoentoon knows a little bit more? But thanks for your help. =)

**Comment by JC5** [comment]
Yeah I feel guilty pinging him every time people have Docker questions I hope he doesn't mind :D

**Comment by schoentoon** [comment]
@JC5 Don't worry, you actually took the right time as I'm slowly returning to github atm..

This simply doesn't work because you don't have a container called firefly-iii-db that is running mysql. I've been meaning to write a simple how 'tutorial' on how to set that up, just haven't gotten to it yet..

**Comment by nwwy** [comment]
A complete Tutorial would be great, cause im a little bit lost here. I thought after building it would be enough to first run the database docker command and then the first one. But it already fails at the database command. 

How do u create a container running mysql called firefly-iii-db?
Thanks you for your answer @schoentoon :)

**Comment by schoentoon** [comment]
Simply creating a mysql container that would link properly would be done with.
`docker run --name firefly-iii-db mysql:latest`, although this won't be enough as you would have to run some of the migration scripts first to fill in the database and all.. I'll try to make that tutorial later tonight, I'll tag you in the pull request or whatever.

**Comment by JC5** [comment]
If you would be so kind, make the pull request in the develop branch.

**Comment by nwwy** [comment]
Thank you, this is very kind of you. 👍

**Comment by grojas7** [comment]
+1 for that tutorial

**Comment by JC5** [comment]
I got this in the mail from a user, what do you think?

If the command starts with docker, it is ran on the host. Otherwise, the command is in the container.

# docker run -itd --name firefly -p 0.0.0.0:80:80 --restart=always docker.io/fedora:latest /bin/bash

# docker exec -it firefly bash

# dnf update -y

# docker restart firefly

# docker exec -it firefly bash

# dnf install composer mariadb-server php php-bcmath php-fpm php-gd php-imap php-intl php-mbstring php-mcrypt php-mysqlnd php-pdo php-tidy php-xml php-zip git zip unzip vim -y

# mysql_install_db

# chown -R mysql /var/run/mariadb/

# chown -R mysql /var/lib/mysql/

# mysqld_safe &  # [1]

# mysql_secure_installation  # [2]

Yes, yes, yes, …

# mysql -u root -p  # [3]

> CREATE DATABASE firefly;

> CREATE USER firefly;

> GRANT ALL ON firefly.* TO `firefly`@`%` IDENTIFIED BY ‘<USER FIREFLY’S PASSWORD>’;

# cd /var/www/html && composer create-project grumpydictator/firefly-iii --no-dev --prefer-dist

# vim .env  # Here, change DB_DATABASE-firefly, DB_USERNAME, DB_PASSWORD

# cd firefly-iii; php artisan key:generate

# php artisan migrate --seed --env=production

# chmod -R a+w <FIREFLY DIR>  # probably hella insecure

# vim /etc/httpd/conf/httpd.conf
<Directory /var/www/html/firefly-iii/public>  # CHANGE THIS LINE TO MATCH FIREFLY DIR
       Options Indexes FollowSymLinks
       AllowOverride All
       Order allow,deny
       allow from all
</Directory>

# httpd &

For a docker container (NOT a full fedora system):
# echo ‘mysqld_safe &’ >> ~/.bashrc
# echo ‘httpd &’ >> ~/.bashrc


For non-docker container (full systemd) replace:
# systemctl enable httpd  # Instead of “echo ‘httpd &’ >> ~/.bashrc”
# systemctl restart httpd  # instead of “httpd &”
# systemctl enable mariadb  # Instead of “echo ‘mysqld_safe &’ >> ~/.bashrc”
# systemctl restart mariadb  # Instead of “mysqld_safe &”

Starting in a docker container
# mysqld_safe &
# httpd &                

[1]
As per https://mariadb.com/kb/en/mariadb/starting-and-stopping-mariadb-automatically/ this is recommended since systemd is not in the docker container
                 
[2]              
If error:
Enter current password for root (enter for none):
ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: YES)
Enter current password for root (enter for none):
Just press enter
      
[3]            
If error:
Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (111 "Connection refused")
Typically, mariadb is not started. Ensure you start it via mysqld_safe or systemctl restart mariadb

**Comment by schoentoon** [comment]
That's actually not the recommended way to do it. It's recommended to have a single application per container, in this case we're running mysql and the web server in the same one. I honestly just keep forgetting to make that damn tutorial.. Guess I'll actually set a reminder for once.

**Comment by JakeAM** [comment]
@schoentoon A tutorial would be much appreciated, I really want to run this using Docker!

**Comment by elamperti** [comment]
This project's container is not as straightforward as expected :cry: The dockerfile @schoentoon proposes may work in certain context (which also needs documentation), but I find it more bloated than it should for a docker container.

Perhaps we should change the approach to better fit this case (and I volunteer to work on this with you once we agree on _how_). What I think it must do:
  * Prepare the project to be run (using `composer` from inside the container)
  * Initialize the database (wherever it is)

Once that's working, a webserver container should be created (because this application needs extra php modules). It could be another container tailored for this purpose, so it stays lean (my `firefly-iii` container size is 588 MB, there's room for improvement there! :grin: ). So in the end there would be three -lighter- containers: one to initialize the project (which will be used just when it starts), the webserver and the database. This would also allow more customizable implementations and perhaps even using the containers for development.

The objective would be having a simple and lightweight setup for newcomers (as me), where getting Firefly-III running could be as simple as setting `.env` and doing `docker-compose up`. Of course we should update the documentation along with that! What do you think?

**Comment by schoentoon** [comment]
As I couldn't find a proper place for it inside the repository I'll just leave it over here instead..

First of all we need to boot up a container running the database, this can be done with a command that looks like the following.

```
docker run -d --name firefly-iii-db \
  -e MYSQL_DATABASE=firefly \
  -e MYSQL_USER=firefly \
  -e MYSQL_PASSWORD=firefly \
  -e MYSQL_RANDOM_ROOT_PASSWORD=yes \
  -v /data/:/var/lib/mysql \
  mysql:latest
```

This will create a mysql database, data stored in /data/ on the host with a username 'firefly' and a password 'firefly'. More documentation
on this can be found over here https://hub.docker.com/_/mysql/

Next up we need to create our env configuration as always, as a database we need to specify 'db' as a hostname with the associcated username and password.

Then we create a container with the actual application, this can be done like the following. Make sure to modify the paths, imagename and db container name accordingly.

```
docker run -d --name firefly-iii \
  --link firefly-iii-db:db \
  -v /path/to/our/env/env:/var/www/firefly-iii/.env:ro \
  -v /path/to/our/storage:/var/www/firefly-iii/storage:rw \
  imagename
```

After doing this it won't work just yet as we haven't initialized the database yet. In order to do this we have to execute artisan inside the application container.

```
docker exec -ti firefly-iii php artisan migrate:refresh --seed
```

After this it should work, in case you're getting 500 errors the permissions of /path/to/our/storage are probably incorrect. The owner should be set to '33' aka the www-data user inside the firefly-iii container..

**Comment by JC5** [comment]
PR is merged, and I will update the Docker guide in the installation today.

There will also be a sandstorm grain available but i have to get firefly reviewed first.

**Comment by JC5** [comment]
And let's not forget: thank you all for your time and efforts. I really appreciate the help.

👍 👍 👍

**Comment by JC5** [comment]
4.3.5 is live and should include all your hard work. :)
