### ISSUE TITLE
Set the opposing account in rules

### ISSUE THREAD

**Issue by b-ryan** [firefly-iii/firefly-iii#5530]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/firefly-iii/about-firefly-iii/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been discussed before.

### Description

Hey there,

First of all - I'm a big fan of this project. Thank you for your work!

I found https://github.com/firefly-iii/firefly-iii/issues/2054 so I am opening a duplicate issue. Since that issue is locked, I cannot comment or vote on it, so I'm opening this issue as a way to add my vote for the feature. Your response in that issue also didn't indicate to me you're completely opposed to this idea. 

I have a growing list of rules where the rule sets the category and the expense account. Right now there are about 25 rules, so duplicating all of them becomes unwieldy. For all of those rules, I am setting the "destination account," but really I want to set the "other account." 

You may still not want to do this because of keeping it simple for users, which I understand. Hopefully there's a way to add this without it being too complex. The data importer already has the concept of the "asset account" and the "opposing account" so this would be a similar experience. 

### Solution

Users would be able to create a rule action to set the opposing account, rather than only being able to set the source and destination accounts.

### What are alternatives?

I believe the only alternative is to duplicate the rules.

**Comment by JC5** [comment]
This will not be possible.

The reason is that there is no context to what the "opposing account" is. Opposing from what? When you're importing data there is always an "asset account" and where there is no asset account there is a "default asset account". So, transactions always have at least one asset account. From that point on, the opposing account is whatever account isn't that account. It could be an expense account (making it a withdrawal), it could be another asset account (making it a transfer) or it could be a revenue account (income). Since there is a definitive base account to work from this is easy and understandable.

When dealing with rules, the "opposing" account could be either the source or destination, depending on how you look at it. And there is no clear way to look at it. There is no "default account" to fall back on. There is of course an "asset account" in all transactions, but is that the "normal account" and is whatever is on the other side the "opposing account"? In that case, how will you deal with transfers? People may consider the opposing account to be themselves, when dealing with income.

I'm not sure what leads you to believe you have to duplicate rules. What is your use case?

**Comment by b-ryan** [comment]
Good point - that seems obvious in retrospect.

My use case is that I want to automatically handle refunds. For example, I have this rule

![image](https://user-images.githubusercontent.com/1183997/149198136-76dfa33f-b3c7-407b-bba8-073b2b3f6798.png)

I ran this rule and then realized I had refunds from Amazon. Initially I became worried that I just overwrote the destination asset account, but it looks like I am safe here. I found some code that seems to prevent setting the destination account for Deposits unless the account is an asset account.

So what I really want is:

- If it's a withdrawal, set the destination account to Amazon
- If it's a deposit, set the source account to Amazon

As far as I can tell, this requires 2 rules.

**Comment by JC5** [comment]
Yes, I'm afraid so.

**Comment by b-ryan** [comment]
I guess I will attempt to use the API to manage these rules then. Seems to me like I may end up with hundreds of them. I am curious how other people deal with this; it seems to me like it would be a typical use case.

**Comment by JC5** [comment]
I too have a lot of rules, although not hundreds. It's a trade-off between trying to automatically managing all my (past) transactions and doing some myself.

Especially when you auto-import, this comes with the territory.

**Comment by JC5** [comment]
One of the things on my list is to make the overview easier on the eyes in the new layout. But otherwise, I'm going to mark this as a "wontfix".
