### ISSUE TITLE
Reconcile Account - Request URI Too Long

### ISSUE THREAD

**Issue by pwsoftwaredesigns** [firefly-iii/firefly-iii#5651]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely me, not you](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

I attempted to reconcile one of my asset accounts across many (9) months.  When I click the "Store Reconciliation" button, nothing happens.  After looking in the console, I see the following error:

Failed to load resource: the server responded with a status of 414 (Request-URI Too Long)

It appears that each cleared transaction is added as a GET parameter.

### Expected behaviour

Perhaps this should be changed to a POST request instead?

### Debug information

See description

**Comment by JC5** [comment]
Thanks for letting me know. That is indeed something I plan to do for the new release; also because this is technically a security issue I need to fix. 

For now however, all I can suggest is not to try to reconcile 9(!) months in one go. Depending on the underlying webserver, 3 months may be the maximum.
