### ISSUE TITLE
Allow merging/converting 2 transactions into a single transfer

### ISSUE THREAD

**Issue by GeorgeBark** [firefly-iii/firefly-iii#5675]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/firefly-iii/about-firefly-iii/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been discussed before.

### Description

First of all, thank you for your amazing work.

I am having the same issue as #1863: 

>  I have two accounts. One is my everyday account while the other is my savings account; both are with the same bank.
> The csv I receive looks like this:
> Date,Account,Description,Credit,Debit
> d/m/Y,111111,text,450,
> d,m,Y,222222,text,,-450

However, it is not limited to the same bank, it could be between different banks.

### Solution

I have been doing some research and there are already similar issues: #4232 #4017 and #1845. 

I totally understand why you have decided to dismiss their requests due to complexity. However, I would like to revisit the issue with a much narrower scenario:

When in a list of transactions, if 2 are selected, enable an action to "merge into transfer". (if one or more than 2 are selected then the option is disabled or not there at all).

To prevent opening Pandora's box and allowing for complex merging, check that:

1. One transaction is a withdrawal, the other is a deposit.
2. The **transactions have the same amount**, oposite sign (they cancel each other out)

If both true, allow to continue. Then:
1. Get the withdrawal as the main transaction
2. Get the account of the deposit
3. Use the same code you have in [ConvertToTransfer.php](https://github.com/firefly-iii/firefly-iii/blob/4b1eaddfc223608edfff523703e810a90ec8bdeb/app/TransactionRules/Actions/ConvertToTransfer.php) to convert the transaction to a transfer with the account id of step 2
4. Remove the deposit transaction

### Additional context

I am not a PHP developer but I would be happy to help with pseudo-code if you wish.

Many thanks!

**Comment by JC5** [comment]
I'm not a fan of this idea.

Firstly, this is the kind of system magic that makes it pretty unclear when options are available, when they're hidden, what they do. What does it mean to merge a transfer? When is it available? Why can't I merge transactions with different amounts? Why can't I have it make two splits instead of one single transfer? Why can't I merge two deposits, what's the difference? A narrow use case opens the door for a wide use case, although that's not the problem per se.

Most importantly, this is a use case meant for users who import data but are unable or incapable of importing transactions in such a way that Firefly III recognizes the opposite account, and creates a transfer automatically. Not that many people have that problem.

I appreciate what's going on here but I'd much rather script something against the API that would fix this for you. 

Ultimately, the problem is cleaning and fixing transactions. Systems like YNAB, Mint and others will automatically clean (most) transactions and fix stuff like this. But since I don't have the capability to offer the same thing for CSV imports or basic imports I have to think of something else.

Adding buttons to magically merge some transactions isn't the solution. I think the solution has to be part of the data importer, but I'm not sure what it can be.

**Comment by GeorgeBark** [comment]
Thanks for the very quick reply.

I see your point and I think I agree with you. In the end this is an importer issue and not really an expense management issue. It should indeed be somehow in the importer but I cannot see either how to implement it unless some "intelligence" is applied, it may not be worth it.

About this:
> I appreciate what's going on here but I'd much rather script something against the API that would fix this for you.

Instead of a script, I wouldn't dare asking you to invest time on my problem, would it be possible to add an API to convert to transfer a given transaction id? I tried with the PUT on the transaction but it doesn't seem to allow changing the "type". If either the PUT accepts changing the type or if a new endpoint is available, I could script it as you mentioned.

Thanks in advance!

**Comment by JC5** [comment]
Yes, this is on my list to add. :+1:

**Comment by GeorgeBark** [comment]
Great, looking forward to it! Many thanks!

**Comment by Inrego** [comment]
I too have the need to be able to merge transactions into a single transfer. I use Nordigen to import my transactions into Firefly, but since I often use different descriptions on source/destination accounts when I transfer, Firefly does not pick this up.
Sure, a way to automate it would be great, but for starters I'm looking for a way how I can manually fix these inconsistencies?

**Comment by WillScott73** [comment]
I third this request

**Comment by JC5** [comment]
https://github.com/firefly-iii/firefly-iii/issues/6304
