### ISSUE TITLE
Add option to create new Account Role

### ISSUE THREAD

**Issue by csankhala** [firefly-iii/firefly-iii#5816]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/firefly-iii/about-firefly-iii/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been discussed before.

### Description

- I would like firefly allows to create new account role like **investment** which can be used to create investment asset accounts like PPF, EPF, Mutual Fund

### Solution

Add option in preference to create new account role

### What are alternatives?

Currently I am using all investment account as saving account

### Additional context

People can have investment accounts like PPF/Mutual Fund which are not fall in saving account category

**Comment by JC5** [comment]
I have it on my list to expand the possibilities that you can choose from. I am not going to add an interface to manage these yourself. I don't want to give people the impression that Firefly III supports investment accounts (it doesn't) so investment accounts will probably not make the list.

**Comment by highaltidude** [comment]
Just installed 2 days ago, loving the project so thank you for the hard work! 

I do think that just adding an option of "Investment Account" or "Brokerage Account" would be great. I don't expect firefly to track my stocks, but just being able to define that role would be very helpful. Users can manually adjust at their own pace IMO. Since Firefly tracks net worth and a lot of people's net worth is in their investment accounts it would be helpful. 

My 2 cents, thanks!
