### ISSUE TITLE
LDAP filter

### ISSUE THREAD

**Issue by gkl1368** [firefly-iii/firefly-iii#5851]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [ ] ... there are no open or closed issues that are related to my problem
- [ ] ... it's [definitely me, not you](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

I also meet this problem on 5.6.16, the ldap auth only worked with no group filter in base dn like "dc=domain,dc=local". If i add group filter like "cn=firefly-group,cn=groups,dc=domain,dc=local", it always show " Login attempt failed. "

### Expected behaviour

LDAP login correct

### Debug information

[2021-10-04 10:50:08] local.WARNING: Login attempt failed.
[2021-10-04T10:50:08.535860+02:00] local.INFO: AUDIT: Login failed. Attempt for user "" failed.

**Comment by JC5** [comment]
I will probably drop ldap support in favor of generic authentication proxy support.

**Comment by nebulade** [comment]
Hi, since with version 5.7.0 the LDAP support is now dropped, it would be great to know if and how the generic authentication proxy could support LDAP. I am trying to package the new version for Cloudron and since the app is integrated with LDAP on Cloudron side, we are currently looking for a migration path to the mentioned alternative support. I am no Laravel expert, so any pointers on how to do this would be great. Thanks!

**Comment by JC5** [comment]
I don't believe it does, sorry.

**Comment by nebulade** [comment]
Ok, thanks for letting us know. So we have dropped the LDAP support in our app package as well and it appears that all users just become local users, which then need to reset their passwords.
