### ISSUE TITLE
Transaction with multiple source accounts

### ISSUE THREAD

**Issue by skibbipl** [firefly-iii/firefly-iii#603]
Here is the scenario:
I have a PayPal balance - 10$. Also I have a credit card connected with PayPal. I want to buy something for 20$. PayPal proposes to pay it - 10$ from PP balance and 10$ from CC. How to track this king of transactions in firefly?

**Comment by JC5** [comment]
There is no way to process such a thing. I would suggest a transfer from your CC to Paypal and then the expense (withdrawal).

Unfortunately withdrawals with multiple sources are not supported.

**Comment by skibbipl** [comment]
It seems I need to use two separate transactions. I wonder how accountants deal with such transactions?

**Comment by JC5** [comment]
In a double-entry bookkeeping system, it's not possible. Money always moves from A to B. Since Paypal pays the vendor, the transaction moves from Paypal > Vendor.

To enable this transaction, there is a second transaction: Creditcard > Paypal.

Joined together this could be displayed a transaction with two sources: Creditcard/Paypal > Vendor. But actually there are two transactions.

What Firefly would need (already needs, but doesn't have) is a way of linking transactions. Like [JIRA can do with issues](https://confluence.atlassian.com/jirasoftwarecloud/linking-issues-776997756.html). Tags are currently doing this but they don't really work well.

It's something I'm thinking about!

**Comment by sameep22** [comment]
Has there been any update in this issue. My use case is that I get paid with food coupons that I can use at restaurants and supermarkets. But they usually do not cover the entire amount, so I have to pay using another card/cash. It gets even more complicated when the transaction is one at the supermarket, where the expense may be split in multiple categories and the payment could also be done using multiple accounts.

**Comment by JC5** [comment]
Sorry, it will not be possible to record these coupons in Firefly III. I suggest you subtract the amount of the coupons from the total amount and store only that.
