### ISSUE TITLE
Duplicate transaction check fields can be changed

### ISSUE THREAD

**Issue by howlzj** [firefly-iii/firefly-iii#6033]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/firefly-iii/about-firefly-iii/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been discussed before.

### Description

I would like to select/de-select which fields are used for duplicate checking when using the API.

My bank provides rich data (e.g category, bill name, tags, etc) but these are often updated after the transaction. When imported (POST /transactions) they are sometimes treated as non-duplicate transactions.

### Solution

These four behaviours would be useful (1 would address this, 2-4 would be nice to have).

1. API endpoint to control which fields are used for calculating transaction hash.
2. Return the duplicate transaction Id in response payload if a duplicate import is detected (to add some logic on the importer side like using PUT update instead).
3. Add a user defined field like ‘batch job number’ the importer could set so an entire bad import could quickly be fully purged. As tag is used for duplicate checking, I can’t use that.
4. Duplicate checking currently has a minor bug that data type is also considered for duplicate (e.g sending amount as str and int seem to be treated as unique).

### What are alternatives?

Import the bare minimum of fields using POST /transactions (to maximise chance of duplicate has being generated and detected) and then use PUT /transaction/{id} to enrich?

**Comment by JC5** [comment]
I'm not going to build this. Feel free to script something yourself though. 

There is something already in place you can use. The [search](https://docs.firefly-iii.org/firefly-iii/pages-and-features/search/) ([API](https://api-docs.firefly-iii.org/#/search/searchTransactions)). There's a great number of fields and things you can search on, and if it returns more than one transaction, don't import. But this is something you have to build yourself for precisely the same reason: I can't solve everybody's unique duplicate checking challenges.

The default transaction endpoint does a very simple but thorough job of duplicate selection, which is why nr 4 in your list is not a bug: a hash is generated over your input. Nothing is changed, converted, or edited. If you change data types, that's on you.

The [data importer](https://github.com/firefly-iii/data-importer/) can do a little bit more. You can assign a data field as the "identifier" (and also indicate in which Firefly III field it is expected to be stored). It will search for the exact value of that data field and stop the import if the identifier exists already. 

In you case, I suggest a similar if-else that searches for your bank's transaction identifier's in your Firefly III database. Something like `external_id_is:"something"`. If it exists, PUT. If it doesn't, POST.

**Comment by howlzj** [comment]
Makes sense. So perhaps a strategy using the existing APIs would be:

- Search API based on sufficiently broad/narrow scope to catch duplicates (e.g. compare date, amount only).
- Some logic or prompt to ask the user if the transaction is actually the same (e.g. create anyway, update, skip).
- Some logic to skip user input step if every field is an exact match (can't see in the docs how the hash is created).
- Use either POST or PUT depending on the result.

Effectively this would take all the logic away from import hash and onto the importer (leave error_if_duplicate_hash as false).
