### ISSUE TITLE
Split transaction - multiple revenue / expense accounts

### ISSUE THREAD

**Issue by ragnarkarlsson** [firefly-iii/firefly-iii#613]
I have a direct debit which pays a deposit into an account, but its an aggregation of several revenue accounts I'd like to track separately. At the moment I can't see a way to set a source account per split item, only category. Is this feasible? 

I could imagine also wanting to split withdrawals to multiple expense accounts as well. eg I have an aggregated withdrawal for both my electricity and gas supply.

**Comment by JC5** [comment]
I'm not sure if I get what you mean, because both of these things are possible.

A split deposit into one of your asset accounts (income) always has one destination account: the asset account. But it can have multiple revenue accounts.

A split withdrawal from one of your asset accounts (an expense) always has one account from which you pay, but it can have multiple destinations (expense accounts).

**Comment by ragnarkarlsson** [comment]
Ignore me, I was clearly tired and UI blind! :tired_face: I edited the description field and not the source field and somehow became totally oblivious to its existence!

**Comment by JC5** [comment]
It happens to the best of us ;)
