### ISSUE TITLE
Nested categories

### ISSUE THREAD

**Issue by coencoppens** [firefly-iii/firefly-iii#626]
Hi,

I'm in the configuration process of a fresh setup and I feel the urge to create nested categories, like so:
* Automobile
  * Accessories
  * Insurance
  * Fuel
  * Maintenance
  * Parking
  * Other
* Clothing
  * Clothes
  * Accessories
  * Shoes
  * Other

It appears this currently isn't possible to create.

* Should I be wanting to add all these categories or is there an alternative?
* Is it a feature you want to consider implementing?

Thanks in advance,
Coen

**Comment by JC5** [comment]
Hi Coen,

In the past, I've considered this but after due consideration: it's not going to be a feature. It's been discussed [before](https://github.com/firefly-iii/firefly-iii/issues/163) but it's a long read.

I've discovered that you rarely gain any _extra_ clarity when you add sub-categories. It helps, but it doesn't help that much. My personal database contains about four and a half years worth of transactions and sub-categories have always been more of an administrative burden than they gave me critical insight into my finances.

Every other financial system out there (literally everyone) has sub-categories. But financial insight isn't gained from having five subcategories for groceries. That's not where the "profit" is. 

If you wish to distinguish further, I suggest adding tags to transactions. You can use things like "insurance" or "maintenance" and have Firefly III report on those tags.

**Comment by coencoppens** [comment]
Hi @JC5,

Thanks for the quick reply. I think your reasoning definitely makes sense: it's something I shouldn't be wanting.

**Comment by tomazsustar** [comment]
Hi, 

first of all thank you for a great product. I have just installed it recently and it is great. I might post a few more comments here and there.

I have read everything  about this issue. However I would still prefer having nested categories than not. For two reasons. It is much simpler to enter just a category than editing another input field and find the correct tag.  And you get a tree structure of you transactions automatically. Tags are good in general, because you can assign any tag anywhere, but it is much more difficult to maintain any tree structure of my transactions. I find it very logical to have nested categories.

**Comment by tomazsustar** [comment]
However I agree, that this is quite complicated to implement from the developers point of view and is better to focus on other improvements.

**Comment by JC5** [comment]
I simply don't see the value of adding more granularity. It'll tell you nothing you didn't already know.
