### ISSUE TITLE
Categories graph displays incorrect labels

### ISSUE THREAD

**Issue by skibbipl** [firefly-iii/firefly-iii#648]
I have a category that is not very often used in transactions. On category details `https://firefly/categories/show/17` graph the labels are displayed for incorrect period of time - february (it was the last time I used the category) instead of may.
![obraz](https://cloud.githubusercontent.com/assets/4746858/26282247/ab5df158-3e0d-11e7-8dbe-8f9872bf083a.png)

**Comment by JC5** [comment]
Yes, it does this because it jumps back (with a max of three periods) to a period where there were transactions. So, when May is empty it starts jumping back until February (3x) where it "stops". 

I built this as an escape for empty views but it's kind of confusing when there really is nothing there. I'll think of something to make this look better.

Apologies for the delay btw, I had a busy week.

**Comment by JC5** [comment]
I've added an info-message explaining what happens and I've fixed a chart that didn't jump back (account page).

![screen shot 2017-07-29 at 14 27 11](https://user-images.githubusercontent.com/5889984/28744845-0c1d3a70-746a-11e7-8421-6bc8c35c280a.png)
