### ISSUE TITLE
Importer uses wrong method of assigning currency info

### ISSUE THREAD

**Issue by JC5** [firefly-iii/firefly-iii#660]
See file ImportStorage.php line 295

**Comment by JC5** [comment]
ImportValidator.php:77
ImportValidator.php:384

**Comment by tomazsustar** [comment]
Does this has to do with the fact that the imports stopped working?

Below the error from the import log, that comes for every transaction...

`[2017-06-09 06:31:16] production.ERROR: Could not create transaction 1. ["The transaction currency id field is required."] []
[2017-06-09 06:31:16] production.ERROR: Could not create transaction 1. ["The transaction currency id field is required."] []
[2017-06-09 06:31:16] production.ERROR: Cannot import row 3, because an error occured when storing data. [] []`

**Comment by JC5** [comment]
Quite possibly so. I'll get right on it!

**Comment by JC5** [comment]
A new release is on it's way so I'm closing this issue :)
