### ISSUE TITLE
Auto-refresh Nordigen contract

### ISSUE THREAD

**Issue by JC5** [firefly-iii/firefly-iii#6770]
- [ ] Detect expired Nordigen contract.
- [ ] Contact Nordigen about renewal
- [ ] Redirect user
- [ ] Update local configuration to grab new requisition ID.
- [ ] Continue.

**Comment by diamant-x** [comment]
Looking forward for this enhancement.
At least only implementing the first step: detecting expired contract (which happens every 3 months) and showing that in the fidi browser instead of a generic "error 500 server error" would already be beneficial. Right now I need to go into the docker logs to understand the error while instead it would just be "aha, it's time to run the link process" without leaving FiDi. :)

Thanks for the efforts so far!

**Comment by alekslyse** [comment]
Any update on this? I was under impression this was not possible cause the need with bank id to renew, but if its possible it would be great. As of now, hopefully its possible to get an email when its expired
