### ISSUE TITLE
Show total balance on dashboard

### ISSUE THREAD

**Issue by simonsmiley** [firefly-iii/firefly-iii#684]
I just wanted to say: awesome webapp!

Is there any reason why the current total balance of all accounts is not shown on the dashboard? If you don't have anything against it, I would like to add it to the very top next to the money in/out  bills topay/payed. 
I haven't done real php development yet, but I think that's a small enough change that I would be able to implement :-)

**Comment by JC5** [comment]
Thanks!

There is no reason why it isn't shown, and I welcome you to build it. 👍 

But remember that you need two boxes to make sure they are symmetrical. So total balance could do it, but you'll need another box as well. Any ideas?

**Comment by simonsmiley** [comment]
Hmm. I only managed to come up with stuff that's not that interesting:
* Current balance - outstanding bills
* Anything about the "cash" (btw. why are there no cash accounts, isn't this also something interesting to track?)
* Change in balance from last week/month/year

**Comment by simonsmiley** [comment]
I just had an idea.
What about changing the graph so it uses a stacked area chart?  
I think it would make the chart more readable and provide the total balance (which could be added to the header "Your account")

**Comment by JC5** [comment]
The sum of in/out could be interesting. I'll play around with it.

As for the cash accounts, it's already possible to track cash. It's just that it would be another "asset account". If you remove money from your account (an ATM withdrawal) or deposit money using an ATM account (possible in some countries) just leave the Revenue/Deposit account empty.

The stacked chart won't happen because then you couldn't see clearly what an individual account is doing.

**Comment by simonsmiley** [comment]
about the charts: could there be both? maybe so that you can toggle or an option in the settings?

**Comment by JC5** [comment]
No, that leads to option creep.
