### ISSUE TITLE
Import fails if there is no mapping to be done

### ISSUE THREAD

**Issue by tomazsustar** [firefly-iii/firefly-iii#693]
If one only selects for example only date, amount and description the import fails at generating configuration. 

If one runs the import with an old configuration by using artisan commands it fineshes successfully.

**Comment by JC5** [comment]
I've tested this, and it seems to be fixed in the current development release. Once I select a date, an amount and a description the system continues. The import configuration is also correct.

I think this particular bug was fixed "accidentally" when fixing something else. I hope to release 4.6.2 this weekend and then we can verify this.

**Comment by tomazsustar** [comment]
OK great. Just for reference I was using 4.6.1.
