### ISSUE TITLE
It is not possible to translate some strings

### ISSUE THREAD

**Issue by Nik-vr** [firefly-iii/firefly-iii#700]
I can not translate some strings in the interface. In particular, the line "Initial balance for", and also Help.
In the "Help" window, a new line "This help text is in English. It is not yet available in your language" is added every time you open this window.

![12](https://user-images.githubusercontent.com/520760/28152437-2d6a8b4c-67a9-11e7-8d8d-53eaa1936ab2.jpg)

PS. Now I translate Firefly in Russian. I translate slowly, because At the same time I study the possibilities of the system (to translate correctly, because some English-language terms do not have complete analogs in Russian with respect to accounting for finance).

**Comment by JC5** [comment]
Some strings are still hard-coded, yes. I have the bad habit of writing in English first and then replacing these with translation-instructions. Thank you for mentioning this particular item, I will change it in the next release and it will become available in Crowdin.

I will also make sure that the text is not repeated, as you say.

As for the help pages themselves, there is a project on CrowdIn to translate them: 

https://crowdin.com/project/firefly-iii-help

However, I must ask you not to start with those, because they are far from complete. Shall I notify you when the help pages have been improved, so you could help translating?

**Comment by JC5** [comment]
Of course, I forget the most important thing: I want to thank you for your translation work. I know how tricky it can be and how much time it takes, and I really appreciate it!

**Comment by Nik-vr** [comment]
I will join the translation to CrowdIn. But now I do not see the Russian language there.

Ok, I will not translate Help. Please notify me when the Help is ready for translation.

**Comment by JC5** [comment]
I have enabled Russian, I forgot to do so.

To set up the config, could you tell me what "Russian" is in Russian? It is used for this list:

![image](https://user-images.githubusercontent.com/5889984/28158382-d1363aa4-67b9-11e7-887f-ad3d1b45cb8e.png)

**Comment by Nik-vr** [comment]
Thank! I begin work!

"Русский (Russian)"
