### ISSUE TITLE
Import error transactions.0.foreign_amount

### ISSUE THREAD

**Issue by mayzyo** [firefly-iii/firefly-iii#7189]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

Importing csv with a `Dest Account` now results in the following error:
`Line #5: transactions.0.foreign_amount: This field requires a number (original value: "(not found)")`

I have imported the exact same csv earlier today on older version of fireflyiii with no issue. After upgrading to 6.0.1, this occurred. After reverting back to 6.0.0, the issue no longer occur.

<img width="565" alt="Screenshot 2023-03-11 134812" src="https://user-images.githubusercontent.com/25147960/224463820-e867a06f-1695-438e-a8a9-73543130bc7c.png">

My role definition looks like this:
<img width="739" alt="Screenshot 2023-03-11 133826" src="https://user-images.githubusercontent.com/25147960/224463984-5a3b912a-3b4f-4273-8d7c-cea99ccd199d.png">

I apologise for not doing any additional testing per the guidelines to narrow the issue down further, as using 6.0.0 does work for me now so I am moving on.

### Debug information

I didn't know to call `/debug` when I encountered the issue unfortunately.

### Additional info

I am running in kubernetes using the docker image on docker hub. Both firefly and importer are using the `latest` tag when I encountered this issue.

Also, the time range in the top right corner of the dashboard isn't working for me in 6.0.1 but does work now in 6.0.0.

**Comment by JC5** [comment]
Could you share your config file and some example lines?

**Comment by mayzyo** [comment]
@JC5 Here you are
[files.zip](https://github.com/firefly-iii/firefly-iii/files/10947647/files.zip)

**Comment by JC5** [comment]
I think I found it and will check it out. Thanks for reporting!

**Comment by rounakdatta** [comment]
I too encountered a similar error on v6.0.1 - when trying to creating a Transfer transaction. Behaviour:
- I try to create a Transfer
- The foreign currency dropdown is null at the moment (which is what I'd want)
![image](https://user-images.githubusercontent.com/20105014/224466947-0f4b4948-d905-4d0c-998c-7ba496dedd69.png)
- I select the Source and Destination accounts, which sets the foreign currency box to be same as my default currency
![image](https://user-images.githubusercontent.com/20105014/224466975-803d3ab5-7344-47ff-ace3-a0020d6543ec.png)
- Due to this, I have to re-enter the amount in the foreign currency text box, otherwise the transaction creation fails.

Thanks!

**Comment by JC5** [comment]
Thanks for the extra info. This issue should be fixed in the next release. If you're curious if it works for you, please use the `develop` branch to validate my fix.
