### ISSUE TITLE
Multiple asset account mapping

### ISSUE THREAD

**Issue by sprucify** [firefly-iii/firefly-iii#721]
When I create one ING asset account and import 4 years of data the current balance is correct.
So I created a second asset account (my business one) that has a lot of transaction flowing back and forth to the first created one.

After importing 4 years of data for the second asset account.
It's current balance is correct, but the current balance of the first asset account is way off.

It probably has double transactions now?

**Comment by JC5** [comment]
Yes, which the import function should have detected but clearly hasn't.

Can you find one or two examples?

**Comment by JC5** [comment]
Wait, did you import both accounts in one go, so in one file? Or multiple files?

**Comment by sprucify** [comment]
Multiple separated csv files.
No reason that an import an import should manipulate transactions om another asset account right?
The transfer transactions between the accounts are detected flawlessly btw

**Comment by JC5** [comment]
It does not touch other transactions, but it is not capable of detecting A<>B, B<>A transactions as being the same in the span of two or more files.

**Comment by sprucify** [comment]
I think the script is not able to distinguish between source and destination IBAN numbers?
Because that would solve the detection of  A<>B, B<>A transactions.

Another option is to add a asset account selection dropdown on the import wizard.
Since in most cases the imported file is only from one asset account.

**Comment by JC5** [comment]
The entire CSV line is remembered and will not be imported twice. So importing the same file twice won't work.

However, FF3 does not judge, and it's perfectly possible to have two transactions on the same day, with the same description, amount and involved accounts. 

Firefly-iii doesn't register it because it doesn't care. Question is, should it? I'll see what I can do this weekend.

**Comment by sprucify** [comment]
I see. So you have some sort of SHA hashing going on per transaction?
In that case it should be possible to distinguish source and destination accounts.

I have also noticed that ING has displayed the name of my second asset account differently over time.
As in sometimes the name in the CSV lines is in capital letters.

**Comment by JC5** [comment]
Yes, the entire line is hashed. This makes sure duplicate lines are not imported.

I'm hesitating to create (another) hash routine or to change the current one. But "duplicate detection" is not a bad feature per se. It requires a few overhauls is all.

**Comment by JC5** [comment]
Duplicate detection has been implemented.

**Comment by sprucify** [comment]
Perfect, thanks a lot.
I will spin up a docker-compose soon then.
Keep up the good work

**Comment by JC5** [comment]
I believe so but some people have reported problems with the current import routine. It should be fixed in the next release which I'm planning to release this weekend. I shall close this issue then, and you can test it at your leisure. 

Open a new ticket or reopen this one if you run into problems. Just wait for the email of me closing this one, and you can try it.
