### ISSUE TITLE
Credit Card Virtual Balance

### ISSUE THREAD

**Issue by kristophr** [firefly-iii/firefly-iii#735]
In your help screen - it says for Credit Cards- use the virtual balance as your credit limit.  However, when I put a value as noted on your help page - it adds it to my total balance.

For instance I have a balance of $500 on this card.  In Virtual Balance I put $1000 as my credit limit (I've tried $1000 and -$1000).  When I save it - it shows $1500 as my balance (or -$500 if I put -$1000).

Not sure if I'm doing something wrong? or if this is intended purpose.

**Comment by kristophr** [comment]
I derped.  Didn't realize I had to put my opening balance as a negative.  Sorry!

**Comment by kristophr** [comment]
After further testing - Its still not working right - unless I am simply not understanding how it works.  I put my "balance" in as a negative.  I put the Virtual Balance as a positive and it shows my outstanding balance as a sum of the two - which isn't correct.

**Comment by JC5** [comment]
It may be buggy indeed, I haven't looked at it for some time. The idea is that you put a positive number in. When your CC limit is 1000, you would put in 1000. That way, when you spent 100 your balance would not be -100 but 900. 

Having said that, I've stopped using it because personally I feel I'm out 100 and not that I still have 900. 

I'll check it out asap!

**Comment by JC5** [comment]
I found one spot where the virtual balance didn't show, but generally speaking it seems to be working. When you have a CC with a limit of $1000 you can give it a virtual balance of +1000. FF will presume you have another 1000 in your accounts.

**Comment by kristophr** [comment]
Ok, I get it.  I just need to think of "Current Balance' as "Available Balance" - that makes more sense now.  Sorry!
