### ISSUE TITLE
Dashboard charts are not currency-aware

### ISSUE THREAD

**Issue by skibbipl** [firefly-iii/firefly-iii#740]
Firefly 4.6.3.1
It seems that dashboard charts are not currency-aware. No matter what currency you use it will always display charts in default currency with ratio 1:1. I guess this is a complicated issue, but graphs that can't convert currencies are not very accurate. I think graphs should display data in default currency, but at least use some predefined currency conversion ratios to make the values more accurate.

**Comment by JC5** [comment]
Yes, I know. An alternative is to be able to show 1 other currency, in the other y-axis. I'll think of something, but it won't be visible yet in the next release I fear.

**Comment by JC5** [comment]
Looking at the code, it depends on what you want.

Currently, the chart works pretty well because each line is correct in it's own context and the only thing broken is the fact that the ticks will always fall back to the default currency.

Here, the ticks are in EUR (default) while one account is GBP. The ticks should not display currency information.

![screen shot 2017-08-19 at 17 56 38](https://user-images.githubusercontent.com/5889984/29488276-c6c1681c-8507-11e7-998f-6d57ed518c0f.png)

So for a quick overview this is the most accurate way of displaying things. Both accounts are "on their own".

If you would like to _compare_ both accounts in one unified currency (ie EUR) then the chart is wrong. But running FF3 with multiple currencies, I'm not sure how that would be done without sacrificing accuracy. Each transaction would have to be converted to the default currency no matter what, which seems counter-intuitive.

What do you think?

**Comment by skibbipl** [comment]
I think that for "Your accounts" chart you don't need to use exchange ratios. Let every account has it's own currency. But what about "Budgets and spending", "Categories" and "Expense accounts"? What if I buy something from category A in two different currencies? How should the bar look like? Maybe there should be a separate bar for each currency?

**Comment by JC5** [comment]
Everything except the budget chart is now multi-currency. I'm going to write something down to fix that because it requires database changes. So If I hear nothing, I'm going to let the bot close this.

Oh, all other charts are on the list too, so slowly but surely, this is being picked up by me.

Sounds OK?

**Comment by skibbipl** [comment]
Yes, fair enough. I'm still back few versions so I need to upgrade my instance.
