### ISSUE TITLE
Suggestion: Set current date for cloned transactions

### ISSUE THREAD

**Issue by skibbipl** [firefly-iii/firefly-iii#770]
Every time I have to remember to set correct date for cloned transaction. I guess this enhancement would save a few clicks.

**Comment by JC5** [comment]
Good idea, done!

**Comment by JC5** [comment]
Closed to clear the list.

**Comment by johanessurya** [comment]
I think it would be good to keep the date with original transaction. I think it would more flexible if you add some button "now" or other quick link to set the date.

Another Suggestion: Right now, date can't be copy pasted. It would helping user so much if we can copy paste the date from other source. Perhaps, not all date format in all country use MM/DD/YYYY, so I could just change to that format and copy paste it to firefly.

**[Little bit about my story] Here is why I tough this one would be helpful:**
I want to transfer my excel of transaction in firefly. I don't want to import it. Hopefully, I know how to use Firefly better. The pain thing I do(I think), typing the date over and over again. My transaction is 6 months ago, so it more faster to type it rather than click down arrow an pick the date.
