### ISSUE TITLE
Display issue on budget page with weekly auto budget

### ISSUE THREAD

**Issue by dreautall** [firefly-iii/firefly-iii#7819]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

This is an odd one. When creating a budget with a weekly auto budget, everything looks fine:
![image](https://github.com/firefly-iii/firefly-iii/assets/109872040/20e7ca6d-9b3e-4e36-a90e-498bc2e9e53c)

However, once you add a transaction, the amount in "Left (day)" is wrong and instead shows the current expenses:
![image](https://github.com/firefly-iii/firefly-iii/assets/109872040/2fd08fce-02a9-4e74-b6ce-16567c49a278)

This does not happen to monthly fixed budgets. It also does not affect the budget detail view page, where all values appear correct:

![image](https://github.com/firefly-iii/firefly-iii/assets/109872040/bff6d9c6-3c6a-4263-beca-2e4cf3b15c1c)

### Debug information

Demo Page

### Steps to reproduce

1. Create a budget with a weekly fixed amount
2. Add a transaction to that budget.

**Comment by JC5** [comment]
This is correct. But also not correct. Multiple weekly budgets fit in one month, and since the view is "one month" Firefly III can't differentiate in which budget limit the expense was made. So it doesn't try to calculate the difference since it doesn't know which day the expense was. See also:

<img width="1590" alt="Screenshot 2023-08-04 at 19 08 35" src="https://github.com/firefly-iii/firefly-iii/assets/5889984/fa36daca-3974-45b2-8f07-0f6d12c7ade7">


When was the 50 spent?

In theory, Firefly III can calculate this and a better view is still on my list. Until then, it's not going to be fixed I'm afraid,

**Comment by JC5** [comment]
Exactly. And I fear that if I remove it, I get *more* questions 😉 .

Can I close this issue?
