### ISSUE TITLE
2 import questions

### ISSUE THREAD

**Issue by zjean** [firefly-iii/firefly-iii#825]
Hi,
I just imported a large set of Rabobank transactions in my freshly updated Firefly installation (v4.6.5), and noticed two things.
1. It looks like transfers are not matched, but just ignored.
I used the standard import description, from the hyperlink on the import page. I didn't create any links. Maybe that causes the error?

2. Bills don't matched during an import. When I hit the 'rescan old transactions' button on the bill, they are found.

besides this, I am really happy with the new import functionality. It performs very well, and does match existing accounts well!

**Comment by JC5** [comment]
1. They are "matched" but just ignored. What do you mean exactly? Are they created? Aren't they?
2. No, they're not. I can extend the import but it's already pretty heavy on resources. Maybe a warning would be enough?

**Comment by zjean** [comment]
Hi, 
thanks for your response.

1. What happened was this.
I have a Rabo savings account X and a checking account Y. Both are added as accounts in FF (with their IBAN as well).
I downloaded all transactions for a certain period from my checkings account only.
In there is a line for a transfer from my checking to my savings account. (And vice versa).
Those lines are not processed by the importer, I can't find the resulting transactions and the balances don't match with my bank account.

Two example lines from the CSV:
`"NL01RABOYYY","EUR","20170808","C","150.00","NL01RABOXXX","My Name","20170808","tb","","","","","","","","","",""`
`"NL01RABOYYY","EUR","20170825","D","50.00","NL01RABOXXX","My Name","20170828","tb","","","","","","","","","",""`

2. A warning would be find indeed. And maybe some extra luxury as to rescan all bills at once, but that might be resource intensive as well.

**Comment by JC5** [comment]
Mmmm, the line _should_ be processed but you never know. I'll experiment with my own Rabobank account to see what happens.

**Comment by JC5** [comment]
I finally had time to look into this. As far as I can tell, transfers are created just fine. I tested this by downloading this month's transactions. I did no significant mapping (just the currency) but I had a normal and a savings account with matching IBAN's.

Transfers to/from accounts I did not have the IBAN from (another savings account) were created as expense/income. But they were correctly linked to my main account.

Could you create a censored test file for me, and share your configuration file?

**Comment by Edubits** [comment]
I seem to have a similar issue with ING. All lines are imported correctly, except for the transfers to and from my savings account. As they don't have their own IBAN they are mapped by name. After importing they are not visible, both when using the import tag to search and when looking in the respective accounts. Also there are no transactions created in the database.
[Attached a censored export](https://github.com/firefly-iii/firefly-iii/files/1346290/NL16INGB0xxx_savings_censored.csv.txt) containing some random transactions in the ING export format. None of these are imported into Firefly.

**Comment by JC5** [comment]
Hi!

Thanks for sharing this file! Unfortunately I could not replicate your issue. I started fresh on an installation of the latest version, v4.6.6. Are you running this version as well? I just released it this morning. It might be that this issue is fixed in the new release.

I started by recreating your accounts. Marking them as savings accounts btw, does not matter:

![screen shot 2017-09-30 at 11 37 58](https://user-images.githubusercontent.com/5889984/31044713-b23d021e-a5d4-11e7-8fc1-2b58df19f002.png)

I used [this import configuration](https://github.com/firefly-iii/import-configurations/tree/master/nl/ing) to pre-configure your file. I did not edit it. This is my column configuration:
  
![screen shot 2017-09-30 at 11 38 40](https://user-images.githubusercontent.com/5889984/31044738-34991f36-a5d5-11e7-91fb-e8801989da9c.png)

This is the mapping. Note that I mapped your main account twice.

![screen shot 2017-09-30 at 11 39 31](https://user-images.githubusercontent.com/5889984/31044743-4cfdf722-a5d5-11e7-9fea-b3e4124ba545.png)

And this is the result:

![screen shot 2017-09-30 at 11 39 57](https://user-images.githubusercontent.com/5889984/31044746-63c2e684-a5d5-11e7-88e7-b57b7d7d5c9b.png)

So as far as I can tell, it works as it should. Let me know if you do things differently: we might find the issue there.

**Comment by Edubits** [comment]
Thanks for the extensive response. I'm following the same steps as far as I can see. After updating to 4.6.6 (I was on 4.6.5) I tried again.

My asset accounts:
<img width="1298" alt="screenshot 2017-09-30 12 22 31" src="https://user-images.githubusercontent.com/188220/31045016-f13d08e6-a5da-11e7-9907-e477d46d271b.png">

My column configuration (based on the same file):
<img width="1395" alt="screenshot 2017-09-30 12 29 59" src="https://user-images.githubusercontent.com/188220/31045032-53c05f4a-a5db-11e7-9d2e-9718865cbca0.png">

My mapping:
<img width="1389" alt="screenshot 2017-09-30 12 30 47" src="https://user-images.githubusercontent.com/188220/31045037-7de0b7a2-a5db-11e7-9eaa-41f613539009.png">

And the result:
<img width="1391" alt="screenshot 2017-09-30 12 31 01" src="https://user-images.githubusercontent.com/188220/31045039-88a4eed8-a5db-11e7-86ef-f71f2b25e55f.png">

Do you have any suggestions for things to check?

**Comment by JC5** [comment]
Let's see. Are you logging on the debug level? If not: could you [enable debug mode](https://github.com/firefly-iii/help/wiki/Enable-debug-logging-and-debug-mode) and empty the `storage/logs` folder?

Then, run the import again. I'm curious to see what the difference is between our installations. You can share the log over Github or send it to me over [email](https://firefly-iii.github.io/contact-information.html)

**Comment by Edubits** [comment]
I've just enabled logging and I'm seeing something interesting:
`[2017-09-30 10:45:46] production.ERROR: There already is a transfer imported with these properties. Compare existing with new.  {"existing":{"names":["Moneyou","Moneyou"],"amount":"xx.xx","date":"2017-09-29","description":"Ontvangen bonus rente"},"new":{"type":"Transfer","description":"Naar Oranje Spaarrekening W2xxxxx78","amount":"-150","date":"2017-09-27","asset":"ING Common","opposing":"ING Common"}} 
[2017-09-30 10:45:46] production.ERROR: Detected a possible duplicate, skip this one (hash: a9a919b532f97bc1403290d08349166cbf5f8232eb4ea076ae524141d82f95c3). {"type":"Transfer","description":"Naar Oranje Spaarrekening W2xxxxx78","amount":"-150","date":"2017-09-27","asset":"ING Common","opposing":"ING Common"} 
[2017-09-30 10:45:46] production.ERROR: Cannot import row #0 because: Detected a possible duplicate, skip this one (hash: a9a919b532f97bc1403290d08349166cbf5f8232eb4ea076ae524141d82f95c3).`
The import seems to think the transactions are all a duplicate with the very same transaction for one of my other savings accounts (this one at Moneyou). For each duplicate there is a different hash though. I'll mail you the full log.

**Comment by JC5** [comment]
Thanks, I've received the log. It seems the duplicate transfer detection routine is broken.  It is meant to detect duplicates in different files: for when you import from account A first, and then from account B. Transfers between A and B would be recorded like so:

```
A > B
B > A
```

And not trigger the hash detection but still be the same one.

I have found the bug and I have pushed a fix. Could you find file `firefly-iii//app/Import/Storage/ImportStorage.php` in your installation and replace the content with the code [under this link](https://raw.githubusercontent.com/firefly-iii/firefly-iii/134f21bada40a3c580ee9efd8e021105245fb76f/app/Import/Storage/ImportStorage.php)?

That should fix the problem for you. I'll wait to see if other bugs pop up before I push a new release, which will also include this fix.

Thanks again for helping me find this!

**Comment by Edubits** [comment]
Great, that seems to work indeed, thanks! Looking at the code the import was quite eager in deciding some transactions were duplicates. 

Let's hope this fixes @zjean's issue as well.

**Comment by zjean** [comment]
Yes, this replacing the ImportStorage.php with the new contents fixes my issue as well! Thanks a lot @Edubits and @JC5 !

**Comment by Edubits** [comment]
@zjean FYI, I noticed another duplication issue today and then found it was already fixed in another issue: #893. You might want to update to that version of ImportStorage.php as well.
