### ISSUE TITLE
Bills cannot use non-default currency

### ISSUE THREAD

**Issue by pkoziol** [firefly-iii/firefly-iii#833]
Recently I got USD debit card, so now I can pay for all my cloud services in USD instead of PLN.

So I edited my bill to match on amounts in USD and made withdrawal. It automatically matched, but...
1. Chart still displays amounts in PLN (both old and new) - OK, maybe not best idea to change currency for existing bills.
2. Bills list also has amounts in PLN.
3. Editing bill also has currency set to PLN.

Same thing with new bill. Looks like currency doesn't matter.

On demo site, I created bill in USD and made withdrawal in EUR and in USD. Both matched.

**Comment by JC5** [comment]
Yes, bills do everything in the default amounts. They cannot cope with multi-currency transactions. Everything will match.

I have to expand bills to make them multi-currency, and I'll write it down as a feature!

**Comment by BogdanNaum** [comment]
Until bills support multi-currency, can we make the 'Currency' field read-only for bills? This will make things clearer for the end-user.

**Comment by JC5** [comment]
In the next version of Firefly III:

- Bills will display everything in the currency that the bill is set in. Charts, text, etc.
- Since the bill now has to be matched with rules, you should add a trigger that says "transaction currency is X". It is not mandatory to do this. Firefly III should suggest this by default.

You can still link EUR transactions to USD bills and this _will_ mess up the charts but with a little discipline you should be able to use this feature.

I've pushed some code that works on the demo site already.

Let me know if this works for you, because then i can tag it as fixed and it'll be included in the next release.

**Comment by JC5** [comment]
And the new release is live!
