### ISSUE TITLE
Ability to export rules, asset accounts, bills

### ISSUE THREAD

**Issue by gavu** [firefly-iii/firefly-iii#859]
I re-installed (for test porpouses) the app multiple times and always had to re-add rules, asset accounts and bills. Everything seems to be automatically generated if not found.

Do you think this would be a feature you might add in the future?

**Comment by JC5** [comment]
https://github.com/firefly-iii/test-data

The file it's missing is the new .env file for your FF installation. I am in the middle of a move so I can't explain it, but it should be able to do what you want ^^

**Comment by JC5** [comment]
Was this useful? Need some help with this?

**Comment by gavu** [comment]
I did not get to test it yet, but I am thinking about re-starting. so yes, I do need some help. what do you mean by "The file it's missing is the new .env file for your FF installation" ?

**Comment by JC5** [comment]
You can simply delete everything from your database except what you wish to keep. That's one way. But the test-data tool uses [json files](https://github.com/firefly-iii/test-data/blob/master/resources/seeds/local.json) to recreate the database. These can be used to quickly initialise a database (such as the demo site or a test environment).

This includes all the things you mentioned. The user_id is always 0 (refers to the JSON array, not to the database).

The .env file of the test-data application should match your Firefly database. In `resources/configurations` you should put a copy of the .env file you want your Firefly installation to get (it is copied).

Since you can have multiple test data sets and multiple databases at the same time, the file in `resources/configurations` must be named like so:

dot-env-`name of json file`-`name of db driver`.txt

Then, you could run this on the command line:

`./test-data/generate-test-data.sh local mysql`

And the tool would import local.json using the mysql driver and copy `dot-env-local-mysql.txt` as the new .env file of your firefly installation.

Open the generate-test-data.sh file to see what it does (may need some editing).

**Comment by gavu** [comment]
The second part seems to be more of a "create" a new environment from new data, since the first one is actually more what I wanted.

Just to make sure I understand correctly:

1. I duplicate my current DB (just for backup)
2. I go to my current environment and delete all the transactions
3. re-import everything

This, however, raises a few question regarding row IDs: 

1. AFAIK, it is not good practice to expose row IDs in URLs
2. considering the huge amount of work to change the row IDs in URLs issue, should I, or should I not reset the row count `ALTER TABLE tablename AUTO_INCREMENT = 1`

**Comment by gavu** [comment]
You answered this on in https://github.com/firefly-iii/firefly-iii/issues/895#issuecomment-335559919

**Comment by JC5** [comment]
👍
