### ISSUE TITLE
Transfers overview, breakdown by month sum is wrong

### ISSUE THREAD

**Issue by gavu** [firefly-iii/firefly-iii#895]
How to reproduce:

1. Go to transfers
2. Click on a month where there are more than 1 transfers

I had the following transfers in august 2016
- AccountA to AccountB: 1500Euro
- AccountB to SavingsAccount: 100Euro

![2017-10-03 21_46_52-all transfers](https://user-images.githubusercontent.com/3742238/31145670-b92e79b0-a884-11e7-8240-d02b6626ade3.png)

**Comment by pkoziol** [comment]
Seems to be working correctly on demo: https://firefly-iii.nder.be/transactions/transfers

**Comment by JC5** [comment]
I'm also having trouble reproducing this.

![screen shot 2017-10-04 at 06 57 02](https://user-images.githubusercontent.com/5889984/31160541-42f40d4e-a8d1-11e7-852e-75e92600da3b.png)

**Comment by gavu** [comment]
Let me just reset everything, reimport all accounts (because of the transfer bug) and I’ll take another look. I’ll update this issue in about 4-6hrs

**Comment by gavu** [comment]
I can't restore the bills and rules (see issue 916) so can't really test again without manuall adding 40+ rules and about 15 bills

**Comment by JC5** [comment]
I saw it.

MySQL is a relational database so it needs the data in the correct order. Generally speaking, any value ending in `_id` needs to exist before an entry can be created.

A rule cannot exist without a rule group, the table contains the field `rule_group_id`. Bills cannot exist without a user, because of the field `user_id`.

So when you're restoring data make sure the users exists before the rule groups before the rules. 

What I generally do, is reset the database, register myself (user_id=1) and then restore other data.

So I suggest a clean database, a new registration (or copied from the old database, also works), and then a copy/paste of the old data (or SQL queries).

Bills require users, piggy banks require accounts, rules require users and rulegroups, etc.

Does that help?

**Comment by gavu** [comment]
It did help, thanks, did not think about the relations, just saw the error and panicked :)

I copied all the rules, bills and accounts. Tomorrow morning, I'll start importing everything and let you know

**Comment by gavu** [comment]
Here's the update:

After clearing everything except the rules/bills/accounts, the values are unchanged:

August 2016: Transferred €1,400.00
August 2016: Sum of all transfers (€1,500.00 + €100.00): €1,600.00

Could the reason be that I am somehow transferring 1500 in and 100 out? so mathematically speaking it's 1500-100?

**Comment by JC5** [comment]
It shouldn't matter. Is this still an issue?

**Comment by gavu** [comment]
I just checked, it's the same, nothing changed. If you add the two transactions in the list, it's 1600, but the highlighted month-widget on the right says 1400 - if you still have the DB-dump I sent you, it should be there, otherwise, I can send you a fresh one

**Comment by JC5** [comment]
I think I found it. I've pushed a possible fix.

**Comment by gavu** [comment]
Now the sums match. Thanks!
