### ISSUE TITLE
Create withdrawal using a bill as template

### ISSUE THREAD

**Issue by skuzzle** [firefly-iii/firefly-iii#922]
Instead of remembering matching keywords to create a withdrawal for a bill, wouldn't it be nice if the bills page offered an action to create a new withdrawal directly for a certain bill?

Maybe one could also add some more information to a bill (such as the account from which the money will be withdrawn) so that a bill can act as a template for the fast creation of a new withdrawal.

**Comment by JC5** [comment]
It would be nice, but it feels a bit like "feature creep". 

Rather than extending the bill features to provide a "template" functionality, Firefly III already features the "clone"-feature that is available from every transaction. What I usually do is take the last transaction from a bill and clone that. The date is automatically updated so it's easy to recreate transactions.

Would that work for you?

**Comment by gavu** [comment]
Not trying to hijack the thread but templates are not a bad idea. Most of my rules and bills are mostly identical, except for the triggers. Duplicating objects would be a nice feature.
