### ISSUE TITLE
SQL Database initialization error

### ISSUE THREAD

**Issue by DeltaKiloz** [firefly-iii/firefly-iii#923]
When I attempt to run the following command to initialize the database:

`php artisan migrate:refresh --seed`

I get the following error:

![firefly-2](https://user-images.githubusercontent.com/5963159/31475792-d52cbba2-aed0-11e7-8ce0-b6bc1881b24d.PNG)

Is there some manual database pre-setting we need to do before running this command, other than setting the .env file to be able to access mysql?

**Comment by JC5** [comment]
It seems your installation is missing the php-MySQL packages, meaning that PHP cannot execute MySQL commands.

**Comment by DeltaKiloz** [comment]
That did the trick, just had to `apt-get install php-mysql` , might want to make sure that's spelled out in your installation guide as one of the required php modules that need to potentially be installed separately.

**Comment by JC5** [comment]
Glad to hear it's working! :+1:

**Comment by JC5** [comment]
Whoops, I forgot to address your feedback about the installation guide. I'm afraid I can't add it. :(

Up until recently, I had a very long installation guide that would include _every_ eventuality that might happen. Missing packages, broken symlinks, weird operating systems (Raspberry PI running Windows XP), you name it, I had it!

Turns out, this only makes the guide complex and hard to navigate while most content is useless for most users.

So nowadays I tell people to Google the basics (some links are provided) so my guide focuses on the important part: installing Firefly III ;-)

**Comment by JC5** [comment]
No longer, I'm afraid. What are you running into?
