### ISSUE TITLE
Dashboard info-boxes not in one line

### ISSUE THREAD

**Issue by nicoschreiner** [firefly-iii/firefly-iii#932]
Hey,

I found some stange behavior with the info-boxes on the dashboard.

If you create a new empty account, login and create the necessary bank-account to get to the dashboard, than the info-boxes are not all in one line:
![firefly-iii_info-boxes-1](https://user-images.githubusercontent.com/31184224/31587851-5fbcb1bc-b1e9-11e7-9832-cb66eb5e64cd.png)

To fix this you need to create a new bill. Than they are all in one line (as they should be):
![firefly-iii_info-boxes-2](https://user-images.githubusercontent.com/31184224/31587865-8e6db786-b1e9-11e7-80e4-3ac0fe06ca56.png)

I tested this with version 4.6.8.

Greetings
Nico

**Comment by JC5** [comment]
Ah yes, that's a silly bug. I'll make sure it gets fixed!

**Comment by Aquariu** [comment]
I cant't quite see how this is a problem. I haven't created any bills so my display looks like the first one Nico put in his message. Yet, I thought this was as per design. Like a normal rearranging of boxes due to the layout of the page and my web brother's window's width.

What will happen when you need a new box for some other usage?

**Comment by JC5** [comment]
@Aquariu: when you have no bills, the boxes are the same but they are too wide.
