### ISSUE TITLE
Net worth dashboard widget ignores if asset account is disabled

### ISSUE THREAD

**Issue by gavu** [firefly-iii/firefly-iii#941]
I have just disabled my CreditCard Asset account as there is no HBCI access to my bank (and I am lazy). I noticed the Net worth did not change. I now have a few questions

* does FF just ignore the status, do imports that produce transfers to the disabled accounts still work?
* what is the difference between disabled asset accounts and hidden asset accounts in preferences?
* what happens when someone disables an asset account?

**Comment by JC5** [comment]
Since you still have the money, the amount still counts towards the net worth. Even for disabled accounts, since disabling accounts has more to do with their availability. You can't select it in new transactions, or piggy banks, but in the import it is still available I believe.

Hiding an account from the frontpage is for clarity only.
