### ISSUE TITLE
Make dashboard panels draggable

### ISSUE THREAD

**Issue by gavu** [firefly-iii/firefly-iii#953]
I am running Firefly III version 4.6.9

#### Description of my issue:

Provide ability to rearrange dashboard widgets by making all panels draggable

**Comment by JC5** [comment]
For the time being the layout will remain as is.

**Comment by gavu** [comment]
there is always hope :)

**Comment by Bubka** [comment]
Hi,

Indeed, the Dashboard should be more flexible. It is even more valid when you use FF on mobile. You have to scroll down again and again to reach for example the Bills widget. I barely use it because of that.

Draggable components would be a great feature.

Another solution could be to have the ability to choose which widget to display (the same way it is currently possible to select which account to display).

**Comment by JC5** [comment]
I'm sorry guys, the layout will stay as it is. If anything changes, a new layout template must be implemented first.
