### ISSUE TITLE
"Submit" button unduely grayed out on the report page after "Back" action

### ISSUE THREAD

**Issue by Aquariu** [firefly-iii/firefly-iii#967]
I am running Firefly III version 4.6.8

#### Description of my issue:
When using the "Back" browser button on any Report page, I go back to the Report selection page as per design but the "Submit" button is greyed out. The only way I can generate another report is by clicking on the Report link on the left pannel or refreshing the page.
It would have seemed normal to me to be able to generate another report since I'm on the appropriate page for that.$

#### Steps to reproduce 
- Generate a report with the Report page
- Use the Back button

(please include if this problem also exists on the demo site)

**Comment by JC5** [comment]
I'm not sure if I can fix that. Your browser doensn't reload the page, it just returns you to the one you came from (disabled buttond and all).

I'm not sure if I can detect a "user pressed the back button"-event to ungray the button. However, since your browser doesn't really reload the page anyway, but simply grabs it from cache it might not help.

I'll look into it.

**Comment by Aquariu** [comment]
Oh ok. I'm totally not an expert in browsers so feel free to dump the issue if it's not appropriate.
I raised the issue because I don't know why the button was grayed. Maybe there are good reasons behind it.

Thanks for looking into it.

Olivier

**Comment by JC5** [comment]
I think I have a solution.

The reason the button grays out is because most forms should not be submitted twice (eg new transactions, new bills). So, graying out the button stops users from re-submitting the form accidentally.

However, requesting a report twice isn't that bad. So why disable the button? 

From the next release onward, this particular button will not gray out and thus, going back allows you to change and resubmit the form.

A note: other forms, such as the one to create a new transaction, will still need to be grayed out and will not be enabled again when you return. I've been looking into this and it's tricky to fix this (and the solution might not work for everybody).

**Comment by JC5** [comment]
Fixed for new release.
