### ISSUE TITLE
Budget - Period navigator date selectors

### ISSUE THREAD

**Issue by gavu** [firefly-iii/firefly-iii#971]
I am running Firefly III version 4.6.9

#### Description of my issue:

I wanted to see how the date selectors in the budget navigator work, what exactly they do and have the following questions:

1. Why are there two selectors? (one on the left and one on the right side of the navigator)
2. Why are some months in each selector missing?
3. Why are they not identical, and if this is not a bug, why can't I select both of them to create a longer period? (the page refreshes)

#### Other important details (log files, system info):

Left selector:
![screen shot 2017-11-01 at 14 56 10](https://user-images.githubusercontent.com/3742238/32278260-6c9cd6ee-bf15-11e7-93a0-7bd6813691fa.png)

Selected period:
November 2017

Right selector:
![screen shot 2017-11-01 at 14 56 19](https://user-images.githubusercontent.com/3742238/32278261-6cbed0be-bf15-11e7-9a88-fcc7d1c75138.png)

**Comment by JC5** [comment]
The left and right selector select the previous and next period, respectively.

The reason there are months missing is because you have selected the "quarter of a year"-view in your preferences, which is reflected in your budget overview. However, the "quarter of a year" date indicator is a little broken. Contrary to the week ("week 34"), month ("september") or even day indicator ("12 sept 2017") the quarter indicator should either be a range ("jan-mar" or "jan-apr") or an indicator of the quarter (Q1, Q2, etc).

This is currently not implemented well making this list confusing: the left selector has the start of each quarter: 1 oct, 1 jul, 1 apr, 1 jan, etc. The right selector has the final date of each quarter 31 dec, 31 mar, 31 jun.

Both should display "Q2 2017" or "Q3 2018" or something similar.

**Comment by gavu** [comment]
Now I get it. It does make sense now :)

**Comment by JC5** [comment]
I've pushed some code to clarify this :+1:

**Comment by JC5** [comment]
Closed, a new release is live.
