### ISSUE TITLE
How does Firefly III handle paycheck deductions in relation to budgets?

### ISSUE THREAD

**Issue by 8bitgentleman** [firefly-iii/firefly-iii#981]
As the title says how can I reconcile paycheck deductions and budgets in firefly iii? 

Here's the scenario: my employer has a program where they can deduct a certain amount, pre-tax, from my salary to pay for transportation to/from work. It can be used for bus tickets, metro cards, etc. If we opt in the allotted amount is taken off our paychecks each month and then HR distributes the transportation vouchers for the upcoming month at the end of the month. 
In firefly III I have a certain amount budgeted for transportation each month. Since starting this program with my employer there isn't an actual transaction when I buy a metro card anymore even though I'm still technically paying for it. How should I deal with this scenario in firefly iii?

**Comment by JC5** [comment]
I don't think you should record these transactions, and you may even forgo the budget entirely.

As such, Firefly can't handle these situations. There is no option to record HR perks. The question is, would you like to? I have similar perks at my job and I have opted to register what I spend through my bank card / credit card, and nothing else. 

If you wish to register these transactions, I would suggest adding an asset account called "Transportation" from which you pay all your tickets. Each month, you would create a deposit in this asset account from "Your company HR" or something. At the end of the month, the asset account should be at zero, after which HR will give you new vouchers (and you register a new deposit).

This creates a expenses/income flow that is more or less equal to what happens in real life. The expenses get added to your total expenses but your revenue also increases.

If you do not do this, nothing is "lost", since no money is gained or lost.

Personally, I would not use Firefly to register these expenses. Ask yourself if you need the administration. Are there disputes over these transportation expenses? Or does it all work out nicely?

**Comment by Aquariu** [comment]
The issue may also exist here for the same kind of vouchers (restaurant vouchers in my case). I'm sure others have the same kind of things related to health insurance (which is deducted from salary in some cases/countries), transportation, or taxes (in France, we should get a pre-salary revenue tax in 2019, many countries already have that).

For "the little things" like bus and restaurant vouchers, I would tend to let it slide. For taxes and bigger amounts, it may be interesting to do something about it.

JC, your way seems complicated. If the intent is just to track the monthly pre-salary deduction, then, you don't need to create a new transaction for daily expenses. If I understant the OP correctly, you can just as easily create a new virtual deposit each month of the correct amount and manually create an expense of the same amount that you can tag/attribute to the right Category/Budget. You can even do that on a yearly bases if the intent is just to have the correct Transportation/Restaurant/Tax/Whatever budget.

OR. Can we split a salary and attribute a negative amount to a transportation expense account ? so that the Salary itself seems higher ? I don't know if that makes sense.

**Comment by JC5** [comment]
You could split the salary deposit? I do that already:

![screen shot 2017-11-06 at 17 01 39](https://user-images.githubusercontent.com/5889984/32450319-35010d06-c314-11e7-9ff0-db4ac990dbb3.png)

**Comment by 8bitgentleman** [comment]
@JC5 Splitting the salary will do nicely, thanks for the help!
