### ISSUE TITLE
Ability to manually match bills

### ISSUE THREAD

**Issue by gavu** [firefly-iii/firefly-iii#991]
Would it be possible to add something like “Hey, your bill matched the name of this transaction but the amount is outside of the set range. Do you want to add it to the list?”

It is pretty useful for when you have fluctuating bills like the phone bill, or the rent. Whenever I fix something in the apartment, I retract that expense from the rent.

**Comment by JC5** [comment]
Does your land lord know you do that? I'll put it on the list :).

**Comment by gavu** [comment]
He did not complain... yet 😆 Thanks!

(I don't know how other people handle this - home improvements and repairs. My landlord also suggested, I could wire the entire amount, and then he can wire the costs back, but that is one extra step no one actually needs...)

**Comment by ErikFontanel** [comment]
This would be very useful. Another reason why: Currently bills only match on a specific date. Especially this month some transaction dates shifted due Jan 1st. Ie. my rent is normally automatically collected on January 1st, but this month that happened a day later.

Possible solutions:
- Match a transaction to a bill for a given period
- Set a date range or a optional date but with date interval instead of a fixed date for bills

**Comment by ErikFontanel** [comment]
Good to know, I'll adjust the matching rules for that particular contract then.

**Comment by JC5** [comment]
I believe this is pretty much fixed now that rules are expanded. Would you like to do a manual matching as well? Personally, I would prefer to do this via rules, for the consistency and user experience.

**Comment by ErikFontanel** [comment]
I prefer rules too, the more automation the better ;)
