### ISSUE TITLE
Monthly regular transactions/payments

### ISSUE THREAD

**Issue by emuhendis** [firefly-iii/firefly-iii#995]
There are bills match transactions. But what about regular payments. For example, I sent 100 try to one account once a month. Is there a eay to repeating transactions monthly?

**Comment by JC5** [comment]
No, there isn't. Such an expense could link to a bill but if it is internally (a transfer) there is currently no mechanism. Neither for regular income (salary for example).

I'm not sure yet how I can present such info in a useful manner. Once I have something, I'll let you know :).

**Comment by emuhendis** [comment]
I think that can be with splitting withdrawal. But you need to add a date column for splits.
Or for every withdrawal you can add a button like "Divide by Date"
So with that with one withdrawal it can produce e.q. 8 different width drawal connected to on main withdrawal.

It's like labelling.

Sorry for complicated explanation.

Figure out: You buy a 1000$ laptop and you pay with you credit card on 17/11/2017.

When you are paying, the bank or the store divide paymend to 5 pieces. 
(Checked the for divided payments, so the word is "installment")

Installment Plan:
1.  17/11/2017  200,0 $
2.  17/12/2017  200,0 $
3.  17/01/2018  200,0 $
4.  17/02/2018  200,0 $
5.  17/03/2018  200,0 $

Thanks.

P.S. In Turkey, Installments with credit cards are widely used. Shopping by installments percentage is approx. %60 in Turkey. So that feature will be great. 
Also if you let me, I want to be in developing Firefly.

**Comment by JC5** [comment]
Aha, that makes sense. All you can do right now is something with tags, but there is no "installments" feature. Splitting a transaction over multiple dates won't work with the current database model. And then there's possible rent as well.

There's an overarching story arch to manage debt, where this might fit in. At the moment, this could best be managed as a bill. Create a bill for the amount per month, with the proper keywords and other data. Disable it once the payment is complete. Then at least you will see what the transaction belongs to.

For now, Firefly will focus on the fact that it's an expense, and it cannot really handle the fact that it's part of a larger plan.

**Comment by LemarinelNet** [comment]
There is such a feature in MS Money 2003 that I currently use.
I plan to move to firefly, since MS Money is no longer supported, and I want a web-based software to be able to fill my expenses event when away from home ;)

To talk about this feature, in MS Money, you can set a "schedule table", where you enter : 
- kind of transaction (account transfert, bill pay, salary...)
- amount of the transaction
- day of the month it happens
- forever or limited number of times (or last occurence date)

I'm really using this feature, since every month I have a bunch of reccurent transactions : 
- house/car Insurance
- my salary, my wife's one
- automatic transfert to save for our future car
- house loan, which is a transfer of the same amount each month
- taxes...

Sorry for my average english, I'm not yet comfident with this vocabulary ;)

**Comment by JC5** [comment]
It's something that is not entirely the same as this discussion, but I understand what you want. It will not happen in the foreseeable future, I must say. But it is on the list!

**Comment by JC5** [comment]
Please subscribe to, or comment on #1469 to track progress of this feature :+1:
