### ISSUE TITLE
Is it possible to have non-integer budgets?

### ISSUE THREAD

**Issue by dp87** [firefly-iii/firefly-iii#996]
I am running Firefly III version 4.6.10

#### Description of my issue:

I got decimal expenses to work without issues, so this is not a locale issue from what I can see, but no matter what I try to enter as a value in a budget, that value is always stripped of the decimal digits.

#### Steps to reproduce 

1. Create a new budget
2. Give it whatever name
3. Give the budget a value of 500.40 or any other float value
4. If you refresh the page, the budget value becomes 500

Is there any way I can get budgets to accept decimal values? Sometimes, some budgeted transactions require an exact amount of money so there is no reason to guess (think insurance or car payments, for example).

**Comment by JC5** [comment]
It's currently not possible. When I built the feature, I only used budgets with whole amounts. This is easier to use, even if it means some budgets will always have a few euro's left in them.

I'll write it down as a future enhancement.

**Comment by dp87** [comment]
That would be amazing, thanks!

And by the way, congrats on the work done so far, I am really impressed. While I was looking for a self-hosted finance manager I was starting to lose any hope to find something that had enough features and also looked good. I think Firefly is even better than some commercial options out there (it's a pity that it lacks an API so we could develop some desktop apps to complete it, but I see it might come at some point in the future), so good job!

**Comment by JC5** [comment]
Sure thing, and thanks! I never get tired of compliments :wink:

**Comment by Aquariu** [comment]
+1 on the congratulations. :) .. however...

`If you don't care about the APIs topic, please just skip the rant below.`

An API would be good to interface with other tools, ok,... but please let the idea of an OS-specific client die.
- APIs change because the software evolves, get new functions quickly --> There are dozens of releases a year. Not all of them would lead to API update but many would. How many times do you think an external developper with his/her time devoted on an OS-specific client would update the thing before giving up ?
- Operating systems evolve making libraries/dev tools/etc... a moving target.
- There's already a very fine cross-OS client: The Web UI. The best client there can be is your browser.

Don't get me wrong, I love the idea of an API but you must define your use case carefully before committing to this. Financial clients such as Money, GNUCash, etc... won't need/care about that because these are All-in-one solutions. Good luck writting plug-ins for them to interface with FF.

Some have external DB options (I tried GNUCash with external DB over the network before I discovered Firefly-III), and it just doesn't work well (and is a security nightmare).

/rant

**Comment by dp87** [comment]
I perfectly understand the complexity of adding an API, and the effort that would go into maintaining it, so I have no issues if this is low priority, or even if it will never see the light of day.

The good thing about having an API is that it could be used for whatever you want, which is awesome, and if this also includes native apps, even better. If not, no big loss as we currently don't have them anyway ;)

**Comment by JC5** [comment]
Hi guys,

There's an API on the list of issues but it's a long way off. I see both the advantages and the disadvantages so I will try to make an informed decision. It will be a step by step process.

As for the budget amount, the next version of Firefly III should support decimal budgets. To double-check if your installation is capable of doing so, open your favorite SQL browser and go to the table `budget_limits`. If the `amount` field is of the `DECIMAL` type, you are good to go!

**Comment by JC5** [comment]
Just FYI, this is already enabled on the [demo site](https://firefly-iii.nder.be/budgets).

**Comment by dp87** [comment]
Amazing! Thank you :)
